### ISSUE TITLE
can not run slamdata front-end app

### ISSUE THREAD

**Issue by RumenTech** [quasar-analytics/quasar#1083]
@jdegoes 
Hey John,

Sorry for posting an issue if this problem has already been addressed.

I have completed setting up environments, I can run magical SQL commands agains MongoDB. (both REPL & WEB)
However, I can not open a page like on the [slamdata demo](http://104.236.166.167:8080/slamdata/index.html).
What I'm trying is as follows.

```
cd quasar-3.0.1-web

java -jar ./web/target/scala-2.11/web_2.11-3.0.1-one-jar.jar -c quasar-config.json --content-path ../slamdata-2.4.1/public
```

API endpoints are working fine, I can get results from these
- `http://localhost:5555/query/fs/?q=SELECT * from "/quasar-test/zips"&limit=5`
- `http://localhost:5555/data/fs/quasar-test/zips?limit=5`
When I open `http://localhost:5555`, it redirects to `http://localhost:5555/files` which returns 404 error.

I tried pre-built version and git-cloning version of slamdata.
Will you help me out again?

Thanks!

**Comment by jdegoes** [comment]
@RumenTech That's a separate project (slamdata/slamdata). 

I'd suggest going to <slamdata.com> and downloading installers, which will give you easy access to SlamData, powered by Quasar.

**Comment by RumenTech** [comment]
@jdegoes 
I see, I just thought these 2 projects are maintained by single company or team.
My problem is that download link on slamdata.com is not working for me and slamdata/slamdata repository doesn't have issues section and I can not post a ticket on JIRA either.

However, this link strongly tells that it is quasar's ability to host front-end app on the same port.
https://github.com/slamdata/slamdata#use-with-quasar

java -jar ./web/target/scala-2.11/web_2.11-3.0.1-one-jar.jar -c quasar-config.json **--content-path ../slamdata-2.4.1/public**

If this is out of your control, it's totally fine, I'll touch base with slamdata anyway.

Thanks for your support, John!

**Comment by jdegoes** [comment]
@RumenTech It's true, these two projects are maintained by one company (and some external contributors). However, the dependency is from SlamData on Quasar: that is, SlamData depends on Quasar, not the other way around.

What this means is that if you want to build the whole solution (the HTML5 web app, powered by the Quasar analytics engine), then you have to build the [slamdata/slamdata](http://github.com/slamdata/slamdata) project. The README in that project contains information on how to build the project from source code.

However, I think you caught us at a bad time!@chrisdima has been working on a new [SlamData.com](http://slamdata.com) website, and it looks like he accidentally broke the download process for the installers. I think he's fixed that now, can you give it another try and see what happens?

**Comment by RumenTech** [comment]
@jdegoes 
Thanks to Jeff Carr's help, I could download the application and run the whole platform (web app powered by Quasar engine). Enjoying the magical platform.

I really appreciate your help!

**Comment by jdegoes** [comment]
Awesome! If you run into any more issues, feel free to post on the SlamData user forum or on the bug tracker (depending whether it's a usage question or a bug). Good luck! :smile:
