### ISSUE TITLE
Error using explicit path in select

### ISSUE THREAD

**Issue by wdhutton** [quasar-analytics/quasar#1107]
I have my mongodb routed to "/".
Using the REPL, I can cd to any database and select a collecion
I cannot select from a collection in using the explicit  path.
I get similar error trying to using the web app with quasar_fdw

My simple quasar-config.json is

{
    "mountings": {
        "/": {
            "mongodb": {
                "connectionUri": "mongodb://weedat03.xxxxxx.com:27017"
            }
        }
    },
    "server": { "port": 5555 }
}

 java  -jar core/target/scala-2.11/core_2.11-4.0.5-one-jar.jar  ./quasar-config.json

Read config from ./quasar-config.json
ðª $ ls
quasar-test/
quasar/
test/
ðª $ select * from "/quasar.zips"
Quasar error: operator '(' expected; "/quasar.zips"
ðª $ select * from "quasar.zips"
Quasar error: operator '(' expected; "quasar.zips"
ðª $ cd quasar
ðª $ select * from zips
Mongo
db.zips.find();

Query time: 1.8s
 city          | loc[0]      | loc[1]     | pop    | state |
---------------|-------------|------------|--------|-------|
 AGAWAM        |  -72.622739 |  42.070206 |  15338 | MA    |
 CUSHMAN       |   -72.51565 |  42.377017 |  36963 | MA    |
 BELCHERTOWN   |  -72.410953 |  42.275103 |  10579 | MA    |
 BARRE         |  -72.108354 |  42.409698 |   4546 | MA    |
 BLANDFORD     |  -72.936114 |  42.182949 |   1240 | MA    |
 BRIMFIELD     |  -72.188455 |  42.116543 |   3706 | MA    |
 CHESTER       |  -72.988761 |  42.279421 |   1688 | MA    |
 CHESTERFIELD  |  -72.833309 |   42.38167 |    177 | MA    |
 CHICOPEE      |  -72.607962 |  42.162046 |  23396 | MA    |
 CHICOPEE      |  -72.576142 |  42.176443 |  31495 | MA    |

**Comment by sellout** [comment]
Try
```sql
select * from `/quasar/zips`
```
note the backticks, and the `/` for separating the db and collection. Please reopen this if it doesn’t work for you. Thanks.

**Comment by wdhutton** [comment]
That works for REPL.

But using the fdw interface to the WEB query server with same config file, I am getting a bad response 400 error.

I have : 
'server=http://weedat03.xxxxxx.com:5555','path=/quasar','timeout_ms=1000','use_remote_estimate=true','fdw_startup_cost=10','fdw_tuple_cost=0.01'

I am getting when accessing table using DBeaver
 
DBCException: SQL Error [XX000]: ERROR: quasar_fdw: Bad response from Quasar 400 (http://weedat03.xxxxxx.com:5555/query/fs/quasar?q=SELECT%20count%28%2A%29%20FROM%20%22zips%22)
  org.postgresql.util.PSQLException: PSQLException: ERROR: quasar_fdw: Bad response from Quasar 400 (http://weedat03.idco.intdata.com:5555/query/fs/quasar?q=SELECT%20count%28%2A%29%20FROM%20%22zips%22)

Issuing same generated query directly to web server i get similar error ... (note 22 = double quote")

http://weedat03.xxxxxx.com:5555/query/fs/quasar?q=SELECT%20count%28%2A%29%20FROM%20%22zips%22

{ "error": "operator '(' expected; \"zips\"" }

**Comment by sellout** [comment]
Ah, that is a bug in quasar-analytics/quasar-fdw. I referenced this from the relevant issue there. It needs to update its quotation syntax to match SQL².

Our apologies.

**Comment by wdhutton** [comment]
Do you have a patch or fix … I can remake the WEB app.

**Comment by jdegoes** [comment]
@wdhutton We don't yet have a solution, please keep tabs on the quasar-analytics/quasar-fdw project, which is a bit behind the latest Quasar at present.

**Comment by wdhutton** [comment]
I am looking for an altenative to the Mongo bi connector.



I was able to manually generate the (FDW) sql2 query I wanted to execute.

Assuming the WEB/FDW and REPL have the same core engine, I was able to evaluate the plan and performance.

I am joining two large mongo collections with a push down clause.

When done as two separate queries, it is lightning fast.

When done as a single join, the performance is not very good.





________________________________

**Comment by jdegoes** [comment]
Quasar FDW has much better pushdown than the MongoDB BI Connector. See [here](http://slamdata.com/analysis/2015/12/08/nosql-analytics-for-mongodb.html) for a comparison.

In the case of JOINs, we try to do predicate push down before the JOIN. Can you show the SQL query and the (generated) MongoDB query plan?

**Comment by wdhutton** [comment]
Note that NO results found.

select ENTITY_ID from `/OMEGA/Xref` where column0 = '0000000666'

Mongo
db.Xref.find(
  { "column0": "0000000666" },
  { "ENTITY_ID": true, "_id": false });


Query time: 0.1s
ENTITY_ID |
-----------|
  32330982 |

select ENTITY_ID from `/OMEGA/RefData` where ENTITY_ID = 32330982

Mongo
db.RefData.find({ "ENTITY_ID": NumberLong(32330982) }, { "ENTITY_ID": true });


Query time: 0.0s
ENTITY_ID |
-----------|
  32330982 |


select xf.ENTITY_ID from `/OMEGA/Xref` as xf  , `/OMEGA/RefData` as rd  where xf.ENTITY_ID = rd.ENTITY_ID  and xf.ENTITY_ID = (select ENTITY_ID from `/OMEGA/Xref/` where column0 = '0000000666')

Mongo
db.Xref.aggregate(
  [
    { "$match": { "column0": "0000000666" } },
    { "$project": { "__tmp6": "$$ROOT" } },
    { "$match": { "__tmp5": true } },
    {
      "$group": { "__tmp8": { "$push": "$__tmp6" }, "_id": { "0": "$__tmp6.ENTITY_ID" } }
    },
    {
      "$project": {
        "_id": true,
        "value": { "left": "$__tmp8", "right": { "$literal": [] }, "_id": "$_id" }
      }
    },
    { "$out": "tmp.gen_0" }],
  { "allowDiskUse": true });
db.RefData.mapReduce(
  function () {
    emit.apply(
      null,
      (function (key, value) { return [{ "0": value.ENTITY_ID }, { "left": [], "right": [value] }] })(
        this._id,
        this))
  },
  function (key, values) {
    var result = { "left": [], "right": [] };
    values.forEach(
      function (value) {
        result.left = result.left.concat(value.left);
        result.right = result.right.concat(value.right)
      });
    return result
  },
  { "out": { "reduce": "tmp.gen_0", "db": "OMEGA", "nonAtomic": true } });
db.tmp.gen_0.aggregate(
  [
    {
      "$match": {
        "value.left": { "$not": { "$size": NumberInt(0) } },
        "value.right": { "$not": { "$size": NumberInt(0) } }
      }
    },
    { "$unwind": "$value.left" },
    { "$unwind": "$value.right" },
    {
      "$project": {
        "ENTITY_ID": {
          "$cond": [
            {
              "$and": [
                { "$lte": [{ "$literal": {  } }, "$value.left"] },
                { "$lt": ["$value.left", { "$literal": [] }] }]
            },
            "$value.left.ENTITY_ID",
            { "$literal": undefined }]
        }
      }
    },
    { "$project": { "ENTITY_ID": true, "_id": false } }],
  { "allowDiskUse": true });

Query time: 102.9s
No results found

**Comment by jdegoes** [comment]
Would you mind writing that query as a real JOIN?

**Comment by wdhutton** [comment]
Query time: 356.1s
No results found

select xf.ENTITY_ID from `/OMEGA/Xref` as xf  join  `/OMEGA/RefData` as rd  on xf.ENTITY_ID = rd.ENTITY_ID  WHERE xf.ENTITY_ID = (select ENTITY_ID from `/OMEGA/Xref/` where column0 = '0000000666')

Mongo
db.Xref.aggregate(
  [
    {
      "$group": { "__tmp0": { "$push": "$$ROOT" }, "_id": { "0": "$ENTITY_ID" } }
    },
    {
      "$project": {
        "_id": true,
        "value": { "left": "$__tmp0", "right": { "$literal": [] }, "_id": "$_id" }
      }
    },
    { "$out": "tmp.gen_2" }],
  { "allowDiskUse": true });
db.RefData.mapReduce(
  function () {
    emit.apply(
      null,
      (function (key, value) { return [{ "0": value.ENTITY_ID }, { "left": [], "right": [value] }] })(
        this._id,
        this))
  },
  function (key, values) {
    var result = { "left": [], "right": [] };
    values.forEach(
      function (value) {
        result.left = result.left.concat(value.left);
        result.right = result.right.concat(value.right)
      });
    return result
  },
  { "out": { "reduce": "tmp.gen_2", "db": "OMEGA", "nonAtomic": true } });
db.tmp.gen_2.aggregate(
  [
    {
      "$match": {
        "value.left": { "$not": { "$size": NumberInt(0) } },
        "value.right": { "$not": { "$size": NumberInt(0) } }
      }
    },
    { "$unwind": "$value.left" },
    { "$unwind": "$value.right" },
    { "$project": { "value": true, "_id": false } },
    { "$out": "tmp.gen_1" }],
  { "allowDiskUse": true });
db.tmp.gen_1.mapReduce(
  function () {
    emit.apply(
      null,
      (function (key, value) { return [key, value.value] })(this._id, this))
  },
  function (key, values) { return values[0] },
  {
    "out": { "replace": "tmp.gen_0", "db": "OMEGA" },
    "query": {
      "$where": function () {
        return (isObject(this.left) && (! Array.isArray(this.left))) ? this.left.ENTITY_ID === this : undefined
      }
    }
  });
db.tmp.gen_1.drop();
db.tmp.gen_2.drop();
db.tmp.gen_0.aggregate(
  [
    {
      "$project": {
        "ENTITY_ID": {
          "$cond": [
            {
              "$and": [
                { "$lte": [{ "$literal": {  } }, "$value.left"] },
                { "$lt": ["$value.left", { "$literal": [] }] }]
            },
            "$value.left.ENTITY_ID",
            { "$literal": undefined }]
        }
      }
    }],
  { "allowDiskUse": true });

**Comment by sellout** [comment]
I think this is the join equivalent:
```sql
select xf.ENTITY_ID
  from `/OMEGA/Xref` as xf,
       `/OMEGA/RefData` as rd
 where xf.column0 = "0000000666"
   and xf.ENTITY_ID = rd.ENTITY_ID
```
written as a cross join, but we optimize that into a pre-filtered inner join.

**Comment by wdhutton** [comment]
Still slow, but got the correct answer.

Query time: 145.8s
ENTITY_ID |
-----------|
  32330982 |


BICONNECTOR Postqresql query

select xf."ENTITY_ID" from public."Xref" as xf,  public."RefData" as rd  where xf.column0 = '0000000666' and xf."ENTITY_ID" = rd."ENTITY_ID"

Using biconnector : 25 seconds

00000: parse <unnamed>: select xf."ENTITY_ID" from public."Xref" as xf,  public."RefData" as rd  where xf.column0 = '0000000666' and xf."ENTITY_ID" = rd."ENTITY_ID" LIMIT 100
00000: StartTransactionCommand
00000: StartTransaction
00000: name: unnamed; blockState:       DEFAULT; state: INPROGR, xid/subid/cid: 0/1/0, nestlvl: 1, children:
00000: bind <unnamed> to <unnamed>
00000: Connected to MongoDB with seed list of '[('weedat02.idco.intdata.com', 27017)]', database 'OMEGA', collection 'Xref'
00000: Configuring with columns 'OrderedDict([('ENTITY_ID', ColumnDefinition(ENTITY_ID, 1700, numeric)), ('_id', ColumnDefinition(_id, 1043, character varying options {'type': 'ObjectId'})), ('column0', ColumnDefinition(column0, 1043, character varying)), ('column1', ColumnDefinition(column1, 1043, character varying)), ('column10', ColumnDefinition(column10, 1043, character varying)), ('column11', ColumnDefinition(column11, 1043, character varying)), ('column12', ColumnDefinition(column12, 1043, character varying)), ('column13', ColumnDefinition(column13, 1043, character varying)), ('column14', ColumnDefinition(column14, 1043, character varying)), ('column15', ColumnDefinition(column15, 1043, character varying)), ('column16', ColumnDefinition(column16, 1043, character varying)), ('column17', ColumnDefinition(column17, 1043, character varying)), ('column18', ColumnDefinition(column18, 1043, character varying)), ('column19', ColumnDefinition(column19, 1043, character varying)), ('column2', ColumnDefinition(column2, 1043, character varying)), ('column20', ColumnDefinition(column20, 1043, character varying)), ('column21', ColumnDefinition(column21, 1043, character varying)), ('column22', ColumnDefinition(column22, 1043, character varying)), ('column23', ColumnDefinition(column23, 1043, character varying)), ('column24', ColumnDefinition(column24, 1043, character varying)), ('column25', ColumnDefinition(column25, 1043, character varying)), ('column26', ColumnDefinition(column26, 1043, character varying)), ('column27', ColumnDefinition(column27, 1043, character varying)), ('column28', ColumnDefinition(column28, 1043, character varying)), ('column29', ColumnDefinition(column29, 1043, character varying)), ('column3', ColumnDefinition(column3, 1043, character varying)), ('column4', ColumnDefinition(column4, 1043, character varying)), ('column5', ColumnDefinition(column5, 1043, character varying)), ('column6', ColumnDefinition(column6, 1043, character varying)), ('column7', ColumnDefinition(column7, 1043, character varying)), ('column8', ColumnDefinition(column8, 1043, character varying)), ('column9', ColumnDefinition(column9, 1043, character varying))])' and aggregation pipeline '[]'
00000: execute <unnamed>: select xf."ENTITY_ID" from public."Xref" as xf,  public."RefData" as rd  where xf.column0 = '0000000666' and xf."ENTITY_ID" = rd."ENTITY_ID" LIMIT 100
00000: Executing query with qualifiers '[column0 = 0000000666]' and columns 'set(['ENTITY_ID', 'column0'])'
00000: Executing aggregation pipeline '[{'$match': {u'column0': {'$eq': u'0000000666'}}}, {'$project': {'ENTITY_ID': True, 'column0': True}}]'
00000: Executing query with qualifiers '[]' and columns 'set(['ENTITY_ID'])'
00000: Executing aggregation pipeline '[{'$project': {'ENTITY_ID': True}}]'
00000: Completed query with row count 999966
00000: Completed query with row count 1
00000: CommitTransactionCommand
00000: CommitTransaction

QUASAR query



select xf.ENTITY_ID from `/OMEGA/Xref` as xf,  `/OMEGA/RefData` as rd  where xf.column0 = '0000000666' and xf.ENTITY_ID = rd.ENTITY_ID
Mongo
db.Xref.aggregate(
  [
    { "$match": { "column0": "0000000666" } },
    {
      "$group": { "__tmp0": { "$push": "$$ROOT" }, "_id": { "0": "$ENTITY_ID" } }
    },
    {
      "$project": {
        "_id": true,
        "value": { "left": "$__tmp0", "right": { "$literal": [] }, "_id": "$_id" }
      }
    },
    { "$out": "tmp.gen_0" }],
  { "allowDiskUse": true });
db.RefData.mapReduce(
  function () {
    emit.apply(
      null,
      (function (key, value) { return [{ "0": value.ENTITY_ID }, { "left": [], "right": [value] }] })(
        this._id,
        this))
  },
  function (key, values) {
    var result = { "left": [], "right": [] };
    values.forEach(
      function (value) {
        result.left = result.left.concat(value.left);
        result.right = result.right.concat(value.right)
      });
    return result
  },
  { "out": { "reduce": "tmp.gen_0", "db": "OMEGA", "nonAtomic": true } });
db.tmp.gen_0.aggregate(
  [
    {
      "$match": {
        "value.left": { "$not": { "$size": NumberInt(0) } },
        "value.right": { "$not": { "$size": NumberInt(0) } }
      }
    },
    { "$unwind": "$value.left" },
    { "$unwind": "$value.right" },
    {
      "$project": {
        "ENTITY_ID": {
         "$cond": [
            {
              "$and": [
                { "$lte": [{ "$literal": {  } }, "$value.left"] },
                { "$lt": ["$value.left", { "$literal": [] }] }]
            },
            "$value.left.ENTITY_ID",
            { "$literal": undefined }]
        }
      }
    },
    { "$project": { "ENTITY_ID": true, "_id": false } }],
  { "allowDiskUse": true });

**Comment by jdegoes** [comment]
@sellout: Anything obviously slow with the above query? At some point we want to fold the aggregate into the preceding map/reduce, but anything beyond that?

@wdhutton What you may be running into is just the fact that MongoDB is not very fast at JOINs. In this case, it may be faster to pull all the data out of Mongo and do the JOIN in PostgreSQL, which is what the MongoDB BI Connector will do (also the Quasar BI Connector, which will have identical performance to the MongoDB BI Connector in this case, and better performance in most other cases).

Once Quasar uses `$lookup` for JOINs, the story may change a bit, as `$lookup` will probably be faster than map/reduce when one side of the JOIN is relatively small.

**Comment by sellout** [comment]
I think supporting `$lookup` will help, but we can’t fold the aggregate into the map/reduce for a couple reasons (one being that even a modest `$unwind` translated to JS is a massive performance hit). Otherwise, the query looks about as good as it can be.
