### ISSUE TITLE
Large queries fail in the GET API

### ISSUE THREAD

**Issue by yanatan16** [quasar-analytics/quasar#1120]
Very large queries (1600 chars or more) fail in the GET API. These same queries succeed in the REPL and the POST API. The response is a flat 400 Bad Request with no error message, and it happens almost immediately. I verified it affects 3.x and 4.x versions.

The issue first came up with [use of the FDW](https://github.com/quasar-analytics/quasar-fdw/issues/7), and [this gist](https://gist.github.com/yanatan16/631ed7729e9eb144ce04) has some experimentation and an example large query.

**Comment by jdegoes** [comment]
Tracked [here](https://slamdata.atlassian.net/browse/SD-1510)
