### ISSUE TITLE
Missing nested fields sometimes return "NA" for the content

### ISSUE THREAD

**Issue by yanatan16** [quasar-analytics/quasar#1122]
Missing fields should be null or missing from the response object in JSON form. However, sometimes with nested expansions, they are the string `"NA"`.

This is the smallest statement I can find to create the "NA" response. It seems to have something to do with an exact index in `replyTo[0]` and the expansion index in `comments[*].text`. (This uses the usual `user_comments` test collection in mongo.)

```
💪 $ SELECT comments[*].text, comments[*].replyTo[0] from `user_comments`;
 text       | 1          |
------------|------------|
 I concur.  |  9817361.0 |
         NA |  9654726.0 |
```

**Comment by jdegoes** [comment]
Tracked [here](https://slamdata.atlassian.net/browse/SD-1509)
