### ISSUE TITLE
Not able to create core_2.11-[version]-SNAPSHOT-one-jar.jar

### ISSUE THREAD

**Issue by dipakdotyadav** [quasar-analytics/quasar#1196]
running `./sbt 'project core' oneJar` doesn't create JAR file `./core/target/scala-2.11/core_2.11-[version]-SNAPSHOT-one-jar.jar` , instead it does create a JAR file `./core/target/scala-2.11/quasar-core-internal_2.11-9.4.2-one-jar.jar`

if anyone can help me out on how to create `core_2.*.jar` file

**Comment by dipakdotyadav** [comment]
I downloaded JAR `core_2.11-9.3.0-one-jar.jar` and run with command `java -jar core_2.11-9.3.0-one-jar.jar -c example-config.json` but throws error `Exception in thread "main" java.lang.Exception: core_2.11-9.3.0-one-jar.jar main class was not found (fix: add main/main.jar with a Main-Class manifest attribute, or specify -Done-jar.main.class=<your.class.name>), or use One-Jar-Main-Class in the manifest`

**Comment by drostron** [comment]
Hi @dipakdotyadav,

We recently restructured our projects a bit and that section of the README wasn't updated accordingly.

Building the repl jar should be:
```
./sbt 'project repl' oneJar
```

The path to the jar should be:
```
./repl/target/scala-2.11/quasar-repl_2.11-[version]-one-jar.jar
```

I'll update the README.

Thanks for reporting the issue.

**Comment by dipakdotyadav** [comment]
Thanks @drostron  the new jar is working now.
