### ISSUE TITLE
Publish command fails because `skeleton` project is not published

### ISSUE THREAD

**Issue by mossprescott** [quasar-analytics/quasar#1267]
When running `publishSigned`, there is an error because the `skeleton` project is not set up to be published, yet the `main` project depends on it.

In 10.1.13, I hacked around this by temporarily removing the dependency. We should decide whether skeleton gets published or not and make sure there is no invalid dependency.

**Comment by wemrysi** [comment]
Fixed in 60ffce826c0a9030bb46de2c6f25e7903aa29973.
