### ISSUE TITLE
Getting error Quasar error: quasar.Predef$.coenvTraverse

### ISSUE THREAD

**Issue by SathishRaju** [quasar-analytics/quasar#1280]
I can able to connect to REPL with the latest released JAR. Can list the dbs in my MongoDB. But when running query got the error below:

💪 $ select \* from users
Quasar error: quasar.Predef$.coenvTraverse(Lscalaz/Traverse;)Lscalaz/Traverse;

I even tried this in various other OSes (Ubuntu, Mac, Fedora). Same error.

**Comment by jedesah** [comment]
@SathishRaju Is this still an issue?

**Comment by zeeiyerWork** [comment]
@jedesah -> Please try and recreate and if not possible to reproduce, then close it, since we have not heard from @SathishRaju for 5 months.

**Comment by alissapajer** [comment]
There is not enough information provided to reproduce this issue so I am closing it.
