### ISSUE TITLE
Satisfy identity laws for import/export

### ISSUE THREAD

**Issue by jdegoes** [quasar-analytics/quasar#1300]
1. Everything that can be exported, should be able to be imported, in a structure and format identical to the export structure.
2. Exporting a resource, then deleting the resource, then importing the exported resource, should recreate the original structure of the file system.
3. Everything that can imported, should be able to be exported, in a structure and format identical to the import structure.
4. Importing from some local resource, then deleting the local resource, then exporting the local resource, should recreate the original structure of the local resource.

**Required supported formats**: JSON, CSV, both uncompressed and zipped, both files and whole directories.

**Comment by syves** [comment]
@jdegoes I wold like a bit more context, and information.
1. Why is this a new feature, is exporting causing the structure to flattened or be changed in some way?
2. What is a example of what a local resource would be? 
3. File system, where should I start to learn about the quasar file system.
4. and how can one do an equality check on a filesystem structure, what kind of data type is that?

**Comment by jdegoes** [comment]
1. It can be regarded as a combination bug fix and new feature. There is some genuinely new functionality here but also some existing functionality which is buggy.
2. Any file or directory structure consisting of JSON or CSV content, possibly compressed if a file, and definitely compressed if it's a directory.
3. Github search or #backend. 😄 
4. There is no data type for it now (as far as I'm aware). The file system has methods to extract out directory structure, download bytes, etc. You'll have to use these methods to either (a) pack it into a structure which you can compare for equality, or (b) compare manually.

**Comment by syves** [comment]
note to self, learn how to create a change log

**Comment by mossprescott** [comment]
Per @jdegoes in chat, we need to include mounts (at least _view_ mounts) when directories are downloaded, and restore them when uploaded.

**Comment by mossprescott** [comment]
Again, per jdegoes, the primary use case here is export/import for decks, but the goal is to have a consistent API that can round-trip everything in all formats.
