### ISSUE TITLE
Data in environment variable names

### ISSUE THREAD

**Issue by paulp** [quasar-analytics/quasar#1309]
The difficulty of working with the CI code (or just running the tests) is increased significantly by squirreling data into environment variable names like `QUASAR_MONGODB_3_2` and then finding/dredging it back out later with string manipulations. It's morally equivalent to having to set `PORT_27017=true` to use port 27017. Is the only motivation is to be able to configure and use several different versions of mongo simultaneously? If so, this use case is not important enough to so complicate the normal one; and there are other ways to pass multiple values.

I mean, we ourselves don't even run the integration tests against more than one mongo at once - in CI they all go to different jobs. So there's little reason to expect anyone else to do so. There are 10+ lines in the front-line README which could be eliminated by doing it more straightforwardly.

**Comment by jdegoes** [comment]
We should probably be using matrix builds so the suite for each backend is run in parallel:

<https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix>

Which probably has implications for how information is threaded into the tests.

**Comment by wemrysi** [comment]
@jdegoes Indeed, https://travis-ci.org/quasar-analytics/quasar/builds/148069354 ;)

**Comment by paulp** [comment]
Or (wip) https://github.com/paulp/quasar/blob/just-it-tests/.travis.yml#L29-L36

**Comment by zeeiyerWork** [comment]
@jdegoes -> can this issue be closed? since we appear to be using Travis build matrix.

**Comment by jdegoes** [comment]
Sounds good

**Comment by zeeiyerWork** [comment]
We already use Travis based build-matrices, which resolves this.
