### ISSUE TITLE
MongoDB 3.4: support for new pipeline operators

### ISSUE THREAD

**Issue by mossprescott** [quasar-analytics/quasar#1315]
When MongoDB 3.4 is available, we should support its enhanced capabilities. It's not yet clear exactly what they'll offer.

See the [MongoDB 3.4 Release Notes](https://jira.mongodb.org/secure/ReleaseNote.jspa?projectId=10000&version=15529), and also [3.3](https://jira.mongodb.org/secure/ReleaseNote.jspa?version=17046&projectId=10000).

Possibilities (as of 2016/7/29):
- configurable sorting (https://jira.mongodb.org/browse/SERVER-1920)
- [`$bucket`](https://jira.mongodb.org/browse/SERVER-23815) and [`$bucketAuto`](https://jira.mongodb.org/browse/SERVER-24152): compute frequency distributions for the values of arbitrary expressions. It's not clear how these would be expressed in SQL².
- exclusion is now supported in`$project` (see https://jira.mongodb.org/browse/SERVER-24921). This will allow us to generate more efficient plans when we need to delete `_id`, for example.

**Comment by sellout** [comment]
Depends on #2376.

**Comment by zeeiyerWork** [comment]
subsumed by #2383 and #2384 - so this particular one can be closed.
