### ISSUE TITLE
Quasar has trouble resolving fields when variables are used

### ISSUE THREAD

**Issue by alissapajer** [quasar-analytics/quasar#1316]
Ported from https://slamdata.atlassian.net/browse/SD-1864.

Problematic query:

```
mystate := "CO"; SELECT * from `/test-mount/testDb/zips` WHERE state = mystate
```

Error:

```
Quasar error: The expression 'state' is ambiguous and might refer to any of the tables ExprRelationAST((),mystate), TableRelationAST(FileIn(DirIn(Root,DirName(quasar-test)),FileName(zips)),None)
```

Temporary workaround:

```
mystate := "CO"; SELECT * from `/test-mount/testDb/zips` WHERE zips.state = mystate
```

**Comment by alissapajer** [comment]
@damonLL Just alerting you to the continued existence of this ticket - I just ported it over to github.

**Comment by alissapajer** [comment]
@jdegoes what is the priority level of this ticket? If qscript-related things are of higher priority (e.g. #1411) then this ticket would not make it in to 3.1.

**Comment by jdegoes** [comment]
Will bump to 3.2.
