### ISSUE TITLE
Parallel regression tests hang in Travis

### ISSUE THREAD

**Issue by mossprescott** [quasar-analytics/quasar#1338]
This causes one of the symptoms recorded in #1295.

After some improvements have been made, we've observed the the Mongo 3.0 read-only build fails somewhat regularly with "no output for 10 minutes" when running in Travis. The other builds also fail this way, but not as often. When it occurs, there are also errors in the log recording connection timeouts in the Mongo driver.

In a test, forcing the regression tests to run one at a time (`serialized` and `parallel in Test : false`) makes all four builds run to completion, albeit slowly. Local testing shows that many thread pools are created (something like 9 threads per test), quickly reaching a peak and then falling off. My inference is that the load of threads and the associated memory pressure is overwhelming Travis's wimpy VMs.

This situation is significantly worse for the "3.0 read-only" build because it use twice as many mongodb driver client instances: a "setup" (read-write) connection for each test as well as the "test" connection.

**Comment by mossprescott** [comment]
All the `it` tests are now serialized, and we're still seeing occasional "connection timed out" errors.

**Comment by nicflores** [comment]
It doesn't seem we are suffering database timeouts during tests any longer. I will go ahead and close this issue.
