### ISSUE TITLE
MarkLogic XML codec for quasar.Data

### ISSUE THREAD

**Issue by wemrysi** [quasar-analytics/quasar#1372]
`quasar.Data` is currently stored in MarkLogic as JSON via naive literal encoding, this needs to be extended to use the XML Data Model (XDM) which supports more data types natively and also likely to be the format most MarkLogic data is in.

**Comment by wemrysi** [comment]
Here are some thoughts about this issue, along with the assumptions I've made and the constraints MarkLogic (at least as far as my understanding goes) places on us. Mostly just to get this out of my head and up here for others to debunk, confirm or amend.

**Assumptions**
* Most data stored in MarkLogic is XML
* We want to support XML documents in this first release
* Lots of in-memory data conversion in MarkLogic is undesirable from a performance standpoint (i.e. normalizing all data formats into an XML encoding of EJson on-the-fly, for example)

**Constraints**
* Many structural operations (MakeMap, MakeArray, shifting, zipping, etc) depend on the format of the data
* Cannot mix native formats in the same "container" (i.e. you can't nest a JSON object inside an XML element)
* "Files" can contain a mix of XML and JSON (and semantic triples, but ignoring those for now)

**Problems**

We're dealing with at least three data formats: XML, JSON and EJson/Data in three different contexts: conversion TO Data (file reads, query results), conversion FROM Data (file writes) and query execution (manipulation of the data within MarkLogic itself, both that which originated from quasar and (mostly) that which did not)

XML cannot natively support the _structure_ of EJson/Data without an embedding of some sort. Examples: top-level objects in XML require an element name which would have to be synthesized and then later stripped, arrays have no direct representaion in XML, one can have repeated elements which you can treat as an array, but how do you distinguish between a single property and an array consisting of a single element (_idea_: possibly by adding an attribute signalling that the element represents an array)? Or an empty array (_idea_: possibly with an empty element?). Or how do you take two lists of repeated elements and concat them? What name is used for the element representing their concatenation?

We test with `Data` values which will likely have some embedding artifacts as described above, but most of the data in MarkLogic is going to be native XML which we'll have to handle differently than we do our embedding of `Data`. Probably want to get some test XML, even of `zips`, as an example of more natural/idomatic XML.

How do these encoding artifacts affect queries? i.e. will users have to know about them depending on where the data originated from? Or will we have to handle translating projections and shifts to take any synthetic elements into account (probably the latter, but adds complexity).

**P1**: Store Data as XML, ignore JSON for now
  * + Allows us to focus on what is likely the most common data stored in MarkLogic
  * + Stores test data in the same format as user data, likely with some embedding artifacts
  * + Allows us to use more native types from XDM for EJson/Data types
  * + Ignore mixed data to start
  * - Need to handle embedding artifacts in queries alonside "standard" XML
  * - no JSON support at first

**P2**: Store Data as JSON
  * + More natual encoding of EJson/Data, modulo some type annotations
  * + Probably means we'll support JSON
  * - Need to handle embedding in JSON in queries? i.e. still have multiple branches for many operations at runtime
  * - Test/development data all in a different format from what most customer data will look like
  * - Have to deal with what happens when we need to perform operations on a dataset containing mixed formats

**Comment by jdegoes** [comment]
It's most important to support existing MarkLogic installations since they will drive support of this connector.

That said, I think a translation between EJSON and XML is possible (not literal translation, although that has to be done, but rather, translation of the semantics of MRA onto the XML data model).

I don't have time to work this out right at the moment, but I'd use some expansion like `foo.bar.baz[*]` into something like `foo > bar > baz > *` (using CSS instead of XQuery here). Every node has an array of children which are ordered, so you can treat nodes both as keys inside a parent virtual object, as well as arrays of the nodes they contain.

**Comment by wemrysi** [comment]
> It's most important to support existing MarkLogic installations since they will drive support of this connector.

That's what we figured as well, thanks for the confirmation.

> I don't have time to work this out right at the moment, but I'd use some expansion like foo.bar.baz[*] into something like foo > bar > baz > * (using CSS instead of XQuery here). Every node has an array of children which are ordered, so you can treat nodes both as keys inside a parent virtual object, as well as arrays of the nodes they contain.

I like that and we're doing something similar to that currently to implement projections. Though when we have to store some EJSON/Data that looks like `{"foo": ["bar", ["baz", "quux"]]}` we need some sort of embedding to represent the nested arrays (along with top-level objects and arrays). I also figured that users shouldn't have to know about our embedding to query this data, i.e. if we encoded this as (for example)

```xml
<foo>
  <ejson:array>
    <ejson:array-element>bar</ejson:array-element>
    <ejson:array-element>
      <ejson:array>
        <ejson:array-element>baz</ejson:array-element>
        <ejson:array-element>quux</ejson:array-element>
      </ejson:array>
    </ejson:array-element>
  </ejson:array>
</foo>
```
a user should be able to `foo[1][0]` and not have to `foo.ejson:array[1].ejson:array-element.ejson:array[0].ejson:array-element`.

There is also the practice of repeating elements to represent a list, i.e.
```xml
<order>
  <name>foo</name>
  <line-item>1</line-item>
  <line-item>2</line-item>
</order>
```
as
```json
{"order": {"name": "foo", "line-item": [1, 2]}}
```
it would seem nice to be able to support that as well, but not sure how to distinguish between "repeated elements as an array" and "the children of this element as an array", maybe attempting both is overly ambitious? Is one preferable to the other?
