### ISSUE TITLE
Show Table Card off by one column

### ISSUE THREAD

**Issue by damonLL** [quasar-analytics/quasar#1419]
Looks like certain data sets can throw off the columns in the Show Table Card.

Reproduce:
1. Upload the waze-jams.json file into SlamData
2. Click on waze-jams.json collection to create new workspace
3. Notice that several columns and data don't match up to the source json file

Screenshot of Show Table:

![ui-columns](https://cloud.githubusercontent.com/assets/7375598/18358926/139374ba-75bd-11e6-8872-8c0c106084b4.png)

Guessing here, but maybe the `segments` array in the JSON doc might be throwing the UI off because it is comprised of many empty documents like this:

```
      "segments": [
        {},
        {},
        {},
        {},
        {},
        {},
        {}
      ]
```

**Comment by damonLL** [comment]
Here is the collection, maybe rename it to .json if you have to.

[waze-jams.txt](https://github.com/quasar-analytics/quasar/files/462238/waze-jams.txt)

**Comment by wemrysi** [comment]
@damonLL If this is still an issue, please file it over at [slamdata/slamdata](https://github.com/slamdata/slamdata/issues).
