### ISSUE TITLE
Request for enhancement: connection troubleshooting

### ISSUE THREAD

**Issue by damonLL** [quasar-analytics/quasar#1431]
Attempting to connect with Percona's MongoDB server, which admittedly we don't currently list as supported, results in an error:

```Warning: Failed to mount '/c7/' because 'Connection failed: For input string: "8-2"'.```

The only parameters given were hostname, port and mount type.  Connecting via mongo shell was successful with no additional parameters beyond hostname and port.

Quasar / SlamData log files provide no additional information.  MongoDB log file shows that connections were made but then immediately disconnected:

```
2016-09-12T14:40:51.978-0500 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:41742 #24 (1 connection now open)
2016-09-12T14:40:58.592-0500 I NETWORK  [initandlisten] connection accepted from 192.168.138.1:56864 #25 (2 connections now open)
2016-09-12T14:40:58.594-0500 I NETWORK  [initandlisten] connection accepted from 192.168.138.1:56865 #26 (3 connections now open)
2016-09-12T14:40:58.597-0500 I NETWORK  [conn26] end connection 192.168.138.1:56865 (2 connections now open)
2016-09-12T14:40:58.597-0500 I NETWORK  [conn25] end connection 192.168.138.1:56864 (1 connection now open)
```

From a user / customer perspective I don't think there are any other troubleshooting steps that can be taken beyond modifying code to possibly extract more meaningful information.

@mossprescott asked that I submit an enhancement request as several questions should be answered:

- Should we log it?
- How / where to log it?
- Include the entire stack trace?

**Comment by damonLL** [comment]
Verified that uninstalling Percona 3.2.9 server and reinstalling MongoDB 3.2.9 works as expected with identical parameters.

**Comment by mossprescott** [comment]
Given the desire to get this into 3.1, I'm planning to do something very simple here: I'll include the entire description of the exception that is caught, along with any "cause" exceptions, in the response. That won't give us access to the stack trace, but it will probably help explain the mysterious "For input string" message. @damonLL, I'll let you know when there's a build available in case you want to try it on Percona again.

I'd like to see us come up with a design for logging in the quasar server that helps with troubleshooting and gives the quasar admin some control, but I don't see that happening right now and I don't think it's all that helpful to add something half-baked.

**Comment by jdegoes** [comment]
@mossprescott Yes, the main point of this ticket should be to return better information (through the normal error reporting mechanisms) when a backend fails to connect, not to add log statements.

**Comment by jdegoes** [comment]
@mossprescott How's this coming along?
