### ISSUE TITLE
mongodb: bad interaction with `[{ "x": x, "y": y } ...]`

### ISSUE THREAD

**Issue by sellout** [quasar-analytics/quasar#1451]
This is a problem in the pre-MRA connector. We’ll have to see if it still exists in the new one.

``` sql
select state, city, [{"pop": pop, "loc": loc} ...] from zips group by state, city
```

For some reason this ends up generating a plan that groups correctly, but then unwinds and groups incorrectly. The final query takes a long time to run (and is wrong anyway).

(BTW, `[ ...]` is added in #1449, so this case will fail for other reasons if that hasn’t been merged yet)

**Comment by jdegoes** [comment]
@natefaubion Is this a blocker for pivot table?

**Comment by natefaubion** [comment]
@jdegoes, as far as I know it is not, but we are currently operating under the assumption that multiple UnshiftArray aggregations will result in arrays that line up (or could be correctly transposed into this form). @sellout mentioned that he believes this is the behavior, but if we wanted to guarantee it, we'd have to use the above form.

**Comment by sellout** [comment]
Fixed in new Mongo.

**Comment by zeeiyerWork** [comment]
Added "status: On hold" - these in case of Mongo means, that these are fixed in new Mongo, but can't be marked as Done/Closed until merge to Master.

**Comment by rintcius** [comment]
verified
