### ISSUE TITLE
Cannot query/filter out `NaN` value

### ISSUE THREAD

**Issue by oleg-rdk** [quasar-analytics/quasar#1458]
When `NaN` value is getting into query output, we get short quasar message:

```
SELECT number FROM `/database/collection` WHERE Timestamp = 1469578582636
Quasar error: null
```

There is also no syntax to filter our `NaN` from query output:

```
SELECT number FROM `/database/collection` WHERE number <> NaN
MongoDB
db.collection.aggregate(
  [
    {
      "$project": { "number": true, "__tmp0": { "$ne": ["$number", "$NaN"] } }
    },
    { "$match": { "__tmp0": true } },
    { "$limit": NumberLong("11") },
    { "$project": { "number": true, "_id": false } }],
  { "allowDiskUse": true });

```

The only way to get `NaN` is to use `TO_STRING` function, but this is the worst case.

**Comment by jdegoes** [comment]
@zeeiyerWork Let's get this done ASAP.

**Comment by jdegoes** [comment]
@zeeiyerWork i.e. before July (May, early June). We have a client depending on it.

**Comment by sellout** [comment]
@rintcius This might be a good ticket to deal with. I’m not sure if it’s Mongo-specific. If we’re lucky, the NaN is returned to us as a BsonDouble, and only explodes once we try to convert the results to JSON, which has no notion of NaN.

Aside: should EJson represent NaN (and the infinities)?

**Comment by sellout** [comment]
Also, @damon’s duplicate (#2221) shows JSON with a literal NaN in it. This isn’t valid JSON, but it seems like Mongo accepts this syntax, so creating data with NaN should be easy.

**Comment by zeeiyerWork** [comment]
@rintcius , @sellout -> Based on recommendations have moved this to May, since there is a customer querying about this.

**Comment by sellout** [comment]
@garyb has suggested treating NaN as an undefined value for our results. I think that makes sense. And I _think_ operationally, IEEE NaN behavior matches our behavior for undefined values.

This would also lead me to _not_ want to encode NaN explicitly in EJson.

**Comment by damonLL** [comment]
@sellout and @zeeiyerWork - reminder that a customer is waiting on this for their JumpStart to move forward. Thank you!

**Comment by zeeiyerWork** [comment]
Hi guys - this is in the May iteration.Are we following what @garyb suggests and if so, what needs to happen to include this in 4.2.2 (which we will release towards end of next week, before Spark summit).

**Comment by rintcius** [comment]
I should have the PR up pretty soon now
