### ISSUE TITLE
Avoid `Reduce`-ing `ShiftedReads` into a map only to immediately `LeftShift`

### ISSUE THREAD

**Issue by wemrysi** [quasar-analytics/quasar#1480]
The query `select count(*) from /explain/data` has the following logical plan
```
Invoke(SQUASH)
 ╰─ Invoke(MAKE_OBJECT)
    ├─ Str("0")
    ╰─ Invoke(COUNT)
       ╰─ Read(/explain/data)
```

which is translated into the following QScript
```
List
 ├─ Read(Read(/quasar-test/run_784f6b88/explain/data))
 ├─ LeftShift((),ZipMapKeys(SrcHole),ConcatArrays(MakeArray(LeftSide), MakeArray(RightSide)))
 │  ╰─ ExternallyManaged(Extern)
 ╰─ Reduce((),Constant(Null()),[Count(ProjectIndex(ProjectIndex(SrcHole, Constant(Int(1))), Constant(Int(1))))],MakeMap(Constant(Str(0)), ReduceIndex(0)))
    ╰─ ExternallyManaged(Extern)
```
applying the `ShiftRead` transformation to this yields
```
List
 ├─ ShiftedRead(ShiftedRead(/quasar-test/run_784f6b88/explain/data, IdStatus(IncludeId)))
 ├─ Reduce((),Constant(Null()),[UnshiftMap(ProjectIndex(SrcHole, Constant(Int(0))), ProjectIndex(SrcHole, Constant(Int(1))))],ReduceIndex(0))
 │  ╰─ ExternallyManaged(Extern)
 ├─ LeftShift((),ZipMapKeys(SrcHole),ConcatArrays(MakeArray(LeftSide), MakeArray(RightSide)))
 │  ╰─ ExternallyManaged(Extern)
 ╰─ Reduce((),Constant(Null()),[Count(ProjectIndex(ProjectIndex(SrcHole, Constant(Int(1))), Constant(Int(1))))],MakeMap(Constant(Str(0)), ReduceIndex(0)))
    ╰─ ExternallyManaged(Extern)
```
and therein lies the rub as `ShiftedRead` yields a data set, which is then `Reduce`-d into a single map and finally `LeftShift`-ed back into a data set to be `Reduce`-d via `Count`. It'd be great if the original data set yielded by `ShiftedRead` could just be used instead.

**Comment by sellout** [comment]
Working on this now.

The “problem” is the `ZipMapKeys` getting in the way of the (simplistic) cancelation. I _think_ in this case, `ZipMapKeys` is failing to be optimized away when it should be, but it might also make sense to enrich cancelation a bit to do it even with `ZipMapKeys` there.
