### ISSUE TITLE
Mongo Connection Failing

### ISSUE THREAD

**Issue by SankarMittapally** [quasar-analytics/quasar#1482]
Hi,

 I am trying to establish mongo connection, but it is failing with below error. Can you please tell me what went wrong here and how to fix this.

There was a problem saving the mount: An unknown error ocurred: 500 "{ \"error\": { \"status\": \"Connection to backend failed.\", \"detail\":
{ \"message\": \"Connection failed: For input string: \\"8-2\\".\" }
} }"

**Comment by mossprescott** [comment]
This was filed and fixed as #1488.

**Comment by SankarMittapally** [comment]
still i am facing the same issue

**Comment by SankarMittapally** [comment]
I build the jar with latest code!!

**Comment by mossprescott** [comment]
@SankarMittapally Can you post the version you're running now and the error details?

**Comment by SankarMittapally** [comment]
@mossprescott Please find the details below.

[sankar@alluxio quasar]$ git branch
* master
[sankar@alluxio quasar]$ git log -1
commit 317114e4f6da5c9ec81db82e8a9f9d46240ca60f
Merge: b0b07e5 f0171f2
Author: Greg Pfeil <greg@technomadic.org>
Date:   Thu Oct 6 21:55:24 2016 -0600

    Merge branch 'sellout-fix-take-drop'
[sankar@alluxio quasar]$
![quasar](https://cloud.githubusercontent.com/assets/13848964/19179296/60188b4a-8c79-11e6-8c2e-73f8c80ee89e.PNG)

**Comment by sellout** [comment]
@SankarMittapally That `git log` output looks right, but the version it matches is 12.3.4, not 11.8.15 (look in the version.sbt file to confirm).

Is it possible you still had a version of Quasar running from before, and you’re connecting to that rather than the new one?

**Comment by SankarMittapally** [comment]
This is the first time I am using quasar for internal purpose.  Version is same but I am not sure why it is showing 11.8.15. 

[sankar@alluxio quasar]$ cat version.sbt
version in ThisBuild := "12.3.4"
[sankar@alluxio quasar]$

**Comment by SankarMittapally** [comment]
@sellout My bad!!.. I used wrong jar while starting.

**Comment by SankarMittapally** [comment]
Warning: Failed to mount '/' because 'Connection failed: java.util.concurrent.TimeoutException: Timed out attempting to connect to:

Getting this, I see the database connecting properly from command line.

**Comment by mossprescott** [comment]
@SankarMittapally Were you ever able to get Quasar to connect to your MongoDB instance? That timeout usually just means you have the wrong host or port, or mongo isn't actually running. If you give me some more details I might be able to help.
