### ISSUE TITLE
MongoDB connection fails if the server version contains anything other than x.y.z

### ISSUE THREAD

**Issue by mossprescott** [quasar-analytics/quasar#1488]
See https://github.com/quasar-analytics/quasar/pull/1474#issuecomment-250755716.

Awaiting confirmation from @damonLL that this is causing the issue reported in #1431, but in any case it's clear that version parsing code is unsafe and will throw an exception if the version string is anything other than digits separated by dots.

**Comment by damonLL** [comment]
Think that's it!  Customers version is 3.2.7-50-g67602c7

Nice work gents, thanks!
