### ISSUE TITLE
avoid creating one-sided joins in autojoin

### ISSUE THREAD

**Issue by alissapajer** [quasar-analytics/quasar#1529]
Currently we create joins (in `autojoin`) even when one side is a constant value (e.g. `Map(Unreferenced, Constant(Int(12)))`). Then later we attempt to normalize them away with `Optimize.elideOneSidedJoin`. In all the `autojoin` cases we can avoid creating them in the first place.

We will still keep `elideOneSidedJoin` around to catch potential other cases, but it will share most of its logic with the `ThetaJoin` avoidance logic.

May help us toward fixing #1411 since we hit the "unsupported order function" because the constant string value representing the ordering is hidden inside a `ThetaJoin`.

**Comment by jdegoes** [comment]
@alissapajer Is this a candidate for 3.1 or should it be in 3.2?

**Comment by alissapajer** [comment]
@jdegoes when is the official final date for 3.1?

**Comment by alissapajer** [comment]
I'm working on this now as an approach to fix #1411, which itself is in 3.1. So I'll label this 3.1.

**Comment by jdegoes** [comment]
Next Friday.
