### ISSUE TITLE
self-joins get elided

### ISSUE THREAD

**Issue by sellout** [quasar-analytics/quasar#1539]
Joining a table against itself gets treated as an auto-join and elided, when it shouldn’t be.

**Comment by alissapajer** [comment]
@sellout can you confirm this example triggers the bug you have in mind?
```
select a1.foo, a1.bar from ack a1, ack a2 where a1.xyz = a2.xyz
```

**Comment by alissapajer** [comment]
A slightly better example, and one that compiles in SQL^2 (the `as` for the table alias is required).

```
select z1.foo, z2.bar from zips as z1, zips as z2 where z1.xyz = z2.pqr
```

**Comment by alissapajer** [comment]
Note to self: this query should be an integration test if it's not already.

**Comment by alissapajer** [comment]
This requires a first-class representation of joins in `LogicalPlan`. That way we can reference the left and right sides separately, even though they may be the same dataset.

**Comment by alissapajer** [comment]
Pertinent self-join information is currently being held in let-bindings in the logical plan, which we elide in QScript.

**Comment by alissapajer** [comment]
Fixable after #1943 is fixed.

**Comment by alissapajer** [comment]
Verified that with #1943 fix "selfjoinWithComplexCondition.test" and "selfjoinConstantOnLeft.test" both pass in Spark.
