### ISSUE TITLE
Verify basic analytic query in QScript

### ISSUE THREAD

**Issue by jdegoes** [quasar-analytics/quasar#1541]
Verify that QScript generated by a basic analytic query is optimized correctly.

``` sql
SELECT 
  state, 
  COUNT(*) AS count, SUM(pop) AS sum, AVG(pop) AS avg, MIN(pop) AS min, MAX(pop) AS max
FROM 
  `/zips/`
WHERE 
  pop > 100000
GROUP BY
  state
ORDER BY
  max DESC, state
OFFSET 1
LIMIT 100
```

**Comment by sellout** [comment]
I think this works as of #1640. The QScript looks right to me, but we’ll have to test it on MarkLogic (or something) to verify.

**Comment by jdegoes** [comment]
@sellout I added an `ORDER BY`, `OFFSET`, `LIMIT` too, just to make it more representative of the type of query the front-end would generate.

**Comment by sellout** [comment]
So, I _think_ this new query also works (although it’s difficult to tell until #1628 is merged … or until it’s tested on a connector).

**Comment by jdegoes** [comment]
@sellout Then let's get #1628 merged as it will enable minimally functioning connectors! 😄

**Comment by sellout** [comment]
#1628 is merged, but that just shows us the plan in a readable way – I gotta get #1640 merged now …

**Comment by sellout** [comment]
@wemrysi Now that #1640 is merged, could you try this query on MarkLogic? I _think_ the plan is correct at this point.

**Comment by wemrysi** [comment]
I made a minor modification to the query to sort `max DESC` for a bit more interesting output and got

`{ "state": "NY", "count": 3, "sum": 317987, "avg": 105995.666666667, "min": 100027, "max": 111396 }`

so :+1:

**Comment by jdegoes** [comment]
@sellout It'd be nice to codify this in a test so we can ensure that it won't regress.
