### ISSUE TITLE
Make Path a proper ADT with type safety

### ISSUE THREAD

**Issue by mossprescott** [quasar-analytics/quasar#155]
Certain operations on `Path`s make sense only for absolute paths and some only for relative paths, and the current representation of file vs. directory paths is awkward.

For example, the right argument of `++` should always be a relative path.

Also, it might make sense to have other things a path can be relative to besides "nothing" (i.e. absolute) and "." (i.e. relative).

See this [discussion](#152).

**Comment by sellout** [comment]
We’ve decided on pathy for this, so now it’s just a matter of replacing all uses of slamengine’s Path with pathy’s Path.
