### ISSUE TITLE
Refactor normalization to make it easier for connectors.

### ISSUE THREAD

**Issue by sellout** [quasar-analytics/quasar#1553]
Right now, it is difficult for a connector to apply the correct set of operations to normalize their transformed QScript. They have to choose a few depending on which components exist in their representation of QScript, and ensure they’re applied until a stable form is reached.

This involves:
1. automatically applying normalization (and optimization) until a stable form is reached,
2. somehow abstracting over the coproduct so we can automatically apply the correct set of operations.

**Comment by alissapajer** [comment]
@djspiewak this might be something you address in your work towards the fallback evaluator. If so, feel free to move this back to 4.2.

**Comment by sellout** [comment]
@djspiewak I think you’ve fixed this with Unicoalesce, no?

**Comment by djspiewak** [comment]
👍
