### ISSUE TITLE
When I executed ./sbt test,following error

### ISSUE THREAD

**Issue by wofish** [quasar-analytics/quasar#1561]
Don't konw if this will offend you. Please forgive me my English is not very good.
when i execute " ./sbt test ",following error:
[info] ServiceSpec
[info] 
[info] /mount/fs should
[info]   + POST view
[info]   + PUT view
[info]   + [SD-1833] replace view
[info]   + MOVE view
[info] /data/fs should
[error]   x MOVE view
[error]    not(fileSystemConfigs empty) because Map() is empty (ServiceSpec.scala:183)
[info] 
[info]   o MOVE a directory containing views and files
[info] not(fileSystemConfigs empty) because Map() is empty, but test is marked as flaky ('\/-(404 Path not found.)' is not \/- with value'200 OK')
[info] 
[info] 
[info] Total for specification ServiceSpec
[info] Finished in 39 seconds, 990 ms
[info] 6 examples, 7 expectations, 1 failure, 0 error, 1 skipped
[info] 
[error] 
[error] cannot create an instance for class quasar.ResultFileQueryRegressionSpec
[error]   caused by java.lang.RuntimeException: No external backends to test. Consider setting one of these environment variables: QUASAR_MONGODB_2_6, QUASAR_MONGODB_3_0, QUASAR_MONGODB_3_2, QUASAR_MONGODB_READ_ONLY, QUASAR_SKELETON, QUASAR_POSTGRESQL, QUASAR_SPARK_LOCAL, QUASAR_SPARK_HDFS, QUASAR_MARKLOGIC, QUASAR_COUCHBASE
[error] 
[error] STACKTRACE
[error]   sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error]   sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error]   sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error]   java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[error]   org.specs2.reflect.Classes$$anonfun$createInstanceForConstructor$1.apply(Classes.scala:61)
[error]   org.specs2.reflect.Classes$class.org$specs2$reflect$Classes$$newInstance(Classes.scala:83)
[error]   org.specs2.reflect.Classes$class.createInstanceForConstructor(Classes.scala:61)
[error]   org.specs2.reflect.Classes$class.org$specs2$reflect$Classes$$findInstance(Classes.scala:47)
[error]   org.specs2.reflect.Classes$class.createInstanceFromClass(Classes.scala:29)
[error]   org.specs2.reflect.Classes$.createInstanceFromClass(Classes.scala:109)
[error]   org.specs2.reflect.Classes$$anonfun$createInstance$1.apply(Classes.scala:25)
[error]   org.specs2.reflect.Classes$$anonfun$createInstance$1.apply(Classes.scala:24)
[error]   org.specs2.control.eff.Arrs.go$2(Eff.scala:246)
[error]   org.specs2.control.eff.Arrs.apply(Eff.scala:253)
[error]   org.specs2.control.eff.Interpret$$anon$1$$anonfun$onEffect$1.apply(Interpret.scala:53)
[error]   org.specs2.control.eff.Interpret$$anon$1$$anonfun$onEffect$1.apply(Interpret.scala:53)
[error]   scalaz.$bslash$div.bimap(Either.scala:91)
[error]   org.specs2.control.eff.Interpret$$anon$1.onEffect(Interpret.scala:53)
[error]   org.specs2.control.eff.Interpret$$anon$1.onEffect(Interpret.scala:45)
[error]   org.specs2.control.eff.Interpret$class.go$1(Interpret.scala:131)
[error]   org.specs2.control.eff.Interpret$class.interpretLoop(Interpret.scala:142)
[error]   org.specs2.control.eff.Interpret$.interpretLoop(Interpret.scala:230)
[error]   org.specs2.control.eff.Interpret$class.interpret(Interpret.scala:55)
[error]   org.specs2.control.eff.Interpret$.interpret(Interpret.scala:230)
[error]   org.specs2.control.eff.Interpret$class.interpret1(Interpret.scala:62)
[error]   org.specs2.control.eff.Interpret$.interpret1(Interpret.scala:230)
[error]   org.specs2.control.eff.ErrorInterpretation$class.runError(ErrorEffect.scala:77)
[error]   org.specs2.control.eff.ErrorEffect$.runError(ErrorEffect.scala:129)
[error]   org.specs2.control.eff.syntax.error$ErrorEffectOps.runError(error.scala:15)
[error]   org.specs2.control.package$.executeAction(package.scala:48)
[error]   org.specs2.runner.SbtRunner$$anon$4.specStructure$lzycompute(SbtRunner.scala:41)
[error]   org.specs2.runner.SbtRunner$$anon$4.specStructure(SbtRunner.scala:38)
[error]   org.specs2.runner.SbtRunner$$anon$4.execute(SbtRunner.scala:52)
[error]   sbt.TestRunner.runTest$1(TestFramework.scala:76)
[error]   sbt.TestRunner.run(TestFramework.scala:85)
[error]   sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[error]   sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[error]   sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
[error]   sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[error]   sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[error]   sbt.TestFunction.apply(TestFramework.scala:207)
[error]   sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
[error]   sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[error]   sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[error]   sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[error]   sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[error]   sbt.std.Transform$$anon$4.work(System.scala:63)
[error]   sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[error]   sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[error]   sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[error]   sbt.Execute.work(Execute.scala:237)
[error]   sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[error]   sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[error]   sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[error]   sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[error]   java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]   java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]   java.lang.Thread.run(Thread.java:745)
[error] 
[error]   CAUSED BY java.lang.RuntimeException: No external backends to test. Consider setting one of these environment variables: QUASAR_MONGODB_2_6, QUASAR_MONGODB_3_0, QUASAR_MONGODB_3_2, QUASAR_MONGODB_READ_ONLY, QUASAR_SKELETON, QUASAR_POSTGRESQL, QUASAR_SPARK_LOCAL, QUASAR_SPARK_HDFS, QUASAR_MARKLOGIC, QUASAR_COUCHBASE
[error]   quasar.TestConfig$.noBackendsFound$1(TestConfig.scala:117)
[error]   quasar.TestConfig$.quasar$TestConfig$$$anonfun$20(TestConfig.scala:124)
[error]   scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:35)
[error]   scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:35)
[error]   scalaz.concurrent.Task$.Try(Task.scala:448)
[error]   scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:35)
[error]   scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:33)
[error]   scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
[error]   scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
[error]   scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:58)
[error]   scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:58)
[error]   scalaz.concurrent.Future.step(Future.scala:118)
[error]   scalaz.concurrent.Future.unsafePerformListen(Future.scala:75)
[error]   scalaz.concurrent.Future.unsafePerformAsync(Future.scala:159)
[error]   scalaz.concurrent.Future.unsafePerformSync(Future.scala:184)
[error]   scalaz.concurrent.Task.unsafePerformSync(Task.scala:99)
[error]   quasar.fs.FileSystemTest.fileSystemShould(FileSystemTest.scala:62)
[error]   quasar.regression.QueryRegressionTest.<init>(QueryRegressionTest.scala:90)
[error]   quasar.ResultFileQueryRegressionSpec.<init>(ResultFileQueryRegressionSpec.scala:30)
[error]   sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error]   sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error]   sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error]   java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[error]   org.specs2.reflect.Classes$$anonfun$createInstanceForConstructor$1.apply(Classes.scala:61)
[error]   org.specs2.reflect.Classes$class.org$specs2$reflect$Classes$$newInstance(Classes.scala:83)
[error]   org.specs2.reflect.Classes$class.createInstanceForConstructor(Classes.scala:61)
[error]   org.specs2.reflect.Classes$class.org$specs2$reflect$Classes$$findInstance(Classes.scala:47)
[error]   org.specs2.reflect.Classes$class.createInstanceFromClass(Classes.scala:29)
[error]   org.specs2.reflect.Classes$.createInstanceFromClass(Classes.scala:109)
[error]   org.specs2.reflect.Classes$$anonfun$createInstance$1.apply(Classes.scala:25)
[error]   org.specs2.reflect.Classes$$anonfun$createInstance$1.apply(Classes.scala:24)
[error]   org.specs2.control.eff.Arrs.go$2(Eff.scala:246)
[error]   org.specs2.control.eff.Arrs.apply(Eff.scala:253)
[error]   org.specs2.control.eff.Interpret$$anon$1$$anonfun$onEffect$1.apply(Interpret.scala:53)
[error]   org.specs2.control.eff.Interpret$$anon$1$$anonfun$onEffect$1.apply(Interpret.scala:53)
[error]   scalaz.$bslash$div.bimap(Either.scala:91)
[error]   org.specs2.control.eff.Interpret$$anon$1.onEffect(Interpret.scala:53)
[error]   org.specs2.control.eff.Interpret$$anon$1.onEffect(Interpret.scala:45)
[error]   org.specs2.control.eff.Interpret$class.go$1(Interpret.scala:131)
[error]   org.specs2.control.eff.Interpret$class.interpretLoop(Interpret.scala:142)
[error]   org.specs2.control.eff.Interpret$.interpretLoop(Interpret.scala:230)
[error]   org.specs2.control.eff.Interpret$class.interpret(Interpret.scala:55)
[error]   org.specs2.control.eff.Interpret$.interpret(Interpret.scala:230)
[error]   org.specs2.control.eff.Interpret$class.interpret1(Interpret.scala:62)
[error]   org.specs2.control.eff.Interpret$.interpret1(Interpret.scala:230)
[error]   org.specs2.control.eff.ErrorInterpretation$class.runError(ErrorEffect.scala:77)
[error]   org.specs2.control.eff.ErrorEffect$.runError(ErrorEffect.scala:129)
[error]   org.specs2.control.eff.syntax.error$ErrorEffectOps.runError(error.scala:15)
[error]   org.specs2.control.package$.executeAction(package.scala:48)
[error]   org.specs2.runner.SbtRunner$$anon$4.specStructure$lzycompute(SbtRunner.scala:41)
[error]   org.specs2.runner.SbtRunner$$anon$4.specStructure(SbtRunner.scala:38)
[error]   org.specs2.runner.SbtRunner$$anon$4.execute(SbtRunner.scala:52)
[error]   sbt.TestRunner.runTest$1(TestFramework.scala:76)
[error]   sbt.TestRunner.run(TestFramework.scala:85)
[error]   sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[error]   sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[error]   sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
[error]   sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[error]   sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[error]   sbt.TestFunction.apply(TestFramework.scala:207)
[error]   sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
[error]   sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[error]   sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[error]   sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[error]   sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[error]   sbt.std.Transform$$anon$4.work(System.scala:63)
[error]   sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[error]   sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[error]   sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[error]   sbt.Execute.work(Execute.scala:237)
[error]   sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[error]   sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[error]   sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[error]   sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[error]   java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]   java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]   java.lang.Thread.run(Thread.java:745)
[error]  
[info] CompileServiceSpec
[info] 
[info] Compile should
[info]   + plan simple query
[info]   + plan query with var
[info]   + return all inputs of a query
[info]   + plan a constant query
[info] 
[info] 
[info] Total for specification CompileServiceSpec
[info] Finished in 30 seconds, 785 ms
[info] 4 examples, 202 expectations, 0 failure, 0 error
[info] 
[error] 
[error] cannot create an instance for class quasar.physical.mongodb.fs.MongoDbFileSystemSpec
[error]   caused by java.lang.RuntimeException: No external backends to test. Consider setting one of these environment variables: QUASAR_MONGODB_2_6, QUASAR_MONGODB_3_0, QUASAR_MONGODB_3_2, QUASAR_MONGODB_READ_ONLY, QUASAR_SKELETON, QUASAR_POSTGRESQL, QUASAR_SPARK_LOCAL, QUASAR_SPARK_HDFS, QUASAR_MARKLOGIC, QUASAR_COUCHBASE
[error] 
[error] STACKTRACE
[error]   sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error]   sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error]   sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error]   java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[error]   org.specs2.reflect.Classes$$anonfun$createInstanceForConstructor$1.apply(Classes.scala:61)
[error]   org.specs2.reflect.Classes$class.org$specs2$reflect$Classes$$newInstance(Classes.scala:83)
[error]   org.specs2.reflect.Classes$class.createInstanceForConstructor(Classes.scala:61)
[error]   org.specs2.reflect.Classes$class.org$specs2$reflect$Classes$$findInstance(Classes.scala:47)
[error]   org.specs2.reflect.Classes$class.createInstanceFromClass(Classes.scala:29)
[error]   org.specs2.reflect.Classes$.createInstanceFromClass(Classes.scala:109)
[error]   org.specs2.reflect.Classes$$anonfun$createInstance$1.apply(Classes.scala:25)
[error]   org.specs2.reflect.Classes$$anonfun$createInstance$1.apply(Classes.scala:24)
[error]   org.specs2.control.eff.Arrs.go$2(Eff.scala:246)
[error]   org.specs2.control.eff.Arrs.apply(Eff.scala:253)
[error]   org.specs2.control.eff.Interpret$$anon$1$$anonfun$onEffect$1.apply(Interpret.scala:53)
[error]   org.specs2.control.eff.Interpret$$anon$1$$anonfun$onEffect$1.apply(Interpret.scala:53)
[error]   scalaz.$bslash$div.bimap(Either.scala:91)
[error]   org.specs2.control.eff.Interpret$$anon$1.onEffect(Interpret.scala:53)
[error]   org.specs2.control.eff.Interpret$$anon$1.onEffect(Interpret.scala:45)
[error]   org.specs2.control.eff.Interpret$class.go$1(Interpret.scala:131)
[error]   org.specs2.control.eff.Interpret$class.interpretLoop(Interpret.scala:142)
[error]   org.specs2.control.eff.Interpret$.interpretLoop(Interpret.scala:230)
[error]   org.specs2.control.eff.Interpret$class.interpret(Interpret.scala:55)
[error]   org.specs2.control.eff.Interpret$.interpret(Interpret.scala:230)
[error]   org.specs2.control.eff.Interpret$class.interpret1(Interpret.scala:62)
[error]   org.specs2.control.eff.Interpret$.interpret1(Interpret.scala:230)
[error]   org.specs2.control.eff.ErrorInterpretation$class.runError(ErrorEffect.scala:77)
[error]   org.specs2.control.eff.ErrorEffect$.runError(ErrorEffect.scala:129)
[error]   org.specs2.control.eff.syntax.error$ErrorEffectOps.runError(error.scala:15)
[error]   org.specs2.control.package$.executeAction(package.scala:48)
[error]   org.specs2.runner.SbtRunner$$anon$4.specStructure$lzycompute(SbtRunner.scala:41)
[error]   org.specs2.runner.SbtRunner$$anon$4.specStructure(SbtRunner.scala:38)
[error]   org.specs2.runner.SbtRunner$$anon$4.execute(SbtRunner.scala:52)
[error]   sbt.TestRunner.runTest$1(TestFramework.scala:76)
[error]   sbt.TestRunner.run(TestFramework.scala:85)
[error]   sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[error]   sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[error]   sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
[error]   sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[error]   sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[error]   sbt.TestFunction.apply(TestFramework.scala:207)
[error]   sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
[error]   sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[error]   sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[error]   sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[error]   sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[error]   sbt.std.Transform$$anon$4.work(System.scala:63)
[error]   sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[error]   sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[error]   sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[error]   sbt.Execute.work(Execute.scala:237)
[error]   sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[error]   sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[error]   sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[error]   sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[error]   java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]   java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]   java.lang.Thread.run(Thread.java:745)
[error] 
[error]   CAUSED BY java.lang.RuntimeException: No external backends to test. Consider setting one of these environment variables: QUASAR_MONGODB_2_6, QUASAR_MONGODB_3_0, QUASAR_MONGODB_3_2, QUASAR_MONGODB_READ_ONLY, QUASAR_SKELETON, QUASAR_POSTGRESQL, QUASAR_SPARK_LOCAL, QUASAR_SPARK_HDFS, QUASAR_MARKLOGIC, QUASAR_COUCHBASE
[error]   quasar.TestConfig$.noBackendsFound$1(TestConfig.scala:117)
[error]   quasar.TestConfig$.quasar$TestConfig$$$anonfun$20(TestConfig.scala:124)
[error]   scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:35)
[error]   scalaz.concurrent.Task$$anonfun$flatMap$1$$anonfun$1.apply(Task.scala:35)
[error]   scalaz.concurrent.Task$.Try(Task.scala:448)
[error]   scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:35)
[error]   scalaz.concurrent.Task$$anonfun$flatMap$1.apply(Task.scala:33)
[error]   scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
[error]   scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
[error]   scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:58)
[error]   scalaz.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:58)
[error]   scalaz.concurrent.Future.step(Future.scala:118)
[error]   scalaz.concurrent.Future.unsafePerformListen(Future.scala:75)
[error]   scalaz.concurrent.Future.unsafePerformAsync(Future.scala:159)
[error]   scalaz.concurrent.Future.unsafePerformSync(Future.scala:184)
[error]   scalaz.concurrent.Task.unsafePerformSync(Task.scala:99)
[error]   quasar.fs.FileSystemTest.fileSystemShould(FileSystemTest.scala:62)
[error]   quasar.physical.mongodb.fs.MongoDbFileSystemSpec.<init>(MongoDbFileSystemSpec.scala:91)
[error]   sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error]   sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error]   sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error]   java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[error]   org.specs2.reflect.Classes$$anonfun$createInstanceForConstructor$1.apply(Classes.scala:61)
[error]   org.specs2.reflect.Classes$class.org$specs2$reflect$Classes$$newInstance(Classes.scala:83)
[error]   org.specs2.reflect.Classes$class.createInstanceForConstructor(Classes.scala:61)
[error]   org.specs2.reflect.Classes$class.org$specs2$reflect$Classes$$findInstance(Classes.scala:47)
[error]   org.specs2.reflect.Classes$class.createInstanceFromClass(Classes.scala:29)
[error]   org.specs2.reflect.Classes$.createInstanceFromClass(Classes.scala:109)
[error]   org.specs2.reflect.Classes$$anonfun$createInstance$1.apply(Classes.scala:25)
[error]   org.specs2.reflect.Classes$$anonfun$createInstance$1.apply(Classes.scala:24)
[error]   org.specs2.control.eff.Arrs.go$2(Eff.scala:246)
[error]   org.specs2.control.eff.Arrs.apply(Eff.scala:253)
[error]   org.specs2.control.eff.Interpret$$anon$1$$anonfun$onEffect$1.apply(Interpret.scala:53)
[error]   org.specs2.control.eff.Interpret$$anon$1$$anonfun$onEffect$1.apply(Interpret.scala:53)
[error]   scalaz.$bslash$div.bimap(Either.scala:91)
[error]   org.specs2.control.eff.Interpret$$anon$1.onEffect(Interpret.scala:53)
[error]   org.specs2.control.eff.Interpret$$anon$1.onEffect(Interpret.scala:45)
[error]   org.specs2.control.eff.Interpret$class.go$1(Interpret.scala:131)
[error]   org.specs2.control.eff.Interpret$class.interpretLoop(Interpret.scala:142)
[error]   org.specs2.control.eff.Interpret$.interpretLoop(Interpret.scala:230)
[error]   org.specs2.control.eff.Interpret$class.interpret(Interpret.scala:55)
[error]   org.specs2.control.eff.Interpret$.interpret(Interpret.scala:230)
[error]   org.specs2.control.eff.Interpret$class.interpret1(Interpret.scala:62)
[error]   org.specs2.control.eff.Interpret$.interpret1(Interpret.scala:230)
[error]   org.specs2.control.eff.ErrorInterpretation$class.runError(ErrorEffect.scala:77)
[error]   org.specs2.control.eff.ErrorEffect$.runError(ErrorEffect.scala:129)
[error]   org.specs2.control.eff.syntax.error$ErrorEffectOps.runError(error.scala:15)
[error]   org.specs2.control.package$.executeAction(package.scala:48)
[error]   org.specs2.runner.SbtRunner$$anon$4.specStructure$lzycompute(SbtRunner.scala:41)
[error]   org.specs2.runner.SbtRunner$$anon$4.specStructure(SbtRunner.scala:38)
[error]   org.specs2.runner.SbtRunner$$anon$4.execute(SbtRunner.scala:52)
[error]   sbt.TestRunner.runTest$1(TestFramework.scala:76)
[error]   sbt.TestRunner.run(TestFramework.scala:85)
[error]   sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[error]   sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[error]   sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
[error]   sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[error]   sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[error]   sbt.TestFunction.apply(TestFramework.scala:207)
[error]   sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
[error]   sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[error]   sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[error]   sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[error]   sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[error]   sbt.std.Transform$$anon$4.work(System.scala:63)
[error]   sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[error]   sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
[error]   sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[error]   sbt.Execute.work(Execute.scala:237)
[error]   sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[error]   sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
[error]   sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[error]   sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[error]   java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]   java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]   java.lang.Thread.run(Thread.java:745)
[error]  
[error] 
[error] cannot create an instance for class quasar.fs.QueryFilesSpec
[error]   caused by java.lang.RuntimeException: No external backends to test. Consider setting one of these environment variables: QUASAR_MONGODB_2_6, QUASAR_MONGODB_3_0, QUASAR_MONGODB_3_2, QUASAR_MONGODB_READ_ONLY, QUASAR_SKELETON, QUASAR_POSTGRESQL, QUASAR_SPARK_LOCAL, QUASAR_SPARK_HDFS, QUASAR_MARKLOGIC, QUASAR_COUCHBASE
-----------------------------May I ask what is the reason?

**Comment by sellout** [comment]
In all that noise, there is this message:

Consider setting one of these environment variables: QUASAR_MONGODB_2_6, QUASAR_MONGODB_3_0, QUASAR_MONGODB_3_2, QUASAR_MONGODB_READ_ONLY, QUASAR_SKELETON, QUASAR_POSTGRESQL, QUASAR_SPARK_LOCAL, QUASAR_SPARK_HDFS, QUASAR_MARKLOGIC, QUASAR_COUCHBASE

In the README, here is the relevant section: https://github.com/quasar-analytics/quasar#testing-option-2-prerequisite-mongodb You only need to set one – pointing to some MongoDB instance, and then it can run the integration tests.

Alternatively, you can run with a dockerized MongoDB via https://github.com/quasar-analytics/quasar#testing-option-1-prerequisite-docker
