### ISSUE TITLE
Spark connector currently ignores `IncludeId` or `ExcludeId` in `ShiftedRead` QScript term

### ISSUE THREAD

**Issue by jedesah** [quasar-analytics/quasar#1571]
My guess is that no test has exposed this problem yet, but it will eventually.

Concretely the `shiftedRead` test in `quasar.physical.sparkcore.fs.PlannerSpec` is incorrect in this regards. It could be fixed simply by using `ExcludeId` instead of `IncludeId`, but then again, a test should be added to validate that `IncludeId` works properly.

**Comment by sellout** [comment]
I know this has been addressed locally by @rabbitonweb, but not sure if it’s part of a PR yet or not.

**Comment by jedesah** [comment]
Ah, okay, good to know!

**Comment by rabbitonweb** [comment]
It's fixed. In master already.
