### ISSUE TITLE
GroupBy does not work correctly

### ISSUE THREAD

**Issue by rabbitonweb** [quasar-analytics/quasar#1583]
Runnning simple `group by` query gives weird result

QScript (Spark):
Subset((),Reduce(ShiftedRead(/patients.json, ExcludeId),ConcatArrays(MakeArray(ProjectIndex(ProjectIndex(ProjectIndex(ProjectField(Guard(SrcHole, Obj(Map(),Some(Top)), SrcHole, Undefined()), Constant(Str(city))), Constant(Int(0))), Constant(Int(1))), Constant(Int(1)))), MakeArray(MakeMap(Constant(Str(j)), ConcatArrays(MakeArray(ProjectIndex(ProjectIndex(ProjectIndex(ProjectIndex(ProjectField(Guard(SrcHole, Obj(Map(),Some(Top)), SrcHole, Undefined()), Constant(Str(city))), Constant(Int(0))), Constant(Int(0))), Constant(Int(0))), Constant(Int(1)))), MakeArray(ProjectIndex(ProjectIndex(ProjectIndex(ProjectIndex(ProjectField(Guard(SrcHole, Obj(Map(),Some(Top)), SrcHole, Undefined()), Constant(Str(city))), Constant(Int(0))), Constant(Int(1))), Constant(Int(0))), Constant(Int(1)))))))),[Arbitrary(ProjectField(Guard(SrcHole, Obj(Map(),Some(Top)), SrcHole, Undefined()), Constant(Str(city))))],MakeMap(Constant(Str(city)), ReduceIndex(0))),Take,Map(Unreferenced,Constant(Int(11))))
╰─ Unreferenced

RDD:
(2) MapPartitionsRDD[199] at map at Planner.scala:116 []
 |  MapPartitionsRDD[198] at filter at Planner.scala:116 []
 |  ZippedWithIndexRDD[197] at zipWithIndex at Planner.scala:116 []
 |  MapPartitionsRDD[194] at map at Planner.scala:211 []
 |  ShuffledRDD[193] at reduceByKey at Planner.scala:210 []
 +-(2) MapPartitionsRDD[192] at map at Planner.scala:209 []
    |  MapPartitionsRDD[191] at map at Planner.scala:75 []
    |  hdfs://localhost:9000/patients.json MapPartitionsRDD[190] at textFile at queryfile.scala:55 []
    |  hdfs://localhost:9000/patients.json HadoopRDD[189] at textFile at queryfile.scala:55 []

Query time: 0.5s
 city   |
--------|
 MARTY  |

**Comment by sellout** [comment]
It helps if you could include the query, so I know what the plan _should_ look like.

**Comment by rabbitonweb** [comment]
I thought I did :) 

Here you go:

`select city from `/patients.json` group by city`

**Comment by sellout** [comment]
Hrmm, it looks like the provenance is having extra `ProjectIndex`es added to it along the way, otherwise the query is correct.

**Comment by rabbitonweb** [comment]
So it is an error on spark side?

**Comment by sellout** [comment]
Oh, sorry, no – it’s a QScript error.

**Comment by sellout** [comment]
I think this must have been fixed by either #1582 or 12.4.12. Will leave it to @rabbitonweb to verify once #1582 is merged.
