### ISSUE TITLE
CB: Additional QScript terms

### ISSUE THREAD

**Issue by drostron** [quasar-analytics/quasar#1601]
- [x] Arbitrary #1653 
- [x] EJson: Meta, Byte, Char #1686 
- [x] Const(Root) #1602
- [x] TimeOfDay, Extract* #1686 
- [x] IfUndefined #1696
- ~~Coalesce~~ #1604
- ~~DupMapKeys, DupArrayIndices, ZipMapKeys, ZipArrayIndices~~ #1692
- [x] BucketField, BucketIndex #1602

**Comment by sellout** [comment]
You don’t have to provide a real implementation for `Const(Root)` or `BucketField`/`BucketIndex`. If you look at another connector, you’ll see that those (as well as two other cases that depend on your flavor of QScript) are implemented with something like `InternalError("unreachable").left` (depending on the monad of the planner).

I’m also going to remove `Coalesce` – that’s another SQL-ism that should be eliminated prior to LogicalPlan.
