### ISSUE TITLE
Upgrade to scalacheck `1.13.1`

### ISSUE THREAD

**Issue by jedesah** [quasar-analytics/quasar#1609]
`scalaz` has now finally upgraded to scalacheck `1.13.x` which should mean that we can do the same.

We should do this sooner rather than later in order to avoid incompatibilities with other libraries like `refined` as pointed out [over here](https://github.com/fthomas/refined/pull/128#issuecomment-254636310)

**Comment by jedesah** [comment]
I'll do this once I get back to the office because in my experience this kind of thing may require multiple full builds and I would rather not wait after my laptop compile times.

**Comment by paulp** [comment]
This task is way bigger than you realize. It isn't enough for scalaz to upgrade to 1.13. *ALL* the dependencies have to do it.

**Comment by jedesah** [comment]
Perhaps, but I remember going through the exercise once and coming to the conclusion that `scalaz` was the only dependency blocking us from upgrading to the latest version of `scalacheck`. I even vaguely recall documenting that fact, but it looks like I am either mis-remembering or someone deleting my comment in the dependencies file.

Also, I never said it would be easy 😄 . That's precisely why I am not even going to attempt this until I get back to my beefed up desktop because I fully expected to be rebuilding the project a number of times in order to get everything lined up okay.

But if you are insinuating that we have bigger fish to fry and this won't provide much benefit in the short term, I would be inclined to agree and I will hold off from spending any time on it until it makes more sense for the business.

**Comment by paulp** [comment]
Yeah - at the very least wait until matryoshka publishes new artifacts against current scalacheck. You need it anyway, and I had to deal with a subset of the problems you would face here over in https://github.com/slamdata/matryoshka/pull/36 .

**Comment by jedesah** [comment]
Fixed by #1936
