### ISSUE TITLE
Fuse multiple FLWOR expressions

### ISSUE THREAD

**Issue by wemrysi** [quasar-analytics/quasar#1625]
Multiple QScript nodes are implemented as XQuery FLWOR expressions, in many cases these can be consolidated into a single expression and avoid traversing the dataset multiple times.

**Comment by sellout** [comment]
This _may_ be more of a QScript issue. We should be consolidating operations as much as possible.

**Comment by wemrysi** [comment]
Its probably a bit of both, but I'm pretty sure there are `for` expressions that can end up nested just because we're using a different part of the FLWOR expression (i.e. mapping and then sorting, which can be done in a single FLWOR expression but currently happen in two nested ones).

We can also switch to using FLWOR for filtering for more consolidation.

**Comment by jdegoes** [comment]
This looks like a big-oh issue for sure. Unless the MarkLogic optimizer is a LOT smarter than I think it is.
