### ISSUE TITLE
SimplifyJoin

### ISSUE THREAD

**Issue by paulp** [quasar-analytics/quasar#1630]
These are all the ways SimplifyJoin is used outside the file in which it is defined. Is there any difference among them? It looks like everyone is calling `shiftRead(qs).transCata(SimplifyJoin[...] simplifyJoin idPrism.reverseGet)` and possibly more. That's a complicated expression to be living four disconnected lives.

And isn't`idPrism.reverseGet` just `reflNT`? Is it written that way by analogy with coenvPrism.reverseGet? 

We know transCata calls are outrageously slow to compile, so if these four can be one, that would be great.

``` scala
connector/src/test/scala/quasar/qscript/Rewrite.scala
42-  def simplifyJoinExpr(expr: Fix[QS]): Fix[QST] =
43:    expr.transCata[QST](SimplifyJoin[Fix, QS, QST].simplifyJoin(idPrism.reverseGet))
44-

couchbase/src/main/scala/quasar/physical/couchbase/fs/queryfile.scala
232-      shft =  shiftRead(qs).transCata(
233:                SimplifyJoin[Fix, QScriptShiftRead[Fix, ?], CBQScript]
234-                  .simplifyJoin(idPrism.reverseGet))

mongodb/src/main/scala/quasar/physical/mongodb/plannerQScript.scala
865-        shiftRead(qs)
866:          .transCata[MongoQScript](SimplifyJoin[T, QScriptShiftRead[T, ?], MongoQScript].simplifyJoin(idPrism.reverseGet))
867-          .transAna(

sparkcore/src/main/scala/quasar/physical/sparkcore/fs/queryfile.scala
76-        qs <- QueryFile.convertToQScriptRead[Fix, FileSystemErrT[PhaseResultT[Free[S, ?],?],?], QScriptRead[Fix, ?]](lc)(lp).map(shiftRead[Fix](_).transCata(
77:          SimplifyJoin[Fix, QScriptShiftRead[Fix, ?], SparkQScript].simplifyJoin(idPrism.reverseGet)))
78-        optQS = qs.transAna(
```

**Comment by sellout** [comment]
Yeah, hoepefully we’ll get to the point where we actually just do one transformation here, and it composes ShiftRead/SimplifyJoin, etc. at the algebra level, but the way things are now, I think encapsulating these transformations (like @jedesah did for `shiftRead`) is the way to go.

And yes – `idPrism.reverseGet` is `reflNT`. In `Rewrite`, we pass around the whole prism or either half as necessary (and yeah, for both Id and CoEnv), so this was just for consistency with that (of course, it should be `idIso: IsoNT`, but I didn’t want to end up duplicating all of Monocle with natural transformations 😉).
