### ISSUE TITLE
Make `skeleton` connector fail gracefully.

### ISSUE THREAD

**Issue by sellout** [quasar-analytics/quasar#1633]
Right now the skeleton connector (I think) uses `???` for everything, which means catastrophic failures. We want it to fail gracefully, so we don’t lose things like PhaseResults when a query is unsuccessful.

This will make it easier to incrementally implement a connector[†], as well as to make queries against a skeleton mount to get LP, QScript etc. output, when running the same query against a real backend causes some catastrophic failure (see #1631).

[†]: For QScript, the skeleton should fail gracefully on `Read` (or `Root`), but everything else should punt to the fallback evaluator, so that implementing some form of `Read` is enough to get a fully-functioning query handler.

**Comment by wemrysi** [comment]
@sellout Looks like the `skeleton` connector uses the `Empty` filesystem for everything, and not `???`, can this be closed?
