### ISSUE TITLE
Support map keys that aren't valid QNames in MarkLogic

### ISSUE THREAD

**Issue by wemrysi** [quasar-analytics/quasar#1642]
The MarkLogic planner can't currently handle field names/aliases that aren't valid QNames which causes problems with the default numeric field aliases and any user-defined names that don't fall into the QName category.

The most promising idea for solving this thus far is to use an XML attribute to store the field name when it isn't a valid QName. This will require the planner for `ProjectField` to take this into account as well as serialization to/from `Data`.

**Comment by wemrysi** [comment]
Microsoft came up with an [encoding](https://msdn.microsoft.com/en-us/library/35577sxd(v=vs.100).aspx) that might be worth considering.

**Comment by jsantos17** [comment]
@zeeiyerWork current milestone for this is July, however the May iteration issues #1760 and #2124 depend on this. After talking with @wemrysi, we agreed that any workarounds to solve #1760 or #2124 would take a similar amount of work to simply fixing this. So we decided to work on this now. Shall we add this to the May/June iteration?

**Comment by zeeiyerWork** [comment]
@jsantos17 -> Yes of course.  Go ahead and change it to the may iteration.
