### ISSUE TITLE
CB: Result set field order not supported by N1QL

### ISSUE THREAD

**Issue by drostron** [quasar-analytics/quasar#1668]
Some connectors such as Couchbase are unable to specify field order for results. We need a way to either specify field order as result metadata or offer a way to relax it per connector rather than across the board.

This has spread to a few query integration tests already and should be solved before unnecessarily ignoring field order in an increasing number of tests.

**Comment by jdegoes** [comment]
For now, this could be a per-backend setting. Ultimately we want to solve it by post-processing results but we don't have the machinery to easily / performantly do that now.
