### ISSUE TITLE
QScript generation slow for a many column pivot table query

### ISSUE THREAD

**Issue by drostron** [quasar-analytics/quasar#1669]
QScript generation for the following query takes about a minute.

```
SELECT row.`city` AS _0, [row.`first_name` ...] AS _1, [row.`age` ...] AS _2, [row.`last_name` ...] AS _3, [row.`state` ...] AS _4, [row.`height` ...] AS _5, [row.`weight` ...] AS _6, [row.`ssn` ...] AS _7 FROM `/couchbase/demo/Patients Pivot.slam/.tmp/2adac5d6-2813-4fe9-ac7a-e1003522b843/out0` AS row GROUP BY row.city ORDER BY row.city
```

Noticed while testing the Couchbase connector with a pivot table of 7 columns and a single dimension.

**Comment by alissapajer** [comment]
When #1622 is fixed, it will be worth checking the timing on this example again. That ticket will remove large chunks of unused QScript, which would definitely be a possible cause of slow QScript compilation.

**Comment by sellout** [comment]
Just to get a few thoughts out of my head:

1. #1622 is fixed, but this query is still slow
2. it _could_ be that we are doing a lot of normalization and other work on the extra structure before it’s finally elided
3. it’s probably a good idea to interleave the elision of extra structure with the transformation from LP.

**Comment by alissapajer** [comment]
As of PR #1912, this query compiles to QScript in under a second.

**Comment by alissapajer** [comment]
I will attempt to enable the tests tagged with #1669 in #1607.

**Comment by alissapajer** [comment]
We can enable `null/nullTestExprs.test`.

**Comment by alissapajer** [comment]
We can enable `temporal/datePartsConverted.test` for CB, ML, Mongo.
