### ISSUE TITLE
Query involving 'LIKE' results in a scalac MatchError

### ISSUE THREAD

**Issue by wemrysi** [quasar-analytics/quasar#1695]
Attempting to run the query with variables specified in the `likeWithConstantFoldablePattern` regression test results in a Scala `MatchError` at `MapFunc.scala:749`.

**Comment by alissapajer** [comment]
Just confirmed that we are missing the match case for `Like`. This should be a quick fix.

**Comment by alissapajer** [comment]
Quick update: the `Like` from `LogicalPlan` should be getting converted to a `Search` node. This appears to be happening in the REPL but not in the integration test.

**Comment by alissapajer** [comment]
@sellout this is up for grabs again - it wasn't a super quick fix and I'm in the middle of other work.

**Comment by alissapajer** [comment]
@wemrysi  I was no longer able to reproduce this bug, and instead was able to just activate the integration test. My best guess is that some fixes in #1933 fixed this, but I haven't verified that hypothesis.
