### ISSUE TITLE
Modify installers project to install Quasar Spark JAR

### ISSUE THREAD

**Issue by jdegoes** [quasar-analytics/quasar#1712]
TODO:

- [x] Modify script to generate sparkcore.jar
- [x] Modify building scripts to include sparkcore.jar
- [x]  Either set instructions to include QUASAR_HOME or set `addJar` to place where sparkcore.jar is (some vodoo magic needed)

**Comment by jdegoes** [comment]
@rabbitonweb Don't forget about this one!

**Comment by rabbitonweb** [comment]
@jdegoes In order for `spark-hdfs` to work we need to include `sparkcore.jar` in the installers. That jar is very light (few kilobytes).
Do we want a separate installers for Quasar and Quasar that works with `spark-hdfs` OR do we want to always include `sparkcore.jar` in the installers (regardless of whether somebody is downloading Quasar to use with Spark or not)

Please note that `spark-local` (connector that will be used for https://github.com/quasar-analytics/quasar/issues/1899) does NOT require `sparkcore.jar`)

**Comment by jdegoes** [comment]
Always include it in the installers.

**Comment by rabbitonweb** [comment]
TODO:

- [ ] Modify script to generate sparkcore.jar
- [ ] Modify building scripts to include sparkcore.jar
- [ ]  Either set instructions to include QUASAR_HOME or set `addJar` to place where sparkcore.jar is (some vodoo magic needed)

**Comment by jdegoes** [comment]
@zeeiyerWork This too is a priority in order for people to use Spark without manual (and currently undocumented) configuration.

**Comment by rabbitonweb** [comment]
@jdegoes the configuration is documented but only for ppl building their own version of quasar (or did you mean something else?)

**Comment by zeeiyerWork** [comment]
@rabbitonweb, @damonLL, @veryfatboy -> I believe we are talking about documentation for end-users , we are getting reports from the field about problems.

**Comment by zeeiyerWork** [comment]
@rabbitonweb -> This would imply that you get familiar with our installers.

**Comment by rabbitonweb** [comment]
@zeeiyerWork yes, this requires undestanding how installers works

**Comment by rabbitonweb** [comment]
CLOSED
