### ISSUE TITLE
GROUP BY Query returns duplicate entries of distinct values

### ISSUE THREAD

**Issue by flosky** [quasar-analytics/quasar#1713]
I am executing this query:

`select TO_STRING(DATE_PART("year", d.created)) || "-" || TO_STRING(DATE_PART("month", d.created)) || "-" || TO_STRING(DATE_PART("day", d.created)) AS date, COUNT(*) AS cnt
from `/local/my_db/downloads` as d
where d.created >= DATE("2016-08-01")
group by TO_STRING(DATE_PART("year", d.created)) || "-" || TO_STRING(DATE_PART("month", d.created)) || "-" || TO_STRING(DATE_PART("day", d.created))
order by d.created desc`

and expect to get one entry for every day with the number of entries for this group (COUNT(*))
but I still get every record that it is in the db. So it looks sth like this:

    2016-11-10, 3
    2016-11-10, 3
    2016-11-10, 3
    2016-11-11, 1
    ...

and this is what I expect:

    2016-11-10, 3
    2016-11-11, 1
    ...

**Comment by jdegoes** [comment]
@sellout Pretty nasty issue here, please take a look when you get a chance.

**Comment by sellout** [comment]
I’ll take a deeper look shortly, but at first glance it seems like the `order by` is forcing the un-grouping, since there’s no single value for `d.created` in each group. If you change it to `order by date`, it should work, but likely not give you exactly the ordering you want, since it’ll be a string ordering.

If that works, there are other ways to iron out the details.

**Comment by jdegoes** [comment]
@sellout Good catch!

**Comment by sellout** [comment]
Looking at your query again, I feel like it could be simplified to:
```sql
select to_string(d.created) as date, count(*) as cnt
  from/local/my_db/downloads as d
  where d.created >= date("2016-08-01")
  group by d.created
  order by d.created desc
```
the problem with the previous one (as I said in my previous comment) is that you were grouping by something that’s different by what you’re ordering by, so the compiler had no choice but to keep _all_ of the `d.created` values that end up in one bucket, and then unwind that bucket to individual values again when you ask it to order by that field.

In the simplified version, you are ordering by the same value you’re grouping by, so the compiler knows there is exactly one value for `d.created` in each group.

**Comment by jdegoes** [comment]
@sellout Should this be closed or is there work that remains?

**Comment by sellout** [comment]
Ah, I suppose I can close it and leave it to @flosky to reopen if it’s still an issue for them 👍🏾

**Comment by flosky** [comment]
Yes, no problem. I will have to update my Slamdata/Quasar setup to the latest version and try again. Probably just around xmas when I have more time.
Thanks for the help.
