### ISSUE TITLE
Single point of docker

### ISSUE THREAD

**Issue by paulp** [quasar-analytics/quasar#1722]
Spread across `bin/run-travis.sh`, `scripts/startCouchbase`, and `scripts/installMarkLogic` is most or all of the logic necessary to relieve developers of the need to manage installations of these databases in order to run tests against them. In the case of marklogic and to a lesser extent couchbase, the docker logic is intermingled with travis logic; marklogic even gets into e.g. `docker build` for what I hope are travis-specific reasons.

It would be great to have a single program which would spin up whatever dockerized databases we know how to spin up.

**Comment by jdegoes** [comment]
I'll write this up into a more general ticket.

**Comment by jdegoes** [comment]
Superseded by #1730
