### ISSUE TITLE
Unable to mount to spark-hdfs

### ISSUE THREAD

**Issue by rabbitonweb** [quasar-analytics/quasar#1728]
When trying to mount to `spark-hdfs` I get an error

```
There was a problem saving the mount: An unknown error ocurred: 400 "{ \"error\": { \"status\": \"Invalid mount configuration.\", \"detail\": { \"reasons\": [ \"Unsupported filesystem type: spark\" ] } } }"
```

The error is due to the fact that the connector file system type is `spark-hdfs`.

Also as a side note, in the UI, the `Mount type` is called `"Spark"`  - I think it should be more sth like `"HDFS (on Spark)"`

**Comment by jdegoes** [comment]
@rabbitonweb Did you mean to create this in slamdata/slamdata?

**Comment by rabbitonweb** [comment]
Moved to https://github.com/slamdata/slamdata/issues/1244

Closing.
