### ISSUE TITLE
Eliminate usage of org.threeten.bp

### ISSUE THREAD

**Issue by paulp** [quasar-analytics/quasar#1729]
Since quasar requires java8 this library is buying us nothing except a lot of otherwise unnecessary code and error prone conversions.

One might be tempted to use implicits and convert between the various similar types, but this turns out to be a lot less trivial than one might anticipate. Just switching to `java.time` is a better use of effort.

**Comment by jdegoes** [comment]
👍 This would most likely be a 10% time project.

**Comment by paulp** [comment]
It turned out to be almost painless. Merged in 79ca389b33.
