### ISSUE TITLE
DATE_PART doesn't work for ISO_DATE 

### ISSUE THREAD

**Issue by cryogenian** [quasar-analytics/quasar#1749]
I have a collection with following "schema" 
```javascript
{ "_id" : ObjectId("57f53249b746cc464b9fac1f"), "dt" : ISODate("1926-08-11T21:00:00Z"), "ts" : -1369278000, "value" : 0.4842846439255769 }
{ "_id" : ObjectId("57f53249b746cc464b9fac20"), "dt" : ISODate("1993-03-21T21:00:00Z"), "ts" : 732747600, "value" : 0.47271090326168097 }
{ "_id" : ObjectId("57f53249b746cc464b9fac21"), "dt" : ISODate("1968-02-05T21:00:00Z"), "ts" : -60058800, "value" : 0.020977698066937056 }
{ "_id" : ObjectId("57f53249b746cc464b9fac22"), "dt" : ISODate("1978-07-23T21:00:00Z"), "ts" : 270075600, "value" : 0.5733601616341653 }
{ "_id" : ObjectId("57f53249b746cc464b9fac23"), "dt" : ISODate("1955-03-16T21:00:00Z"), "ts" : -466916400, "value" : 0.7161196150201754 }
{ "_id" : ObjectId("57f53249b746cc464b9fac24"), "dt" : ISODate("1924-07-04T21:00:00Z"), "ts" : -1435633200, "value" : 0.11387358349052235 }
{ "_id" : ObjectId("57f53249b746cc464b9fac25"), "dt" : ISODate("1937-06-20T21:00:00Z"), "ts" : -1026615600, "value" : 0.9649450316634763 }
{ "_id" : ObjectId("57f53249b746cc464b9fac26"), "dt" : ISODate("1917-03-05T21:00:00Z"), "ts" : -1667012400, "value" : 0.16969064247916554 }
{ "_id" : ObjectId("57f53249b746cc464b9fac27"), "dt" : ISODate("1911-04-26T21:00:00Z"), "ts" : -1851908400, "value" : 0.19975430639659764 }
{ "_id" : ObjectId("57f53249b746cc464b9fac28"), "dt" : ISODate("1940-05-31T21:00:00Z"), "ts" : -933649200, "value" : 0.6063859894813727 }
```

This query 
```sql
select distinct date_part("year", dt), date_part("month", dt), dt, value 
from `/mongo/testDb/dates` 
```
Returns nulls in first two columns for every date before 1970.

**Comment by sellout** [comment]
Does `select *` show reasonable values for the “dt” field?

If you’re inserting using `ISODate` on any version of Mongo we support (2.6+), it should have no problem storing values from before 1970. But calling `date_part("year", dt)` should be translated to simply `{"$year": "$dt"}` or `dt.getUTCFullYear` (depending on which of Mongo’s languages end up being generated).

It seems we don’t have any StdLib tests that cover pre-epoch dates. That’s definitely an oversight that we should remedy with this issue.

**Comment by sellout** [comment]
Found this comment: `// FIXME: should be some negative value (this will miss any date before 1970)` while looking for the culprit 😄

**Comment by sellout** [comment]
This was an easy fix, and only affected old Mongo (although it _could_ affect new Mongo at some point). But the bug was in our aggregation pipeline type checking.

**Comment by sellout** [comment]
I also added tests in the StdLibSpec to deal with pre-1970 dates, which identified a similar bug (also fixed) in MarkLogic Interval handling.
