### ISSUE TITLE
Bug: Spark only ORDER all ASC or DESC - you can't mix

### ISSUE THREAD

**Issue by rabbitonweb** [quasar-analytics/quasar#1763]
When running a query `select * from foo order by a asc, b desc, c asc ...`, Spark connector takes first asc/desc as a hint and uses it for ordering other columns.

In other words you can either ``select * from foo order by a asc, b asc, c asc ...` OR `select * from foo order by a desc, b desc, c desc ...` but you can not mix
 
Test failing because of that is `largestZips.test`

**Comment by jdegoes** [comment]
You can also investigate "negation", since (`foo asc` is the same as `negate(foo) asc`) for some definition of `negate` (which is trivial for most types but arrays not so much due to unbounded length).
