### ISSUE TITLE
Bug: Spark JOIN returns cartesian product instead of normal join

### ISSUE THREAD

**Issue by rabbitonweb** [quasar-analytics/quasar#1764]
Failing test: `sameFieldName.test`

Not that `PlannerSpec` covers joins and those tests are passing.
Needs further investigation

**Comment by wemrysi** [comment]
I don't this this is a Spark issue (or at least not _only_ a Spark issue) as it looks like the `QScript` plan is currently nonsensical for the query, see https://github.com/quasar-analytics/quasar/issues/1581#issuecomment-263738179 for more detail.

**Comment by rabbitonweb** [comment]
I need to go to @wemrysi & @sellout academy to improve my qscript reading skills :)

Thx for the info!

**Comment by rabbitonweb** [comment]
Fixed in https://github.com/quasar-analytics/quasar/pull/1922
