### ISSUE TITLE
Add tests to StdLibSpec checking comparison between Date & Timestamp is incorrect

### ISSUE THREAD

**Issue by rabbitonweb** [quasar-analytics/quasar#1778]
Any comparison (LT, GT, EQ) between `Date` & `Timestamp` should return `Data.NA`

**Comment by zeeiyerWork** [comment]
@rabbitonweb is unsure if it is done or not. But will check in the may sprint.

**Comment by rabbitonweb** [comment]
It's implemented for sparkcore, waits for other connectors to fill the gap.

**Comment by alissapajer** [comment]
I think we should close this ticket when #2203 lands and then open a specific ticket for each backend for which the new tests are failing.
