### ISSUE TITLE
Add ability to configure SparkContext for Quasar users

### ISSUE THREAD

**Issue by rabbitonweb** [quasar-analytics/quasar#1782]
We need to add ability to give our users way to configure connection with Spark. Right now it is available only via environment variables, but we might have clients willing to keep that configuration internal (within the quasar).

This requires some discussion on how we are going to achieve that.

**Comment by jdegoes** [comment]
It should be via the mount API, like all connector-specific configuration.

**Comment by rabbitonweb** [comment]
Duplicated by https://github.com/quasar-analytics/quasar/issues/1900
