### ISSUE TITLE
Generated QScript for query could omit join

### ISSUE THREAD

**Issue by rabbitonweb** [quasar-analytics/quasar#1783]
Given query:

```
SELECT
 last_name || ", " || first_name AS Name,
 city as City,
 state as State,
 codes[*] AS Code
FROM `/myserver/db_name/patients`
```

produces QScript with a `Join` in it. That `Join` could be omitted with `LeftShift`

**Comment by sellout** [comment]
To add a bit to this – the LP -> QScript conversion will insert a join at some point, with most of the projections on one side and the shifted `codes[*]` on the other.

This is exactly what LeftShift is designed to handle. I _think_ this can / should be handled in `unifySimpleBranches`.

**Comment by alissapajer** [comment]
A simpler example:
```
select city, loc[*] from zips
```
