### ISSUE TITLE
Hyphen "-" in key names

### ISSUE THREAD

**Issue by akkirajub** [quasar-analytics/quasar#1790]
Currently there is no way to place a key with a hyphen in it's name as part of Select list.  Hyphen by default means 'minus' in ANSI SQL and so it should be treated as minus.  However, given that MongoDB supports  an hyphen to be part of a field name (like first-name)  there has to be a way to specify that in Quasar SQL.   

Example :  Following does not work
SELECT c.first-name FROM "/users" c  WHERE c.first-name = 'Sherlock'

There are JSON implementations like wrapping field name with [``]. Something like ['first-name'].  Same may be considered to be implemented on quasar and the SQL above may look like
SELECT c.[`first-name`] FROM "/users" c  WHERE c.[`first-name`] = 'Sherlock'

Agreed, that's not a best practice to have an hyphen in  document names or field names but it is supported my MongoDb and it looks limiting if Quasar doesn't support.

**Comment by jdegoes** [comment]
You can use backticks, which will escape all characters, e.g. 

```
foo.`first-name`
-- equivalently:
foo{"first-name"}
```

**Comment by sellout** [comment]
There are some other syntactic bits that won’t work in the current version of Quasar. Try this version of your query:
```sql
SELECT c.`first-name` FROM `/users` c WHERE c.`first-name` = "Sherlock"
```
We use double quotes for strings, backticks for identifiers, and single quotes for character literals.

**Comment by akkirajub** [comment]
Oh. I missed that. Thank you both.  I thought I tried all combination.  False alarm. Sorry about it.
