### ISSUE TITLE
Cache discovery information.

### ISSUE THREAD

**Issue by beckyconning** [quasar-analytics/quasar#1797]
Currently when discovery is used (rather than a full OIDC provider record including JWKs being provided in config) Quasar uses discovery to get the keys every time it needs to verify a token / return providers.

Instead this information should be cached after discovery.

**Comment by wemrysi** [comment]
@beckyconning Would you mind filing this over at [slamdata/quasar-advanced](https://github.com/slamdata/quasar-advanced/issues)?

**Comment by wemrysi** [comment]
I went ahead and moved this over to slamdata/quasar-advanced#143
