### ISSUE TITLE
Incorrect mimetype being sent for font files

### ISSUE THREAD

**Issue by natefaubion** [quasar-analytics/quasar#1852]
Quasar is currently sending font files as `text/plain` which breaks in Chrome, so no icons show up.

**Comment by sellout** [comment]
And it seems like this is something that changed with the recent update to HTTP4S, since it was working properly in a previous Quasar release, right?

**Comment by natefaubion** [comment]
Correct.

**Comment by natefaubion** [comment]
I was previously using QA 0.5.4, which is based on 13.something, and everything worked correctly then.

**Comment by drostron** [comment]
Once I add an Origin header to a request I'm able to reproduce the issue. It appears to be something related to CORS. Investigation continues...

**Comment by beckyconning** [comment]
This is also affecting videos in Safari.

**Comment by drostron** [comment]
The current plan is to downgrade http4s until fixed. @jr offered to submit a PR for this.

**Comment by drostron** [comment]
The current plan is to downgrade http4s until fixed. @jedesah offered to submit a PR for this.
