### ISSUE TITLE
Metastore corruption when multi-file workspace gets converted to single file

### ISSUE THREAD

**Issue by damonLL** [quasar-analytics/quasar#1855]
From customer:
```
If I create a pivot table in 4.1.0-prerelease2 with quasar-advance 0.6.0
and add a show chart card then this shows no data and also corrupts
the metastore so that when I close the workspace neither the mount
points nor their content is displayed. To recover from this I need to
delete the Metastore. The same happens if I open an old multifile
workspace, once it’s converted to a single file workspace the metastore
is corrupted
```

Appears the common denominator is when a workspace is opened and then saved, going from multi-file format to single-file format, the metastore gets corrupted.

**Comment by damonLL** [comment]
Linked to HelpScout ticket 1305.

**Comment by natefaubion** [comment]
I don't think this is _directly_ related to migration. I ran migration on all the workspaces in the demo dump you sent me, and they were all OK.

**Comment by natefaubion** [comment]
Also note, the migration is simply a matter of reading in all the separate files together, and writing it back out to one file. After that it removes the old per-deck directories and purges the `.tmp` folder.

**Comment by ocasta** [comment]
Agreed. I think the common denominator is pivot tables

**Comment by natefaubion** [comment]
I don't think it's directly related to pivot tables either. Pivot tables just generate view queries like every other card. I can't reproduce the issue with any trivial pivot table, but it's always possible that some specific kind of query is tripping up the backend. It also may be interacting strangely with permissions or something. It's difficult to tell without some more info. Have we been able to reproduce this elswhere? Would it be possible to capture the request log to quasar and see what is happening? Is quasar yielding any errors that aren't propagating to the frontend?

**Comment by natefaubion** [comment]
I have been able to trigger the behavior.

**Comment by natefaubion** [comment]
I was able to trigger the behavior by creating a view mount with this query:
```
SELECT row.gender AS gender, [row.city ...] AS city FROM `/srv/demo4/data/patients` AS row GROUP BY row.gender ORDER BY row.gender
```

Using the following JSON payload
```
{
	"view": {
		"connectionUri": "sql2:?q=SELECT+row.gender+AS+gender%2C+%5Brow.city+...%5D+AS+city+FROM+%60%2Fsrv%2Fdemo4%2Fdata%2Fpatients%60+AS+row+GROUP+BY+row.gender+ORDER+BY+row.gender"
	}
}
```

Which is generated by the Pivot Table. The request succeeds, but subsequent queries all fail and I can't get directory listings due to the corrupted meta store. To me this query looks OK, so there might be some issue with the way the backend is handling it.

**Comment by natefaubion** [comment]
If I do this in regular quasar, I get this error when parsing the config file:

```
Error in configuration file, using default configuration: Failed to parse ./config.json: operator ']' expected; `...': CursorHistory(List(El(CursorOpDownField(connectionUri),true), El(CursorOpDownField(view),true), El(CursorOpDownField(/srv/demo4/Untitled Workspace 2.slam/.tmp/out783e73b3-d66c-4f4f-bf76-26a9c7e44e17),true), El(CursorOpDownField(mountings),true)))
```

Which I think is related to https://github.com/quasar-analytics/quasar/issues/1845
