### ISSUE TITLE
Add means of controlling the content disposition filename

### ISSUE THREAD

**Issue by natefaubion** [quasar-analytics/quasar#1861]
As per http://stackoverflow.com/questions/93551/how-to-encode-the-filename-parameter-of-content-disposition-header-in-http

https://github.com/slamdata/slamdata/issues/1369

I blindly tried adding the appropriate headers to the `request-headers` query param, crossing my fingers that it would magically work, to no avail 😆

Right now the UI lets you type a filename, but its an obnoxious noop.

**Comment by drostron** [comment]
When using mitmproxy to intercept a request and update the `request-headers` query param to `{"Accept":"application/ldjson;disposition=\"attachment; filename=random_file\""}` the response contains `Content-Disposition:  attachment; filename="random_file"` and Chrome downloads the file as the specified filename. @natefaubion Is that workable/reasonable?

**Comment by natefaubion** [comment]
That should be workable as long as I can do the UTF-8 encoding as in the linked stackoverflow post. Specific test case would be `Content-Disposition: attachment; filename*=UTF-8''Na%C3%AFve%20file.txt`.

**Comment by drostron** [comment]
Currently quotes are being added to the `filename*` value and that appears to throw off at least Chrome. I'll look into it further.

**Comment by drostron** [comment]
The behavior stems from Http4s supporting RFC 2616 and not RFC 5987.
