### ISSUE TITLE
Mongo collections with '.' in the name

### ISSUE THREAD

**Issue by uapasha** [quasar-analytics/quasar#1869]
Can quasar work with mongo collections with the '.' in the name?  
Currently when I make ```GET /metadata/fs/[path]``` request to db with such names I get incorrect data object in response. 
Particularly, directory name consists of only first part of the name.  
For example my_db/some.Collection results in "some" being the name of the collection that I get in ```GET /metadata...``` response

**Comment by jdegoes** [comment]
@uapasha A simple workaround is to use a slash literal character (`/`) instead of the dot.

Quasar translates path separator characters into dots, and visa versa, on MongoDB.

**Comment by uapasha** [comment]
@jdegoes How can I configure this? I create mount through POST using this params:
```js
{
  type: 'post',
  url: 'mount/fs/',
  options: {
    content: {
      mongodb: {connectionUri: uri},
    },
    headers: {
      'X-File-Name': `${mountName}/`,
    },
  },
};
```

**Comment by sellout** [comment]
@uapasha There’s nothing to configure, just request `GET /metadata/fs/my_db/some/Collection`

**Comment by zeeiyerWork** [comment]
@sellout - please comment on whether anything needs to be done here or whether "."s in Mongo collection names are forbidden when working via Quasar - or do we escape whatever character is in the name now.

**Comment by sellout** [comment]
@zeeiyerWork Yeah, there is no issue here.

It’s not that `.` are forbidden, it’s that `.` are Mongo’s “directory” separator. So, if a Quasar user wants to create a collection with a `.` in the name we encode it. If a user creates a collection with a dot in the name outside of Quasar, like `foo.bar`, then that collection is queryable through Quasar as `foo/bar`.
