### ISSUE TITLE
Handle SQL `distinct` in SQL² compiler rather than in individual connectors.

### ISSUE THREAD

**Issue by sellout** [quasar-analytics/quasar#1882]
This is a followup to some of the comments in #1856.

It is a more general solution to the problem by treating `distinct` as a SQL-ism, and generating the correct set of sort/group/sort operations when compiling to LogicalPlan, rather than requiring individual connectors handle it.

**Comment by rabbitonweb** [comment]
Does it mean that we will have no qscript that does `sort->grupby->sort` ?

**Comment by sellout** [comment]
It means the opposite – right now you would see QScript that did `sort -> groupby` and you would have to identify it as a case (`distinct`) that should be implemented like `sort -> groupby -> sort`. But with this change the `sort -> groupby -> sort` will be explicit in both the LogicalPlan and QScript.

**Comment by jdegoes** [comment]
@sellout I don't understand why DISTINCT would be translated into sort -> groupby -> sort. Can you explain?

**Comment by sellout** [comment]
@jdegoes Only if the query has an `order by`.

The semantics of `select distinct foo from bar order by baz` are such that given the set
```
foo | baz
---------
"a" | 1
"b" | 2
"a" | 3
```
the results must be `("a", "b")`, not `("b", "a")`, that is, `distinct` is an order-preserving group by. This actually only matters in the case where you sort by a value that’s not in the result set (our “synthetic” fields). So, if you sort by something in the result set, you want `group by -> sort` in the LP, but if you sort by a synthetic field, you need to `sort -> group by -> sort` – the first sort ensures that you pick the correct element from each distinct group, so that they re-sort properly after reducing.
