### ISSUE TITLE
Error parsing Integer to string in query

### ISSUE THREAD

**Issue by jirejas** [quasar-analytics/quasar#1897]
Hello everyone.

I'm working on doing queries with the DATE_PART function. For example:

select DATE_PART("month",ASALTARCEP.contextData.timestamp) from ASALTARCEP;

It works fine but when I try to convert the result of DATE_PART (it returns an integer) to string with CONVERT function, I obtain "Quasar error: the function convert could not be found in the standar library". So I'm trying to do it with CAST but I am not being able to achieve any conversion to String.  

What method can I use to parse a Integer to String in a query? 

Best regards.

**Comment by jdegoes** [comment]
`TO_STRING`
