### ISSUE TITLE
Abstract single module definition of connector

### ISSUE THREAD

**Issue by jdegoes** [quasar-analytics/quasar#1898]
In a single trait, we need to include all the types and methods required to _completely specify_ a connector. Then we need to implement the trait for all existing connectors, and modify a connector integration so that it is as simple as adding a new connector implementation to a list of connectors.

The goal is to make it _crystal clear_ for a connector author _exactly_ what is necessary to implement in order to have a fully-working connector, integrated with the regression tests, standardized tests, etc.

**Comment by zeeiyerWork** [comment]
@djspiewak: Also chatted with @rabbitonweb -> Perhaps y'all should also chat. The 2 Spark (local, hdfs) connectors are based on spark-core and there were a couple of questions on how that abstraction would "lift" into the work done here. <Thanks>

**Comment by djspiewak** [comment]
@rabbitonweb We should catch up tomorrow.  I'm traveling today, but should be around tomorrow morning to touch base on how this should work.
