### ISSUE TITLE
Support API for setting up, configuring Spark local

### ISSUE THREAD

**Issue by jdegoes** [quasar-analytics/quasar#1899]
Ensure this can be configured from any CE or AE build of Quasar.

TODO:

- [x] Implement backend 
- [x] Specification for `spark-local` to front-end team

**Comment by rabbitonweb** [comment]
@jdegoes "from any CE or AE " - can u expand the acronyms ?

**Comment by jdegoes** [comment]
Community Edition, Advanced Edition.

**Comment by rabbitonweb** [comment]
TODO:

- [ ] Specification for `spark-local` to front-end team
- [ ] Default mount to `spark-local` when no mounts specified

**Comment by rabbitonweb** [comment]
Implemented on both backend & fronted
