### ISSUE TITLE
Support configuration for production Spark clusters

### ISSUE THREAD

**Issue by jdegoes** [quasar-analytics/quasar#1900]
TODO:

- [x] Propose`connectionURI` specification for front-end team
- [x] Implement new `connectionURI`
- [x]  New `connectionURI` implemented on front-end side
- [x] BUG: on backend wrong sparkUri is created

**Comment by rabbitonweb** [comment]
We need to add ability to give our users way to configure connection with Spark. Right now it is available only via environment variables, but we might have clients willing to keep that configuration internal (within the quasar).

**Comment by rabbitonweb** [comment]
Things we need to provide as part of configuration for our users to set:
(details at http://spark.apache.org/docs/latest/configuration.html)

**For Executors**
- spark.executor.memory
- spark.executor.cores
- spark.executor.extraJavaOptions
- spark.default.parallelism
- spark.files.maxPartitionBytes

**For Diver**
- spark.driver.cores
- spark.driver.maxResultSize
- spark.driver.memory
- spark.local.dir


**Shuffle & Memory** 
- spark.reducer.maxSizeInFlight
- spark.reducer.maxReqsInFlight
- spark.shuffle.file.buffer
- spark.shuffle.io.retryWait
- spark.memory.fraction
- spark.memory.storageFraction

**Other**
- spark.cores.max
- spark.speculation
- spark.task.cpus

TODO:

- [ ] Make those configurations part of `connectionURI`
- [ ] Update SlamData to give ability to provide those values

**Comment by rabbitonweb** [comment]
Specification for new `connectionUri`
