### ISSUE TITLE
Ability to deploy SlamData and/or Quasar as a Windows Service or Linux Daemon

### ISSUE THREAD

**Issue by damonLL** [quasar-analytics/quasar#1901]
We've received multiple requests to install SlamData as an OS service or daemon rather than a standard Java application. This would allow administrators to manage starting, stopping and status monitoring of the SlamData process itself through normal OS means.

For Linux perhaps something like the answer mentioned in this [StackOverflow Post](http://stackoverflow.com/questions/7687159/how-to-convert-a-java-program-to-daemon-with-jsvc) would be helpful.

Whether this would be helpful for standalone Quasar is unknown - it hasn't been requested.

Re-opening under Quasar issues.  Original was logged as SlamData Issue [#1436](https://github.com/slamdata/slamdata/issues/1436)

**Comment by nicflores** [comment]
@damonLL, I can probably get you something for linux rather quickly, for windows it may take me a little longer or I may have to punt the windows to someone else who is more familiar with the windows internals. 

For linux, do you have an idea if most of the systems you are dealing with are running `systemd`? If its any RedHat or Debian flavor after 2015 then they are probably running `systemd`. You can ask the admins you are working with if they use `systemctl` to control their services or if they use `service`. It is possible some folks still use `service` despite `systemd` running on their OS. Another way to check is to just try the command `systemctl list-unit-files` if you get a long list of items like `<some-name>.service` then they are running `systemd`. You can check if systemd is controlling a service by  running something like:
```
vagrant@nomad:~$ systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2017-08-03 20:24:39 UTC; 20h ago
     Docs: https://docs.docker.com
 Main PID: 14637 (dockerd)
    Tasks: 17
   Memory: 22.0M
      CPU: 38.564s
   CGroup: /system.slice/docker.service
           ├─14637 /usr/bin/dockerd -H fd://
           └─14642 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --shim docker-containerd-shim --runtime
```
To restart or stop a service using systemd you can use `systemctl restart docker.service` or `systemctl stop docker.service`.

If you think you are bumping into both `systemd` and the legacy `sysvinit` then I'll have to write something for both. If it is just `systemd` writing a unit file to control Slamdata should be fairly quick.

**Comment by jdegoes** [comment]
@nicflores Take a look at this one: https://wrapper.tanukisoftware.com/doc/english/download.jsp

**Comment by damonLL** [comment]
@nicflores - I'm not sure which customers are using which service approaches. I would think it's a safe bet to say that whatever the Linux community is migrating toward in the past 2 - 3 years across major distros is what we should shoot for supporting.  I know practically all flavors of Linux are in use, however: Amazon Linux, Ubuntu, Redhat/CentOS. We do have some customers running Windows as well.

The solution @jdegoes references seems solid.

**Comment by nicflores** [comment]
An immediate solution to running Slamdata as service on linux can be achieved by allowing systemd to mange the service for us by dropping the following systemd files in place:
```
vagrant@vagrant:/etc/systemd/system$ cat slamdata.service
[Unit]
Description=SlamData Linux Service
After=syslog.target
After=network.target

[Service]
User=<someuser>
ExecStart=/usr/bin/java \
  -Dlicense_full_name=${FNAME} \
  -Dlicense_registered_to=${RNAME} \
  -Dlicense_email=${EMAIL} \
  -Dlicense_company=${COMPANY} \
  -Dlicense_street=${STREET} \
  -Dlicense_tel_number=${TEL} \
  -Dlicense_fax_number=${FAX} \
  -Dlicense_city=${CITY} \
  -Dlicense_zip=${ZIP} \
  -Dlicense_country=${COUNTRY} \
  -Dlicense_key=${KEY} \
  -jar ${SLAMDATA_HOME}/quasar.jar unsecured --content-path ${SLAMDATA_HOME}/public
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure

[Install]
Alias=slamdata

vagrant@vagrant:/etc/systemd/system$ cat slamdata.service.d/override.conf
[Service]
Environment=SLAMDATA_HOME=/home/vagrant/slamdata
Environment=FNAME=myfirstname
Environment=RNAME=myusername
Environment=EMAIL=my@office.com
Environment=COMPANY=mycompany
Environment=STREET=mystreet
Environment=TEL=5555
Environment=FAX=5555
Environment=CITY=Boulder
Environment=ZIP=80306
Environment=COUNTRY=US
Environment=KEY=LLGT4-FPCCL-C2DEN-HIPEW-FPNEL
```
Going this route the OS would manage the service for us and the `Restart` directive in the `slamdata.service` would keep there service alive if it dies. 

Trying out the Java Service Wrapper library mentioned above by @jdegoes, I was able to configure a rather simple example of how to use this in Linux.  With `quasar.jar` and `/public` sitting next to each other in a directory, I added Java Service Wrapper artifacts like this:
```
vagrant@vagrant:~/slamdata$ tree ./
./
├── bin
│   ├── slamdata
│   ├── testwrapper
│   └── wrapper
├── conf
│   └── slamdata.conf
├── lib
│   ├── libwrapper.so
│   ├── wrapperdemo.jar
│   ├── wrapper.jar
│   └── wrappertest.jar
├── logs
│   └── wrapper.log
├── public/...
├── quasar.jar
```

Then using the following command I was able to start the service:
```
vagrant@vagrant:~/slamdata$ ./bin/slamdata console
Running SlamData Service...
wrapper  | --> Wrapper Started as Console
wrapper  | Java Service Wrapper Community Edition 64-bit 3.5.33
wrapper  |   Copyright (C) 1999-2017 Tanuki Software, Ltd. All Rights Reserved.
wrapper  |     http://wrapper.tanukisoftware.com
wrapper  |
wrapper  | Launching a JVM...
jvm 1    | WrapperManager: Initializing...
jvm 1    | Configuration file '/home/vagrant/.config/quasar/quasar-config.json' not found, using default configuration.
jvm 1    | Using metastore: jdbc:h2:file:/home/vagrant/.config/quasar/quasar-metastore.db
jvm 1    | log4j:WARN No appenders could be found for logger (com.zaxxer.hikari.HikariConfig).
jvm 1    | log4j:WARN Please initialize the log4j system properly.
jvm 1    | log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
jvm 1    | Server started listening on port 20223
jvm 1    | Press Enter to stop.

^Cwrapper  | INT trapped.  Shutting down.
wrapper  | <-- Wrapper Stopped
```

After going through this exercise it seems like this will be something the installers will have to deploy. I'll run this by someone more familiar with the installers to figure out where exactly it should live. The above config only covers Linux, so I'll have to put something together for windows as well. This may be more work than what I was anticipating for this issue, so depending on what other say about adding this feature to the installers, I may split this ticket into two and address using Java Wrapper and incorporating it into the installers separately.

**Comment by nicflores** [comment]
@zeeiyerWork and @jdegoes ,
I decided to give Java Service Wrapper a try. Its not too bad to get up and running with it. I've got Java Service Wrapper configs for Linux, Windows, and Mac. My thought was that the installers would deliver a zipped file containing the the Java Service Wrapper directory structure I mentioned above. If the user wants to control Slamdata using the Java Service Wrapper they would just unzip it and run the start command. There's one more thing to figure out, and that's passing in JAVA_OPTS from the environment as opposed to hardcoding those values in the config file, which is what I've currently done.

There's a catch though with JSW, I didn't notice this until testing things in Windows, looks like it requires a license. Looking through the license info [here](https://wrapper.tanukisoftware.com/doc/english/accountLicenses.jsp#purchase) it seems that we need the Developer License. More details about the Developer license can be found [here](https://wrapper.tanukisoftware.com/doc/english/licenseDevelopment.html). From that link the Developer License allows us to distribute JSW distribute it with Slamdata.

How would you guys like to proceed? Purchase a license or work around it by using Systemd in Linux and some else for Windows (I'll have to investigate a little more to determine what else is out there).

**Comment by jdegoes** [comment]
@nicflores This should be part of slamdata-backend and not quasar, and we can and should purchase a license for JSW if you recommend it as a viable solution for slamdata-backend.

**Comment by nicflores** [comment]
@jdegoes, I definitely think JWS is our best option to run Slamdata as a service across different platforms. I'll get in touch with their support to get some of my license questions answered and then move forward with a license purchase.

**Comment by nicflores** [comment]
I was able to leverage install4j's ability to deploy an application as a service on Mac, Linux, and Windows. PR is up for review over in slamdata/installers.
