### ISSUE TITLE
Test for Spark robustness

### ISSUE THREAD

**Issue by rabbitonweb** [quasar-analytics/quasar#1907]
- [x] Enable all integration tests for Spark that are not effected by QScript issues
- [x] Upgrade to latest version of Spark
- [x] set-up 2.1.0 cluster for tests
- [x] spark-connectors should fail gracefully when mounted more then one
- [x] unmounting spark connector should free resources (there is a bug most probably in front-end)

**Comment by rabbitonweb** [comment]
Upgrade in https://github.com/quasar-analytics/quasar/pull/1908

**Comment by rabbitonweb** [comment]
**Should be fixed in SparkCore:**
`typeOf.test` - `MapFunc` `TypeOf` must be implemented in `CoreMap`
`multitypeFlatten.test`, `likeWithConstantFoldablePattern.test`, `different-flattens.test` - gives wrong results, problems with LIKE, must investigate

**QScript bugs:**
`statesByShortestFirstCity.test`, `singleFieldOrderedDistinct.test`, `LocationCount.test` - issue is that any `select foo from bar group by foo order by baz` will create QScript like `Reduce(Sort(Read(..)))` but Spark will loose order after reduce, we need `Sort(Reduce(Sort(Read(..))))`. This is fixed on some mysterious @sellout branch but pushing this to master requires removal of old mongo connector - so we are waiting patiently for that to happen :)
`tripleFlatten.test` - known bug #732
`nonJsJoinCondition.test` - self JOINs
`servlet.test` - pending #465, #467
`skipCount.test` - unknown
`multitypeFlatten.test` - unknown

**Comment by alissapajer** [comment]
@rabbitonweb can you make individual tickets for the QScript bugs that don't have tickets already?

**Comment by rabbitonweb** [comment]
@alissapajer I will double check if tickets exits

**Comment by rabbitonweb** [comment]
FINISHED
