### ISSUE TITLE
Improve QScript performance on basic select query

### ISSUE THREAD

**Issue by alissapajer** [quasar-analytics/quasar#1909]
Below shows how long it took to generate `QScript` from a `LogicalPlan` for a given query. Clearly we have a serious exponential performance problem. (Note that I only ran each query once to generate the times.)

`select a, b, c from zips`
0.113s

`select a, b, c, d from zips`
0.121s

`select a, b, c, d, e from zips`
0.378s

`select a, b, c, d, e, f from zips`
1.632s

`select a, b, c, d, e, f, g from zips`
9.350s

`select a, b, c, d, e, f, g, h from zips`
55.733s

`select a, b, c, d, e, f, g, h, i from zips`
334.901s

**Comment by alissapajer** [comment]
`select a, b, c from zips` generates the following `LogicalPlan`:
```
Let('__tmp0)
├─ Let('__tmp1)
│  ├─ Read(/mongoq/test/zips)
│  ╰─ Typecheck(Obj(Map[], Some(Top)))
│     ├─ Free('__tmp1)
│     ├─ Free('__tmp1)
│     ╰─ Constant(NA)
╰─ Invoke(Take)
   ├─ Invoke(Squash)
   │  ╰─ Invoke(ObjectConcat)
   │     ├─ Invoke(ObjectConcat)
   │     │  ├─ Invoke(MakeObject)
   │     │  │  ├─ Str("a")
   │     │  │  ╰─ ObjectProject('__tmp0{"a"})
   │     │  ╰─ Invoke(MakeObject)
   │     │     ├─ Str("b")
   │     │     ╰─ ObjectProject('__tmp0{"b"})
   │     ╰─ Invoke(MakeObject)
   │        ├─ Str("c")
   │        ╰─ ObjectProject('__tmp0{"c"})
   ╰─ Constant(Int(11))
```
which compiles to the following `QScript`:
```
Subset(Take)
├─ Unreferenced
├─ From
│  ╰─ LeftShift
│     ├─ Read(/test/zips)
│     ├─ Struct
│     │  ╰─ ○
│     ├─ IdStatus
│     │  ╰─ IdStatus(ExcludeId)
│     ╰─ Repair
│        ╰─ ConcatMaps
│           ├─ ConcatMaps
│           │  ├─ MakeMap
│           │  │  ├─ Constant(Str(a))
│           │  │  ╰─ ProjectField
│           │  │     ├─ Guard
│           │  │     │  ├─ RightSide
│           │  │     │  ├─ Type(Obj(Map[], Some(Top)))
│           │  │     │  ├─ RightSide
│           │  │     │  ╰─ Undefined
│           │  │     ╰─ Constant(Str(a))
│           │  ╰─ MakeMap
│           │     ├─ Constant(Str(b))
│           │     ╰─ ProjectField
│           │        ├─ Guard
│           │        │  ├─ RightSide
│           │        │  ├─ Type(Obj(Map[], Some(Top)))
│           │        │  ├─ RightSide
│           │        │  ╰─ Undefined
│           │        ╰─ Constant(Str(b))
│           ╰─ MakeMap
│              ├─ Constant(Str(c))
│              ╰─ ProjectField
│                 ├─ Guard
│                 │  ├─ RightSide
│                 │  ├─ Type(Obj(Map[], Some(Top)))
│                 │  ├─ RightSide
│                 │  ╰─ Undefined
│                 ╰─ Constant(Str(c))
╰─ Count
   ╰─ Map
      ├─ Unreferenced
      ╰─ Constant(Int(11))
```
One thing to note immediately (compile-performance related or not) is that in the `LogicalPlan` we have a single `Typecheck` where in the `QScript` we have the same `Guard` duplicated for each `ProectField`. We would like to require a backend to perform this calculation only once, but that may be out of the scope of this ticket.

**Comment by alissapajer** [comment]
I should also note that the times were generated using the work in #1906 .

**Comment by jdegoes** [comment]
😱

**Comment by alissapajer** [comment]
Some updates: We are spending all of our time in `MapFunc.normalize` via `freeMF`. We are spending time there not due to that particular algorithm, but because prior to getting there, we generate _huge_ `QScript`. A subset of the intermediate `QScript` for `select a from zips` is 440 lines long (when rendered as a tree) and contains ~15 duplicate sections that look like
```
│  │     │     │  │        │  │  ├─ ConcatArrays
│  │     │     │  │        │  │  │  ├─ MakeArray
│  │     │     │  │        │  │  │  │  ╰─ ConcatArrays
│  │     │     │  │        │  │  │  │     ├─ MakeArray
│  │     │     │  │        │  │  │  │     │  ╰─ LeftSide
│  │     │     │  │        │  │  │  │     ╰─ MakeArray
│  │     │     │  │        │  │  │  │        ╰─ RightSide
│  │     │     │  │        │  │  │  ╰─ MakeArray
│  │     │     │  │        │  │  │     ╰─ ConcatArrays
│  │     │     │  │        │  │  │        ├─ ConcatArrays
│  │     │     │  │        │  │  │        │  ├─ MakeArray
│  │     │     │  │        │  │  │        │  │  ╰─ MakeArray
│  │     │     │  │        │  │  │        │  │     ╰─ ProjectIndex
│  │     │     │  │        │  │  │        │  │        ├─ RightSide
│  │     │     │  │        │  │  │        │  │        ╰─ Constant(Int(0))
│  │     │     │  │        │  │  │        │  ╰─ MakeArray
│  │     │     │  │        │  │  │        │     ╰─ ProjectIndex
│  │     │     │  │        │  │  │        │        ├─ RightSide
│  │     │     │  │        │  │  │        │        ╰─ Constant(Int(1))
│  │     │     │  │        │  │  │        ╰─ MakeArray
│  │     │     │  │        │  │  │           ╰─ Constant(Str(a))
```
all nested various levels deep surrounded by various `ProjectIndex`s. The same `QScript` subset for `select a, b from zips` has ~36 duplicate sections split across `Constant(Str(a))` and `Constant(Str(b))` variants. Then it gets exponentially worse. For `select a, b, c, from zips` that subset has over 150 duplicate sections (and my scroll buffer filled up at ~4000 lines, with more tree left to print).

I think this structure is getting created in the compiler (not the normalizer), but we do normalize `QScript` as we compile, so we need to keep that in mind. In `autojoin` we create the `ConcatArrays` structure that dominates the tree. Coming out of the `autojoin` though, we see this structure "condensed", and not duplicated. So post-`autojoin` we are exploding out this structure, which is what we need _not_ to do.

**Comment by sellout** [comment]
Good – this matches our suspicions – I think we need to make sure we `pruneArrays` along with (before) the incremental normalization. It might not help as much as we’d like (because we don’t always know whether we still need the provenance info until we get closer to the root), but it should be a fairly easy change to make and something we should be doing anyway. We need to make sure we run `pruneArrays` across the full branches at each step, though, and not just at the current node.

If that’s _not_ sufficient, then we probably need to start common subexpression elimination.

**Comment by alissapajer** [comment]
@sellout I don't think it's possible to `pruneArrays` before incremental normalization (in `convertAndNormalize`) because at that stage we are still working with a `Target` which contains unreified provenance and value information. The `Ann` at this stage may still contain references to an array in the value. We could run `pruneArrays` also considering the `Ann`, sort of doing a fake reification that is not propagated forward, but I'm not confident that is the correct approach.

I'm also not sure yet if we can call `pruneArrays` incrementally where we call `normalizeCoEnv` on various `Free` structures; this might have the same problem as above. 

Additionally, even if we could call `pruneArrays` incrementally, for a query with just a few fields selected, the subquery alone will still have over 100,000 lines of `QScript` (post inlining), and I think that's an underestimate. From what I can see, we have a subexpression factored out nicely after we perform a series of `autojoin`, and then we perform a massive inlining of that substructure (in `coalesceQC`, and maybe other places). Calling `pruneArrays` before we inline wouldn't really have an effect because all (or nearly all) indices in that substructure are used at various places. And so we have to create the massive substructure before we can prune it, but we need to avoid creating that massive substructure entirely.

I've accounted for the creation of about half of the duplicate structure, but not all of it yet. So I'd like to fully understand if `coalesceQC` is responsible for all the inlining or if there's another source.

**Comment by alissapajer** [comment]
For example, in `coalesceQC` we replace every `SrcHole` in the `FreeMap` of the `Map` with the `repair` of the `LeftShift`, thereby eliminating the `Map`. This pattern of replacement combines exponentially and gives us our giant `QScript`. 

I think that `pruneArrays` addresses the symptoms rather than the cause of the problem. Now, subexpression elimination is no small task to implement in `QScript`, so at this investigation stage I'd still like to think more if we can improve compile performance at all without such a drastic step (albeit a step we've expected to have to do). But since we are the ones explicitly creating the pattern of `ConcatArrays` with access to the left and right sides, I think there may be a way we can be smarter in the entire process of merging and concating.
```
  1 Map(
  2   LeftShift(
  3     BucketField(BucketField(Root,SrcHole,Constant(Str(test))),SrcHole,Constant(Str(zips))),
  4     SrcHole,
  5     IncludeId,
  6     ConcatArrays(
  7       MakeArray(ConcatArrays(MakeArray(LeftSide), MakeArray(RightSide))),
  8       MakeArray(ConcatArrays(
  9         ConcatArrays(
 10           MakeArray(MakeArray(ProjectIndex(
 11             ProjectIndex(
 12               ConcatArrays(MakeArray(LeftSide), MakeArray(RightSide)),
 13               Constant(Int(1))),
 14             Constant(Int(0))))),
 15           MakeArray(ProjectIndex(
 16             ProjectIndex(
 17               ConcatArrays(MakeArray(LeftSide), MakeArray(RightSide)),
 18               Constant(Int(1))),
 19             Constant(Int(1))))),
 20         MakeArray(Constant(Str(a))))))),
 21   ConcatArrays(
 22     ConcatArrays(
 23       ConcatArrays(
 24         MakeArray(MakeArray(ProjectIndex(ProjectIndex(ProjectIndex(SrcHole, Constant(Int(0))), Constant(Int(1))), Constant(Int(0))))),
 25         MakeArray(MakeArray(ProjectIndex(ProjectIndex(ProjectIndex(SrcHole, Constant(Int(1))), Constant(Int(0))), Constant(Int(0)))))),
 26       MakeArray(ProjectIndex(ProjectIndex(ProjectIndex(SrcHole, Constant(Int(0))), Constant(Int(1))), Constant(Int(1))))),
 27     MakeArray(ProjectField(ProjectIndex(ProjectIndex(SrcHole, Constant(Int(1))), Constant(Int(1))), ProjectIndex(ProjectIndex(SrcHole, Constant(Int(1))), Constant(Int(2)))))))
```

**Comment by sellout** [comment]
> I don't think it's possible to pruneArrays before incremental normalization (in convertAndNormalize) because at that stage we are still working with a Target which contains unreified provenance and value information.

We can still apply `pruneArrays` before normalization – if an array is accessible via the Ann, then it must be accessible via `Target.value`, which means it won’t get pruned anyway.

Also, I think putting `pruneArrays` between convert and normalize is the right thing to do anyway. We _should_ be composing these things as much as possible rather than chaining them. That it might reduce this problem is just the reason to make that change now.

I agree that we can perhaps improve the way we deal with concatting/merging, etc. There are definitely places we duplicate things when we could instead unify references (without yet getting into CSE).

**Comment by alissapajer** [comment]
@sellout We need to take the `Ann` into account at the time of calling `pruneArrays` - that was my point. If there is an array in the value, that array might be dereferenced in the annotation, meaning, we will prune that too much (removing indices which are actually used) if we don't also take the annotation into account.

**Comment by alissapajer** [comment]
Update: So, we indeed can _correctly_ call `pruneArrays` during incremental compile. This is because any array at the "root" level (the level that is be referenced by the annotation) cannot be pruned because this array represents the result of the query (at that stage), which we are required to return in full to the user (eventually). At the end of the world we can `pruneArrays` again after we reify provenance and values.

But adding in this extra incremental array pruning doesn't solve our problem one bit. And compile times only get slower (we're walking the giant tree one more time). It doesn't solve our problem because the giant array we create _is_ at the "root" level at the stage we call `MapFunc.normalize`. Within this array there are subarrays that _could_ be pruned, but this is not a case that `pruneArrays` currently looks for. So, at the time of the horrible inlining, we create the giant array at the "root" level, and so `pruneArrays` has no effect. So I still maintain that we shouldn't be inlining because that's causing the exponential growth of the size of the tree. And array pruning doesn't work unless you are pruning a non-"root" value.

**Comment by alissapajer** [comment]
Yes! I just compiled a select query with 20 fields in 0.357s. Fingers super-crossed that this fix is for real :) Previously 9 fields took > 300s to compile while now 9 fields compile in 0.189s. I simply ran `normalizeMapFunc` incrementally inside `coalesceQC` in the case that I knew was being hit tens of thousands (or more) of times. I will add `normalizeMapFunc` to all the other cases in `coalesceQC` as well. But the commonly-hit case was `Map(LeftShift, _)`, as discussed previously as the source of the massive inlinings.

Still need to run tests, there could be more work left. But this is a big win so far.

**Comment by alissapajer** [comment]
TODO for self - time the `QScript` compilation of all the integration test queries that are running slowly to determine if we have _other_ performance bugs in `QScript`.

**Comment by jdegoes** [comment]
> Yes! I just compiled a select query with 20 fields in 0.357s. Fingers super-crossed that this fix is for real :) Previously 9 fields took > 300s to compile while now 9 fields compile in 0.189s.

This is a huge improvement! Ultimately I'd like compilation time to be insignificant (e.g. one to two orders of magnitude faster than presently for these sized queries). But one step at a time. 😄

**Comment by alissapajer** [comment]
@jdegoes I agree that we'll need to make `QScript` compile faster down the road. Right now `QScript` compile generally dominates the time it takes to go from raw SQL^2 to `QScript`. But for now, backend computation is dominating the query time, at least for some backends. We'll take a careful look at this when we switch out old mongo for mongoq, and we might need to work more on `QScript` performance then so that mongoq is as fast as old mongo.
