### ISSUE TITLE
Metastore possibly becomes corrupt when Quasar gets JVM OutOfMemoryError

### ISSUE THREAD

**Issue by damonLL** [quasar-analytics/quasar#1910]
This is more of a suspicion than a known fact, but since it has happened at least one verifiable time before, and several suspected other times, I think it needs addressing.

To reproduce, I would imagine that giving the JVM a very constrained memory profile (-Xms128m -Xmx256m) would cause this pretty quickly, given a large dataset and a complex query.

While this has proven to corrupt the metastore with at least one customer, I'm curious if it might also corrupt the quasar-config.json file in the Community Edition as well somehow.

If this is difficult to reproduce or determine, let me know and I'll spend the time gathering data, setting up an environment, etc.  Too important to not address, even if I'm wrong in my description.

**Comment by jdegoes** [comment]
@damonLL When you get a chance, please try to reproduce to save engineering time in fixing it.

**Comment by drostron** [comment]
In an effort to reproduce the issue I've repeatedly run the JVM out of memory without seeing metastore corruption. Perhaps this happened to coincide with one the the other corruption issues that has been addressed. @damonLL have you seen this occur recently or been able to reproduce?

**Comment by damonLL** [comment]
@drostron I have not seen it recently, no. The last time was several months ago so if you've tried unsuccessfully to corrupt it via OutOfMemoryError then I would say there isn't much left to do. Perhaps all of the metastore resilience changes recently have addressed it.

**Comment by drostron** [comment]
@damonLL Ok, closing for now. Please reopen with any additional context if you happen to see this again.
