### ISSUE TITLE
MarkLogic passing all applicable query regression tests

### ISSUE THREAD

**Issue by wemrysi** [quasar-analytics/quasar#1948]
A catch-all issue to track the remaining query regression tests that are failing for MarkLogic. Only those that are expected to pass are listed here, connector-specific tests for other connectors are omitted.

Test | Notes
------|--------
caseVariations.test| Ordering after `distinct`.
caseWithGroup.test| Ordering after `distinct`.
citiesByLargestZip.test| Ordering after `distinct`.
different-flattens.test| QScript provenance issue (#1951).
flattenGroupedObject.test| Attempts to string match on an object, something isn't projecting a field properly? (#2359) 
groupByFlatten.test| ~Non-literal numeric field names (#1760)~ Some other issue related to QScript. Several connectors have it disabled. cc @alissapajer
guardedExpression.test| Runtime typechecks (#1506).
joins/3WayJoin.test|
joins/constantOnLeft.test|
joins/crossJoin.test|
joins/groupedJoin.test|
joins/innerEquiJoin.test|
joins/innerEquiJoinWithWildcard.test|
joins/joinSubSelects.test|
joins/joinWithComplexCondition.test|
joins/joinWithMultipleConditions.test|
joins/joinWithReversedCondition.test|
joins/orderJoinByAlias.test|
joins/sameFieldNameComplex.test|
joins/selfjoinConstantOnLeft.test|
joins/selfjoinWithComplexCondition.test|
LocationCount.test| Doesn't look like _any_ connectors (including legacy mongo) pass this one.
multistageFlatten.test| Runtime typechecks (#1506).
multitypeFlatten.test| Runtime typechecks (#1506).
nonJsJoinCondition.test| Due to #2110.
null/nullTestExprsWithMissing.test| Disabled for all connectors.
servlet.test| Disabled for all connectors.
shortCities.test| Ordering after `distinct`.
singleFieldOrderedDistinct.test| Ordering after `distinct`.
symmetricNonJsJoinCondition.test|  Due to #2110.
temporal/filterOnDate.test| Cast arguments to `temporalTrunc`.
temporal/timestampsAndIntervals.test| Cannot divide using `xs:duration`, need to narrow to one of the subtypes.
tripleFlatten.test| Fail to distinguish between array/object for flatten.
unifyFlattenedFieldsWithMultipleUses.test| `loc` fields not filtered properly. #2366 LogicalPlan bug.
flattenArray.test|Related to #2188. Skipped for `marklogic_xml`
flattenArrayLeftWithUnflattened.test|Related to #2188. Skipped for `marklogic_xml`
flattenArrayWithUnflattened.test|Related to #2188. Skipped for `marklogic_xml`
unifyFlattenedFields.test|Related to #2188. Skipped for `marklogic_xml`
union.test|Related to #2188. Skipped for `marklogic_xml`

**Comment by alissapajer** [comment]
Closing, as these tests are all tracked by individual issues.
