### ISSUE TITLE
Slow QScript plan generation

### ISSUE THREAD

**Issue by drostron** [quasar-analytics/quasar#1950]
A few `explain`s with approximate timings from the repl:

```
explain select meta(brewery).id as brewery_meta_id, brewery.name as brewery_name, beer.name as beer_name, beer.brewery_id as beer_brewery_id from `/cb/beer-sample/brewery` as brewery join `/cb/beer-sample/beer` as beer on meta(brewery).id = beer.brewery_id where beer.name = "Pale"
```
~ 1 minute

---

```
explain SELECT META(brewery).id AS brewery_meta_id, brewery.name AS brewery_name, beer.name AS beer_name, beer.brewery_id AS beer_brewery_id, beer.category AS beer_category FROM `/cb/beer-sample/brewery` AS brewery JOIN `/cb/beer-sample/beer` AS beer ON META(brewery).id = beer.brewery_id WHERE beer.category = "North American Ale"
```
No return after a few minutes (canceled)

---

```
explain select meta(brewery).id as brewery_meta_id, brewery.name as brewery_name, beer.name as beer_name, beer.brewery_id as beer_brewery_id from `/cb/beer-sample/brewery` as brewery join `/cb/beer-sample/beer` as beer on meta(brewery).id = beer.brewery_id
```
~ 45 seconds

---

```
explain select brewery.name as brewery_name from `/cb/beer-sample/brewery` as brewery join `/cb/beer-sample/beer` as beer on meta(brewery).id = beer.brewery_id
```
~ 1 second

**Comment by jdegoes** [comment]
@alissapajer This takes precedence over the join work.

**Comment by alissapajer** [comment]
@jdegoes I'm on it.

**Comment by damonLL** [comment]
@drostron also noticed that when using `*` instead of specific fields in the `SELECT` clause it comes back very quickly.  Also the more fields that were added, the longer it took.

**Comment by alissapajer** [comment]
@damonLL thanks for extra the info. This is similar to what I fixed before, so I need to figure out how to make our `QScript` optimizations resilient to this once and for all. The difference here seems to be the added `join`.

**Comment by alissapajer** [comment]
Ok I just brought down the compilation time of the ~45 second query above to ~0.8sec spent in main `QScript` compilation. Now 0.8sec is still way too slow in the big picture, and I'll do some more investigation here in case there is more low-hanging fruit. 

Also the query in the bug report that never returned, returned the `QScript` in ~0.9sec. Again too slow for what our customers need, but much more usable than never.

This was the same problem as before, just applied to other cases. I have an idea about how to apply the solution more generally so we won't keep hitting the same cases...

**Comment by alissapajer** [comment]
Just a touch more documentation of timing: I'm seeing the "never" query returning in couchbase in a total of ~2.0 seconds. So half the time is `QScript`, half is elsewhere.
