### ISSUE TITLE
Invalid selector for DATE_PART: "isodoy"

### ISSUE THREAD

**Issue by natefaubion** [quasar-analytics/quasar#1963]
Both the docs on quasar and slamdata mention "isodoy" as a DATE_PART, but the backend says it is invalid. I also tried "isoday" in case it was a typo, but that fails as well.

**Comment by sellout** [comment]
It should be valid – but it’s possible it’s not implemented for specific connectors (I know Mongo is missing one or two date part implementations). The exact error message will help us identify if it’s failing in a connector or before (and we can update the message to make it clearer that it’s part of Quasar, but not implemented by a particular connector).

**Comment by natefaubion** [comment]
The status is "Invalid mount configuration", which I assume means that it's not implemented by the connector.

**Comment by sellout** [comment]
Ok, so I don’t know why this is categorized as “invalid mount configuration”, but it looks like `"isodoy"` is missing from the SQL->LP compiler.

Thanks.

**Comment by wemrysi** [comment]
@natefaubion Did you receive the error in response to creating a view mount with this query?

**Comment by natefaubion** [comment]
Oh that must be it! Didn't even think about that :)

**Comment by sellout** [comment]
So, some more general thoughts (as always). We should probably provide _only_ the ISO parts in LP. SQL wants other parts, but we can compile those to more complex expressions.

**Comment by zeeiyerWork** [comment]
Does not seem like an urgent issue - so pushing to May2017 iteration

**Comment by sellout** [comment]
Hrmm, looking at Postgres docs, etc. I don’t see “isodoy” existing anywhere. I think it’s a doc error. We _do_ have “doy”, and I don’t know how “isodoy“ would differ from that.

But, I would still like to strip down LP to only expose the ISO parts, and let either the SQL² compiler or some stdlib of parameterized views provide the other parts.

**Comment by sellout** [comment]
Ah, looking at the docs, it seems like that “isodoy” is a typo of “isodow”.

**Comment by sellout** [comment]
Tracking the larger refactoring in #2169.
