### ISSUE TITLE
Adjust or remove VFS stuff in Table

### ISSUE THREAD

**Issue by djspiewak** [quasar-analytics/quasar#1987]
A lot of the VFS and API permissioning stuff in precog is going to get in the way of how we want to use it in quasar.  I may have to bribe @nuttycom with some high quality coffee to acquire knowledge of what it all means…

**Comment by nuttycom** [comment]
I accept such bribes. :D

**Comment by djspiewak** [comment]
Incoming…

**Comment by djspiewak** [comment]
Overlaps with #1989.  Basically, the VFS stuff *is* the storage layer; there is no disparity.  Makes sense, if you think about it.  So this ticket is invalid.
