### ISSUE TITLE
Figure out storage stuff (JDBM/NIHDB?)

### ISSUE THREAD

**Issue by zeeiyerWork** [quasar-analytics/quasar#1989]
I think @paulp's current branch is still wired up to JDBM.  That's not a terrible solution just to get things running, but it might be just as easy to rewire NIHDB, especially since we're already resurrecting things more or less en masse.

**Comment by djspiewak** [comment]
Paul's stuff is *not* wired up to JDBM; it's not wired up to anything at all!  All of the storage backends were deleted.  So we're restoring NIHDB, since we have to restore something, and there's no point in restoring any of the sub-optimal alternatives.

**Comment by djspiewak** [comment]
Depends on #2207.  This issue is done once that one closes.
