### ISSUE TITLE
Readme is missing some information about connection formats

### ISSUE THREAD

**Issue by garyb** [quasar-analytics/quasar#1995]
In the section [here](https://github.com/quasar-analytics/quasar#database-mounts) there's a full example of a MongoDB mount, but for the other connectors on the connection URI is listed, and not the mount type name used as the key above the `connectionUri`:

```
      "mongodb": {
        "connectionUri": "mongodb://<user>:<pass>@<host>:<port>/<dbname>"
      }
```

Can we get some clarification on what these values should be? We're assuming `mongodb`, `marklogic`, `couchbase`, but we've discovered some confusion about the name for `spark` in the code we have in the frontend currently (slamdata/purescript-quasar#27).

**Comment by nicflores** [comment]
@garyb,
Would a list of supported connection URI's like this:

```
{
  "server": {
    "port": 8080
  },
  "metastore": {
    "database": {
      "postgresql": {
        "database": "metastore",
        "userName": "postgres",
        "password": "",
        "parameters": {
          "loglevel": 0
        }
      }
    }
  },
  "mountings": {
    "/mongo/": {
      "mongodb": {
        "connectionUri": "mongodb://<host>:<port>/<db-name>"
      }
    },
    "/couchbase/": {
      "couchbase": {
        "connectionUri": "couchbase://<host>[:port]/<bucket-name>?password=<password>&docTypeKey=<type>&[&queryTimeoutSeconds=<seconds>]"
      }
    },
    "/marklogicjson/": {
      "marklogicjson": {
         "connectionUri": "xcc://<username>:<password>@<host>:<port>/<database>[/root/dir/path]?format=json"
      }
    },
    "/marklogicxml/": {
      "marklogicxml": {
         "connectionUri": "xcc://<username>:<password>@<host>:<port>/<database>[/root/dir/path]?format=xml"
      }
    },
    "/sparkhdfs/": {
      "sparkhdfs": {
        "connectionUri": "spark://<spark_host>:<spark_port>|hdfs://<hdfs_host>:<hdfs_port>|<root_path>"
      }
    },
    "/sparklocal/": {
      "sparklocal": {
        "connectionUri": "spark_local=\"/path/to/data/cars.data\""
      }
    }
  }
}
```
be more useful/clear? Each connection URI can be embedded with its respective connector section within the README. Some sections have this info, but maybe using a more explicit json example like the above will help readers a little more.

**Comment by garyb** [comment]
Yeah, that'd be great! Enumerating all the options in one example like this would certainly be handy from the front-end point of view. :smile:

If we're keeping the more in-depth text descriptions for the connector configs it'd still be good to add what the key value should be for the `connectionUri` though, as currently only `mongodb` and `view` keys are mentioned in their respective sections.

**Comment by nicflores** [comment]
@garyb,
Let me know what you think of [this](https://github.com/nicflores/quasar/tree/issue-1995-update-readme-with-connection-uri-info#connector-mountings). I added a section for _Connector Mountings_, with a general format and included a list of the supported protocols.

**Comment by garyb** [comment]
That still doesn't address the `mountKey` variations for each of the connectors, which is the thing I was trying to get out of this originally. :wink:

The `connectionUri` alone is not enough to determine the mount type as far as I understand, it must also be under an appropriate `mountKey` for the mount to be valid.

**Comment by nicflores** [comment]
Ok, @garyb, take another look and let me know what you think.

**Comment by garyb** [comment]
That's perfect, thanks!
