### ISSUE TITLE
MongoDB Atlas 3.4 Support

### ISSUE THREAD

**Issue by damonLL** [quasar-analytics/quasar#2003]
Quasar (and in turn SD) is unable to connect to [MongoDB's Atlas](https://www.mongodb.com/cloud/atlas) cloud offering when Atlas users select MongoDB 3.4 as their cluster version.  MongoDB version 3.2 clusters appear to work.

Also note that we demo against MongoDB 3.4 frequently without issue, but that is outside of an Atlas hosted environment.

**Comment by rintcius** [comment]
Verified on `next-major` - can connect to Mongo Atlas 3.4 with mongo java driver 3.3.0. 
Example URI:

```
"mongodb://kay:myRealPassword@mycluster0-shard-00-00-wpeiv.mongodb.net:27017,mycluster0-shard-00-01-wpeiv.mongodb.net:27017,mycluster0-shard-00-02-wpeiv.mongodb.net:27017/admin?ssl=true&replicaSet=Mycluster0-shard-0&authSource=admin"
```
See https://docs.atlas.mongodb.com/driver-connection/#java-driver-example

**Comment by rintcius** [comment]
verified
