### ISSUE TITLE
epic: QScript: Improvements: Phase-A

### ISSUE THREAD

**Issue by zeeiyerWork** [quasar-analytics/quasar#2008]
More urgent qscript improvements.

**Comment by zeeiyerWork** [comment]
All QScript enhancements slotted for first 1/2 of 2017

**Comment by alissapajer** [comment]
@zeeiyerWork would it be okay if I delete the list of "children" tickets above? I am breaking this up into two separate epics, and we will be able to see which ticket is in which epic based on its label.

**Comment by zeeiyerWork** [comment]
@alissapajer -> Yes. Thanks.
