### ISSUE TITLE
epic: LogicalPlan: Overhaul: Phase A

### ISSUE THREAD

**Issue by zeeiyerWork** [quasar-analytics/quasar#2010]

**Comment by sellout** [comment]
A few changes to the task list:
- #1537 isn’t an LP issue
- #1551 may be obsolete, or should be updated to be `TypeOf` instead of `Match`
- #1798 is really about how we hook up the fallback evaluator (which doesn’t yet exist)
- #1892 is closed
- #1923 is closed
