### ISSUE TITLE
epic: Connector: Generic Issues

### ISSUE THREAD

**Issue by zeeiyerWork** [quasar-analytics/quasar#2014]
Container for issues pervasive across all connectors

**Comment by alissapajer** [comment]
@zeeiyerWork I'm not sure that this epic is necessary. Any issue that affects all connectors can be housed in a more specific epic, for example an epic about `QScript` or `LogicalPlan` or file system algebra improvements. There are only 2 issues in this epic right now. Let me know if I can close this epic and re-house those 2 issues.

**Comment by alissapajer** [comment]
There are now no issues in this epic. One was moved to a qscript epic and the other issue was closed as invalid.

**Comment by zeeiyerWork** [comment]
Sure - will go ahead and close it as unneeded for as of now. The epic originally existed for those issues that exhibit SYMPTOMs that plague all connectors and not a specific connector - but I guess since they will be soon all be based on the abstract connector implementation, we can house issues there or if the CAUSE is known, they can go into QSCRIPT or whatever the underlying cause is.
