### ISSUE TITLE
Default mount to `spark-local` when no mounts specified

### ISSUE THREAD

**Issue by rabbitonweb** [quasar-analytics/quasar#2040]
Now that `spark-local` is mountable from UI, we can add auto-mount when quasar is first installed to folder holding some examples for new users to explore.

Different approaches are possible, most probably the best one would add examples during installation process. But other approaches are possible too.

**Comment by rabbitonweb** [comment]
This issue might be blocked till https://github.com/quasar-analytics/quasar/pull/2038 is merged

**Comment by zeeiyerWork** [comment]
Seems like #2038 is merged -> so can we progress on this issue now?

**Comment by zeeiyerWork** [comment]
We are not doing this - we are instead defaulting to mimir as the default mount point. This gets around the problem of a single "spark-context", while at the same time allowing more Slamdata capability to shine.
Hence closing this out as Wontfix.
