### ISSUE TITLE
Query fails when JOINing 3 MongoDB collections and a WHERE clause

### ISSUE THREAD

**Issue by damonLL** [quasar-analytics/quasar#2041]
The following query fails:

```
SELECT
  firm.Name
from :results AS r
JOIN `/ts/t/FirmAnnualReport` AS f
  ON f.Year = r.Year
JOIN `/ts/t/Firm` AS firm
  ON f.Associations.FirmId = firm.Associations.FirmId
WHERE
  f.Aum <= r.Aum
```

Removing the third collection resolves the issue.  The number of fields in the `SELECT` clause does not matter; tested with single field and multiple fields.

MongoDB error message sent to engineers in separate channel.

**Comment by alissapajer** [comment]
Discussed with @sellout and @damonLL. Bug does not surface when we have a 2-way join; a 3-way join is required. Additionally reference to two distinct join sides in the filter appears to be necessary to trigger the bug as well.

**Comment by sellout** [comment]
This is fixed in new Mongo.

**Comment by rintcius** [comment]
this query works:
```
select z1.city, z2.state, z3.* from `/m32/test/extraSmallZips` as z1 join `/m32/test/smallZips` as z2 on z1.`_id` = z2.`_id` join `/m32/test/zips` as z3 on z2.`_id` = z3.`_id` where z3.pop >= z2.pop
```

@alissapajer  Can you confirm that this query triggered the bug before?

**Comment by alissapajer** [comment]
I ran the following query against mongo 3.2 (legacy) in quasar 20.15.4 and it does not error, and the results look reasonable. I tweaked the query suggested above just a bit to make it mirror the original query better.
```sql
select z3.loc from `extraSmallZips` as z1 join `smallZips.json` as z2 on z1.`_id` = z2.`_id` join `zips` as z3 on z2.city = z3.city where z2.pop <= z1.pop
```
So, there are a few possibilities:

1. This query was fixed on master pre 20.15.4. I will check out HEAD as of the issue creation date and run this query there.
2. The usage of `:results` was causing the error. I will dig up @damonLL's original bug report to gain more insight.
3. There is some other component of the original query that I overlooked in trying to mirror it.

**Comment by alissapajer** [comment]
I ran the mirror query against quasar 18.3.1 and it returns successfully, so I have been unable to replicate the original bug. @damonLL can I ask for your help in confirming that this issue has been fixed? Maybe we can replicate more of the original environment that this query was run in.

**Comment by alissapajer** [comment]
We don't have any more information about the original query, so I am going to close this issue since the query that most resembles the user's query is correct. We can reopen this if the bug surfaces again.
