### ISSUE TITLE
Implement backend abstraction in marklogic

### ISSUE THREAD

**Issue by djspiewak** [quasar-analytics/quasar#2092]
A stub implementation is currently provided.  Further work needs to be done to remove the phantom type-based configuration from marklogic, so that things can be isolated in `Config`.

**Comment by djspiewak** [comment]
This is going to slip out of 4.2.  Even just on compile times alone, it's impossible to get it done, and I keep running into very perplexing implicit resolution issues.  I've pushed my work thus far to `wip/marklogic-abstraction` on my quasar fork.

**Comment by zeeiyerWork** [comment]
I suppose then I should move this to the May iteration. Since without a concrete example (which you mentioned would be Marklogic) on the abstract connector, it would be hard for other connectors to follow. The plan is to hopefully have the other connector developers pair program with @djspiewak during Slamfest to minimize any potential back and forth to get all the connectors onto this abstraction.

**Comment by djspiewak** [comment]
I think that's a good plan. Connector authors would certainly have an easier time than I would, and pairing aggressively is thus the answer.  I just felt that it was important not to push back FBE any further.

**Comment by zeeiyerWork** [comment]
Yep - hear you, but we have maintained that this (the connector abstraction) is a pre-req for FBE. And moving at least 1 connector onto it is a way to validate that the abstraction has reached some modicum of maturity. If we can do some work to validate that and leave the rest to pair programming exercises over 2-3 days @ slamfest, that might be the best way forward.

**Comment by djspiewak** [comment]
It depends on what you want the priorities to be. I could keep working on this, but it's going to stretch out both due to compilation times and because of untangling marklogic's complex implicit dependencies.  I don't see a shortcut to validation.

**Comment by djspiewak** [comment]
As a sidebar in case you missed it: the abstraction itself is already PR'd. This is just the marklogic implementation.

**Comment by wemrysi** [comment]
@djspiewak If I can be of help getting this finished, let me know.

**Comment by zeeiyerWork** [comment]
OK @djspiewak has a valid point. At this point, he should start paying attention to FBE and the Connector developers are tasked with moving individual connectors to the abstraction and working with him on issues. So i will assign those to @rabbitonweb (for Spark), @drostron (for Couchbase), @wemrysi (for Marklogic) and @sellout (for Mongo) as of now. I will pull these into May optimistically, although its just a soft-commitment, with the hope that we can make a lot of progress @ slamfest via pair programming with @djspiewak for a day or more. <thanks>
