### ISSUE TITLE
MarkLogic: Zero Setup

### ISSUE THREAD

**Issue by jdegoes** [quasar-analytics/quasar#2108]
There are two serious usability issues with the MarkLogic connector that need to be rectified:

1. MarkLogic must contain one or more directories in the database before documents will be displayed.
2. MarkLogic documents must be located within a directory, which requires that users create a directory, and place their documents inside there.

Both limitations need to be eliminated so that upon configuring a new MarkLogic mount, with mount configuration accepted by Quasar, the user will see all the data in MarkLogic without any additional steps.

**Comment by jdegoes** [comment]
@damonLL Please review, confirm, and add any other issues.

**Comment by damonLL** [comment]
Thanks @jdegoes, I've asked @wemrysi to comment when he has a moment to provide more insight.  To my best understanding, yes, those are the primary pain points.  After a brief Slack discussion w/ @wemrysi, the situation may be more complex, but will let him comment.

**Comment by wemrysi** [comment]
Just to clarify 2), a "directory" is, effectively, some metadata applied to a path, so if documents have URIs like `/foo/bar/baz.json` then one can create the directories `/foo/` and `/foo/bar/` retroactively without having to move any data around.

**Comment by damonLL** [comment]
That's an important distinction, thanks @wemrysi - I did not convey that accurately to @jdegoes then.  I'll make that doc change as well, as I'm sure many users would not assume that is the case.

**Comment by jdegoes** [comment]
@wemrysi What we're missing is a fool-proof way to mount MarkLogic in such a fashion that "all there data appears". We have to figure out how to get there, because the current situation is too much trial & error.

**Comment by wemrysi** [comment]
Sure, agreed, just trying to give an accurate picture of the current situation.

**Comment by wemrysi** [comment]
Directories currently serve to make filesystem operations in an ML mount tractable in Quasar. Without them, operations like listing the contents of a directory take time proportional in the number of documents in the database having that directory prefix.

Initial attempts at omitting them weren't successful from a performance standpoint, but it'd be worth another look to see if we can figure out how to get the set of immediate children of a path without directories.

Another possibility might be to incrementally create directories that don't exist as a user explores the filesystem, this also has tradeoffs as each directory brings with it an index which must be maintained by the server when new documents are added. Maybe if we encourage the use of multiple, targeted mounts deeper in the filesystem hierarchy over one or two mounts towards the top of the hierarchy, we can limit the effect on the database to just the data a user is interested in analyzing with Quasar.

The indexes implied by directories are also leveraged during queries to limit candidate documents when the path being queried refers to a directory.

**Comment by jdegoes** [comment]
> Without them, operations like listing the contents of a directory take time proportional in the number of documents in the database having that directory prefix.

How about silently ensuring they are indexed appropriately?

**Comment by wemrysi** [comment]
@jdegoes Yeah, that's what I was getting at regarding incrementally creating directories. As operations are performed on the filesystem, we could ensure all the directories in the paths exist, adding them if not. We do this for mutable operations already, but not for read-only operations on existing paths.

**Comment by zeeiyerWork** [comment]
@wemrysi -> If possible, would like to chat with you to brain storm a bit about possible solves. Also can I include this in the May iteration. Seems like an important issue to solve, if the goal is a reasonably usable Marklogic connector which passes some lenient SLAs in terms of simple queries that do not involve aggregation, join. Thanks.

**Comment by wemrysi** [comment]
@zeeiyerWork We can discuss possible solutions, or feel free to add any ideas here if you like. I think the direction that @jdegoes and I were discussing is promising, assuming we're ok with the requirement that using MarkLogic requires the ability to create directories.

Yet another possibility would be to do the fast thing if directories exist and the slow thing if they don't and let users know they can speed things up considerably if they're willing to add directories.

As for adding this to May, sure though we'll likely need to bump something else.

**Comment by jdegoes** [comment]
> @zeeiyerWork We can discuss possible solutions, or feel free to add any ideas here if you like. I think the direction that @jdegoes and I were discussing is promising, assuming we're ok with the requirement that using MarkLogic requires the ability to create directories.

How about creating the directories by default, but if that fails, do the slow thing.

We need to plumb warnings through the system at some point so we can deliver useful information to end-users / IT.
