### ISSUE TITLE
Compiling doesn't fail in some cases where they should

### ISSUE THREAD

**Issue by garyb** [quasar-analytics/quasar#2131]
If you compile the query:

``` sql
SELECT "Hello world"
```

On the MongoDB backend, it doesn't complain about anything. If a view mount is created with that query, attempting to read from the view gives:

``` json
{
  "error": {
    "status": "Failed to execute SQL^2 query.",
    "detail": {
      "message": "Unable to insert data into MongoDB: MongoDB is only able to store documents in collections, not `Text(Hello, World!)`.",
      "data": "Text(Hello, World!)",
      "logicalplan": {
        "type": "LogicalPlan/Invoke",
        "label": "Squash",
        "children": [
          {
            "type": "LogicalPlan/Invoke",
            "label": "MakeObject",
            "children": [
              {
                "type": "LogicalPlan/Constant/Str",
                "label": "\"total\""
              },
              {
                "type": "LogicalPlan/Invoke",
                "label": "Count",
                "children": [
                  {
                    "type": "LogicalPlan/Constant/Str",
                    "label": "\"Hello, World!\""
                  }
                ]
              }
            ]
          }
        ]
      }
    }
  }
}
```

Is there any way we can detect things like this during compilation? It makes error handling in the front end somewhat problematic, as there are some queries we don't get errors for until it's "too late" to provide a good error message.

In theory we could fetch the first result of a view after mounting it or something like that to check this, but if the query is expensive this is really bad.

This kind of problem is quite rare I think, but as we currently provide `SELECT "Hello World";` as the default query, it is right in the user's face (I'll tweak this query to include an `AS value` to avoid this specific instance though).

**Comment by sellout** [comment]
`select "Hello world"` is a valid query that should return the single result `"Hello world"`. And the second query (which looks like it’s maybe `select count(*) from /viewMount`?) is also valid.

But this query should be statically evaluated and never reach a connector. The problem is either that we don’t do view mount substitution until after static evaluation, or (more likely) that there are static evaluation rules missing for one of the LP operations in the error.

**Comment by jdegoes** [comment]
Let's treat this as a bug and fix it. /cc @zeeiyerWork

**Comment by sellout** [comment]
A quick check shows me that `Count` only handles literal sets, not other literals – but all other literals are singleton sets, so should return `1` statically. The other operators look fine.

I can add a test and hopefully fix this quickly.
