### ISSUE TITLE
Include option to append extensions to Quasar file names before downloading

### ISSUE THREAD

**Issue by damonLL** [quasar-analytics/quasar#2144]
Related to SlamData Issue [1714](https://github.com/slamdata/slamdata/issues/1714)

Would like to request a new feature, or fix a feature if this is already supposed to be available.

When a directory within the Quasar file system is requested, Quasar will compress/zip the contents. From SlamData's UI, a user is able to select either CSV or JSON format (or the Quasar API allows selection).  It is clear that Quasar understands the request as the resulting files are appropriately formatted.

However, the files themselves do not contain `.csv` or `.json` extensions after the zip file is uncompressed.  This is probably by design as the file names in the Quasar file system probably don't already contain them.  Can we provide an option that would allow specifying whether or not to add an extension to the file names as they are included in the zipped file?

This is likely more helpful for the SlamData project users than direct Quasar users, but you can imagine a user downloading a database / folder's worth of json files without the .json extensions, opening them in their favorite text editor and not having appropriate syntax highlighting, etc. b/c of the missing extension.

**Comment by jdegoes** [comment]
@damonLL The extension should be automatically chosen and should never be wrong.

Does that work?

**Comment by damonLL** [comment]
@jdegoes not from what we've seen.  Currently you request the download and it provides a compressed zip file.  You unzip it and it contains the folders and files, but none of the files have extensions.

However, if you download a *single* file, it does have an extension.

**Comment by jdegoes** [comment]
@damonLL I know that it's not functioning correctly, but will the above behavior work?

**Comment by damonLL** [comment]
I misunderstood @jdegoes. You're stating what it **should** do?  If that is the case, then yes.

**Comment by jdegoes** [comment]
Perhaps we can add new options to the API:

 * **On Download**: An option to add format extensions to all data files.
 * **On Upload**: An option to strip format extensions from all data files.

Then in the download setup, we can add the following option:

 * **Add file extensions**

This option will add file extensions to files which do not already have them, and it will add extensions based on the content type of the file.

@damonLL Does this seem reasonable?

**Comment by damonLL** [comment]
Sounds perfect, thanks @jdegoes

**Comment by zeeiyerWork** [comment]
Talking to @nicflores -> if the front-end sends content-disposition-filename header = "<filename>.csv.zip" or "<filename>.json.zip" in the request, you will get the desired behavior. So does not look like anything else needs to happen to Quasar. So I will create a slamdata ticket for them to do so, and close this one out.

**Comment by zeeiyerWork** [comment]
Closing this, given https://github.com/slamdata/slamdata/issues/2200

**Comment by garyb** [comment]
Reopening this, as it doesn't quite behave as desired. The requested feature is this:

- Choose to download a single file, as an archive
- The file **inside** the archive gains the file extension of the appropriate type

Currently we can name the archive whatever we want via the content-disposition header, but the file inside the archive will use the exact filename that existed in the VFS.

**Comment by nicflores** [comment]
@garyb, thanks for re-opening this issue. I can confirm that simply editing the content-disposition header with the filename doesn't have the result I had in mind. I'll get on this asap.

**Comment by garyb** [comment]
@nicflores I don't think this is super urgent, if you have other things to do already. It was just something we tested/discussed during SlamJam :)

**Comment by nicflores** [comment]
@garyb, thanks for the heads up.

**Comment by zeeiyerWork** [comment]
@nicflores -> Would be get it by 4.3 code-freeze is possible. We need to make sure all import/export/download and workspace mobility is in a good place, sooner than later. Thanks,

**Comment by nicflores** [comment]
@zeeiyerWork, @drostron and I worked on this a little today. I'm gonna write a couple of tests and hopefully PR this by the end of the day tomorrow.
