### ISSUE TITLE
Audit time stuff

### ISSUE THREAD

**Issue by djspiewak** [quasar-analytics/quasar#2166]
The old joda-time code was incorrectly ported.  Among other things, `org.joda.time.DateTime` is more analogous to `java.time.ZonedDateTime` than it is to `java.time.LocalDateTime` ([source](http://blog.joda.org/2014/11/converting-from-joda-time-to-javatime.html)).  It is very likely that some of the time-related code is buggy, and perhaps in ways which will only show up when we put the code on other servers.

We need to be *very* careful about this!  Attention @damonLL and others!  Just putting this on your radar for when FBE starts doing real things.  We'll loop back to this ticket later.

**Comment by damonLL** [comment]
Thank you for the heads up @djspiewak !  I'm copying @dugdun too.  We haven't heard of any issues with auditing and time, if I'm reading this correctly.  Would this impact anything outside of auditing?  Like timestamp evaluations in a query?

**Comment by alissapajer** [comment]
@damonLL so by "audit" here we meant that we needed to change a bunch of instances of `java.time.LocalDateTime` to `java.time.ZonedDateTime` in the fallback evaluator internals. But we haven't even exposed SQL^2 time-related functions yet in the fallback evaluator, so closing this issue has no effect on SlamData at all, from a user perspective. 

@djspiewak was there some other discussion about this somewhere?

**Comment by alissapajer** [comment]
@damonLL ah I just read the original issue description and now see @djspiewak's alert! Sorry to repeat everything said there :)

So to clarify, we fixed this _before_ we exposed anything time-related to users, so there will not be any user-facing impact.

**Comment by damonLL** [comment]
Aha, thanks @alissapajer! Very good to know.
