### ISSUE TITLE
Write failures when persisting to MarkLogic are not communicated properly

### ISSUE THREAD

**Issue by wemrysi** [quasar-analytics/quasar#2197]
When attempting to persist a document that isn't currently supported by a MarkLogic XML mount, the write fails but the error isn't properly reported. It isn't clear yet whether this is related to the MarkLogic connector or is a more general issue with reporting write errors from any connector.

**Comment by zeeiyerWork** [comment]
Assigning this the may iteration, since it seems that #2124 (which is already in May) depends on this. @wemrysi - assigning this to you for now, but please reassign, if it is something deeper across all connectors.

**Comment by jsantos17** [comment]
@wemrysi I can probably work on this while altering the embedding of EJSON in XML. I'll assign it to myself.

**Comment by wemrysi** [comment]
@jsantos17 Thanks, but I actually already fixed the problem, just need to add a regression test and PR.
