### ISSUE TITLE
Move SparkCore to BackendModule

### ISSUE THREAD

**Issue by rabbitonweb** [quasar-analytics/quasar#2216]
- [x] spark-local
- [x] spark-hdfs
~~- [ ] spark-elastic~~ (moved to https://github.com/quasar-analytics/quasar/issues/2715)
~~- [ ]  spark-cassandra~~ (moved to https://github.com/quasar-analytics/quasar/issues/2716)

**Comment by zeeiyerWork** [comment]
Closing this because it is a duplicate of #2096
