### ISSUE TITLE
Error in query

### ISSUE THREAD

**Issue by rabbitonweb** [quasar-analytics/quasar#2226]
works:
```
SELECT
  quarter AS Q,
  value AS Value,
  region AS Region
FROM `/loc/revenue.ldjson
```

does not work:

```
SELECT DISTINCT Value AS value, Q AS dimension, Region AS series, null AS parallel FROM `/loc/Untitled Workspace 9.slam/.tmp/out2bcf11b8-ccba-445b-9c96-a2beda9f7a4b` ORDER BY Region ASC, Q ASC
```

**Comment by rabbitonweb** [comment]
Should be working once https://github.com/quasar-analytics/quasar/issues/1882 is fixed

**Comment by zeeiyerWork** [comment]
#1882 is fixed in new-mongo. So this can be tested against the next-major branch or against master once next major merges to quasar master (before Aug31).
