### ISSUE TITLE
Multitable Joins in Spark returns no data

### ISSUE THREAD

**Issue by dugdun** [quasar-analytics/quasar#2228]
When building a workspace in Spark, it was noticed that a four table join query returned no results, although the same query in MongoDB with similar data works just fine.

To use the following query, you need to first open the `/loc/customers.data` file and then add a dropdown from the **Setup Form** card and display it. Mirror this deck and add a **Query** card with the following SQL Query.

```sql
SELECT
  o.order_key AS OrderKey,
  o.purchase_date AS PurchaseDate,
  c.last_name || ", " || c.first_name AS Name,
  c.city AS City,
  c.state AS State,
  i.clothing_size AS Size,
  i.clothing_type AS Type,
  i.clothing_color AS Color,
  i.price AS UnitPrice,
  oi.qty AS Quantity,
  i.price * oi.qty AS PricePaid,
  SUM(i.price * oi.qty) AS TotalPaid,
  i.clothing_brand AS Brand
FROM
  :results AS c
JOIN `/loc/orders.data` AS o
ON c.customer_key = o.customer_key
JOIN `/loc/ordered_items.data` AS oi
ON oi.order_key = o.order_key
JOIN `/loc/inventory_items.data` AS i
ON i.item_key = oi.item_key
GROUP BY
  i.price * oi.qty
```

If you limit this query to join on just the `:results` of `/loc/customer.data` and `/loc/orders.data` you will get the expected results.

**Comment by zeeiyerWork** [comment]
A 2-way join between Orders and Customers did return data - so hopefully this turns out to be low effort. Hence scheduled for May, since it would be good to be able to demo this functionality at Spark Summit 2017.

**Comment by alissapajer** [comment]
This may be a qscript issue. There is a know qscript bug (@wemrysi is working on it now for #1929) where we fail to align join provenance with other related provenance. Given how we use the results of joins in this query, we may be hitting that bug.

**Comment by rabbitonweb** [comment]
This issue is solved on backend side. There are separate issues on the frontend that effect this functionality (and some other demo workspaces), but issue for it is already opened on slamdata repo https://github.com/slamdata/slamdata/issues/2142
