### ISSUE TITLE
simple join query does not work

### ISSUE THREAD

**Issue by doglasfc** [quasar-analytics/quasar#2231]
Hi, 
 I'm newcomer to slamdata. just write following query against mondodb 3.4.4.

SELECT b.name as A_NAME, c.c_name as B_CLASS_NAME from `/edb/obj` as b JOIN `/edb/class_obj` AS c ON c._id=b.classobjid

Here:
1. obj and class_obj are two collections undder same database edb.
2. SELECT b.name as A_NAME from `/edb/obj` as b    -----  works, return A_NAME column data
3. SELECT c.c_name as B_CLASS_NAME from `/edb/class_obj` AS c  ---- -----  works, return B_CLASS_NAME column data

always get error as below:

{
  "error": {
    "status": "Malformed SQL^2 query.",
    "detail": {
      "message": "operator '*' expected; but found `*** error: '!' expected but _ found'"
    }
  }
}

it looks slamdata does not support "c._id" as join condition..., but look at the slamdata document, it should work!!!

**Comment by sellout** [comment]
@doglasfc Sorry, I think the docs are slightly out of date with the latest release. The SQL specification requires that identifiers that don’t begin with a letter need to be quoted, so you need to do
```sql
SELECT ... ON c.`_id`=b.classobjid
```

That error message is also unfortunate. It looks like the tokenizer is failing, but then the parser treats the tokenizer’s error message as the unexpected token somehow.

**Comment by doglasfc** [comment]
@sellout Thanks for quick response. actually I did that already. (someone suggested that.)  but no luck, the new error message returned as following:

"  An unknown error occurred: 500 ""  "

It even did very bad thing:  it destroyed mongodb mount info strangely and I'm no longer able to re-create mount again which I always get 
"  An unknown error ocurred: 500 ""  " ,  then I did remove slamdata software and re-install it, I still get same error... I'm using latest slamdata version 4.2.0, what version are you using? Have you tested that?

**Comment by damonLL** [comment]
@doglasfc SlamData will create a `quasar-metastore.mv.db` file which stores the mount information.  You'll need to remove that file since it's likely corrupt now (which I mentioned in the forums).  It's located in the same location as the `quasar-config.json` file, see our [docs](quasar-metastore.mv.db) on where that is.

1. Stop SlamData
2. Remove metastore file
3. Restart SlamData
4. Remount MongoDB

**Comment by doglasfc** [comment]
Thanks for the reply. will do that.  so the key is  following statement is still not working...

SELECT ... ON c.`_id`=b.classobjid

this is what i'm asking right now... Please help!  do you know anyone is working on this issue?

**Comment by alissapajer** [comment]
@doglasfc I'd like to confirm, did you follow the four steps that @damonLL suggested, and then after performing those steps try running the query again? You'll need to run the query after performing those steps in order for the query to work.

**Comment by doglasfc** [comment]
yes. confirmed. actually, before running the test sql2 statement, i have a
fresh slamdata software setup VM environment. (Linuxmint Mate 18.1 +
MongoDB 3.4.4), then mount to MongoDB successfully,, then test query on
single collection successfully, looks everything ok at this point... make a
vm snapshot.

now running the SELECT ... ON c.`_id`=b.classobjid, issue occurred back to
the snapshot was, test other database collections but similar SELECT ... ON
p.`_id`=m.customerid. isuue still there...

thanks!

**Comment by doglasfc** [comment]
yes. confirmed. actually, before running the test sql2 statement, i have a
fresh slamdata software setup VM environment. (Linuxmint Mate 18.1 +
MongoDB 3.4.4), then mount to MongoDB successfully,, then test query on
single collection successfully, looks everything ok at this point... make a
vm snapshot. now running the SELECT ... ON c.`_id`=b.classobjid, issue
occurred back to the snapshot was, test other database collections but
similar SELECT ... ON p.`_id`=m.customerid. isuue still there... thanks!

**Comment by dugdun** [comment]
@sellout after doing some testing around this today, I found out that any MongoDB query joining tables and specifically using the `_id` field will cause metastore corruption. It doesn't matter if `_id` is used in a join

```
select ... on a.`_id` = b.classobjid`
```

or if it's just returned/projected in the results

```
select a.`_id` ... on a.somefield = b.somefield
```

**Comment by dugdun** [comment]
Note that this only appears to happen when `join`ing tables. I can do a single table query using the `_id` field without issue.

**Comment by doglasfc** [comment]
Thank you for taking time to re-produce this issue, please let me know once
the issue has been fixed.

**Comment by doglasfc** [comment]
anyone know the schedule for fixing this issue?

**Comment by zeeiyerWork** [comment]
@sellout and @drostron -> Moved this to ASAP. Metastore getting corrupted is just too intrusive, since you pretty much lose a work. How do we add more defensiveness in the implementation to prevent this.

**Comment by drostron** [comment]
@zeeiyerWork I'll take a look. I'd say the defensiveness will be addressing whatever bug is being hit.

**Comment by sellout** [comment]
I think there is possibly two things here – 1. a query shouldn’t be able to corrupt the metastore, so either there’s a bug in the metastore that needs to be fixed or the metastore needs to signal an error that a connector is doing something bad, and then 2. the connector needs to be fixed to not do that.

I’m kind of skeptical of #2, since connectors don’t/shouldn’t know anything about the metastore, but I also don’t see how the metastore can be corrupted by certain queries otherwise.

**Comment by sellout** [comment]
@drostron I just unassigned myself, but feel free to bring me back on if this needs Mongo stuff solved. Thanks.

**Comment by zeeiyerWork** [comment]
@drostron -> 

1. I am unsure what i did, but after a few workspaces managed to corrupt my metastore locally - this is very intrusive, since I basically lost all of my work. Hence the "ASAP" milestone to this bug.
2. I am unsure if this is relevant, since i did restart slamdata on my local Mac and am unsure if that blows away the old log and starts a new log? So dunno if this is just the symptom of why I can't see my workspaces anymore - But I see this stack trace in the logs:
quasar.metastore.UnexpectedValueException
        at quasar.metastore.package$.unexpectedValue(package.scala:101)
        at quasar.metastore.package$.quasar$metastore$package$$$anonfun$25(package.scala:94)
        at scalaz.$bslash$div.leftMap(Either.scala:98)
        at quasar.metastore.package$.quasar$metastore$package$$$anonfun$24(package.scala:94)
        at doobie.util.composite$Composite$$anon$1$$anonfun$4.apply(composite.scala:45)
        at doobie.util.composite$Composite$$anon$1$$anonfun$4.apply(composite.scala:45)
        at doobie.util.composite$Composite$$anonfun$1$$anonfun$apply$3.apply(composite.scala:37)
        at doobie.util.composite$Composite$$anonfun$1$$anonfun$apply$3.apply(composite.scala:37)
        at doobie.free.resultset$ResultSetOp$$anonfun$primitive$1$$anonfun$apply$1.apply(resultset.scala:91)
        at scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:339)
        at scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:339)
        at scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$7.apply(Task.scala:347)
        at scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$7.apply(Task.scala:347)
        at scalaz.concurrent.Task$.Try(Task.scala:457)
        at scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:347)
        at scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:347)
        at scalaz.concurrent.Future.step(Future.scala:119)
        at scalaz.concurrent.Future.unsafePerformListen(Future.scala:75)
        at scalaz.concurrent.Future$$anonfun$unsafePerformListen$1$$anonfun$apply$4.apply(Future.scala:79)
        at scalaz.concurrent.Future$$anonfun$unsafePerformListen$1$$anonfun$apply$4.apply(Future.scala:79)
        at scalaz.Free$$anonfun$map$1.apply(Free.scala:99)
        at scalaz.Free$$anonfun$map$1.apply(Free.scala:99)
        at scalaz.Free.resume(Free.scala:117)
        at scalaz.Free.go2$1(Free.scala:161)
        at scalaz.Free.go(Free.scala:165)
        at scalaz.Free.run(Free.scala:271)
        at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:432)
        at scalaz.concurrent.Future$$anonfun$apply$15$$anon$3.call(Future.scala:432)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by damonLL** [comment]
Are we leaving a connection pool open when we don't need to? We also ran into corruption of metastore when the JVM had an OutOfMemoryError, so maybe we're not opening and closing the connection on an as-needed basis, and simply leaving it open until we shut down Quasar? Just a thought, seen it happen with other apps.

**Comment by drostron** [comment]
@zeeiyerWork @damonLL I have a fix and a PR is imminent. There's a bug related to rendering sql that's hit when writing view queries to the metastore.

**Comment by doglasfc** [comment]
So #2231 is fixed? where I can download this fixed version?  ( Can't find it  on https://slamdata.com/community-edition/ )

**Comment by jdegoes** [comment]
@doglasfc You must build SlamData from source code, unless you are a SlamData customer, in which case you have access to the downloads.

**Comment by doglasfc** [comment]
I did download  slamdata-4.2.2-qa-prerelease-7, build it from source code successfully, but it can't create mount to mongodb 3.4. the error message is: "There was a problem saving the mount: AJAX request failed: GET /metadata/fs/"

**Comment by jdegoes** [comment]
You will need to run the Quasar Analytics service and point SlamData to it. I suggest posting to the SlamData user forum to see what other users of Community are doing to get it running.
