### ISSUE TITLE
Old-Mongo connector: SQL2 AVG function seems to not work?

### ISSUE THREAD

**Issue by zeeiyerWork** [quasar-analytics/quasar#2259]
## Environment:
Slamdata: 4.2.0 | Mongo: local on my machine -> MongoDB shell version v3.4.2

## Issue:
AVG(column-name) in SQL-2 returns nothing.

## Anecdote:
- SELECT c.name as hotelName, AVG(c.rating) AS avgRating, count(*) AS ratingCount FROM `/testDB/myMongo/hotelDB/hotelReviews` AS c WHERE c.name like "Hyatt%" GROUP BY c.name
- Returns attached image (Note that AVG returns nothing) - sounds like a BUG, since the documentation advertises [AVG as functional in SQL-2 Documentation.
](http://docs.slamdata.com/en/latest/sql-squared-reference.html?highlight=AVG#double-grouping)
![image](https://cloud.githubusercontent.com/assets/24783629/26601986/d25b65ee-4536-11e7-9c18-530b56ded5aa.png)

## Other Explanations:
- Don't hold water
- Rating does have values in it, since one can see it in Preview (numbers) and Charts (avgRating by hotel) etc.
![image](https://cloud.githubusercontent.com/assets/24783629/26602093/2bd898ee-4537-11e7-9fb4-d60781136f7f.png)
![image](https://cloud.githubusercontent.com/assets/24783629/26602133/4e6ee084-4537-11e7-818b-fc0d3f29f4b3.png)

## Dataset:
is [this](https://data.world/datafiniti/hotel-reviews) imported into Mongo.

Yes, I should test via REPL as well, but didn't

**Comment by jdegoes** [comment]
@zeeiyerWork Is rating a string value or a numeric value?

**Comment by zeeiyerWork** [comment]
@jdegoes: numeric, imho.  

> db.hotelReviews.findOne();
{
	"_id" : ObjectId("592ccf745f12b7696652f77a"),
	"address" : "Riviera San Nicol 11/a",
	"categories" : "Hotels",
	"city" : "Mableton",
	"country" : "US",
	"latitude" : 45.421611,
	"longitude" : 12.376187,
	"name" : "Hotel Russo Palace",
	"postalCode" : 30126,
	"province" : "GA",
	"reviews" : {
		"date" : "2013-09-22T00:00:00Z",
		"dateAdded" : "2016-10-24T00:00:25Z",
		"doRecommend" : "",
		"id" : "",
		**"rating" : 4,**
		"text" : "Pleasant 10 min walk along the sea front to the Water Bus. restaurants etc. Hotel was comfortable breakfast was good - quite a variety. Room aircon didn't work very well. Take mosquito repelant!",
		"title" : "Good location away from the crouds",
		"userCity" : "",
		"username" : "Russ (kent)",
		"userProvince" : ""
	}
}

**Comment by dugdun** [comment]
@zeeiyerWork the field that you want to aggregate on is **reviews.rating** and not **rating** as you have in your query. Once you make that change you should get the results you're expecting.

**Comment by zeeiyerWork** [comment]
@dugdun, @jdegoes: got it - i just realized that after some more querying. 
I guess a warning would have helped that this column does not exist, wrt usability (i suppose we could do more once SST is in play).

> db.hotelReviews.find ( {name: /^Hyatt/}, {"name":1, "reviews.rating":1}).pretty()
{
	"_id" : ObjectId("592ccf745f12b7696652fd4c"),
	"name" : "Hyatt Regency Reston",
	"reviews" : {
		"rating" : "2"
	}
}
