### ISSUE TITLE
Appears that SQL-2 parser does not play well with columns that start with a number? 

### ISSUE THREAD

**Issue by zeeiyerWork** [quasar-analytics/quasar#2262]
## ENVIRONMENT:
Slamdata 4.2.0 | Mongo: Local. 3.2.4

## ISSUE
Appears we have difficulty parsing SQL-2 queries if column names start with a number.

## DATASET:
- not relevant, since it can be reproduced easily.

## ANECDOTE:
SELECT c.Dismissal as dismissal, AVG(c.BF) as ballsFaced, AVG(c.Mins) as minutesAtCrease, AVG(c.Runs) as runsScored FROM `/testDB/myMongo/sportsDB/playerSRT` AS c WHERE c.Runs NOT in "DNB" GROUP BY c.Dismissal

works and produces chart as in the below image.
![image](https://cloud.githubusercontent.com/assets/24783629/26610076/33767c88-455a-11e7-9c77-1520af244c55.png)

However, 
SELECT c.Dismissal as dismissal, AVG(c.4s) as fours, AVG(c.6s) as sixes, AVG(c.BF) as ballsFaced, AVG(c.Mins) as minutesAtCrease, AVG(c.Runs) as runsScored FROM `/testDB/myMongo/sportsDB/playerSRT` AS c WHERE c.Runs NOT in "DNB" GROUP BY c.Dismissal
returns: 
  **SQL-2 Malformed query exception.
 "message": "operator '*' expected; but found `4'"**

## ALTERNATIVE EXPLANATIONS:
- Tried wrapping the column name in all manners of quotes, but to no avail.
- Mongo itself allows document fields to start with numeric prefix.
- And preview Table does not seem to have an issue with it as in this image.
![image](https://cloud.githubusercontent.com/assets/24783629/26610121/6912f02e-455a-11e7-9a7b-c5b5b183a969.png)

## OTHERS:
- Could not find any documentation about this.
- Have only tested with front-end, not with REPL.

**Comment by sellout** [comment]
Examples of “all manners of quotes” would be helpful. SQL does require identifiers that start with numbers to be quoted. What _should_ work is
```sql
avg(c.`4s`)
```
If it does, please close this.

**Comment by zeeiyerWork** [comment]
You are correct -> It does work. I did try all of the quotes, ', "", `, escaping with \ etc. - but seems I must have missed the back-tick. Closed.
