### ISSUE TITLE
Basic QA testing for mimir

### ISSUE THREAD

**Issue by djspiewak** [quasar-analytics/quasar#2268]
This is basically the final stage of the initial implementation epic.  Depends on all the rest.  We're less concerned about individual queries failing, and more interested in QA testing all the functionality that the frontend needs to do (load, save, etc).  Whatever the frontend does.

Assigned to Iyer so he can delegate to QA once the rest of the enclosing epic (#1732) is done.

**Comment by zeeiyerWork** [comment]
Reassigning this to @dugdun - perhaps we should get started with what test cases we want to subject it to. Ideally in the long run there will be an equivalent set of demos on sd1.demo.slamdata.com against mimir.

**Comment by djspiewak** [comment]
@zeeiyerWork What criteria would you apply to this?  QA is ongoing on mimir; should this be closed?

**Comment by zeeiyerWork** [comment]
Yeah @daniel - you authored it, but QA is ongoing (including Mimir) via Profiq + sporadic efforts from doug. I suppose the goal should be to have data-sets used @sd1.demo.slamdata.com in mimir and making sure they work just as well.That is happening independently, so agree with closing it.
