### ISSUE TITLE
MongoDB Arithmetic Operators - Phase A

### ISSUE THREAD

**Issue by rintcius** [quasar-analytics/quasar#2272]
Implement some of the arithmetic operators as mentioned in https://github.com/quasar-analytics/quasar/issues/1954

### Arithmetic Operators

 - [x] Support `$abs`
 - [x] Support `$ceil`
 - [x] Support `$floor`
 - [x] Support `$trunc`

**Comment by zeeiyerWork** [comment]
Assigning June milestone based on chat with @rintcius

**Comment by zeeiyerWork** [comment]
@rintcius, @sellout -> Take it you will create supporting tickets if needed in other epics, if the work is mostly about exposing these in SQL-2 and LP.

**Comment by alissapajer** [comment]
@zeeiyerWork these math operations are low priority per the discussion here https://github.com/quasar-analytics/quasar/issues/2198#issuecomment-316174962. Would it be okay if we don't include this is the "New Mongo" epic?

**Comment by rintcius** [comment]
verified
