### ISSUE TITLE
Create new API endpoint to allow clients to configure Metastore database location

### ISSUE THREAD

**Issue by jedesah** [quasar-analytics/quasar#2274]
This API will update the contents of the quasar config file to reflect the new backing store specified by the client and start using the new metadata store for any future API requests.

Couple questions:
- Should the endpoint return a failure response and not do anything if it can't connect to the new database or should it change the config file and just continue with the current metastore or should this be an option? Unless someone has an objection I will go with fail for a database configuration that does not point to a live database
- Should Quasar attempt to roll over all content of the current metastore to the new metastore if the new one is empty (or even if it is not...)? I am thinking it should not, that it should just start running with wtv it finds in the new one and initialize the new one to the starting state if it's empty. We can always create a `/migrate` endpoint for migrating the current configuration of a metastore to another. Perhpas it would be reasonable to make this an optional parameter of the request to avoid creating an entirely new endpoint. I'll go with this last option unless anyone has any objections.

**Comment by jedesah** [comment]
@jdegoes If we successfully connect to the new metastore but fail when attempting to persist the new metastore location value to the config file should we abort the whole thing? I'm thinking yes.

**Comment by jdegoes** [comment]
> Should the endpoint return a failure response and not do anything if it can't connect to the new database or should it change the config file and just continue with the current metastore or should this be an option? Unless someone has an objection I will go with fail for a database configuration that does not point to a live database

We should make it difficult as possible (ideally: impossible) to transition the configuration from a working state to a non-working state. If necessary, later and in response to customer demand, we can add a "force" mode.

> Should Quasar attempt to roll over all content of the current metastore to the new metastore if the new one is empty (or even if it is not...)? 

Combining them is conflation and reduces composability. Better to have a separate migration endpoint like you note. With that said, however, if the intention of the user is migration, and the new target has no metadata, then the moment that Quasar "switches over" to the new target, the user becomes unauthorized. This argues that switching should at least come with the option of migration, so a user isn't left in a stranded, non-functional state (see first point).

> If we successfully connect to the new metastore but fail when attempting to persist the new metastore location value to the config file should we abort the whole thing? I'm thinking yes.

I think so. See first point.

**Comment by kRITZCREEK** [comment]
Is this fully implemented (can I start integrating this with the frontend)?

**Comment by jedesah** [comment]
@kRITZCREEK Yes! Thx for asking. Wanted to notify you but forgot.

**Comment by zeeiyerWork** [comment]
@jedesah - so where did we end up on the data-migration. 
What @kRITZCREEK suggests at least makes sure you are not completely locked out. 

But is there a separate ticket for data migration (Typical use-case: Download slamdata and work with it. Happy - now move it to a departmental level implementation by switching from H2 to Postgres. So as per the commentary earlier, seems like we must minimally move admin/user group then give the option if they want to move all the contents over from H2-> Postgres.
