### ISSUE TITLE
Mounting a Module creates a spurious warning

### ISSUE THREAD

**Issue by jedesah** [quasar-analytics/quasar#2282]
The Module is still mounted and works as expected but the repl or the server complains about failing to mount a mount of type `module'`.

Presumably somehow a duplicate of the mount with a type of `module'` is created in the datastore

**Comment by garyb** [comment]
I don't think it's actually finding `module'`, that's just part of the message:

```
Warning: Failed to mount '<name>' because 'Invalid mount config, '<module contents>', because: Unsupported filesystem type: module'.
```
So:
```
'Invalid mount config, '<module contents>', because: Unsupported filesystem type: module'
```

It's just a little hard to see with the nested quotes.

**Comment by garyb** [comment]
It's the same error as #2836 for sure too, but I don't see it until using the latest Quasar :wink:

**Comment by garyb** [comment]
Actually, sorry, I could be wrong about that. I am now seeing it on my downgraded-to-v23 Quasar also. Looks like I'm just unobservant, or perhaps didn't have any modules mounted :smile:
