### ISSUE TITLE
Modify `/server/port` endpoint to persist port change to config file

### ISSUE THREAD

**Issue by jedesah** [quasar-analytics/quasar#2284]

**Comment by zeeiyerWork** [comment]
@jedesah -> Will this cover logfile location and SSL Configuration as specified in "Server" tab on the front-end or are those covered in a separate ticket?

**Comment by jedesah** [comment]
This is done. Forgot to close. But no, it doesn't cover SSL and auditing config. This was done in Quasar whereas those two other things are specific to SlamData backend. Currently struggling with how to achieve reusability in SlamData Backend so to not just re-do the work that was done in Quasar. We've accumulated some technical debt in that regard
