### ISSUE TITLE
MP4 H.264 Videos don't play in Safari

### ISSUE THREAD

**Issue by beckyconning** [quasar-analytics/quasar#2313]
They do when hosted from other web servers but not when hosted from Quasar.

**Comment by beckyconning** [comment]
![screen shot 2017-06-12 at 15 04 51](https://user-images.githubusercontent.com/457901/27038863-21d1244a-4f84-11e7-8194-1a33869e08c1.png)

**Comment by natefaubion** [comment]
Is this the content-type issue we had previously with font files? What content-type is it sending?

**Comment by jedesah** [comment]
@beckyconning Any chance you could post an intro video on this ticket?

**Comment by jedesah** [comment]
@beckyconning I seem to be able to reproduce this. I'm still curious why in the image you posted there are two lines and one of them is red while the other is black and they are not identical.
