### ISSUE TITLE
Extend the `GET /metadata/fs/[path]` endpoint with `offset` and `limit` parameters

### ISSUE THREAD

**Issue by garyb** [quasar-analytics/quasar#2315]
For slamdata/slamdata#1848, and just general sensible-web-api-ness we could use the ability to paginate the FS data for cases when there are large numbers of items present.

I'd suggest something that follows the same scheme as the `GET /data/fs/[path]` endpoint, adding optional `?offset=[offset]&limit=[limit]` query parameters.

**Comment by Cmdv** [comment]
cheers @garyb was going to ask about this 😃
