### ISSUE TITLE
can't mount mongodb 3.4 when run slamdata-4.2.2-qa-prerelease-7 ???

### ISSUE THREAD

**Issue by doglasfc** [quasar-analytics/quasar#2327]
the error says:   "There was a problem saving the mount: AJAX request failed: GET /metadata/fs/"

**Comment by zeeiyerWork** [comment]
No one else seems to be reporting issues mounting mongodb with slamdata 4.2.2 or later. So I am going to close this as some kind of a transient issue. Further, this should be filed in slamdata (the ui that fronts quasar). hope that works.
