### ISSUE TITLE
Enable `unifyFlattenedFieldsWithUnflattened` for at least one qscript-based backend

### ISSUE THREAD

**Issue by alissapajer** [quasar-analytics/quasar#2331]
This integration test query
```
select `_id` as zip, loc[*] from zips order by loc[*]
```
along with the very similar `unifyFlattenedFieldsWithMultipleUses`
```
select `_id` as zip, loc[*] from zips where loc[*] > 68 order by loc[*]
```
is creating qscript that includes a theta join. The qscript should not contain a theta join. To note, the query
```
explain select loc[*] from zips order by loc[*] 
```
does not contain a join in the qscript, so the additional field selection is causing source merging to fail. Also to note, the qscript for the query
```
explain select `_id` as zip, loc[*] from zips
```
does not contain a join but contains many unused array elements, so pruning those could help with the source merge mentioned above.

**Comment by alissapajer** [comment]
The problem has nothing to do with the alias; `explain select state, loc[*] from zips order by loc[*]` provides an equivalent example of the problem.

**Comment by wemrysi** [comment]
This appears to have regressed with the removal of the legacy MongoDB connector.

**Comment by alissapajer** [comment]
This integration test is also tracked in #2366 where it's classified as a bug in `LogicalPlan`.
