### ISSUE TITLE
Add metastore resilience for corrupt views

### ISSUE THREAD

**Issue by drostron** [quasar-analytics/quasar#2340]
Recently we've seen a few SQL² pretty printer bugs cause the entire metastore to become corrupt despite most mounts and views being unaffected.  Ideally we'd issue a warning and skip mounting the corrupt view rather than giving up on the entire metastore.

**Comment by zeeiyerWork** [comment]
Metastore corruption related issues -> 
- https://github.com/quasar-analytics/quasar/issues/1910  
- https://github.com/quasar-analytics/quasar/issues/2294
