### ISSUE TITLE
Support SSTs on Processes

### ISSUE THREAD

**Issue by natefaubion** [quasar-analytics/quasar#2344]
Currently the features are mutually exclusive. If we use processes, we can't use SSTs, and if we use SSTs we can't use processes.

**Comment by jdegoes** [comment]
@zeeiyerWork High priority for this one.

**Comment by jedesah** [comment]
What are SSTs?

**Comment by natefaubion** [comment]
https://github.com/quasar-analytics/quasar/pull/2125

**Comment by zeeiyerWork** [comment]
@natefaubion -> Since this issue is created in quasar, I take it what you are saying is that SSTs implementation needs mutations to accommodate "processes" ?

**Comment by zeeiyerWork** [comment]
@wemrysi - please lmk how i can help. Given high priority, assigned it to ASAP milestone.

**Comment by natefaubion** [comment]
@zeeiyerWork Yes.

**Comment by wemrysi** [comment]
@natefaubion Given support for processes in queries (#2178), would supporting SSTs for an arbitrary query suffice?

This would replace the current support for a path, to recover that you'd just ask for an SST for `select * from /the/path`.

**Comment by zeeiyerWork** [comment]
From what I discovered in conversations with @garyb -> SSTs need to support functions so as to make them composable vis-a-vis the interfaces for "processes"

**Comment by wemrysi** [comment]
Yeah, it's what "support" looks like that I'm trying to ascertain. If we can generate an SST for any query, and you can import functions and call them in queries, is that enough? If it isn't, what is?

**Comment by garyb** [comment]
> Given support for processes in queries (#2178), would supporting SSTs for an arbitrary query suffice?
> 
> This would replace the current support for a path, to recover that you'd just ask for an SST for `select * from /the/path`.

@wemrysi from my point of view that sounds great - there may be other concerns @natefaubion knows of that I don't though.

**Comment by garyb** [comment]
Thinking more on it, I'm pretty confident that if arbitrary queries are accepted and variables can be passed through as part of the request (ala `GET /data/`) that's all we need though - the variable-passing is the only other condition that "processes" would require.

Would changing the interface to be query-based cause issues with potentially caching computed SST info if that comes in further down the line though?

**Comment by wemrysi** [comment]
@garyb Sounds good, I'll have `GET /schema` accept a query and variables similar to `GET /query`, in addition to the compression parameters.

As for caching, I'm not really sure. I can speculate, but without actual requirements its hard to say. It would seem that, for queries equivalent to a read of a path, using `/foo/bar/baz` as a cache key and `select * from /foo/bar/baz` would be fairly similar.

**Comment by natefaubion** [comment]
The issue is that with process, I don't have a query. I have a path to function within a module mount, and the arguments to pass to that module. I suppose I can generate a bogus query from that, but since I already have the path and arguments, it seems like the interface could largely be the same.

**Comment by wemrysi** [comment]
@natefaubion Yeah, creating a query that invokes the process is what I had in mind. Supporting SSTs on queries seems to allow for a single, consistent interface for all datasets (static or computed), which is why I suggested it. It also seemed from other SST discussions that this was desired (i.e. the only way to get at metadata in a dataset is via a query). We started with only supporting SSTs on paths as it was easiest and wasn't clear (to me, at least) yet on how SlamData would consume them.

@jdegoes what do you think?

**Comment by wemrysi** [comment]
@natefaubion If using a query is going to be an issue for slamdata let me know and I'll investigate other options.

**Comment by natefaubion** [comment]
No, it's not really an issue as long as I can import other modules in the query. It just adds a somewhat redundant wrapper around it, and I don't know what any of the other implications for SSTs or caching are, so I'll defer to y'all.
