### ISSUE TITLE
SST interval values are turned into decimals

### ISSUE THREAD

**Issue by garyb** [quasar-analytics/quasar#2356]
From some test data like this:

``` json
{ "testInterval": { "$interval": "P7DT12H34M" } }
{ "testInterval": { "$interval": "P3DT12H34M" } }
```

The returned structure is:

``` json
            "testInterval": {
                "measure": {
                    "count": 2,
                    "distribution": {
                        "mean": 477240000,
                        "variance": 59719680000000000
                    },
                    "min": 304440000,
                    "max": 650040000
                },
                "structure": {
                    "type": "decimal"
                }
            }
```

**Comment by sellout** [comment]
This may also be Mongo-specific, like #2355, for the same reason (Mongo uses decimal values as intervals, even though `"P1MT"` isn’t always the same number of seconds 😕)

**Comment by garyb** [comment]
@sellout looks like you're right with this one too, as spark local gives a map. However, it still is just encoded as a map with a seconds property, so it also doesn't encode intervals faithfully. :wink:

**Comment by wemrysi** [comment]
@garyb Hm, good point, interestingly the representation we're using for that type in Quasar only provides a time-based representation, so we don't have any more information than, effectively, seconds + nanoseconds. We'll need to change that if we want to represent date-based values.

**Comment by garyb** [comment]
That's probably a separate issue from what we're seeing here then I guess, as this is accurate in terms of how a query would behave if an interval is used in the current representation. Should I open a new one?

**Comment by wemrysi** [comment]
@garyb Agreed, a new issue would be welcome, thanks!
