### ISSUE TITLE
SST json encoding - precise?

### ISSUE THREAD

**Issue by garyb** [quasar-analytics/quasar#2358]
This one is more of a question... and at the moment a redundant one at that! After #2354 #2355 #2356 #2357 it will be important though.

Because of the above issues I've not been able to have the `/schema` endpoint produce a value that would need `precise` encoding for it to be unambiguous, but I just wanted to double check whether that is the case - the `Accept` header seems to be ignored on this endpoint.

**Comment by wemrysi** [comment]
As I mention in #2354, we aren't currently preserving metadata about the structure of values in SSTs, so some of the type information is lost. How we decide to handle that will inform how the results of the `/schema` endpoint are encoded.

Currently, we're precise-encoding the `EJson` representation of the values, but we don't have the metadata to know that a map used to be a `timestamp` or an `oid`.
