### ISSUE TITLE
Metastore corruption when querying from a subquery using union all

### ISSUE THREAD

**Issue by dugdun** [quasar-analytics/quasar#2361]
I know that there have been other metastore issues and some have been fixed in the 4.2.2 QA builds, but I've come across another case of corruption in the latest QA build. This might fall under the work being tracked in #2340, but wanted to call out the specifics of this case.

SlamData version 4.2.2QA8

The following query causes metastore corruption:

```
SELECT
        *
FROM
    (
        SELECT
                1 as val
            ,   "test1" as type
        UNION ALL
        SELECT
                2 as val
            ,   "test2" as type
        UNION ALL
        SELECT
                3 as val
            ,   "test3" as type
        UNION ALL
        SELECT
                4 as val
            ,   "test4" as type
    ) as OUTPUT
```

This writes a view out to the metastore, and this is what we save:

```
PATH         : /mongodb-3.4/dougsworkflows/Misc/John - Try to pivot.slam/.tmp/out450476ef-e57e-4a4e-80cc-2adc7d9f5a0d
TYPE         : view
CONNECTIONURI: sql2:///?q=%28select%20%2A%20from%20%28%28%28%28select%201%20as%20val%2C%20%22test1%22%20as%20type%29%29%20union%20all%20%28%28select%202%20as%20val%2C%20%22test2%22%20as%20type%29%29%29%20union%20all%20%28%28select%203%20as%20val%2C%20%22test3%22%20as%20type%29%29%29%20union%20all%20%28%28select%204%20as%20val%2C%20%22test4%22%20as%20type%29%29%20as%20output%29
```

At this point in time, SlamData is unusable and we see entries in the log about `quasar.metastore.UnexpectedValueException`.

**Comment by jdegoes** [comment]
However this is fixed, in the end, no issue should cause SlamData to fail to start (least of all queries stored in views!).

**Comment by drostron** [comment]
Agreed and #2340 will address this generally for the metastore. The current behavior is as it's been in QAdv since its introduction.
