### ISSUE TITLE
Preserve type metadata in SSTs

### ISSUE THREAD

**Issue by wemrysi** [quasar-analytics/quasar#2363]
Generating SSTs should take type metadata (`{"_ejson.type" : ...}`) into account and only merge structure where the type is equal, when present, preserving the tagged structure as unique otherwise.

Motivated by #2354, #2355, #2356 and #2357.

**Comment by jdegoes** [comment]
Only `.ejson.type` counts for equality — all other metadata, arguably, should not differentiate between two otherwise identical values. Though the metadata itself could be analyzed separately to result in statistical type for the metadata.
