### ISSUE TITLE
Support optional common subexpression elimination

### ISSUE THREAD

**Issue by sellout** [quasar-analytics/quasar#2374]
Add an optional transformation for connectors that support `let` expressions to eliminate duplicate subexpressions.

**Comment by alissapajer** [comment]
This is contained within #1549. I'll keep this open since we might want to implement the portion with `let` separately from other subexpression elimination.

**Comment by alissapajer** [comment]
Closing as it's tracked by #1549. Since #1549 isn't a small task, it will likely require other issues which may well fall into an epic.
