### ISSUE TITLE
MongoDB String Operation Expressions

### ISSUE THREAD

**Issue by zeeiyerWork** [quasar-analytics/quasar#2388]
Again are these already supported and it is more about Mapfunc work? If so, please rehome the issue under the appropriate epic/topic.
- [x] $indexOfBytes, 
- [x] $indexOfCP, 
- [x] $split, 
- [x] $strLenBytes, 
- [x] $strLenCP,  
- [x] $strcasecmp, 
- [x] $substrBytes, 
- [x] $substrCP

**Comment by zeeiyerWork** [comment]
@rintcius , @sellout -> Please rehome or create shadow issue in SQL-2/LP epic if appropriate.

**Comment by zeeiyerWork** [comment]
Decide on which ones are exposed via SQL-2 and which ones stay hidden. 
- So all have to be implemented in the connector.
- But we have to decide which ones require SQL-2 representation and corresponding work in SQL-2 parser, LP and QScript (@alissapajer, @jdegoes -> any opinions on which ones).

**Comment by jdegoes** [comment]
Many of these can be taken advantage of if exposed in their more general form (as an ordered set-level operation which the user can apply to a "zoomed in" array of chars). Though if we're too far away from that now, we could add them as special case functions and generalize later.

**Comment by sellout** [comment]
Most of these (all the `*Bytes`/`*CP` ones) simply replace existing operations, and we should use the `CP` variants on the newer versions of Mongo.

`$strcasecmp` – I’m not sure if this should be exposed via MapFunc, but should perhaps be used as an optimization of `Eq(ToLower(a), ToLower(b))` ⇒ `$strcasecmp(a, b)` (and a similar match for ToUpper/ToUpper).

`$split` probably needs to be exposed in MapFuncCore.

**Comment by rintcius** [comment]
Notes: 

- `$strcasecmp` was already there
- didn't expose `$split` for now since I couldn't find a similar SQL function
- used the `*Bytes` variant for `length` analogous to how Mysql works https://stackoverflow.com/questions/1734334/mysql-length-vs-char-length (there is also a `char_length` which maps to the `CP` variant)
- also used the `*Bytes` variant for `substring` because 1) it is in agreement with the existing StdLib tests where the `CP` variant is not 2) it is in agreement with how `length` above works

**Comment by jdegoes** [comment]
@rintcius `SPLIT` is definitely needed, see here: https://github.com/quasar-analytics/quasar/issues/2455

It should return an array of strings.

**Comment by rintcius** [comment]
adding `split` function but in separate PR #2554

**Comment by rintcius** [comment]
Note: used `CP` variants after all - see https://github.com/quasar-analytics/quasar/pull/2548#issuecomment-318485862

**Comment by rintcius** [comment]
verified
