### ISSUE TITLE
SST TypeStat measure values are hard to decode without looking deeply at the structure

### ISSUE THREAD

**Issue by garyb** [quasar-analytics/quasar#2404]
From some test data like this:

``` json
{ "testString": "abc" }
{ "testString": "hello world" }
{ "testString": "qwerty" }
```

The returned structure is:

``` json

            "testString": {
                "measure": {
                    "count": 3,
                    "min": "abc",
                    "max": "qwerty",
                    "minLength": 3,
                    "maxLength": 11
                },
                "structure": {
                    "type": "array",
                    "of": {
                        "measure": {
                            "count": 3
                        },
                        "structure": {
                            "type": "character"
                        }
                    }
                }
            }
```

Which isn't incorrect, but it makes the `TypeStat` difficult to decode - we don't know it's a string, so either we have to try every type stat parse permutation and backtrack, or ideally we'd include the information somewhere in the result so that we know it's a string - this is probably related to the likes of #2354, in that stringiness might be available as metadata? 

Another option would be to include a `tag` field for each `TypeStat` constructor so we could decode unambiguously based on that alone. That would be ideal in fact, as we could solve `const` stats the same way then, as that has basically the same problem.

**Comment by wemrysi** [comment]
@garyb The stringiness for the `TypeStat` is known already, just not made explicit anywhere as you pointed out. I think adding a `tag` field or similar sounds good.
