### ISSUE TITLE
Confusing relative import resolution within SQL^2 modules

### ISSUE THREAD

**Issue by natefaubion** [quasar-analytics/quasar#2418]
I would like to get some clarification about how relative imports should resolve in the following cases within a module mounted at `/foo`:

```sql
-- 1) Relative import
IMPORT `./bar`;

-- 2) Relative import in a function
CREATE FUNCTION bar(:n)
BEGIN
  SELECT * FROM `./baz` WHERE n < :n
END

-- 3) Relative import passed in via `invoke`
CREATE FUNCTION baz(:path, :n)
BEGIN
  SELECT * FROM :path WHERE n < :n
END
```
Where (3) is called as 
```
/invoke/fs/foo/baz?path=`./quux`&n=42
```

For (1), it currently resolves _inside_ the module, so `/foo/bar`, which is really strange since I'm also defining a function at `/foo/bar`. Should it instead resolve to `/bar`, ie. a sibling module?

For (2), I'm not actually sure what it does currently, but since a function has a path on the file system, my assumption would be that it should resolve to `/foo/baz`, and in any case, (2) and (3) should resolve identically I'd think.

Some other questions
  * Can I mount a module at the same path as a function?
  * Can I create a file at the same path as a module?
  * Can I create a file within a module?
  * Are modules and files in completely different namespaces that may or may not overlap?

**Comment by natefaubion** [comment]
Or rather, are modules, functions, and files all in separate namespaces? Like could I have a function, module, or path at any given point on the filesystem?

**Comment by zeeiyerWork** [comment]
@jedesah and @natefaubion -> Can this issue be closed since @jedesah is referencing a PR that seems to fix a related issue?

**Comment by jedesah** [comment]
It's no longer a blocker for the frontend, but this ticket is still valid as the spec needs to be clarified regarding this issue.

**Comment by jdegoes** [comment]
@jedesah In my opinion, all relative links inside a module should resolve relative to the location of the module. All relative links inside a query (including imports) resolve relative to the location of the query.

@natefaubion Thoughts?

**Comment by jedesah** [comment]
> all relative links inside a module should resolve relative to the location of the module

I just want to bring attention to the fact that although that may seem natural for paths within an import statement, it's a little less natural for "data" paths within a function body because modules are considered a directory within the filesystem. We could make a distinction between resolution semantics for a path within an import and within a function body, but that would be confusing in its own way. I'm happy to switch both to being relative to the module location, I can't say I had given it too much thought when I was implementing it, just ended up the way it did somewhat accidentally. I definitely agree it's weird for imports though.

I agree that any path in a query should be relative to the query location, but I believe that is how it works currently. The problem currently, is that a relative "data" path within a function body will resolve relative to the query location when I think it should probably resolve relative to the module (or module location, depending on the decision regarding my comment in the first paragraph). But @natefaubion I think you prefer if relative path resolution be the same whether it's defined in the body or being passed in as an argument which goes against what I was thinking?

**Comment by jdegoes** [comment]
It would violate referential transparency to have it mean one thing when passed in as a function parameter, and another when it does not. That, in general, makes reasoning harder, which is the main argument for uniform interpretation.

I think users will treat the modules as if they are a file, and indeed, it would be nice if they are exposed as a file in all ways the user can see. In this case, paths being relative to the location of the "file module" (i.e. parent directory containing the module) makes a lot of sense.

**Comment by jedesah** [comment]
@jdegoes Good point on referential transparency. So I guess all relative paths are relative to the query that actually use them then.

> I think users will treat the modules as if they are a file, and indeed, it would be nice if they are exposed as a file in all ways the user can see

Are you suggesting functions no longer be exposed as files inside of a module directory but instead as metadata of a module file?

**Comment by jdegoes** [comment]
@jedesah Ah, I see what you're saying. I guess that could go either way. But still, I feel if a user types `IMPORT "./foo"` inside a module, they are probably trying to import "foo" which exists in the parent of the module directory, as a sibling of the module. The other interpretation would be invalid, wouldn't it?

**Comment by natefaubion** [comment]
I would think that, a relative path within a function definition should always resolve based on where the function is mounted, not imported and used. So as a function author, I'm using a known path of my choosing. If I pass in a path as a parameter, it should always be relative to the call-site. So as a function consumer, I'm using a known path of my choosing.

The problem is that I'm not entirely sure what the semantics of `:variables` are in all cases. Many times they behave in a somewhat unhygienic manner, via naive substitution. For example, given the query:

```sql
SELECT * FROM foo as bar WHERE :filter
```

I can call this with `filter=bar.baz>42`. At the call site, I don't have `bar` in scope, but via naive substitution it gets bound at it's usage. The search card depends on this behavior. I'd consider this inconsistent though with what I'd expect for path resolution. Are there different semantics for how identifiers work vs variables?

**Comment by jedesah** [comment]
On the relative path resolution front. I agree with @natefaubion that it would be very unintuitive for a module function author to have relative paths within a function body resolved according to the location of the query that calls the function. If that's what they want to accomplish, they can do that by making the path a variable. @jdegoes You bring a good point about referential transparency, but I think in this case we can convince ourselves that it's not violating referential transparency as I discuss below.

The way I think of it, the filesystem is a very dynamic thing, it can change at any time. When someone is importing a function within a module, they are importing wtv function body is there at that very moment (could be changed seconds later by someone modifying the module contents). One can see a relative path within a module as a convenience for implementing their module. It doesn't change the fact that at a given point in time, a function body resolves to a particular implementation which is fixed. Basically, what I am saying, is that the module system offers no guarantees as to the "stability/longevity" of the contents of a module and relative paths don't affect this observed behavior. To the client query, it's all the same whether there is a relative path or someone just modified the contents of the module 2 seconds ago.

This isn't how the current system behaves so I'll see if it would be possible to change it without pushing function into LogicalPlan unless there are any objections

**Comment by jedesah** [comment]
#2734 changes the behavior to what I described above

**Comment by jedesah** [comment]
There were a few things discussed here, but the main problem was fixed so I'm going to close this and we can open a new issue if we decide later on that we want the behavior or modules or imports to change in some way.
