### ISSUE TITLE
SELECT (1) and SELECT (*) should produce same output

### ISSUE THREAD

**Issue by damonLL** [quasar-analytics/quasar#2451]
To my knowledge these should present the same result sets:

`SELECT COUNT(1) FROM ... WHERE ...`
`SELECT COUNT(*) FROM ... WHERE ...`

However the former literally results in the value `1` being returned.

Example query on MongoDB, perhaps it varies on another DB?
```
SELECT COUNT(1) from `/mongodb/data/patients`
WHERE state = "TX"
```
Results in `1`
```
SELECT COUNT(*) from `/mongodb/data/patients`
WHERE state = "TX"
```
Results in `2013`

**Comment by jdegoes** [comment]
They are the same in SQL, but they are not the same in SQL<sup>2</sup>.

In SQL, `COUNT(1)` is expanded to `COUNT(foo)`, where `foo` is the first column. Such numerical ordinals are allowed in several places in SQL (e.g. `ORDER BY 1, 3, 2`), but are not supported at all in SQL<sup>2</sup>, nor is it possible to give such a weird feature a composable, non-magical semantics.

**Comment by damonLL** [comment]
Thanks @jdegoes - good clarification and will be put into the docs.
