### ISSUE TITLE
SPLIT functionality request

### ISSUE THREAD

**Issue by damonLL** [quasar-analytics/quasar#2455]
Requesting a `split` feature be added to SQL² which allows string conversion to an array based on a pattern (delimiter).

A short example from @jdegoes of what it might look like:
`WHERE foo IN TRIM(SPLIT(:bar, ",")[*])` or something

For reference sake, PostgreSQL uses `split_part` found [here](https://www.postgresql.org/docs/9.1/static/functions-string.html)  `split_part(string text, delimiter text, field int)`

Origin of this request is from a customer who would like to take a String from SlamData created in Markdown and use the individual elements in the String. For example, Markdown may be:

`interests = ____`

The variable `interests` might then contain a String value of `soccer, hockey, tennis`

Ideally we query against that similar to:

```
SELECT ...
FROM ...
WHERE userInterest IN TRIM(SPLIT(:interests,',',[*])
```

**Comment by jdegoes** [comment]
👍

**Comment by jdegoes** [comment]
@damonLL Btw, the customer may want to use the search card here. I don't think we have a way to do "OR" search queries, but if we did, it would fit this use case nicely.

**Comment by zeeiyerWork** [comment]
@rintcius -> @damonLL is asking for this in SQL-2, so are you taking care of it across the board or are you just implementing the Mongo-Connector piece of it via #2388. To add it to SQL-2 do we need another ticket - @alissapajer ?

**Comment by alissapajer** [comment]
I think it makes sense for this ticket to cover adding `split` to SQL^2 and then carrying that through `LogicalPlan` and into `QScript`. Then we can have other individual tickets to address handling it in each backend.

**Comment by rintcius** [comment]
@alissapajer @zeeiyerWork indeed, #2554 adds `split` to SQL^2, LP and QScript (using commits from #2388 which is indeed just mongo). I'm also adding  support for the backends that I can work out fairly quickly. Will add tickets for the remaining ones.
