### ISSUE TITLE
SQL Query runs fine in SQL card but returns 500 error when ran in MarkDown Card

### ISSUE THREAD

**Issue by dugdun** [quasar-analytics/quasar#2466]
Customer reported issue.

**Issue**: Customer can run the following SQL Query (database name obfuscated, but both collections are in the same database) in an **SQL** card and see the results in a preview table without issue:

```
SELECT 
        DISTINCT (fund.fundName)
FROM
        `/uat-suxxxxxx/fund` AS fund
FULL JOIN
        `/uat-suxxxxxx/journalEntryRevised` AS journalEntryRevised
    ON
        fund.`_id` = journalEntryRevised.fund.`_id`
ORDER BY
        fund.fundName ASC
```

Using the same query and assigning to a variable producing a drop down in a **MarkDown** card and then showing the MarkDown gives the following error when passed to the `query/fs` endpoint:

```
An error occurred.
Failed to execute SQL^2 query.: MongoDB Error: Command failed with error 13070: 'value too large to reduce' on server xxx.xxx.xxx.xxx:27017. The full response is { "ok" : 0.0, "errmsg" : "value too large to reduce", "code" : 13070 }
```

The error leads me to believe that the **MarkDown** version is running a Map/Reduce process, which might make sense since the query is doing a `FULL JOIN`, but it doesn't explain why the **SQL** version runs without error. I have the complete HTTP request/response HAR data, which I can send to the assigned engineer (didn't want to paste to public repo).

**Expected Result**: I would expect either both queries when ran by the **Preview Table** and **Show MarkDown** cards to either complete successfully, or they should both fail with the same error code. I would not expect one to work while the other failed.

**Notes**: I have not been able to reproduce this locally unfortunately, so I can't give any data and a test query to work with.

**Comment by dugdun** [comment]
Forgot to mention that the client is running SlamData Advanced version 4.2.4 with Quasar Advanced 0.9.2. The client is using the tarball download and not an installer version. The database this is running against is MongoDB 3.4.x.

**Comment by zeeiyerWork** [comment]
@dugdun -> does the Markdown fixes as part of 4.2.5 somehow fix this. I suppose not, based on the description and the fact that this is in quasar - just wanted to check?

**Comment by dugdun** [comment]
@zeeiyerWork I will have to ask client if the query now runs in the Markdown card. I don't think any of the recent work in this area would have changed how the `FULL JOIN` query was processed in the Markdown cards, but this issue might have been resolved when @natefaubion made other changes to the front end code.

When this issue was written up, the SQL ran in the **Query** card ran successfully which tells me that Quasar was able to process the query using the AggFramework. The same query in **Setup Markdown** threw the error. The error is what is returned from the MongoDB Map/Reduce process when too much data has been sent to the reduce process.

**Comment by zeeiyerWork** [comment]
Since source=customer, important issue. But seems we need to wait for input from @dugdun, before we can prioritize and schedule.

**Comment by dugdun** [comment]
Talked to the client and the recent work in the Markdown cards did not fix this issue. We have determined however that what they really wanted to do is use an `INNER JOIN` in this case. I have removed the customer label from the ticket, but we should probably still determine why the **Query** card takes one path while the **Setup Markdown** card goes down a different path for the same query.

**Comment by jdegoes** [comment]
@dugdun It's because the front-end has its own SQL parser, which is subtly different than the backend parser. 😢 

@natefaubion May have some ideas, especially for working around.

**Comment by natefaubion** [comment]
@dugdun The big overhaul of the frontend parser is in master, but not in 4.2.5. There were a lot of inconsistencies and printer issues that were fixed besides the `JOIN` issue. Additionally, the parser is now used pervasively in `master`, so there shouldn't be any place where it's using raw user input to construct queries, meaning that while I can't _guarantee_ that the frontend parser is identical to the backend (and free of bugs), it should at least be consistent in it's behavior.

**Comment by natefaubion** [comment]
FWIW, sql-squared now parses all the backends regressions tests, and verifies that they print and reparse as an equivalent AST. Whether or not the initial parse is identical to the backend parse isn't something I can really verify atm.

**Comment by zeeiyerWork** [comment]
@dugdun -> will be good to verify that you do not see this inconsistency in 426 (since front-end parser changes should be in). Can you please comment here after verifying.

**Comment by dugdun** [comment]
Testing in 4.2.6 on my machine gives me the same error:

```
An error occurred.
Failed to execute SQL^2 query.: MongoDB Error: Command failed with error 13070: 'value too large to reduce' on server 127.0.0.1:27017. The full response is { "ok" : 0.0, "errmsg" : "value too large to reduce", "code" : 13070 }
```

This means too much data was being sent to the Map/Reduce process. I think that `FULL JOIN`s should be sent to Map/Reduce and not to the Aggregation Framework, so I'm not sure how the client got their query to run in the **Query** card using a `FULL JOIN`. I never saw the query run, just took what they said in email as fact.

I think that since both ways of running SQL queries are returning the same error for me, and I believe that they are both properly going through the Map/Reduce framework we can close this. As mentioned earlier the client stated that they should have been using `INNER JOIN` for their query anyways.

We can reopen this issue should anyone else run into the same issue, but I think at this time it's not something that needs to be worked on.
