### ISSUE TITLE
Integration tests for Spark-family of connectors. 

### ISSUE THREAD

**Issue by zeeiyerWork** [quasar-analytics/quasar#2471]

**Comment by nicflores** [comment]
Some work on this front has already begun in this branch:

https://github.com/nicflores/quasar/tree/wip/docker-spark-connectors

Currently this branch contains docker-compose definitions for containerized Small Spark Cluster, FTP, ElasticSearch, Cassandra, and Travis matrix definitions for each. What's missing is Hadoop, a little more config in order to get travis to spin up each of these up along side a Spark, and maybe a little more config to make Spark aware of each of these storage container.

**Comment by nicflores** [comment]
Currently the branch above contains the following working containers:
```
quasar_spark_cluster
quasar_ftp
quasar_elasticsearch
quasar_cassandra
quasar_hadoop
```
Still to do
- [ ] travis matrix builds to bring up `quasar_spark_cluster` and associated connector
- [ ] put spark and associated connector containers on an IP that allows for container to container communication and host to container communication.

**Comment by nicflores** [comment]
@rabbitonweb, I have a zip branch building in travis right now:

https://travis-ci.org/quasar-analytics/quasar/jobs/260787413#L612

There may be some work that still needs to be done to pin down the correct connectionURI's for the new connectors but for the most part I think the difficult stuff is out of the way. Check the link above and let me know what you think. We can discuss what needs to change at a later day.

Also, @zeeiyerWork mentioned that you may need an S3 connector as well. I'd like to get some clarification from you as how you'd like to proceed on this front.

**Comment by zeeiyerWork** [comment]
Yeah @damonLL, @nicflores, @rabbitonweb -> wrt testing Spark against JSON on S3
1. Feel this is important - since we might get more @bats in the field.
2. Options are:
- Keep a test S3 mount available with pre-existing JSON content which we refer to in tests. This might be cheaper, since on S3 Storage Costs = 1/10th of Upload Costs. 
- However to be consistent with how we run other tests, we may want to create a S3 test-folder on the fly and upload JSON to it, run integration tests and tear it down. Maybe costs more given repeated S3 ingests, but perhaps negligible if it is just a handful of JSONs uploaded on each test execution.

Thanks

**Comment by nicflores** [comment]
@rabbitonweb, can you please post the full connection URI's for each of the new spark connectors just as we need them to show up in`it/testing.conf`. My guess is that they will look something like this:
```
spark_cassandra=http://${CONNECTORIPADDR}:9042
spark_elastic=http://${CONNECTORIPADDR}:9200
spark_ftp=ftp://${CONNECTORIPADDR}:21
spark_hdfs=hdfs://${CONNECTORIPADDR}:8020
```
but it just a guess. Feel free to repost if any of the above are incorrect.

**Comment by nicflores** [comment]
Added matrix build for S3 which only spins up the spark cluster container since we will be using a preexisting S3 bucket.

**Comment by rabbitonweb** [comment]
hdfs connectionURI: `spark_hdfs = "spark://<spark_host>:<spark_port>?hdfsUrl=<hdfs_url>&rootPath=<rootPath>`

where
- `roothPath` just set to `/`
- `hdfsUrl` set to `hdfs://<hdfsHost>:<hdfsPort>`
- both `roothPath` and `hdfsURl` must be decoded

**Comment by rabbitonweb** [comment]
`spark_elastic = "spark://<spark_host>:<spark_port>?elasticHost=<elasticHost>&elasticPort=<elasticPort>"`

where `elasticHost` must be decoded

**Comment by rabbitonweb** [comment]
FTP is really just HDSF connector, thus

connectionURI: spark_hdfs = "spark://<spark_host>:<spark_port>?hdfsUrl=<ftpUrl>&rootPath=<rootPath>

where

roothPath just set to /
ftpUrl set to ftp://<host>
both roothPath and ftpUrl must be decoded

**Comment by rabbitonweb** [comment]
S3 is really just HDSF connector, thus

connectionURI: spark_hdfs = "spark://<spark_host>:<spark_port>?hdfsUrl=<s3Url>&rootPath=<rootPath>

where

roothPath just set to /
s3Url set to whatever s3 we have for tests
both roothPath and s3Url must be decoded

**Comment by rabbitonweb** [comment]
cassandra connectionURI: `spark_cassandra = "spark://<spark_host>:<spark_port>?cassandraUrl=<cassandraUrl>&rootPath=<rootPath>`

where
- `roothPath` just set to `/`
- `cassandraUrl` set to `cassandra://cassandra_host:port`
- both `roothPath` and `cassandraUrl` must be decoded]

**Comment by rabbitonweb** [comment]
This is not over yet
