### ISSUE TITLE
Postgres Metastore Seems Broken in Master

### ISSUE THREAD

**Issue by djspiewak** [quasar-analytics/quasar#2472]
Steps to reproduce:

1. Blow away your quasar_metastore docker
2. Recreate using [standard steps](https://gist.github.com/alissapajer/18be04d6b9c77d99e643f35930ab2d25)
3. Add a mount using the web endpoint (I added the `mimir` mount point) using the json `'{ "mimir": { "connectionUri": "/tmp/precog" } }'`
4. Run the repl
5. Verify the mount exists with `ls`
6. Attempt to `cd` into it

It won't work.  And it gives the same error as cding into a non-existent mount:

```
Using metastore: jdbc:postgresql://0.0.0.0:5432/metastore?loglevel=0
💪 $ ls
mimir@ (mimir)
💪 $ cd mimir
Quasar error: Dir not found: /mimir/
💪 $ cd fuubar
Quasar error: Dir not found: /fuubar/
💪 $ 
```

**Comment by drostron** [comment]
How is metastore being implied here and why are other connectors working fine?

**Comment by djspiewak** [comment]
Invalid!  This is caused by the mount being empty.  Opening a new issue for it.
