### ISSUE TITLE
Empty mounts are listed as non-existent

### ISSUE THREAD

**Issue by djspiewak** [quasar-analytics/quasar#2473]
Ran into this and thought it was a different issue (#2472).  If you create a mount that does not have any data in it (no dirs and no files), the repl will believe that it doesn't exist even though it displays as present.  The result will be the same error as if there was no mount at that path whatsoever.  Note that this is only relevant to data stores which don't have "default" datasets (so, not mongo) such as mimir and marklogic.

A workaround is to upload the test dataset.  But really, we should ensure that empty mounts are allowed and meaningful, since it doesn't make any sense for them to cause errors.

**Comment by nicflores** [comment]
This seems to be fixed in @sellout's `remove-old-Mongo` branch:
```
💪 $ ls
mimir@ (mimir)
💪 $ cd mimir
💪 $ ls
💪 $ cd ..
Root
💪 $ ls
mimir@ (mimir)
```

**Comment by djspiewak** [comment]
Confirming that this bug is once again present in master.

**Comment by zeeiyerWork** [comment]
Since this seems more of an edge case (hence not skulled), moving this to a later iteration (for now we advise customers that mounts can't be empty)/
