### ISSUE TITLE
Quasar should perform case insensitive comparison on OAuth email addresses

### ISSUE THREAD

**Issue by damonLL** [quasar-analytics/quasar#2498]
Quasar currently compares email addresses in the Metastore with the email addresses the user logs in with for the OAuth provider. This is an equality match, including case. I suggest we make this a case insensitive match.

We've run into at least one customer who was delayed by a few days while we determined the cause. The current workaround is to add multiple versions of the email address (with upper and lower case variations) to the Metastore.

If a user authenticates properly against OAuth, but their email address is not the exact same, they will likely see this error in the SlamData UI (though could be coming from Quasar?)

![image001](https://user-images.githubusercontent.com/7375598/28292996-6c7cb64a-6b17-11e7-8fa3-c4d86acb8af5.png)

If this needs to move to SlamData Issues repo just let me know - but seems like Quasar does most  (if not all) of the OAuth / Metastore communication.

**Comment by wemrysi** [comment]
@damonLL would you mind filing this at slamdata/quasar-advanced?

**Comment by zeeiyerWork** [comment]
This issue was moved to slamdata/slamdata-backend#217
