### ISSUE TITLE
Investigate slow flatten tests in mimir

### ISSUE THREAD

**Issue by djspiewak** [quasar-analytics/quasar#2521]

**Comment by alissapajer** [comment]
Locally I've seen the following flatten-related tests run slowly in mimir:
```
flatten array with unflattened field [./flattenArrayWithUnflattened.test] (1 minute 41 seconds, 626 ms)

flatten array on the left with unflattened field [./flattenArrayLeftWithUnflattened.test] (2 minutes 27 seconds, 259 

unify flattened fields [./unifyFlattenedFields.test] (2 minutes 8 seconds, 577 ms)
```

The initial step for this ticket is figuring out what code paths within mimir are causing these tests to run slowly. All the tests are related to `LeftShift` in `QScript`, so a good place to start looking in mimir would be [where mimir handles `LeftShift`](https://github.com/quasar-analytics/quasar/blob/master/mimir/src/main/scala/quasar/mimir/Mimir.scala#L272)

**Comment by nicflores** [comment]
Default values in 'yggConfig.maxSliceSize` and `yaggConfig.smallSliceSize` seems to be the issue. Increasing these values has reduced the times of the test times posted above. PR coming shortly.

```
[info] + flatten array with unflattened field [./flattenArrayWithUnflattened.test] (2 seconds, 472 ms)
[info] + flatten array on the left with unflattened field [./flattenArrayLeftWithUnflattened.test] (1 second, 695 ms)
[info] + unify flattened fields with unflattened field [./unifyFlattenedFieldsWithUnflattened.test] (511 ms)
```
