### ISSUE TITLE
Implement a better Table#toJson

### ISSUE THREAD

**Issue by djspiewak** [quasar-analytics/quasar#2534]
The function we're currently using to return data to quasar is `Table#toJson`.  This function was never intended for anything other than debugging and testing, and it makes absolutely no attempt to be efficient.  (in fact, quite the opposite in places)  It's possible to do better even without moving to an unboxed representation at the quasar level (like `renderJson`).  We should at least take this step before the initial public release.

**Comment by djspiewak** [comment]
Note that #2626 completely obviates this issue.

**Comment by zeeiyerWork** [comment]
We do want to implement https://github.com/quasar-analytics/quasar/issues/2626 - so I suppose it supersedes this. Therefore, closing this out.
