### ISSUE TITLE
multistageFlatten.test Query appears to diverge during compilation

### ISSUE THREAD

**Issue by wemrysi** [quasar-analytics/quasar#2540]
Attempting to `explain` the following query from `multistageFlatten.test` against the MongoDB connector just hangs at the `repl`:

`explain select * from mongo32/testdata/nested_foo where (foo LIKE "%zap%" OR foo[*] LIKE "%15%" OR foo[*][*] LIKE "%meh%" OR foo[*][*].baz LIKE "%moo%" OR foo[*][*].baz[*] LIKE "%quu%" OR a LIKE "%13%")`

it isn't clear if it is just taking a very long time (I waited minutes) or has indeed diverged. I also haven't tried against other connectors to confirm the divergence is in QScript, but it seems likely as this test is disabled for all connectors.

**Comment by alissapajer** [comment]
As of #2902 this query takes ~10 seconds to `explain`. Though it returns incorrect results against spark. I didn't test any other connectors. The qscript contains many joins because source merging through the shifts is failing. This is possibly related to #2133.

**Comment by alissapajer** [comment]
Possibly also related to #2366.

**Comment by drostron** [comment]
This relates to the search card slows

**Comment by djspiewak** [comment]
Closing for the same reason as #2935
