### ISSUE TITLE
date_part should return undefined when applied to a non-temporal argument in MongoDB

### ISSUE THREAD

**Issue by wemrysi** [quasar-analytics/quasar#2541]
The `invalidDateFilter.test` query is failing on QScript-based MongoDB connectors due to `date_part` being applied to a numeric argument, instead it should return `undefined`.

**Comment by alissapajer** [comment]
@drostron are you in progress on this? If so, :+1:. If not, would it be okay if I unassign you so someone else (or yourself in the future) can grab it?

**Comment by drostron** [comment]
@alissapajer I started looking at it the other day and am back to it today now that the initial VCache work is submitted.

**Comment by jsantos17** [comment]
This a manifestation of a wider problem. There are other queries that exhibit similar behavior, yet don't error on execution. Any query with a filter that requires typechecks in the predicate is also affected by this issue.

**Comment by jsantos17** [comment]
After some research I have found that it's not only typechecks that have this problem. Pretty much every `Guard` in a `Filter`'s `FreeMap` have similar problems. The implementation pulls every `Guard`  from `Filter` and puts them after `Project`. Consider the following query and its plan for Mongo 3.4:

```sql
select city from zips where length(city) < 4
```

On master, this plans as:

QScript:

```
QScript (Mongo-specific):
Map
├─ Filter
│  ├─ ShiftedRead(/jps/zips, ExcludeId)
│  ╰─ Guard
│     ├─ ProjectField
│     │  ├─ ○
│     │  ╰─ Constant(Str(city))
│     ├─ Type(Str)
│     ├─ Lt
│     │  ├─ Length
│     │  │  ╰─ ProjectField
│     │  │     ├─ ○
│     │  │     ╰─ Constant(Str(city))
│     │  ╰─ Constant(Int(4))
│     ╰─ Undefined
╰─ ProjectField
   ├─ ○
   ╰─ Constant(Str(city))
```

Workflow:
```
Workflow (raw):
Chain
├─ $ReadF(jps; zips)
├─ $ProjectF
│  ├─ Name("0" -> "$city")
│  ├─ Name("1" -> { "$strLenCP": "$city" })
│  ├─ Name("src" -> "$$ROOT")
│  ╰─ IgnoreId
├─ $MatchF
│  ╰─ And
│     ├─ Doc
│     │  ╰─ Expr($0 -> Type(Text))
│     ╰─ Doc
│        ╰─ Expr($1 -> Lt(Int32(4)))
╰─ $ProjectF
   ├─ Name("value" -> "$src.city")
   ╰─ ExcludeId
```

Physical plan:
```javascript
db.zips.aggregate(
  [
    {
      "$project": { "0": "$city", "1": { "$strLenCP": "$city" }, "src": "$$ROOT" }
    },
    {
      "$match": {
        "$and": [
          { "0": { "$type": NumberInt("2") } },
          { "1": { "$lt": NumberInt("4") } }]
      }
    },
    { "$project": { "value": "$src.city", "_id": false } }],
  { "allowDiskUse": true });
```

As you can see, the `Guard` typechecks have been put after the `$ProjectF`, which is a bug. I believe we can plan this correctly by putting all typechecks before `$ProjectF` and the other extracted selectors after `$ProjectF`. The plan for this query would look something like

```
Chain
├─ $ReadF(jps; zips)
├─ $MatchF
│  ╰─ Expr("city" -> Type(Text))
├─ $ProjectF
│  ├─ Name("0" -> "$city")
│  ├─ Name("1" -> { "$strLenCP": "$city" })
│  ├─ Name("src" -> "$$ROOT")
│  ╰─ IgnoreId
├─ $MatchF
│  ╰─ Expr($1 -> Lt(Int32(4)))
╰─ $ProjectF
   ├─ Name("value" -> "$src.city")
   ╰─ ExcludeId
```

This works, but I don't know if I'm missing any corner cases here. I would basically pull any `Selector.Type` before `$ProjectF` into another `$MatchF`. The query in `invalidDateFilter.test` can be fixed similarly

Thoughts on this? @wemrysi, @alissapajer, @drostron, @rintcius

It's worth noting that old Mongo doesn't do this optimization. All typechecks and conditions are inside the `$project`.

Full `EXPLAIN` for the query [here](https://gist.github.com/jsantos17/300c01202b92e2537f6cff81ef944ed8)
