### ISSUE TITLE
Github releases page is reported as phishing site

### ISSUE THREAD

**Issue by cervenyprofiq** [quasar-analytics/quasar#2546]
After clicking on link on released build, I got warning in Chrome/Firefox.
```
Deceptive site ahead

Attackers on github-production-release-asset-2e65be.s3.amazonaws.com may trick you into doing something dangerous like installing software or revealing your personal information (for example, passwords, phone numbers, or credit cards).

Automatically send some system information and page content to Google to help detect dangerous apps and sites. Privacy policy
Back to safetyHIDE DETAILS
Google Safe Browsing recently detected phishing on github-production-release-asset-2e65be.s3.amazonaws.com. Phishing sites pretend to be other websites to trick you. Learn more.
```

![](http://i.imgur.com/6zyRTyO.gif)

**Comment by rintcius** [comment]
Thanks for your report @cervenyprofiq ! I tried to reproduce this, but for me it just downloads the jar from this location `https://github.com/quasar-analytics/quasar/releases/download/v20.11.0/quasar-repl-assembly-20.11.0.jar`. Note that in your case the location looks different.

Could you try again (as I suspect it may have been a glitch in github)? If it still doesn't work can you try doing the same using Chrome Incognito Mode?

**Comment by cervenyprofiq** [comment]
Well, this is awkward. I am not able to reproduce it now. Closing, sorry for your time spent on this.

**Comment by rintcius** [comment]
Not a problem @cervenyprofiq
