### ISSUE TITLE
Pre-bake data-sets with Fallback Evaluator

### ISSUE THREAD

**Issue by zeeiyerWork** [quasar-analytics/quasar#2570]
Example: Have an example-data directory:
- With pre-baked data-sets (e.g. patients, olympics)
- Perhaps one data-set that is simple so people can convince themselves, that what they can do with their existing tools, also works with Slamdata.
- Perhaps one that is complex (in terms of nesting), where others break down, while Slamdata shines.

There is a companion ticket in Slamdata (which is about pre-baking Workspaces/Decks that use the data-sets example-data)

@jdegoes , @damonLL , @JeffACarr , @dugdun -> Please comment on which specific data-sets you wish to include in the distribution.

**Comment by jdegoes** [comment]
Patients data, olympics data, zips. Anything else?

**Comment by zeeiyerWork** [comment]
Needs -> Additional command to quasar-jar to add a mount point.

**Comment by damonLL** [comment]
@zeeiyerWork: agree w/ @jdegoes. The patients, olympics and zip data sets would be good, I would also throw in the timeseries data set.  We can create some sample workspaces for these as well.

I've zipped up those data sets: [default-data.zip](https://github.com/quasar-analytics/quasar/files/1195263/default-data.zip)

**Comment by djspiewak** [comment]
@damonLL Just to see if we can save me a bit of work…  These datasets are not all in the same format. Some of them are newline-delimited, while others are just "big ol' json array" format.  Do we have things a bit more normalized so I don't have to spend time scripting detection for that?

**Comment by damonLL** [comment]
@djspiewak - they can be converted without too much effort. Which format would you prefer? Does this also mean users will be limited to a specific formatting for JSON files?

**Comment by djspiewak** [comment]
@damonLL Newline delimited is the easiest for me.

There's no limitation from the backend side.  This is just the fact that the ingest endpoint has to tell the quasar service what format it is uploading in, and it's annoying to have to detect one format or another in the upload script when passing through multiple files.

**Comment by damonLL** [comment]
here you go @djspiewak 

[default-data.zip](https://github.com/quasar-analytics/quasar/files/1216383/default-data.zip)

**Comment by djspiewak** [comment]
@damonLL That's actually the same zip file.  I'll just normalize things.

**Comment by djspiewak** [comment]
…aaaand here's the baked result: [default-baked.tar.bz2](https://www.dropbox.com/s/x2yqaxtv0w0plrp/default-baked.tar.bz2?dl=1).  The contents of that tarball are a single directory, representing a mimir mount point.  The name of the directory is not significant, but the names of the directories *within* this directory are.

**Comment by damonLL** [comment]
@djspiewak sorry - I actually did fix it, but was in the wrong directory when uploading the newest version, oh well ¯\_(ツ)_/¯
