### ISSUE TITLE
Zips downloaded from quasar have strange internal structure

### ISSUE THREAD

**Issue by garyb** [quasar-analytics/quasar#2587]
When I open a quasar-produced zip in PowerArchiver it shows as containing a directory called `.` with the contents beneath that. When trying to extract the zip on Windows it chokes entirely:

<img width="441" alt="slack-imgs" src="https://user-images.githubusercontent.com/693642/28879410-ffbc8ffa-7799-11e7-96b1-2e7ee828b5ba.png">

Screenshot courtesy of @kRITZCREEK :wink:

**Comment by nicflores** [comment]
we get similar behavior when downloading directories, i.e. files are contained within a directory called `.`
