### ISSUE TITLE
Create endpoint to allow selection of OAuth provider and persist to Config

### ISSUE THREAD

**Issue by zeeiyerWork** [quasar-analytics/quasar#2589]
1. Part 1:
Endpoint to support selection of OAuth provider.
![image](https://user-images.githubusercontent.com/24783629/28898418-b296ec9c-779a-11e7-89fb-9370612964d1.png)
2. Part 2: 
Persist to config (and config eventually moves to Metastore).

**Comment by jedesah** [comment]
This ticket should be in SlamData Backend.

**Comment by zeeiyerWork** [comment]
Agreed - Ok will move it.

**Comment by zeeiyerWork** [comment]
This issue was moved to slamdata/slamdata-backend#213
