### ISSUE TITLE
Create endpoint to allow specification of "VFS-home", "Artifacts-DB" and "Theme" and persist to config.

### ISSUE THREAD

**Issue by zeeiyerWork** [quasar-analytics/quasar#2590]
In support of 
![image](https://user-images.githubusercontent.com/24783629/28898570-7b277280-779b-11e7-8ebf-05403fb040aa.png)

**Comment by jdegoes** [comment]
These are client-side settings that don't need any server-side support just yet. If anything, SlamData Advanced should have a place to store the settings for identified / authenticated users.

The artifact Isolation will require "soft links" for Quasar, and a ticket already exists for that.

**Comment by zeeiyerWork** [comment]
Unclear:

- First of all these settings need to be persisted somewhere. Today the only option is config-file or client-side user-storage. Config-file: we are moving to Metastore in preparation for quasar-clustering. 
- Some of these settings appear to be global (i.e. should not vary based on an individual user). e.g. Isolate Slamdata-artifacts-db is likely to be a system-wide setting independent of users/authors. So that will need a backend REST service to persist. Of course more work needs to happen to actually use it, by the rest of quasar.

- Default Theme & Home-Directory-Location within VFS could be user-level setting or a global setting by the Admin across all users. (User level over-rides will be spec'ed later. Themes already have a deck-level over-ride). That is one interpretation, which will again need a REST service to persist.

**Comment by jdegoes** [comment]
1. They can be persisted client-side. Or, if we add a user profile to authenticated users — which would be added in SlamData Advanced, **NOT** in Quasar — then it could be persisted there. This is NOT related at all to "config file".
2. The artifact isolation is NOT global. In a cloud setting, such as SlamData Cloud, or in a multi-tenant situation, artifacts may need isolation different users may have different artifact isolation preferences (each customer of SlamData Cloud will have a different artifact isolation directory).
3. The home directory and theme setting are PER USER settings. While an admin may have control over home directory at some point — within reason, since even the admin may have limited access in a Cloud scenario — that functionality is not part of the MVP and is not spec'd out.

You have copied over the screenshot but none of the notes. The issue will be more clear with the notes attached to the original issue.

**Comment by zeeiyerWork** [comment]
Thanks @jdegoes. Yes should have added detailed notes. 

>>>> The artifact isolation is NOT global. In a cloud setting, such as SlamData Cloud, or in a multi-tenant situation.

You raise a good point here, which is that the **scope of settings is a function of deployment modality**. i.e. 

1. DESKTOP -> The single author is the Admin - so all Admin functionality is likely available to the desktop user. 
2. CLOUD/MULTI-TENANT -> We do not have any deployments of this nature **today**, but yes, we would have to accommodate either @ "user" scope or Create an altogether new concept such as "tenant" or "partition" where each "tenant/partition" could have multiple "users".  There may be benefits to not overloading "tenants" as "users". 
3. ENTERPRISE -> which is **ALL** of our deployments today, I would expect artifact-isolation to be **global/system-wide** - and not give each author a preference to dictate where Slamdata artifacts go (since it will just increase the number of potential failure points and complicate the persistence and operational-management story within the enterprise).

>> would be added in SlamData Advanced, NOT in Quasar 
Agreed. Would be good to specify this as well. e.g. The interpretation we are working with is that artifact isolation is available within OSS Quasar as well, which couple with the previous point, would mean that it does go into the "config-file" of today...

It seems that to minimize confusion and multiple interpretations, we would need for each of the settings - additional metadata that details
### Scope 
- Session-level, User-level (persists across multiple sessions), Tenant-level or Global.
- Orthogonally scope could relate to the entire cluster of Quasars or be specific to 1 Quasar in the Quasar-cluster (this presumably could be handled via just command level JVM over-rides).
### Persistence (client-side, server-side (within config)):
- Since any setting is application "configuration". 
- If it is being stored server-side, it is in the "config file" (that is the only place to persist unless it is transient and stored just in memory and not expected to survive a server-restart).
- Most "config file" will move to Metastore to support Quasar-clustering
- Except those settings that will relate to a specific node in the Quasar-cluster (e.g. different JVM settings, or running 1 as a canary (where it has different log-levels etc.)).

I am taking a shot at this and will add it to the epic - so you can clarify further: Something like a table -> Parameter | Scope | Persistence @ Deployment Modality.

**Comment by jdegoes** [comment]
@zeeiyerWork Again, these are client-side settings for now. You can work on specs for an API (NOT in Quasar, but SlamData Advanced), which lets the front-end reliably store arbitrary "profile" data for authenticated users. That would be quite useful and is a small amount of work. Beyond that, no additional specs are required.

**Comment by zeeiyerWork** [comment]
Engineering is not in agreement with Product on slamdata-artifacts-db being a client-side setting (i.e. a setting with scope = specific-user-browser on the client-side). So we will skip implementation of that for 4.3 pending more rigorous specifications/discussions. 

The reasons are the following:
1. The "text" promises something, but the implementation as described by you, will fail to deliver it. Since if stored as user-storage, and I as an author open up a new browser, i no longer have the Slamdata-artifacts-db setting and I will now "pollute" the production db with slamdata artifacts.
![image](https://user-images.githubusercontent.com/24783629/28933488-123412be-7832-11e7-9dc6-6d89978bea64.png)
2. Again, if even if one uses the same browser, some authors may set it and some may not - and thus the promise of no "pollution" of the production db remains unmet.
3. From an implementation perspective, anyways - the frontend needs to send this along as the targetDB, for it to take effect, which wasn't anyways in scope.

Even with home-directory-setting and default-theme, one could make a case that these are global level settings (i.e. defaults) which an "ADMIN" sets. (i.e. have the notion of an Admin group - user belonging to that group will see all tabs and set defaults). A given end-user may override some (and sees only My-Settings). But for now, one can just buy into a less sophisticated implementation and just say that these (home-directory and default-theme) are just user-level settings (the admin does not get to set any defaults in this regard).

**Comment by zeeiyerWork** [comment]
This issue was moved to slamdata/slamdata-backend#214
