### ISSUE TITLE
[next-major] Parameterized filtering on Mongo results in empty set

### ISSUE THREAD

**Issue by natefaubion** [quasar-analytics/quasar#2592]
I'm constructing the following module mount:

```sql
CREATE FUNCTION card4947c7ab48884d2cb6b09ea041263091(:filter, :`distinct`) BEGIN CASE WHEN :`distinct` THEN SELECT DISTINCT * FROM `/mongodb/data/olympics` WHERE :filter ELSE SELECT * FROM `/mongodb/data/olympics` WHERE :filter END END
```

And I'm calling `/invoke` with these params:
* filter: `(((SEARCH(city, "^.*USA.*$", true)) OR ((SEARCH(country, "^.*USA.*$", true))) OR ((SEARCH(discipline, "^.*USA.*$", true))) OR ((SEARCH(event, "^.*USA.*$", true))) OR ((SEARCH(gender, "^.*USA.*$", true))) OR ((SEARCH(sport, "^.*USA.*$", true))) OR ((SEARCH(type, "^.*USA.*$", true))) OR ((SEARCH(year, "^.*USA.*$", true)))))`
* distinct: `false`

In the old mongo connector, this query results in a filtered set, but with new mongo this results in an empty set.

**Comment by alissapajer** [comment]
@natefaubion I wanted to clarify if this query is actually returning no results or if it's returning value-boxed results and the frontend just isn't extracting the actual value.

In #1819 it seems like the frontend has a workaround in place for extracting boxed results. Is this correct?

Also, in the future, the mongo connector will not return boxed results like it is now.

**Comment by natefaubion** [comment]
Yes, that's correct, it is not returning any results. I tried the same query on master and next-major (inspecting the raw request/response), with the query returning results on master, and returning an empty result set on next-major.

**Comment by rintcius** [comment]
@natefaubion I'm getting the expected results.

```
curl -v -X PUT http://localhost:8080/mount/fs/m32/mymodule/ -d '{ "module": "CREATE FUNCTION olympicsFn(:filter, :`distinct`) BEGIN CASE WHEN :`distinct` THEN SELECT DISTINCT * FROM `/m32/test/olympics` WHERE :filter ELSE SELECT * FROM `/m32/test/olympics` WHERE :filter END END" }'

# simple invoke
curl "http://localhost:8080/invoke/fs/m32/mymodule/olympicsFn?filter=true&distinct=false"

# invoke with specified search
curl "http://localhost:8080/invoke/fs/m32/mymodule/olympicsFn?filter=(((SEARCH(city%2C%20%22%5E.*USA.*%24%22%2C%20true))%20OR%20((SEARCH(country%2C%20%22%5E.*USA.*%24%22%2C%20true)))%20OR%20((SEARCH(discipline%2C%20%22%5E.*USA.*%24%22%2C%20true)))%20OR%20((SEARCH(event%2C%20%22%5E.*USA.*%24%22%2C%20true)))%20OR%20((SEARCH(gender%2C%20%22%5E.*USA.*%24%22%2C%20true)))%20OR%20((SEARCH(sport%2C%20%22%5E.*USA.*%24%22%2C%20true)))%20OR%20((SEARCH(type%2C%20%22%5E.*USA.*%24%22%2C%20true)))%20OR%20((SEARCH(year%2C%20%22%5E.*USA.*%24%22%2C%20true)))))&distinct=false"
```

I'm curious what happens if you provide `filter=true` instead of the search. If that doesn't shed any light, maybe debug your use case together?

**Comment by rintcius** [comment]
@natefaubion I'm closing this issue, as this looks correct at the server side - please feel free to reopen if you still find something wrong with this
