### ISSUE TITLE
Split function for mimir

### ISSUE THREAD

**Issue by rintcius** [quasar-analytics/quasar#2618]
Connector implementation of #2455

**Comment by djspiewak** [comment]
This is basically one line, and really should be done in #2455 (as noted).

**Comment by rintcius** [comment]
closing, it's added to #2554 now

**Comment by djspiewak** [comment]
@rintcius Random process note…  This should be auto-closed by merging the PR, rather than closing it while the PR is in review.  This can be done by adding `Fixes #2618` to the body of the PR description.  I'm making that change now just to ensure that the metadata remains in sync.

**Comment by rintcius** [comment]
@djspiewak - yeah normally I'd do that but it only works like that for `master` (and this is on `next-major`). Also the process for `next-major` is a bit different because they are left open with a specific `status: Fixed in New Mongo`, so I thought it'd be easier closing this now

**Comment by djspiewak** [comment]
Ah, I see.  Let's just close this manually once the PR merges then

**Comment by djspiewak** [comment]
…or rather, add the status.
