### ISSUE TITLE
Unable to download entire Mimir/FBE mount point

### ISSUE THREAD

**Issue by damonLL** [quasar-analytics/quasar#2628]
I'm not sure if this is expected behavior. If click the Download icon next to the mount name of a Mimir mount point, it starts to download and then pauses.

I've successfully downloaded a folder and it's contents that resides within the Mimir mount point; however.

I've been hesitant to try any other databases recently though since all of mine are heavily populated, so I'm not sure if this is expected. If it is, then perhaps we should remove the download icon next to all mount points. (or fix this one if it's local to Mimir)

Put this in quasar instead of SlamData as my guess is it's backend, but let me know and I'll gladly migrate it to SlamData Issues.

**Comment by damonLL** [comment]
This is apparently not the case with Quasar, only Quasar Advanced. Where should this Issue reside?

**Comment by djspiewak** [comment]
@jedesah Opinions?

**Comment by jedesah** [comment]
@damonLL @djspiewak If it works as expected in Quasar but not so in SDBE then I would guess it's most probably a SDBE specific issue, probably related to authentication/authorization

**Comment by djspiewak** [comment]
Makes sense.  @damonLL can you reopen against slamdata-backend?
