### ISSUE TITLE
Programmatic way to add a mount point. 

### ISSUE THREAD

**Issue by zeeiyerWork** [quasar-analytics/quasar#2630]
Based on discussion with the team, need a command line option/service invocation) to add a mount point. This is useful in several contexts including testing. Returns success or failure (with descriptive/actionable failure reason). Another ticket where it was referenced is [here](https://github.com/slamdata/slamdata/issues/2071). Similar to how we can invoke quasar-cability to initialize/update Metastore.

**Comment by djspiewak** [comment]
We already do.  Quasar exposes mounting configuration as a REST endpoint, and thus you can add mounts from any command line that has `curl` installed.

**Comment by zeeiyerWork** [comment]
@garyb, @beckyconning -> fyi !

**Comment by djspiewak** [comment]
Oh actually I'm realizing this may be something subtly different than I thought when reading the ticket.  Let me dig through quickly…

**Comment by djspiewak** [comment]
Ok, I apologize for the confusion.  To be clear, this ticket is describing an endpoint for *updating the metastore*, which is definitely not something we currently have.  This would be more appropriately assigned to @jedesah.

**Comment by zeeiyerWork** [comment]
yeah @nic can pull in @jedesah for help.
Thanks.

**Comment by jedesah** [comment]
We do have a REST endpoint to add mounts. Is there reason to expose this as well as a command? I personally don't see much benefit

**Comment by zeeiyerWork** [comment]
@jedesah - We need to make mimir mount point a default in 4.3. Therefore there was a request from the front-end (@garyb, @beckyconning ) enquiring on how to do this programmatically. If there is a REST call, then presumably just let FE know how to invoke it - so we can as part of a fresh install, also add a mimir mount point. Similarly in other automated end-end testing scenarios, it is useful to mount programmatically execute some test and tear it down.

**Comment by jedesah** [comment]
This is the endpoint: https://github.com/quasar-analytics/quasar#post-mountfspath

**Comment by jdegoes** [comment]
Looks like it's already possible to do programmatically. There's probably no reason to add command-line functionality when that can be layered on top of the API.

**Comment by zeeiyerWork** [comment]
Additional commentary at https://github.com/slamdata/slamdata/issues/2071 - yep seems like we can close this out if installer can invoke via curl.
