### ISSUE TITLE
Remove WrapObjectDynamic from TransSpecModule

### ISSUE THREAD

**Issue by edmundnoble** [quasar-analytics/quasar#2642]
According to @djspiewak `WrapObjectDynamic` can be generated by QScript but not SQL^2; there's no efficient way to implement it in mimir, so it should be dropped.

**Comment by jdegoes** [comment]
If `WrapObjectDynamic` is object construction with dynamic keys, this is not recommended. You can generate it via `{keys : values ...}`, for example.

**Comment by edmundnoble** [comment]
How? The LHS of the : isn't parsed as a query.

**Comment by jdegoes** [comment]
If that's true, it's an oversight in the grammar.

**Comment by edmundnoble** [comment]
My bad, it's parsed as a query. It just results in a runtime exception because it isn't implemented, as can be seen on line 55 of SliceTransform.scala.

```
💪 $ select {(select cars.name from cars): name} from cars
💪 $ Exception in thread "AeshProcess: 18" java.lang.RuntimeException: WrapObjectDynamic(Cond(IsType(Leaf(Source),JObjectUnfixedT),Cond(IsType(DerefObjectStatic(Leaf(Source),.name),JTextT),DerefObjectStatic(Leaf(Source),.name),DerefArrayStatic(OuterArrayConcat(WrappedArray(WrapArray(Leaf(Source)))),[1])),DerefArrayStatic(OuterArrayConcat(WrappedArray(WrapArray(Leaf(Source)))),[1])),Cond(IsType(Leaf(Source),JObjectUnfixedT),DerefObjectStatic(Leaf(Source),.name),DerefArrayStatic(OuterArrayConcat(WrappedArray(WrapArray(Leaf(Source)))),[1]))) (of class quasar.yggdrasil.TransSpecModule$trans$WrapObjectDynamic)
```

**Comment by djspiewak** [comment]
Going to close this as invalid, since we need to keep it.  I'll open a ticket for actually implementing it; at present, I have no idea how it is even conceptually possible in precog.

**Comment by jdegoes** [comment]
@djspiewak Quite possibly we need a naive mode that loads data as streams of `Ejson` or something, and does direct evaluation in a streaming fashion (similar to Mimir but without having a columnar table layout). This could be used in (a) cases of high heterogeneity, e.g. every row is different from every other row, or (b) cases of high dynamism.
