### ISSUE TITLE
Documentation for the metastore endpoint is missing userName field

### ISSUE THREAD

**Issue by kRITZCREEK** [quasar-analytics/quasar#2653]
For the postgresql metastore configuration the documentation is missing the `userName` field.

**Comment by jedesah** [comment]
:+1:

**Comment by damonLL** [comment]
@kRITZCREEK are you referring to our [SlamData docs](http://docs.slamdata.com/en/latest/administration-guide.html?configuring-postgres-as-metastore#configuring-postgres-as-metastore) or some Quasar docs I don't know about?

**Comment by kRITZCREEK** [comment]
@damonLL Don't you worry! I'm talking about the README.md file in this repository.
