### ISSUE TITLE
QScript should use objects rather than arrays to carry context

### ISSUE THREAD

**Issue by djspiewak** [quasar-analytics/quasar#2681]
QScript currently builds a lot of arrays, which it then peels apart later in order to carry along information that it needs (often duplication, one side of which will be transformed while the other must be preserved).  The problem is when this introduces undefinedness, connectors are being implicitly expected to maintain sparse arrays throughout the computation pipeline, which is not always an assumption that backends can satisfy.  Objects do not have this flaw, as objects are sparse by definition, and thus qscript would not be making any assumption to use objects rather than arrays as its context structure.

So rather than something that builds an array `[.foo, .foo]` and later derefs `[0]` or `[1]`, it would build an object `{"0": .foo, "1": .foo}` and later deref `.0` or `.1`.

**Comment by alissapajer** [comment]
Completed with the switch to QSU.
