### ISSUE TITLE
Broken DeleteField semantics on Spark

### ISSUE THREAD

**Issue by djspiewak** [quasar-analytics/quasar#2691]
Deleting a nonexistent field currently returns `NA`, where it should return the original object.  As an example:

```
DeleteField({"a":1, "b":2}, .c)
```

Spark returns `Data.NA` from the above.  The result should be `{"a":1, "b":2}`

**Comment by alissapajer** [comment]
Fixing this enables `orderedWildcardWithProjection.test` and `sortWildcardOnExpression.test` on `next-major`. 

`QScript` is deleting a nonexistent field (which is incorrect, though not strictly so), which was hitting this spark bug. This `QScript` issue will be tracked separately.

**Comment by alissapajer** [comment]
The `QScript` issue is tracked in #2703.
