### ISSUE TITLE
Mimir should handle `ConcatArrays` of two strings or a string and an array

### ISSUE THREAD

**Issue by alissapajer** [quasar-analytics/quasar#2692]
SQL^2 uses `||` for both array and string concat (and heterogeneous concat of a string and an array). For example,`"foo" || "bar"` evaluates to `"foobar"` and `"foo" || [1,2,3]` evaluates to `["f","o","o",1,2,3]`. Mimir does not currently handle the string case or the heterogeneous case.

It's a separate discussion whether these are the semantics for `||` that we'd like to uphold for SQL^2.

**Comment by djspiewak** [comment]
Moving this into the initial implementation epic, since it exists in the demo queries.
