### ISSUE TITLE
Cannot use `?? {}` in `OBJECT_CONCAT` or `DELETE_FIELD` arguments

### ISSUE THREAD

**Issue by garyb** [quasar-analytics/quasar#2720]
Example query that is rejected:

``` sql
SELECT OBJECT_CONCAT(DELETE_FIELD(t0, "b"), t0 ?? {}) FROM `/spark-local/structure_test_deep.json` AS t0
```

Error message from quasar:
``` json
{
  "error": {
    "status": "Error in query.",
    "detail": {
      "message": "Unknown arguments: List(Obj(Map(),Some(Top)), Coproduct(Obj(Map(),Some(Top)),Const(Obj(Map()))))"
    }
  }
}
```

However, using either `t0` or `{}` alone works fine:
``` sql
SELECT OBJECT_CONCAT(DELETE_FIELD(t0, "b"), {}) FROM `/spark-local/structure_test_deep.json` AS t0
SELECT OBJECT_CONCAT(DELETE_FIELD(t0, "b"), t0) FROM `/spark-local/structure_test_deep.json` AS t0
```

The issue seems to be specifically with using constant values with `??`, as using a map on the RHS with some value computed from t0 is fine, but other constant map values are not.

**Comment by garyb** [comment]
I should perhaps have mentioned that this is definitely when appearing in function arguments too, not relating to constants with `??`, as that does work in other situations. Example:
``` sql
SELECT t0.a ?? {} FROM `/spark-local/structure_test_deep.json` AS t0
```

**Comment by alissapajer** [comment]
This should be retested.

**Comment by djspiewak** [comment]
This works in master.

**Comment by alissapajer** [comment]
@djspiewak I think we really should add an integration test for this.

**Comment by djspiewak** [comment]
It's very close to another integration test we've already added actually, unless there's something specific about this query that I'm missing?

**Comment by alissapajer** [comment]
What integration test is it close to?

If we have a test for it already, that's sufficient, but we should reference that test in this issue, in that case.

**Comment by djspiewak** [comment]
`bug2958.test`

**Comment by alissapajer** [comment]
@djspiewak this issue was specifically filed for using `?? {}` in function arguments. That integration test doesn't use `?? {}` in function arguments (or at all). We don't know when this was fixed or when, so we should have a test explicitly for this.

**Comment by djspiewak** [comment]
kk
