### ISSUE TITLE
Temporary cached data sets are not purged

### ISSUE THREAD

**Issue by natefaubion** [quasar-analytics/quasar#2751]
Since I upgraded to v21 and enabled a cached view, my directory listing is now littered with thousands of unique `__quasar.tmp` files. They all appear to point to data snapshots for my cached query.

<img width="668" alt="screen shot 2017-09-11 at 11 32 11 am" src="https://user-images.githubusercontent.com/144058/30290630-e9bd4720-96e4-11e7-90ff-681d2fe22708.png">

A couple of things:

* These should definitely be cleaned up
* We should make these dotfiles so that the FS view does not show them by default.

**Comment by zeeiyerWork** [comment]
@drostron -> It seems that 
a> older copies of cached content should not stick around (perhaps we leave 1-2 versions around just in case).
b> If a user deletes a deck (with a cached card) or just a cached card within a deck, I hope we are plugged in to those events to tear-down cache appropriately.

**Comment by natefaubion** [comment]
> If a user deletes a deck (with a cached card) or just a cached card within a deck, I hope we are plugged in to those events to tear-down cache appropriately.

In my PR, I issue a DELETE to card mounts. There aren't any events for the backend to respond to other than that, but it should cleanup tmp files if the original view is deleted.

**Comment by drostron** [comment]
We can and should cleanup temp files.
