### ISSUE TITLE
Mimir doesn't work on windows 

### ISSUE THREAD

**Issue by cryogenian** [quasar-analytics/quasar#2765]
Steps to reproduce using SD master (2017.09.15) 
Quasar 23.1.2 and 20.14.13

+ Mount mimir somehow
+ Try to upload any file 
+ Open same uri in other page

Expected result 
+ File appears in fs ui
+ Fs ui in other page is loaded

Actual result
+ PUT requests doesn't return anything. Loading spins forever
+ Fs ui is blocked. Loading spins forever

Same behaviour for workspaces 
+ Mount mimir
+ Drilldown to mimir folder
+ Create workspace
+ Insert query card
+ Put any valid query (e.g. 
```sql
SELECT COUNT(*) AS ct, country FROM `/local/local/olympics` GROUP BY country
```
+ Press `Run query`
+ Slide to the next card

Expected result
+ Next card action list appears

Actual result 
+ Spinner. `PUT` doesn't return anything. 

If you go to mimir folder in fs ui, it doesn't work.

**Comment by djspiewak** [comment]
This doesn't surprise me *too* much, but it's going to be extremely tricky to reproduce since I don't actually have windows on my work machine.  I can test on my gaming rig after SlamJam, but not before.
