### ISSUE TITLE
Metastore endpoints and config format are inconsistent

### ISSUE THREAD

**Issue by kRITZCREEK** [quasar-analytics/quasar#2769]
Follow-up for https://github.com/quasar-analytics/quasar/pull/2767.

The config format expects the h2 location to be specified like so:

```
 "h2": {
   "file": "`database_url`"
 }
```
while the metastore endpoints return and expect a different format:
```
 "h2": {
   "location": "`database_url`"
 }
```

Seems like a sensible idea to unify the two.

**Comment by jedesah** [comment]
I'm almost certain the metastore endpoint accepts both but I'll have a look. Entirely possible the config file doesn't accept `"location"` which it should as I was under the impression this would be the same code path.

**Comment by kRITZCREEK** [comment]
This has now become a blocker for https://github.com/slamdata/purescript-quasar/pull/65, since we can't be sure what format to expect from the Quasar endpoints. Could we settle on one of `location` or `file` please? We'd prefer `file` since that how it works in the configuration file.

**Comment by jedesah** [comment]
Okay, moved to the top of my queue. `file` should only be for backwards compatibility, it's a bug that it's showing up anywhere else, I'll standardize on `location` everywhere.

**Comment by kRITZCREEK** [comment]
That's great news, thanks!

**Comment by jedesah** [comment]
I'm going to run one more sanity check, but @kRITZCREEK I'm pretty sure both the config file and the endpoint will accept both `file` and `location` but will produce `location`. What exactly is the behavior you are running into that is blocking slamdata/purescript-quasar#65?

**Comment by kRITZCREEK** [comment]
Allright, so I only ever have to expect location from quasar? In that case I'm good :) We probably also want to revert https://github.com/quasar-analytics/quasar/pull/2767 in that case.

**Comment by jedesah** [comment]
Good point! Will do! That PR got opened and merged a little too quickly for me to intervene and mention that `location` was the desired behavior moving forward
