### ISSUE TITLE
The metadata endpoint for mimir mounts gives a 404 when the mount is empty

### ISSUE THREAD

**Issue by garyb** [quasar-analytics/quasar#2773]
I'd expect a response like this instead:

``` json
{ "children": [] }
```

All the other mounts behave this way, and given the mount does actually exist it seems reasonable that it should return an empty list rather than "I don't exist".

**Comment by djspiewak** [comment]
I've noticed this in the REPL too (there it shows up as an error).  My understanding was that this is actually a bug in the quasar filesystem, but if other mounts aren't exhibiting the same behavior, then that seems unlikely.  I'll investigate a bit more and see if I can figure out why it's happening.

**Comment by garyb** [comment]
It's probably worth double checking that assertion... I think it's impossible to have an empty Mongo mount, so I might not have seen the exact scenario before.

**Comment by wemrysi** [comment]
@djspiewak @garyb This looks like a duplicate of #2473, mind if we just reopen that one?

**Comment by garyb** [comment]
Sure thing 👍

**Comment by djspiewak** [comment]
Closing as duplicate of #2473.  I can confirm that this is indeed broken once again though.
