### ISSUE TITLE
Explosively horrible qscript from structure editor query

### ISSUE THREAD

**Issue by djspiewak** [quasar-analytics/quasar#2775]
SQL:

```sql
SELECT OBJECT_CONCAT(DELETE_FIELD(t2, "c"), {"test": OBJECT_CONCAT(t2.test, {"c": OBJECT_CONCAT(t2.test.c, t2.c) ?? t2.c}) ?? {"c": t2.c}}) ?? t2 FROM (SELECT OBJECT_CONCAT(DELETE_FIELD(t1, "b"), {"test": OBJECT_CONCAT(t1.test, {"b": OBJECT_CONCAT(t1.test.b, t1.b) ?? t1.b}) ?? {"b": t1.b}}) ?? t1 FROM (SELECT OBJECT_CONCAT(DELETE_FIELD(t0, "a"), {"test": OBJECT_CONCAT(t0.test, {"a": OBJECT_CONCAT(t0.test.a, t0.a) ?? t0.a}) ?? {"a": t0.a}}) ?? t0 FROM `/spark-local/structure_test_deep.json` AS t0) AS t1) AS t2
```

Logical plan:

```
Let('__tmp0)
├─ Let('__tmp1)
│  ├─ Read(/spark_local/zips)
│  ╰─ Typecheck(Obj(Map[], Some(Top)))
│     ├─ Free('__tmp1)
│     ├─ Free('__tmp1)
│     ╰─ Constant(NA)
╰─ Let('__tmp2)
   ├─ Invoke(Squash)
   │  ╰─ Invoke(IfUndefined)
   │     ├─ Invoke(ObjectConcat)
   │     │  ├─ Invoke(DeleteField)
   │     │  │  ├─ Free('__tmp0)
   │     │  │  ╰─ Str("a")
   │     │  ╰─ Invoke(MakeObject)
   │     │     ├─ Str("test")
   │     │     ╰─ Let('__tmp3)
   │     │        ├─ ObjectProject(Free('__tmp0){"test"})
   │     │        ╰─ Typecheck(Obj(Map[], Some(Top)))
   │     │           ├─ Free('__tmp3)
   │     │           ├─ Invoke(IfUndefined)
   │     │           │  ├─ Invoke(ObjectConcat)
   │     │           │  │  ├─ Free('__tmp3)
   │     │           │  │  ╰─ Invoke(MakeObject)
   │     │           │  │     ├─ Str("a")
   │     │           │  │     ╰─ Let('__tmp4)
   │     │           │  │        ├─ ObjectProject(Free('__tmp0){"a"})
   │     │           │  │        ╰─ Typecheck(Obj(Map[], Some(Top)))
   │     │           │  │           ├─ Free('__tmp4)
   │     │           │  │           ├─ Let('__tmp5)
   │     │           │  │           │  ├─ ObjectProject(Free('__tmp0){"test"})
   │     │           │  │           │  ╰─ Typecheck(Obj(Map[], Some(Top)))
   │     │           │  │           │     ├─ Free('__tmp5)
   │     │           │  │           │     ├─ Let('__tmp6)
   │     │           │  │           │     │  ├─ ObjectProject(Free('__tmp5){"a"})
   │     │           │  │           │     │  ╰─ Typecheck(Obj(Map[], Some(Top)))
   │     │           │  │           │     │     ├─ Free('__tmp6)
   │     │           │  │           │     │     ├─ Invoke(IfUndefined)
   │     │           │  │           │     │     │  ├─ Invoke(ObjectConcat)
   │     │           │  │           │     │     │  │  ├─ Free('__tmp6)
   │     │           │  │           │     │     │  │  ╰─ Free('__tmp4)
   │     │           │  │           │     │     │  ╰─ ObjectProject(Free('__tmp0){"a"})
   │     │           │  │           │     │     ╰─ Constant(NA)
   │     │           │  │           │     ╰─ Constant(NA)
   │     │           │  │           ╰─ Constant(NA)
   │     │           │  ╰─ Invoke(MakeObject)
   │     │           │     ├─ Str("a")
   │     │           │     ╰─ ObjectProject(Free('__tmp0){"a"})
   │     │           ╰─ Constant(NA)
   │     ╰─ Free('__tmp0)
   ╰─ Let('__tmp7)
      ├─ Invoke(Squash)
      │  ╰─ Invoke(IfUndefined)
      │     ├─ Invoke(ObjectConcat)
      │     │  ├─ Invoke(DeleteField)
      │     │  │  ├─ Free('__tmp2)
      │     │  │  ╰─ Str("b")
      │     │  ╰─ Invoke(MakeObject)
      │     │     ├─ Str("test")
      │     │     ╰─ Let('__tmp8)
      │     │        ├─ ObjectProject(Free('__tmp2){"test"})
      │     │        ╰─ Typecheck(Obj(Map[], Some(Top)))
      │     │           ├─ Free('__tmp8)
      │     │           ├─ Invoke(IfUndefined)
      │     │           │  ├─ Invoke(ObjectConcat)
      │     │           │  │  ├─ Free('__tmp8)
      │     │           │  │  ╰─ Invoke(MakeObject)
      │     │           │  │     ├─ Str("b")
      │     │           │  │     ╰─ Let('__tmp9)
      │     │           │  │        ├─ ObjectProject(Free('__tmp2){"b"})
      │     │           │  │        ╰─ Typecheck(Obj(Map[], Some(Top)))
      │     │           │  │           ├─ Free('__tmp9)
      │     │           │  │           ├─ Let('__tmp10)
      │     │           │  │           │  ├─ ObjectProject(Free('__tmp2){"test"})
      │     │           │  │           │  ╰─ Typecheck(Obj(Map[], Some(Top)))
      │     │           │  │           │     ├─ Free('__tmp10)
      │     │           │  │           │     ├─ Let('__tmp11)
      │     │           │  │           │     │  ├─ ObjectProject(Free('__tmp10){"b"})
      │     │           │  │           │     │  ╰─ Typecheck(Obj(Map[], Some(Top)))
      │     │           │  │           │     │     ├─ Free('__tmp11)
      │     │           │  │           │     │     ├─ Invoke(IfUndefined)
      │     │           │  │           │     │     │  ├─ Invoke(ObjectConcat)
      │     │           │  │           │     │     │  │  ├─ Free('__tmp11)
      │     │           │  │           │     │     │  │  ╰─ Free('__tmp9)
      │     │           │  │           │     │     │  ╰─ ObjectProject(Free('__tmp2){"b"})
      │     │           │  │           │     │     ╰─ Constant(NA)
      │     │           │  │           │     ╰─ Constant(NA)
      │     │           │  │           ╰─ Constant(NA)
      │     │           │  ╰─ Invoke(MakeObject)
      │     │           │     ├─ Str("b")
      │     │           │     ╰─ ObjectProject(Free('__tmp2){"b"})
      │     │           ╰─ Constant(NA)
      │     ╰─ Free('__tmp2)
      ╰─ Invoke(Take)
         ├─ Invoke(Squash)
         │  ╰─ Invoke(IfUndefined)
         │     ├─ Invoke(ObjectConcat)
         │     │  ├─ Invoke(DeleteField)
         │     │  │  ├─ Free('__tmp7)
         │     │  │  ╰─ Str("c")
         │     │  ╰─ Invoke(MakeObject)
         │     │     ├─ Str("test")
         │     │     ╰─ Let('__tmp12)
         │     │        ├─ ObjectProject(Free('__tmp7){"test"})
         │     │        ╰─ Typecheck(Obj(Map[], Some(Top)))
         │     │           ├─ Free('__tmp12)
         │     │           ├─ Invoke(IfUndefined)
         │     │           │  ├─ Invoke(ObjectConcat)
         │     │           │  │  ├─ Free('__tmp12)
         │     │           │  │  ╰─ Invoke(MakeObject)
         │     │           │  │     ├─ Str("c")
         │     │           │  │     ╰─ Let('__tmp13)
         │     │           │  │        ├─ ObjectProject(Free('__tmp7){"c"})
         │     │           │  │        ╰─ Typecheck(Obj(Map[], Some(Top)))
         │     │           │  │           ├─ Free('__tmp13)
         │     │           │  │           ├─ Let('__tmp14)
         │     │           │  │           │  ├─ ObjectProject(Free('__tmp7){"test"})
         │     │           │  │           │  ╰─ Typecheck(Obj(Map[], Some(Top)))
         │     │           │  │           │     ├─ Free('__tmp14)
         │     │           │  │           │     ├─ Let('__tmp15)
         │     │           │  │           │     │  ├─ ObjectProject(Free('__tmp14){"c"})
         │     │           │  │           │     │  ╰─ Typecheck(Obj(Map[], Some(Top)))
         │     │           │  │           │     │     ├─ Free('__tmp15)
         │     │           │  │           │     │     ├─ Invoke(IfUndefined)
         │     │           │  │           │     │     │  ├─ Invoke(ObjectConcat)
         │     │           │  │           │     │     │  │  ├─ Free('__tmp15)
         │     │           │  │           │     │     │  │  ╰─ Free('__tmp13)
         │     │           │  │           │     │     │  ╰─ ObjectProject(Free('__tmp7){"c"})
         │     │           │  │           │     │     ╰─ Constant(NA)
         │     │           │  │           │     ╰─ Constant(NA)
         │     │           │  │           ╰─ Constant(NA)
         │     │           │  ╰─ Invoke(MakeObject)
         │     │           │     ├─ Str("c")
         │     │           │     ╰─ ObjectProject(Free('__tmp7){"c"})
         │     │           ╰─ Constant(NA)
         │     ╰─ Free('__tmp7)
         ╰─ Constant(Int(11))
```

QScript: https://gist.github.com/6911a89d74a44af852e3959f48a42ad8

Obviously a pretty gnarly query, but the qscript is lololololololol.

**Comment by alissapajer** [comment]
@djspiewak can I get access somewhere to the `structure_test_deep.json` data?

**Comment by alissapajer** [comment]
This is not fixed yet by PR #2902 but I think it possibly could be fixed using the work in that PR. Still investigating.

**Comment by garyb** [comment]
@alissapajer here's `structure_test_deep`:
``` json
{ "a": 1, "b": { "ba": { "innermost": true }, "bb": ["x", false, { "foo": "bar" }], "bc": 0.5 }, "c": [] }
{ "a": 2, "b": { "ba": { "innermost": false }, "bb": ["y", true, { "foo": "baz" }], "bc": 60 }, "c": [true, false, "maybe"] }
{ "a": 3, "b": { "ba": true, "bb": ["z", { "foo": "quux" }] }, "c": null }
```

**Comment by alissapajer** [comment]
@garyb is this issue blocking all use of the structure editor? Or are you able to use the structure editor in some contexts?

**Comment by zeeiyerWork** [comment]
My $.02 -> is that the structure editor would still be usable in a lot of contexts. Getting into this state is possible with nested data and multiple operations - which we can advise users against to begin with.  Hence moving this to the 4.4 epic. @garyb if you disagree ,please do comment. Thanks

**Comment by garyb** [comment]
It's fine applying one edit, quite slow applying two, and explodes like this on three. Adding cache cards in between edits will help, but unless we force that it's a bit risky to let through IMO.

**Comment by zeeiyerWork** [comment]
Right - can we add a caveat  around > one edit for now and address in 4.3.x (i take it this was a column - rename correct?)

**Comment by zeeiyerWork** [comment]
@alissapajer, @wemrysi, @garyb -> This is back in scope, based on the commentary at https://github.com/slamdata/slamdata/issues/2386. It seems that the options are
- either fix this and release structure editor.
- or do not release structure editor.
So we need some investigation on this and an opinion on level of effort.

**Comment by djspiewak** [comment]
@alissapajer So the qscript generated here is still very large.  Doesn't appear to contain any joins (good!), and generates very quickly, but it's large.  Do we consider this provisionally-fixed?

**Comment by alissapajer** [comment]
@djspiewak let's consider this fixed when the generated qscript is correct (regardless of its size). The logical plan is also pretty big. If the qscript is correct, but there are connector-specific bugs, then we can open separate issues for those.

**Comment by alissapajer** [comment]
How does this query run against mimir and mongo?

**Comment by alissapajer** [comment]
Thinking about this more, if the qscript is correct but we can identify areas where it could be smaller, then I'm thinking we should close this issue when qsu lands, but then open a new issue tracking the too-verbose qscript.

**Comment by djspiewak** [comment]
Ironically the easiest way to test this might be to just run the query.  Haven't done that yet against any backend.

**Comment by djspiewak** [comment]
@garyb When you get a chance, can you re-test the structure editor on quasar 27.0.0 or higher?  I tried compiling the query in the OP (modulo the new function names) and it now compiles in less than a second (from the REPL), and the qscript looks reasonable.  I'd be very interested to know whether or not the underlying issue is resolved, and if the structure editor is now usable at reasonable depth.

**Comment by garyb** [comment]
(Moving this from a Slack message I sent to Daniel)

Ok, so unfortunately it's still kinda slow quite quickly, but it doesn't completely explode now: https://gist.github.com/garyb/6ffc22924376c59ef28b128660371ae8

It takes a few minutes to run this 4-step structure edit for me.

(Something else we discussed is that the initial example here returns the empty set)

None of these 4 operations seem to have any issues when I've tried applying them at various levels of the structure, but doing the flatten operation does seem to always result in an empty set. I'll dig into that a bit more and provide a minimalish example.

**Comment by alissapajer** [comment]
@garyb can you open new issues for any new findings regarding structure editor queries? We're going to close this one out when we add a test showing that the initial query in this issue compiles. And then we can dig into other bugs separately.

**Comment by djspiewak** [comment]
Results:

```
Query time: 194.6s
 a  | b.bc | b.bd   | b.bb[0] | b.bb[1] | b.bb[2].foo | b.be[0] | b.be[1] | b.be[2] | b.be  | b.ba  | b.bb[1].foo |
----|------|--------|---------|---------|-------------|---------|---------|---------|-------|-------|-------------|
  1 |  0.5 |   true | x       |   false | bar         |         |         |         |       |       |             |
  2 |   60 |  false | y       |    true | baz         |    true |   false | maybe   |       |       |             |
  3 |      |        | z       |         |             |         |         |         |  null |  true | quux        |
```

Also an absurd amount of qscript…

**Comment by djspiewak** [comment]
Ok, proud developer moment… That 400k node qscript generates in just *56 seconds*.  Most of the 200s total runtime on the query is in evaluation.

**Comment by djspiewak** [comment]
I'm satisfied that the issue described in the OP is sorted for the moment (which is to say, horrendous compilation times).  @garyb When you get a chance, can you open a fresh issue for the performance of the queries involved in the structure editor?  This is probably going to end up being a bit of a serious investigation, but maybe we can find some query tweaks which will allow it to collapse a bit more.

**Comment by djspiewak** [comment]
Some random math…

7 * 7 * 7 * 9 = 3087

This is the amount of expansion you're going to get due to the number of inner-references you have.

The outer freemap has about 18 operations.  So we actually have an even more horrible expansion:

18 + 7 * 18 + 7 * 7 * 18 + 7 * 7 * 7 * 18 = 7200 operations

But that's without including guards, and there are guards *everywhere*.  What's worse is guards double up their parameters.  Each operation is going to have at least one guard, which is a doubling per guard:

18 * 2 + 2 ^ 18 * 7 * 18 * 2 + 2 ^ 18 * 7 * 7 * 18 * 2 + 2 ^ 18 * 7 * 7 * 7 * 18 * 2 = 3,765,436,452

I'm actually kinda impressed that we ONLY ended up with 400,000 nodes.  My guess is that I'm overestimating the number of guards with doubled contents, or under-estimating the value we can get out of Hole.

Either way, this query is nuts.  One way that we could probably bring it down a bit is to be less crazy with guards.  Or at the very least, allow them to collapse together.

**Comment by alissapajer** [comment]
@djspiewak is there a reason you reopened this?

**Comment by alissapajer** [comment]
Ah, probably because of this comment https://github.com/quasar-analytics/quasar/pull/3180#issuecomment-346902943

**Comment by djspiewak** [comment]
My plan was to just let it close with the PR.
