### ISSUE TITLE
Dynamic loading in sbt doesn't work on windows

### ISSUE THREAD

**Issue by djspiewak** [quasar-analytics/quasar#2797]
Christoph was testing.  Bad things happened.  Not coincidence.

Mostly what happened is it couldn't load the classes for the dynamically loaded backend modules, with `ClassNotFoundError`.  I'm guessing that something is not windows-friendly about the path setups.

**Comment by djspiewak** [comment]
Can't reproduce this one either.  web/run and repl/run both worked for me.

**Comment by djspiewak** [comment]
Reproduced it now.

**Comment by djspiewak** [comment]
Ok, so the cause of this is sort of multi-fold.  First off, I was using `posixCodec` on Windows, which isn't going to be able to parse absolute paths on that system.  Second though, even after fixing this, it *still* doesn't work because `Path.windowsCodec` (in pathy) is incorrect!  It doesn't actually handle the leading drive information.  This is probably solvable by prepending `\` to the path, but that's not the correct way to deal with the issue.

I'll fix this in pathy, but in the meantime, dynamic loading is not going to work on any Windows system.  Mimir works; none of the other connectors do.  This is probably a blocker for 4.3, though not a blocker for releasing to @dugdun.  (attn @zeeiyerWork)

**Comment by wemrysi** [comment]
@djspiewak See `quasar.config.FsPath` which exists for this exact reason.

**Comment by djspiewak** [comment]
@wemrysi Interesting. That handles Windows paths by sandboxing though, which is probably the right encoding from a Pathy standpoint, but not something that I externally care about.  I'll probably just switch to `java.io.File` for now (since I don't actually use `Path` directly: I create `File` and convert, then convert `Path` back into `File` out the other side) just to get this working, since we really can't release without this.
