### ISSUE TITLE
Reenable Spark in master

### ISSUE THREAD

**Issue by djspiewak** [quasar-analytics/quasar#2800]
This entails fixing the following three things:

- [x] Propagate the stupid context classloader stuff through to whatever Netty is doing
- [x] Ensure that no other areas are similarly problematic
- [ ] Make the `sparkcore` project publish two assembly JARs during publication: with and without the Spark dependency
  + Also make the spark assembly JARs match the naming convention of the other connectors while we're at it

Once all of this is done, we can reenable Spark publication in `build.sbt` as well as in `scripts/publishJar`.

**Comment by rabbitonweb** [comment]
Publishing of two jars was moved to https://github.com/quasar-analytics/quasar/issues/2873
