### ISSUE TITLE
Plugins directory doesn't work 

### ISSUE THREAD

**Issue by cryogenian** [quasar-analytics/quasar#2813]
Windows 10. Quasar version 24.0.15 

I downloaded quasar-mongodb-internal-plugin and quasar-web-assembly, put plugin into `./plugin/` directory. 

Tried following commands 
```
java -jar quasar-web-assembly.jar --content-path "PATH_TO_SD_PUBLIC" -p ./plugin/
java -jar quasar-web-assembly.jar --content-path "PATH_TO_SD_PUBLIC" -p ./plugin
java -jar quasar-web-assembly.jar --content-path "PATH_TO_SD_PUBLIC" -p "FULL_PATH_TO_PLUGIN_DIR"
```
Both told me that `plugin directory does not exists (or it's a file)` 

Then I tried 
```
java -jar quasar-web-assembly.jar --content-path "C:\Users\zimal\Projects\slam\public" --backend:quasar.physi
cal.mongodb.MongoDb\$=./plugin/quasar-mongodb-internal-assembly.jar
```
This worked but, I still can't mount mongodb. The error is 
```json
{ "error": { "status": "Invalid mount configuration.", "detail": { "reasons": [ "Unsupported filesystem type: mongodb" ] } } }
```

**Comment by djspiewak** [comment]
When you tried the `FULL_PATH_TO_PLUGIN_DIR` option, did you use Windows-style paths?

**Comment by djspiewak** [comment]
Oh, also, this could be somewhat related to @kRITZCREEK's issues with dynamic loading, reported here: #2797

**Comment by cryogenian** [comment]
@djspiewak I tried both

**Comment by djspiewak** [comment]
Ok so that's just broken then.

**Comment by djspiewak** [comment]
@cryogenian Can you do me a favor and try using `--plugins` rather than `-p`?

**Comment by cryogenian** [comment]
@djspiewak The same problem with `--plugin`
Honestly I'm a bit more concerned about `--backend` doesn't work

**Comment by djspiewak** [comment]
`--plugins` plural.  But yeah, `--backend` works but not on Windows.  See #2797.  Very definitely on my short-term todo list.

**Comment by djspiewak** [comment]
@cryogenian When you get a chance, can you test this again with the latest quasar?  I think everything is working now.

**Comment by zeeiyerWork** [comment]
@cryogenian - can you confirm? So we can close this out? 
Thanks

**Comment by cryogenian** [comment]
The issue remains with 24.4.1

**Comment by zeeiyerWork** [comment]
@djspiewak -> fyi

**Comment by djspiewak** [comment]
I'll look into it.  @dugdun Can you confirm whether or not this works on Mac?  I can test relatively easily enough; just wondering if you already know.  @cryogenian Is it just that the `-P` option still isn't working, or is `--plugins` also not functional?

**Comment by dugdun** [comment]
I am currently using the following command on my Mac to run Quasar 24.1.12 without issue:

```
java $(tr '\n' ' ' < ~/vmoptions.txt) -jar ~/quasar/quasar-web-assembly-24.1.12.jar -c ./quasar-config.json --plugins ~/quasar/plugins/24.1.12/ --content-path ./public/ -L /slamdata
```

Let me try pulling down a newer Quasar release to see if something broke. I'll also try with the `-P` option.

**Comment by djspiewak** [comment]
@dugdun Does `-P` work?  Or just `--plugins`?

**Comment by dugdun** [comment]
Hmm.... Something weird going on. I just tried starting with Quasar 24.4.1 and trying to load a workspace and the orange spinner just sat there. I restarted with Quasar 24.1.12 (what I was using previously I thought) and tried load the workspace again and still just see the orange spinner. This is usually a sign that things are not going to work as once things start processing the spinner changes to black stating that the workspace is loading. Rolled back to Quasar 23.1.4 (before connectors broken out) and things are working without issue.

@djspiewak can we look at things on my system at some point today? I thought we had the `--plugins` option working at one point in time on my Mac.

**Comment by djspiewak** [comment]
I won't be in the office today, but I'll push this to the top of my stack.  It's entirely possible that something is very broken here.  I'll make sure things are working on both Mac and Windows.

**Comment by dugdun** [comment]
OK. I just restarted with Quasar 24.4.1 and was able to get a very simple workflow to run under MongoDB 3.4. Trying to load another one right now, but it's just sitting there with the orange spinner. DevTools doesn't show anything trying to run after the initial call to /data/fs API call. I'll try looking at things on my end as well. It could be that I was running under the pre-connector split Quasar version, and not 24.1.12 like I originally though. 😦

**Comment by djspiewak** [comment]
Confirmed that dynamic loading is working just fine on mac (both with `-P` and `--plugins`), but *not* working on Windows.  Fixing.

**Comment by djspiewak** [comment]
Moving the discussion of this specific issue to #2797.  Please see that issue for more updates.
