### ISSUE TITLE
many ITs not running on Travis anymore

### ISSUE THREAD

**Issue by rintcius** [quasar-analytics/quasar#2854]
It looks like many ITs from connector specific sbt modules such as `mongoIt`, `marklogicIt` are not running in Travis anymore. 

I have checked these 
* not running `mongoit` tests: mongo 3.2 and 3.4
* running `mongoit` tests: mongo 2.6 and 3.0
Would be good to check the other connectors too

Note that I'm just assuming that the `mongoit` are running for 2.6 and 3.0 - the logs are not very clear on was has run exactly, see this excerpt for a 3.0 build:

```
[info] TaskResourceSpec
[info] CouchbaseStdLibSpec
[info] SparkStdLibSpec
[info] FilterPlannerSpec
[info] XmlStructuralPlannerSpec
[info] DirectoryQueriesSpec
[info] OperationsSpec
[info] FormatAwareFileSystemSpec
[info] JsonMarkLogicStdLibSpec
[info] XmlMarkLogicStdLibSpec
[info] JsonStructuralPlannerSpec
[info] MongoDbJsStdLibSpec
[info] MongoDbExprStdLibSpec
[info] MongoDbIOSpec
[info] MongoDbFileSystemSpec
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for rdbmsIt/exclusive:testOnly
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] Passed: Total 25, Failed 0, Errors 0, Passed 12, Skipped 13
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[success] Total time: 37 s, completed Sep 28, 2017 11:39:37 AM
```

**Comment by jedesah** [comment]
Looks like we might have missed [this line](https://github.com/quasar-analytics/quasar/blob/master/scripts/build#L111) in the dynamic loading change
