### ISSUE TITLE
Consistent naming of logical plan and qscript functions

### ISSUE THREAD

**Issue by alissapajer** [quasar-analytics/quasar#2859]
We need to make the function names across logical plan and qscript consistent (and the same where possible). These should also be consistent with the names of the SQL² functions described in https://github.com/quasar-analytics/quasar/issues/2808.

For example, in logical plan we have `ObjectProject` and in qscript we have `ProjectField`. See https://github.com/quasar-analytics/quasar/issues/2808#issuecomment-332976168 for more description.

**Comment by djspiewak** [comment]
It's not just naming.  Arity is also a relevant factor here, such as with the `ArrayLength` function.
