### ISSUE TITLE
Selecting constant returns single value

### ISSUE THREAD

**Issue by rintcius** [quasar-analytics/quasar#2877]
Selecting a constant from a table returns a single value:
```
select 1 from zips
Query time: 0.0s
 value |
-------|
     1 |
```

Compare this to:
```
select 1, pop from zips
Query time: 0.4s
 0  | pop    |
----|--------|
  1 |  15338 |
  1 |  36963 |
  1 |   4546 |
  1 |  10579 |
  1 |   1240 |
  1 |   3706 |
  1 |   1688 |
  1 |    177 |
  1 |  23396 |
  1 |  31495 |
...
```

I think the number of rows returned by the first query should be the amount of rows in the table instead, just like the 2nd query. This is also what postgres does.

BTW also if the table does not exist the constant is returned:
```
(v24.1.14) 💪 $ select 1 from idontexist
Query time: 0.0s
 value |
-------|
     1 |
```

**Comment by djspiewak** [comment]
This comes from MRA's semantics for constants.  It's one of the ways in which we consciously diverge from SQL.

**Comment by rintcius** [comment]
Hmm, is this something that MRA dictates to us/SQL2? I'd think this example would be in the realm of how MRA is mapped to SQL2, i.e. open to our interpretation.

I mean, I can see that according to MRA there has to be a way to represent constants. This is there in SQL2: `select 1` without any table. But I don't see why it follows from MRA that SQL2 has to interpret `select 1 from randomtable` as a single constant 1.

**Comment by djspiewak** [comment]
Constants are constants, regardless of where they are selected from.  This has some important implications for the results of reductions, particularly when reducing over dimensional data (e.g. `count(foo[_])`).  It's very definitely something which is forced on us by MRA.

**Comment by alissapajer** [comment]
Closing this as the current behavior is the desired and expected behavior.

I don't mean to end the conversation prematurely though, so if more conversation is required, please continue discussing.
