### ISSUE TITLE
Spark-hdfs build doesn't work and takes 3 hours to fail

### ISSUE THREAD

**Issue by djspiewak** [quasar-analytics/quasar#2881]
Example: https://travis-ci.org/quasar-analytics/quasar/builds/283230710

I've disabled the build for now.

**Comment by rabbitonweb** [comment]
Seems like somebody changed the way sparkcore.jar is being build. Will have a look tomorrow

**Comment by rabbitonweb** [comment]
Fixed with https://github.com/quasar-analytics/quasar/pull/2891
