### ISSUE TITLE
Build caching isn't working anymore

### ISSUE THREAD

**Issue by djspiewak** [quasar-analytics/quasar#2906]
Every job seems to be re-building everything.  That's very much less than ideal.

**Comment by alissapajer** [comment]
I've initiated contact with Travis about this.

**Comment by zeeiyerWork** [comment]
@alissapajer -> could you keep me cc'ed. I am talking to them about a couple of other issues as well.

**Comment by alissapajer** [comment]
I spoke with travis customer support, and they have escalated this issue to engineering.

**Comment by alissapajer** [comment]
This was an issue with travis itself that they have now resolved. Confirmed that caches are downloading correctly again.
