### ISSUE TITLE
Queries with a field and a reduction return undefined

### ISSUE THREAD

**Issue by jsantos17** [quasar-analytics/quasar#2933]
Consider the query

```
select state, sum(pop) from smallZips
```

The expected results are objects with the shape:

```
{"state": "MA", "1": 12093}
{"state": "MA", "1": 12093}
{"state": "MA", "1": 12093}
```

where `1` is the sum of the populations in `smallZips`. One per entry in `smallZips`. Instead, we get an object with a single key. 

```
{"1": 12093}
```

This issue is only present in the MongoDB connector. Using a different reduction like `count` showcases the same behavior. Mimir and Marklogic both return correct results.

The query `select city, state, sum(pop) from smallZips` works correctly as well, even in the Mongo connector.

**Comment by jdegoes** [comment]
Thanks for writing this up. Seems like a pretty serious error given how sensitive it is to changes in input.

**Comment by zeeiyerWork** [comment]
It seems specific to just the Mongo connector - Given the previous comments, am scheduling it in October milestone (preferably for the 5.0 target).

**Comment by rintcius** [comment]
Haven't analyzed fully yet, but there's something weird in the query: `"in": "$$a"` from the crystallized workflow gets translated into `"in": "$$ROOT"` in the mongo query.

Excerpt crystallized workflow: 

```
Chain
├─ $FoldLeftF
│  ├─ Chain
│  │  ├─ $ReadF(test; smallZips)
│  │  ├─ $GroupF
│  │  │  ├─ Grouped
│  │  │  │  ╰─ Name("0" -> {
│  │  │  │          "$push": {
│  │  │  │            "$let": {
│  │  │  │              "vars": {
│  │  │  │                "a": [
│  │  │  │                  {
│  │  │  │                    "$arrayElemAt": [["$_id", "$$ROOT"], { "$literal": NumberInt("0") }]
│  │  │  │                  },
│  │  │  │                  {
│  │  │  │                    "$arrayElemAt": [["$_id", "$$ROOT"], { "$literal": NumberInt("1") }]
│  │  │  │                  }]
│  │  │  │              },
│  │  │  │              "in": "$$a"
│  │  │  │            }
│  │  │  │          }
│  │  │  │        })
│  │  │  ╰─ By({ "$literal": null })
```

Excerpt mongo query:

```
db.smallZips.aggregate(
  [
    {
      "$group": {
        "0": {
          "$push": {
            "$let": {
              "vars": {
                "a": [
                  {
                    "$arrayElemAt": [["$_id", "$$ROOT"], { "$literal": NumberInt("0") }]
                  },
                  {
                    "$arrayElemAt": [["$_id", "$$ROOT"], { "$literal": NumberInt("1") }]
                  }]
              },
              "in": "$$ROOT"
            }
          }
        },
        "_id": { "$literal": null }
      }
    },
```

**Comment by zeeiyerWork** [comment]
Thanks. Hope its a quick fix to get to "in": "$$a" from "in": "$$ROOT".
