### ISSUE TITLE
FS api unicode support regression

### ISSUE THREAD

**Issue by beckyconning** [quasar-analytics/quasar#2945]
getting a file named времен via the file api returns 404 not found. this didn't used to be the case.

времен is encoded as `%D0%B2%D1%80%D0%B5%D0%BC%D0%B5%D0%BD`

**Comment by wemrysi** [comment]
@beckyconning Mind including the Quasar version and connector(s) used when you observed this problem? Thanks!

**Comment by beckyconning** [comment]
quasar-analytics/quasar@v25.0.16

mongodb

**Comment by beckyconning** [comment]
false alarm! it was us. i opened a ticket too early. thanks @wemrysi
