### ISSUE TITLE
`Select count(*)` doesn't work for view mounts generated from static values

### ISSUE THREAD

**Issue by cryogenian** [quasar-analytics/quasar#2956]
quasar 25.0.16

Making view mount with `select {"foo": 12}`
PUT@
```
http://localhost:8080/mount/fs/test-mount/testDb/Untitled%20Workspace%204.slam/.tmp/out9cf86875-62bb-41a4-957c-1996e7032bd2
``` 
with payload 
```json 
{"view":{"connectionUri":"sql2:?q=SELECT%20%7B%22foo%22:%2012%7D"}}
```

Counting it with 
```
http://localhost:8080/query/fs/test-mount/testDb/Untitled%20Workspace%204.slam/?q=SELECT%20COUNT(*)%20AS%20count%20FROM%20%60./.tmp/out9cf86875-62bb-41a4-957c-1996e7032bd2%60
```
return 
```json
{ "error": { "status": "Failed to execute SQL^2 query.", "detail": { "message": "Unable to insert data into MongoDB: MongoDB is only able to store documents in collections, not `Null`.", "data": "Null", "logicalplan": { "type": "LogicalPlan/Constant", "label": "NA" } } } }
```

Surprisingly the same error appears for mimir connector 0_o

**Comment by nicflores** [comment]
This error is certainly happening in Mongo. The error seems to a little worse in that we can't query a static view at all. So queries like `select ___ from 'static-view'` all fail. For example:

Mount a view containing `{"foo":12}`:
```
→ curl "http://localhost:20223/mount/fs/mongo34/test-view" -X PUT -d '{"view":{"connectionUri":"sql2:?q=select%20%7B%22foo%22%3A%2012%7D"}}'
added /mongo34/test-view
```

then in the repel issue a query against the view created in the step above:

```
(v26.0.1) 💪 $ explain SELECT foo FROM `/mongo34/test-view`
Quasar error: Plan execution failed: Unable to insert data into MongoDB: MongoDB is only able to store documents in collections, not `Null`., cause=None
```
one can replace `select foo` by `select *` or `select count(*)` etc. to get similar errors.

The final crystallized plan does contain a `Null` as an argument to `$PureF`:
```
Workflow (crystallized):
Chain
├─ $PureF(Null)
╰─ $ProjectF
   ├─ Name("__quasar_mongodb_sigil" -> { "$literal": NumberInt("12") })
   ╰─ ExcludeId
```
which may indicate the source of the error message printed above.

@garyb or @cryogenian is there a sense of how often the frontend uses queries against static views? 

@zeeiyerWork if these queries are extensively used by the frontend then it may be worth giving this issue a ☠️.

**Comment by garyb** [comment]
I'm not sure really, it might only be when the user enters a static query - @cryogenian will know better for sure though.

**Comment by zeeiyerWork** [comment]
@cryogenian -> Please see above comment and let us know. I do understand that you closed https://github.com/slamdata/slamdata/issues/2390 stating that the fix needed to be in quasar. Thx

**Comment by jedesah** [comment]
I think this might be a very similar issue to https://github.com/quasar-analytics/quasar/issues/2976. My guess is that view execution is not making use of the code that "intercepts" constant plans and returns their results before sending them off to a connector. I can have a look at this to see if that might be the issue. Now that I think of it, if this is the case, it might be causing @cryogenian's last comment on https://github.com/quasar-analytics/quasar/issues/2947 as well

**Comment by nicflores** [comment]
Thanks for taking a look Jr.

**Comment by zeeiyerWork** [comment]
reassigning to @jedesah as per earlier conversation and possible link to https://github.com/quasar-analytics/quasar/issues/2976

**Comment by zeeiyerWork** [comment]
blocking fe and looks like fix for another skulled issue may concomitantly fix this.

**Comment by djspiewak** [comment]
This is fixed in master.
