### ISSUE TITLE
Querying view mount returns 500

### ISSUE THREAD

**Issue by cryogenian** [quasar-analytics/quasar#2968]
Quasar version 25.1.0 

PUT@http://localhost:8080/mount/fs/test-mount/testDb/LayoutF.slam/.tmp/out6f0e452b-145c-4877-8552-7952651b26f2
Payload:
`{"view":{"connectionUri":"sql2:?q=SELECT%20*%20FROM%20%60/test-mount/testDb/flatViz%60"}}`

GET@http://localhost:8080/data/fs/test-mount/testDb/LayoutF.slam/.tmp/out6f0e452b-145c-4877-8552-7952651b26f2?offset=0&limit=300
Returns:
500: Internal server error

Quasar#25.0.16 works fine

**Comment by zeeiyerWork** [comment]
@jedesah - does your other PR fix this regression as well, or is this a separate issue?

**Comment by jedesah** [comment]
It would be worth giving `25.1.1` a try since that's the version with my fix for `invoke` and it does mess with interpreter composition which seems to likely be the culprit but this seems likely to have been introduced specifically in `25.1.0` cc @drostron. I'll happily investigate what's going on if @dave doesn't have any immediate idea what might have happened.

**Comment by drostron** [comment]
@jedesah and I were unable to reproduce the issue against mongo and mimir for a view mounts querying a data file and a view. We tested on both 25.1.0 and latest master. @cryogenian could you provide a few more details in order for us to replicate?

**Comment by zeeiyerWork** [comment]
Maybe get on a call/Pair program exercise -> to minimize this back and forth. Mentioning this since the same thing has happened on 2 other tickets.

**Comment by jedesah** [comment]
@cryogenian What kind of file is `/test-mount/testDb/flatViz`?

We tried to reproduce on Mongo but we will try one more time. If not, perhaps we can hop on a call tmr.

**Comment by cryogenian** [comment]
@jedesah actually it can be anything, olympics does not work too

**Comment by cryogenian** [comment]
This works when only mimir or mongodb connected. Also only one connector jar should live in plugins directory

**Comment by drostron** [comment]
Closing per #2975 and #2988
