### ISSUE TITLE
SQL^2 OID() function throws an error

### ISSUE THREAD

**Issue by dugdun** [quasar-analytics/quasar#2969]
Tested against Quasar: 25.0.24

**Sample Query**: 

```sql
select
        oid(test)
from
        `/mongodb-3.4/test/oidtest`
```

This query returns a Server 500 error.

The test data set has just a couple of documents that have a field called **test** with a string representation of a MongoDB ObjectID value.

**Sample Data**:

```
db.oidtest.insert({"test" : "59ef6d6a6c11c02f6e4922c8"})
db.oidtest.insert({"test" : "5852f1e6153eb29eb1f32978"})
```

This same query works in Quasar 20.14.7

**Comment by jdegoes** [comment]
Let's make sure this gets a test to prevent future regression. Very important function here!
