### ISSUE TITLE
Selecting literal value returns error

### ISSUE THREAD

**Issue by dugdun** [quasar-analytics/quasar#2976]
Version: SlamData 4.3.0 prerelease 5

Adding a default query card puts the query `SELECT "Hello, World!"` in the card. In previous versions you could add a **Preview Table** card after this and the text would appear in the table. Now when you do this you the following error:

![screen shot 2017-10-24 at 15 33 22](https://user-images.githubusercontent.com/828514/31969126-c8d1aff2-b8d0-11e7-8ba9-f124d0246af0.png)

This error occurs no matter what literal value you try to select, even if you are **SELECT**ing from a collection. If you add a collection and a field name (even if it doesn't exist in the collection), you don't get this error.

When creating a similar workspace in Mimir, I get the same error message about not being able to insert data into MongoDB.

Running in the REPL I don't get the error:

```
(v25.0.24) 💪 $ cd /mongodb-3.4/data
(v25.0.24) 💪 $ select "Hello, World!"
Rewritten Joins:
Str("Hello, World!")

Query time: 0.0s
 value          |
----------------|
 Hello, World!  |
```

Based off comments from @garyb in [SlamData issue 2413](https://github.com/slamdata/slamdata/issues/2413#issuecomment-339163013) this is an issue in Quasar.

**Comment by jsantos17** [comment]
@jedesah Since this is working fine in the REPL, do you think it might have something to do with the HTTP interface to Quasar?

**Comment by jedesah** [comment]
@jsantos17 Yes that seems like a reasonable hypothesis. More specifically, I would take a look at `queryPlan` which is called from the web layer but not the repl (after having a quick look at the repl code). As part of this fix we should also make sure that both the repl and web are exercising mostly the same code path. `queryPlan` intercepts "constant" plans, I'm thinking there might be something odd going on related to that.

**Comment by jedesah** [comment]
@jsantos17 Are you working on this? I have a pretty good idea how to fix it if you are otherwise busy and would like me to jump on this?

**Comment by jsantos17** [comment]
@jedesah I am not. Feel free to unassign me.

**Comment by zeeiyerWork** [comment]
OK assigning @jedesah to this based on above conversation.

**Comment by jedesah** [comment]
Another possibility aside from the web vs repl hypothesis is that it has do with views as I suspect the "create a query card followed by create a preview table" workflow involves creating a view. @garyb Could you comment on that so that I know which hypothesis to explore first?

**Comment by garyb** [comment]
Ah yes you're right, that'll create a view.

**Comment by jedesah** [comment]
@garyb Awesome. Thx for the quick response!

**Comment by djspiewak** [comment]
This is fixed on master
