### ISSUE TITLE
Convert all LPish things to QScriptish things

### ISSUE THREAD

**Issue by djspiewak** [quasar-analytics/quasar#2997]
Basically, this is the fabled autojoin elimination, that also needs to do a bunch of things unrelated to `AutoJoin`.

**Comment by alissapajer** [comment]
- [ ] `Transpose` => `LeftShift`
- [ ] `LPReduce` => `QSReduce`
- [ ] `AutoJoin` => `ThetaJoin` (for now we will default to creating `ThetaJoin`s but in the future will optimize by not creating unnecessary joins)
