### ISSUE TITLE
Metastore can become in a state where downloading views closes connection with outstanding data.

### ISSUE THREAD

**Issue by beckyconning** [quasar-analytics/quasar#3005]
Attached is a metastore where downloading views closes connection with outstanding data and a metastore which works correctly.

[quasar-metastore-broken.db.mv.db.zip](https://github.com/quasar-analytics/quasar/files/1432014/quasar-metastore.db.mv.db.zip)

[quasar-metastore-working.db.mv.db.zip](https://github.com/quasar-analytics/quasar/files/1432019/quasar-metastore.db.mv.db.zip)

**Comment by beckyconning** [comment]
It may be that this broken state can only be achieved by using slamdata-backend but once this state is achieved the error is present in both slamdata-backend and quasar.

This occurs in both v25.3.4 and v25.0.16

**Comment by beckyconning** [comment]
Against Local (mimir) the connection is closed with outstanding data:

```
➜ curl http://localhost:20223/data/fs/local/Untitled%20Workspace%2013.slam/\?request-headers\=%7B%22Authorizat
ion%22:%22Bearer%20eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvc2xhbWRhdGEuY29tIiwic3ViIjoiMTY0IiwiYXVkIjoiUkZRbUVlUzBWdzhVV1V
jaFFpbzV0UWN6c0tJcXBMIiwiaWF0IjoxNTA4OTQ2NDE3LCJleHAiOjE1MTE1NzQ0MTcsImF1dGhfdGltZSI6MTUwODk0NjQxNywibm9uY2UiOiIxZTBmMDY0NDRjNGRjY2ViYmI5ODI3Mz
Q5OTQxYWQ1ZSIsImVtYWlsIjoiYmVja3lAc2xhbWRhdGEuY29tIiwiZW1haWxfdmVyaWZpZWQiOiIiLCJhdF9oYXNoIjoiWlRsbU1qa3pORGd4T1dRd056TTNPVEZpWVRsallXVmtZalV6T
0dVd04yRSJ9.TiS7Xqveov3gYmQbP0mP4goOs6t9VUx40Ndrar_xyaRZx7N322BSlKHjOczgqDtP09Rcudguh0A_Amj0Iv0a1EDN2w2HDgVOBiReYPQZpE8wRRcb7nSgkS-wS-P97aXe0QX
w2TgxmafGnxgGoysySBFfon_sZfRFL16KOBQVbwo-ZWxTC2D6x0nIG0pjPjA_JPssqMTwO-s0x6ZdpBv_D-lUo8w8ne1GBIumGwhD63GhfkdatsYzUORuZn3ePQhkG3CDKA5Te0d8_1S2Ej
IpOCvCQ4WlVVKvHWcDxws14e19PZWpEnd4RxL1Bi7hNGWNCQFD6sWUFiIN0DalD_n6pg%22%2C%22Accept-Encoding%22:%22gzip%22%2C%22Accept%22:%22application/zip%2C
application/json%3Bmode\=readable%3Bdisposition\=%5C%22attachment%3B%20filename\*\=UTF-8%27%27Untitled%20Workspace%2013.slam.zip%5C%22%22%7D   
T_K.quasar-metadata.jsonA                                                                                                                      
E=EiڌTq\v3iPiһ                                                                                                                                 
url: (18) transfer closed with outstanding read data remaining                                                                                 
.߃Z     X
Krd%jεhq[mPT_KindexQ0G cۀM尶LcV>NF                                                                                                             
                                                                                                                                        
                                 v$/Z4%RР
                                         jG{.LaXUM׈p؅d߇_񀣟3)V2*+^gB:y
                                                                    1=p[4}x2@                                                                  
                                                                             #+Z2%p\CZҢoQv4$ߝPK    
```

Against MongoDB the connection stays open forever with no data received.

**Comment by beckyconning** [comment]
I wiped my metastore last week btw.

**Comment by drostron** [comment]
☠️'d this for the moment until I collect more info around severity.

**Comment by drostron** [comment]
I see truncated SQL² for a couple of view mounts within `quasar-metastore-broken.db.mv.db` such as
```
sql2:///?q=CREATE%20FUNCTION%20ROUND2%28%3Aval%2C%20%3An%29%0A%20%20BEGIN%0A%20%20%20%20%28%28ROUND%
```
which decodes to
```
sql2:///?q=CREATE FUNCTION ROUND2(:val, :n)
  BEGIN
    ((ROUND%
```
Not clear yet on how this might occur since we validate upon mount.

**Comment by drostron** [comment]
Previous deleted comment regarding truncation was just misleading tooling.

**Comment by drostron** [comment]
After working with @beckyconning I'm able to reproduce the failing download behavior.

Initially we were only able to trigger the following error on startup
```
Warning: Failed to mount '/mimir/amodule/' because 'Invalid mount config, '[module] CREATE FUNCTION z(:i)
  BEGIN
    (select :i)
  END', because: Unsupported filesystem type: module'.
```
After importing Becky's mimir mount contents into my environment we were able to trigger the download error.

Steps from a fresh metastore
1. Create a `mimir` mount
1. Mount a module under that mount
1. Restart quasar and notice failure

I've since been able to reproduce the download error with the above steps and a subsequent download of the module, but only when running against slamdata-backend. Further once the error state is triggered in SB it is also manifested in Quasar.

Investigation ensues.

**Comment by garyb** [comment]
There's an issue for that module warning already at #2282 - the download problem isn't caused by that alone, as I also get a bunch of those warnings on startup, but don't encounter the download issue described here.

**Comment by drostron** [comment]
@garyb Thanks for the additional info and reference to #2282. On Quasar we see the module warning after the steps without download error whereas on SB we see both the warning and the subsequent download error. It's not clear yet whether the warning is connected to the download error.

**Comment by garyb** [comment]
Sure 👍 just thought I'd give another datapoint on that warning in case it turns out to be a red herring in the search for the cause.

**Comment by drostron** [comment]
New minimal steps required to arrive at a failed download from a fresh metastore against Quasar
1. Create a module  
1. Attempt to download module and notice download failure  

I wonder if this worked at some point or if we just missed it when adding modules.

**Comment by garyb** [comment]
Being unable to download modules is a different known problem I think :wink:. #2741 

The workspace Becky created on the front end to originally replicate this shouldn't have had a module in it, only a view. Right @beckyconning?

**Comment by drostron** [comment]
@garyb Thanks for yet another reference 😉. And yes, it appears modules just haven't been included in download support yet.

I've been unable to replicate this issue unless modules are involved.

**Comment by zeeiyerWork** [comment]
Yeah @jedesah is on #2741  - we need that if workspaces that reference modules are to be downloadable.

This one was created since @beckyconning opines that even if modules are not involved, we could have problems downloading workspaces if the metastore somehow gets into a weird state. But @drostron is opining that this is not reproducible unless modules are involved even when using quasar-metastore-broken.db - correct? If so, we should mark this as a duplicate of #2741, unless @beckyconning has evidence to the contrary?

**Comment by drostron** [comment]
Correct, I'm unable to trigger a download failure unless modules are involved using `quasar-metastore-broken.db` (where it isn't broken) and the associated mimir mount contents.

**Comment by zeeiyerWork** [comment]
@beckyconning - plz advise - should we close this out?

**Comment by beckyconning** [comment]
This is still an issue even where modules are not involved. We reproduced this on Dave's machine via my metastore. How to get into this state is still unknown however I have reached this state three times now.

**Comment by beckyconning** [comment]
To be clear: downloading views is broken when the metastore reaches this state.

**Comment by beckyconning** [comment]
Downloading views is how the download card works.

**Comment by drostron** [comment]
From what I recall, the views involve a module in some fashion and therefore fail. I'll double check against @beckyconning's env. If this is indeed the case the metastore is in a fine state, we just don't handle serialization of modules yet per #2741.

**Comment by beckyconning** [comment]
This is not what I am experiencing.

**Comment by beckyconning** [comment]
I am unable to download views which only reference a non-module resource when my metastore gets into this state.

**Comment by zeeiyerWork** [comment]
@drostron - perhaps pair with @beckyconning asap -> since if it is an issue, it needs to be fixed (assuming its not an extremely rare edge-case). If not, its distracting from other "skulled" issues. Just reiterating what you are already perhaps doing. Thanks.

**Comment by beckyconning** [comment]
This may be related to issues with permissions where whether accessing a file requires Mount access type depends on unspecified implementation details.

**Comment by beckyconning** [comment]
This is a frontend issue, will raise the associated issue and link it here in the morning.
