### ISSUE TITLE
Add join tests for Mongo using the QScript DSL

### ISSUE THREAD

**Issue by jsantos17** [quasar-analytics/quasar#3015]
The largest amount of disabled tests for #2667 is related to join planning. There is some rather straightforward QScript that still results in unnecessarily complex physical plans, which makes me believe we have Mongo-specific issues planning joins. For example, consider the simple join in this query:

```sql
select zips2.city from zips join zips2 on zips.`_id` = zips2.`_id`
```

The QScript for the query:

```
EquiJoin
├─ Unreferenced
├─ Filter
│  ├─ ShiftedRead(/jps/zips, IncludeId)
│  ╰─ Guard
│     ├─ ProjectIndex
│     │  ├─ ○
│     │  ╰─ Constant(Int(1))
│     ├─ Type(Obj(Map[], Some(Top)))
│     ├─ Constant(Bool(true))
│     ╰─ Constant(Bool(false))
├─ Filter
│  ├─ ShiftedRead(/jps/zips2, IncludeId)
│  ╰─ Guard
│     ├─ ProjectIndex
│     │  ├─ ○
│     │  ╰─ Constant(Int(1))
│     ├─ Type(Obj(Map[], Some(Top)))
│     ├─ Constant(Bool(true))
│     ╰─ Constant(Bool(false))
├─ List
│  ╰─ tuple
│     ├─ ProjectKey
│     │  ├─ ProjectIndex
│     │  │  ├─ ○
│     │  │  ╰─ Constant(Int(1))
│     │  ╰─ Constant(Str(_id))
│     ╰─ ProjectKey
│        ├─ ProjectIndex
│        │  ├─ ○
│        │  ╰─ Constant(Int(1))
│        ╰─ Constant(Str(_id))
├─ Inner
╰─ ProjectKey
   ├─ ProjectIndex
   │  ├─ RightSide
   │  ╰─ Constant(Int(1))
   ╰─ Constant(Str(city))
```

I don't see any way we can simplify this QScript further, but new Mongo's plan still needs mapReduce, unlike old Mongo's plan that can plan this entirely in aggregation. This is related to #2878

**Comment by zeeiyerWork** [comment]
@jsantos17, @rintcius -> I take it the plan of action is to re-enable these after #2878 gets merged to see if these still result in a MR (instead of Aggregation)?

**Comment by rintcius** [comment]
@zeeiyerWork Plan is to start using QScript DSL (that @edmundnoble implemented recently) for mongo planner tests instead of `sql^2`. In this way the planner tests become more like unit tests (right now they are more like integration tests)

**Comment by rintcius** [comment]
@jsantos17 - @wemrysi noted that the QScript can be simplified using `ExcludeId` instead of `IncludeId`. In this way all these nodes

```
   ├─ ProjectIndex
   │  ├─ <something>
   │  ╰─ Constant(Int(1))
```

will just be `<something>`, so it's actual a nice use-case for QScript based planner test

**Comment by alissapajer** [comment]
As a side note, we have a plan for `QSU` so that `LeftShift` and `Reduce` will not reify extra information in their `repair`s, and `LeftShift` will always have the correct identity flag.

Connectors should still be able to handle the case when unnecessary identity information is requested of them, but the number of these cases will be drastically reduced. The only time they _could_ arise is in a post-`QSU` rewrite, though I'm not sure such a rewrite is possible.
