### ISSUE TITLE
Selectively apply mongo's mapBeforeSort

### ISSUE THREAD

**Issue by rintcius** [quasar-analytics/quasar#3029]
The `mapBeforeSort` rewrite was added because a `map` on map-reduce that happens after a `sort`, unsorts the results. However, currently `mapBeforeSort` is _also_ applied when a query can be executed completely on agg.pipeline, so in these cases it is not necessary to apply this rewrite. In fact doing this rewrite unnecessarily often is the root-cause that the query needs to run on map-reduce instead of agg, so we should only apply this rewrite when it is necessary.

Part of #2884

**Comment by jsantos17** [comment]
Might be useful: we should avoid applying this when a `Map`'s `FreeMap` matches the `StaticMap` extractor. Those `Map`s can be planned in aggregation [as shown here](https://github.com/quasar-analytics/quasar/blob/master/mongodb/src/main/scala/quasar/physical/mongodb/MongoDbPlanner.scala#L1183). There are same other conditions necessary for it to be plannable in aggregation, but it's a codepath worth exploring.
