### ISSUE TITLE
MongoDB JOIN fails if you use OID() function if the field is missing

### ISSUE THREAD

**Issue by dugdun** [quasar-analytics/quasar#3052]
Tested in Quasar 26.0.5.

While the issues around `OID()` were fixed in #2969, a new bug has surfaced using the `OID()` function as part of a `JOIN` statement.

When you do this you will get an error as follows:

```
Failed to execute SQL^2 query.: MongoDB Error: Command failed with error 10448: 'Error: invalid object id: length : @:8:78 @:4:1 ' on server calibermind-sb-shard-00-00-aweli.mongodb.net:27017. The full response is { "ok" : 0.0, "errmsg" : "Error: invalid object id: length :\n@:8:78\n@:4:1\n", "code" : 10448, "codeName" : "Location10448" }
```

**Steps to reproduce**:

Run the following `insert`s in the MongoDB shell in the `test` database:

```
db.oidtestparent.insert({"_id": ObjectId("5a035d84a1180dcd84162e72"), "a": 1})
db.oidtestchild.insert({"parentid": "5a035d84a1180dcd84162e72", "b": 2})
db.oidtestchild.insert({"b": 3})
```
Run the following command in the Quasar REPL:

```
select * from `/mongodb-3.4/test/oidtestparent` as p inner join `/mongodb-3.4/test/oidtestchild` as c on p.`_id` = oid(c.parentid)
```

Doing this you will get the same error mentioned above.

**NOTE**: Running the following in the REPL works without error:

```
select oid(parent) from `/mongodb-3.4/test/oidtestchild`
```

so it seems that there might be missing checks during the `JOIN` phase that are present if you're using the `OID()` function call to just project out the field.

**Comment by jsantos17** [comment]
This looks like a bug in the selector phase of the Mongo connector. The typechecks from the join key (i.e the typecheck that checks if `c.parentId` is actually a string) is moved to the `Read` of `RightSide` in the join as a `Filter`. Then the selector phase of the connector attempts to extract the `Guard` on `Str` but somehow fails and returns a `{ $literal: true }`, which is obviously incorrect.

This is the problematic code in the physical plan:

```
├─ $ReadF(jps; zips)
├─ $ProjectF
│  ├─ Name("0" -> { "$literal": true }) <---
│  ├─ Name("1" -> { "$literal": true }) <---
│  ├─ Name("src" -> ["$_id", "$$ROOT"])
│  ╰─ ExcludeId
├─ $MatchF
│  ╰─ And
│     ├─ Doc
│     │  ╰─ Expr($0 -> Eq(Bool(true)))
│     ╰─ Doc
│        ╰─ Expr($1 -> Eq(Bool(true)))
├─ $SimpleMapF
│  ├─ Map
│  │  ╰─ Obj
│  │     ├─ Key(0: new ObjectId(_.src[1].act.organizationId))
│  │     ╰─ Key(content: _.src)
│  ╰─ Scope(Map())
```

The QScript that generates the filter is correct, but we're not extracting the `Guard`s correctly.

<details><summary>QScript</summary>
```
And
├─ Guard
│  ├─ ProjectKey
│  │  ├─ ProjectKey
│  │  │  ├─ ProjectIndex
│  │  │  │  ├─ ○
│  │  │  │  ╰─ Constant(Int(1))
│  │  │  ╰─ Constant(Str(act))
│  │  ╰─ Constant(Str(organizationId))
│  ├─ Type(Str)
│  ├─ Constant(Bool(true))
│  ╰─ Constant(Bool(false))
╰─ Guard
   ├─ ProjectKey
   │  ├─ ProjectIndex
   │  │  ├─ ○
   │  │  ╰─ Constant(Int(1))
   │  ╰─ Constant(Str(act))
   ├─ Type(Obj(Map[], Some(Top)))
   ├─ Constant(Bool(true))
   ╰─ Constant(Bool(false))
```
</details>

**Comment by jsantos17** [comment]
Skulling as this is a correctness problem.

**Comment by jsantos17** [comment]
It's worth noting that this doesn't plan correctly in old Mongo either. It results in an error when it attempts to create the `ObjectId`. Similar to what happens in new Mongo. Anyway, the query is fixed in my branch. Here's the error from old Mongo:

```
Quasar error: Plan execution failed: MongoDB Error: Command failed with error 10448: 'Error: invalid object id: length :
_funcs1/<@:4:71
_funcs1@:4:1
' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Error: invalid object id: length :\n_funcs1/<@:4:71\n_funcs1@:4:1\n", "code" : 10448, "codeName" : "Location10448" }, cause=Some(Command failed with error 10448: 'Error: invalid object id: length :
_funcs1/<@:4:71
_funcs1@:4:1
' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "Error: invalid object id: length :\n_funcs1/<@:4:71\n_funcs1@:4:1\n", "code" : 10448, "codeName" : "Location10448" })
```
