### ISSUE TITLE
Track down likely invalid qscript

### ISSUE THREAD

**Issue by djspiewak** [quasar-analytics/quasar#3089]
There are signs that the qscript we generate, under certain circumstances, may be broken.  When testing with mimir, we saw:

- [ ] `MatchError`
- [ ] `AssertionError`
- [ ] A bunch of timeouts indicative of broken plans

Traces can be seen [here](https://gist.github.com/djspiewak/62aa3d49d8cd31b7d2f959e9c3e504df).  Each query should be examined to see what kind of qscript (educated) is being generated and why it is that mimir is barfing on it.  We can't actually rule out bugs in mimir, but it's more probable for the moment that these are bugs in qsu.

**Comment by djspiewak** [comment]
Timeouts and assertion errors are gone now.  Though there are a couple interesting test *failures*, where we produced incorrect results: https://gist.github.com/b9f54dd8b9b7db692d88f8deba70a62a

**Comment by edmundnoble** [comment]
Checked, these issues will all be fixed by #3112 and #3079; they're caused by some stray `IncludeId`'s, there's extra map keys and array indices all over the results of every flatten.

**Comment by djspiewak** [comment]
Closing this, since the thought process which led to the query initially is now addressed.
