### ISSUE TITLE
Adjacent LeftShift collapse

### ISSUE THREAD

**Issue by djspiewak** [quasar-analytics/quasar#3092]
Subsumes part of #2998 

Look for a join on two `LeftShift` nodes with a common source.  Put them together one-above-the-other (which one doesn't matter), ensuring that original value access works.  This will fix the issue in #2935 and likely also #2366

Obviously this will be implemented as a rewrite on the graph, probably after `ReifyProvenance`.

**Comment by alissapajer** [comment]
This should also fix https://github.com/quasar-analytics/quasar/issues/2540
