### ISSUE TITLE
Extension header not being respected on backport

### ISSUE THREAD

**Issue by beckyconning** [quasar-analytics/quasar#3140]
The file is downloaded with no extension in its name.

`http://localhost:63176/data/fs//test-mount/testDb/smallZips?request-headers=%7B%22Accept-Encoding%22%3A%22gzip%22%2C%22Accept%22%3A%22text%2Fcsv%3BcolumnDelimiter%3D%2C%3BrowDelimiter%3D%5C%5Cn%3BquoteChar%3D%5C%22%3BescapeChar%3D%5C%22%3Bdisposition%3D%5C%22attachment%3B%20filename*%3DUTF-8%27%27smallZips.csv%5C%22%22%7D`

downloads

`smallZips`

**Comment by nicflores** [comment]
I just tested the csv download issue on:
```
{"name":"SlamData-Server","version":"0.11.9","components":[{"name":"Quasar","version":"20.14.18"}]}
```
and it works, these are the backport versions for 4.2.7 release

**Comment by zeeiyerWork** [comment]
@nicflores and @beckyconning - perhaps pair program Monday am to see if there is really an issue or not. Too many issues are ping-ponging across teams, hence the suggestion. thanks.

**Comment by beckyconning** [comment]
i was on 0.11.8 so that might be the issue. will try again on 0.11.9 when there is time. thanks.

**Comment by zeeiyerWork** [comment]
Closing this since this does not seem to be an issue anymore.
