### ISSUE TITLE
Valid predicate gets planned into something that nulls out the query

### ISSUE THREAD

**Issue by djspiewak** [quasar-analytics/quasar#3153]
https://gist.github.com/53c9d59881e7e7f50c0da7e1f9fa2725

On the `qsu` branch.

Not clear to me what's happening here.  The `"CA" = b.state` predicate is what causes the results to be empty.  If I remove it, we get a real result set, and the result set *includes* a `state` value of `CA`.  So the predicate is valid.  The QScript looks fine to me, and this test works on other connectors.

**Comment by djspiewak** [comment]
I'm guessing this is related? https://gist.github.com/9da8ec92c145be82cbd4c06641d1e1bc

**Comment by zeeiyerWork** [comment]
reassigning to @rintcius since it could be related to #3048. So @rintcius please re-evaluate this after the PR for that lands...

**Comment by rintcius** [comment]
Both queries are working as expected now. Also note that these queries are ITs (`selfJoinConstantOnLeft` and `selfJoinWithComplexCondition`) and not excluding mongo.
