### ISSUE TITLE
group by simple expression gives IndexOutOfBoundsException

### ISSUE THREAD

**Issue by rintcius** [quasar-analytics/quasar#3171]
This query from `PlannerSpec` gives an `IndexOutOfBoundsException`:

`select city, sum(pop) from extraSmallZips group by lower(city)`

```
 +    // [error]     java.lang.IndexOutOfBoundsException: 1
 +    // [error]     	at scala.collection.LinearSeqOptimized$class.apply(LinearSeqOptimized.scala:65)
 +    // [error]     	at scala.collection.immutable.List.apply(List.scala:84)
 +    // [error]     	at scala.collection.immutable.List.apply(List.scala:84)
 +    // [error]     	at scalaz.$bslash$div.fold(Either.scala:57)
 +    // [error]     	at quasar.qscript.analysis.OutlineInstances$$anon$3.quasar$qscript$analysis$OutlineInstances$$anon$3$$$anonfun$24(Outline.scala:263)
```

**Comment by djspiewak** [comment]
Couldn't reproduce this on current master.  Can you reconfirm?

**Comment by rintcius** [comment]
Hmm weird, still there for me, both in IT and from the REPL

After removing the pending from the associated IT (`groupBySimpleExpression.test`):

```
[error] ! group by simple expression [./groupBySimpleExpression.test] (849 ms)
[error]  java.lang.IndexOutOfBoundsException: 1 (Outline.scala:263)
[error] quasar.qscript.analysis.OutlineInstances$$anon$3.quasar$qscript$analysis$OutlineInstances$$anon$3$$$anonfun$24(Outline.scala:263)
[error] matryoshka.patterns.package$.matryoshka$patterns$package$$$anonfun$5(package.scala:59)
[error] matryoshka.patterns.package$lambda$$ginterpretM$1.apply(package.scala:59)
[error] matryoshka.patterns.package$lambda$$ginterpretM$1.apply(package.scala:59)
[error] matryoshka.package$.hylo(package.scala:225)
[error] matryoshka.package$.matryoshka$package$$$anonfun$17(package.scala:225)
[error] matryoshka.package$lambda$$hylo$1.apply(package.scala:225)
[error] quasar.qscript.MapFuncCore$$anon$1.traverseImpl(MapFuncCore.scala:479)
[error] quasar.qscript.MapFuncCore$$anon$1.traverseImpl(MapFuncCore.scala:405)
[error] quasar.qscript.MapFuncCore$$anon$1.map(MapFuncCore.scala:405)
```

REPL:

```
(v26.1.7) 💪 $ select city, sum(pop) from extraSmallZips group by lower(city)
(v26.1.7) 💪 $ [error] (AeshProcess: 2) java.lang.RuntimeException: 1
java.lang.RuntimeException: 1
	at quasar.effect.Failure$.quasar$effect$Failure$$$anonfun$16(Failure.scala:104)
	at quasar.effect.Failure$$anon$5.apply(Failure.scala:94)
	at quasar.effect.Failure$$anon$5.apply(Failure.scala:94)
	at scalaz.NaturalTransformation$$anon$1.apply(NaturalTransformation.scala:19)
	at scalaz.NaturalTransformations$$anonfun$natToFunction$1.apply(NaturalTransformation.scala:41)
	at scalaz.$bslash$div.fold(Either.scala:57)
	at quasar.fp.free.package$EnrichNT$$anon$2.apply(package.scala:26)
	at quasar.fp.free.package$EnrichNT$$anon$2.apply(package.scala:26)
	at scalaz.NaturalTransformations$$anonfun$natToFunction$1.apply(NaturalTransformation.scala:41)
	at scalaz.$bslash$div.fold(Either.scala:58)
	at quasar.fp.free.package$EnrichNT$$anon$2.apply(package.scala:26)
	at quasar.fp.free.package$EnrichNT$$anon$2.apply(package.scala:26)
	at scalaz.NaturalTransformations$$anonfun$natToFunction$1.apply(NaturalTransformation.scala:41)
	at scalaz.$bslash$div.fold(Either.scala:58)
```

**Comment by djspiewak** [comment]
@rintcius Looks like this only happens with mongodb.  I was testing with mimir.  I'm guessing mongodb does some sort of qscript rewrite which assumes a certain form that we're no longer generating?

**Comment by rintcius** [comment]
@djspiewak Ah, yes very well possible. I'll label it as a mongo issue

**Comment by rintcius** [comment]
The query executes fine now (using some PRs that are not in `master` yet), but the results are different from old mongo.

Demonstration with an extra where-clause to limit the number of results: `select city, sum(pop) from extraSmallZips where city like "S%"  group by lower(city)`

limited dataset (`select city, pop from extraSmallZips where city like "S%"`):

```
 city          | pop    |
---------------|--------|
 SOUTHAMPTON   |   4478 |
 SOUTH HADLEY  |  16699 |
 SPRINGFIELD   |   2323 |
 SPRINGFIELD   |  22115 |
 SPRINGFIELD   |  14970 |
 SPRINGFIELD   |  12739 |
 SOUTHFIELD    |    622 |
```

results new mongo:
```
 1        | city          |
----------|---------------|
  16699.0 | SOUTH HADLEY  |
    622.0 | SOUTHFIELD    |
  52147.0 | SPRINGFIELD   |
  52147.0 | SPRINGFIELD   |
  52147.0 | SPRINGFIELD   |
  52147.0 | SPRINGFIELD   |
   4478.0 | SOUTHAMPTON   |
```

results old mongo:
```
  city          | 1        |
---------------|----------|
 SOUTHAMPTON   |  16699.0 |
 SOUTH HADLEY  |  16699.0 |
 SPRINGFIELD   |  16699.0 |
 SPRINGFIELD   |  16699.0 |
 SPRINGFIELD   |  16699.0 |
 SPRINGFIELD   |  16699.0 |
 SOUTHFIELD    |  16699.0 |
 SOUTHAMPTON   |    622.0 |
 SOUTH HADLEY  |    622.0 |
 SPRINGFIELD   |    622.0 |
 SPRINGFIELD   |    622.0 |
 SPRINGFIELD   |    622.0 |
 SPRINGFIELD   |    622.0 |
 SOUTHFIELD    |    622.0 |
 SOUTHAMPTON   |  52147.0 |
 SOUTH HADLEY  |  52147.0 |
 SPRINGFIELD   |  52147.0 |
 SPRINGFIELD   |  52147.0 |
 SPRINGFIELD   |  52147.0 |
 SPRINGFIELD   |  52147.0 |
 SOUTHFIELD    |  52147.0 |
 SOUTHAMPTON   |   4478.0 |
 SOUTH HADLEY  |   4478.0 |
 SPRINGFIELD   |   4478.0 |
 SPRINGFIELD   |   4478.0 |
 SPRINGFIELD   |   4478.0 |
 SPRINGFIELD   |   4478.0 |
 SOUTHFIELD    |   4478.0 |
```

I'm tempted to say new mongo is correct, but not sure. @jdegoes can you confirm the result in new mongo is correct?

Note that both old and new mongo give the expected result for `select upper(lower(city)), sum(pop) from extraSmallZips where city like "S%"  group by lower(city)`:

```
 0             | 1      |
---------------|--------|
 SOUTH HADLEY  |  16699 |
 SOUTHFIELD    |    622 |
 SPRINGFIELD   |  52147 |
 SOUTHAMPTON   |   4478 |
```

**Comment by wemrysi** [comment]
@rintcius new mongo is correct as the `city` field isn't reduced, but it is still grouped by `lower(city)` so we'd expect it to join only with the results of the grouping bucket it falls into whereas old mongo was doing a full cartesian.

**Comment by jsantos17** [comment]
Do we know what was the partial function leading to the runtime exceptions? Seems like something we might want to handle explicitly so we can provide a better error message.

**Comment by jdegoes** [comment]
Please, no partial functions! 😉

**Comment by djspiewak** [comment]
There are some places where it can’t be avoided, which is a shame but true. Qscript has an obvious one in the Reduce node (the repair references ReduceIndex, which uses integer offsets into the reducer set). QSU is full of partial function calls that we strongly believe are total (barring bugs) due to the graph encoding.

Technically, any implementor of qscript is implementing a partial function in a sense, with the alternate case being Undefined.

Obviously we want to keep this sort of thing to a minimum, but sometimes it is necessary.

**Comment by jdegoes** [comment]
It's never *necessary* to use partial functions, since you can lift any partial function into a type signature that actually reflects its capacity to fail for some inputs. It's very often *convenient* to use partial functions, i.e. requires less work plumbing types.

> QSU is full of partial function calls that we strongly believe are total (barring bugs) due to the graph encoding.

I've heard this before, too many times to count. *"I know that call to `Option.get` is safe, so I'll call it."* Only (a) we make lots of mistakes, even when we're sure of things, and (b) code changes so invariants that hold at one time fail to hold at later times.

That said we've got bigger problems to worry about right now. *Triage*.

**Comment by djspiewak** [comment]
> It's never necessary to use partial functions, 

Gödel says otherwise. :-)

In a lot of these cases, yes, we can make things total by adding a ton of boilerplate. It isn’t universally true though in the mathematical sense.

**Comment by jdegoes** [comment]
It's *never* necessary to use a function that throws errors for some inputs; it's never even necessary to use a function that *might run forever* for some inputs, since you can model anything in a total language using, e.g., the partiality monad.

Threading, e.g., `Option` or `Either` through your program is _not_ boilerplate IMO. It's accurately modeling what you can prove to the compiler. 

If we ever have a runtime exception in our code, we're doing something _very wrong_.

**Comment by djspiewak** [comment]
> It's never necessary to use a function that throws errors for some inputs; it's never even necessary to use a function that might run forever for some inputs, since you can model anything in a total language using, e.g., the partiality monad.

Still nope.  The partiality monad doesn't solve the problem, it just allows you to choose incompleteness over inconsistency.  As an example, if you wish to write an Agda interpreter in Agda, you will need to use an unsafe function at some point to allow your partiality monad to run for an unbounded number of steps.  Where by "unbounded" I do not mean "infinite", I simply mean "cannot be fixed to a definite finite bound."  Total languages are still limited.  Certainly vastly less limited than most people think, but the maths is very clear here; there is a proof, there is no debate.

> Threading, e.g., Option or Either through your program is not boilerplate IMO. It's accurately modeling what you can prove to the compiler.

Yes, and as with all proofs, the cost/benefit ratio has to be considered.  In this case, it would be proving the absence of a certain class of errors that is already, practically-speaking, absent.  And the cost in terms of boilerplate would be extremely high.

Now, a different graph encoding which constructively avoids these cases (or some subset of them) would almost certainly be worthwhile under a cost/benefit analysis.  Threading `Option` is not.

**Comment by jdegoes** [comment]
> The partiality monad doesn't solve the problem, it just allows you to choose incompleteness over inconsistency.

Partiality monad pushes the problem out of your program and into the external interpreter. Which is an illustration that, if nothing else, all partiality (as well as all "effects") can be pushed to the edge of the world.

> In this case, it would be proving the absence of a certain class of errors that is already, practically-speaking, absent.

Except they're not absent. We blew up with one. And we'll hit these other supposedly impossible to hit cases. And then maybe we can discuss removing them from the code? 😉

**Comment by djspiewak** [comment]
> Except they're not absent. We blew up with one.

Not actually the sorts of errors I was thinking of.  :-)  The `QSUGraph` partiality has bitten us like, exactly once.  The index out of bounds here is almost certainly the mongo backend rewriting away a reduce (or something like that) and failing to realize that it is still being referenced by a `repair`.  That is fixable by using an `HList` rather than a `List` of reducers, and then a `Nat` instead of an `Int` in the repair, along with a bunch of reified evidence that things align.  It's doable, but would be absurdly difficult.

This is kind of what I mean by qscript being a giant partial function.  At the end of the day, it's an instruction set.  It's pretty well typed, but it's hard to go all the way there, and there's limited value in the last mile.

**Comment by rintcius** [comment]
There was a non-existent index in qscript, which blew up when the mongo specific transformation `PreferProjections` tried to rewrite it. This got solved in one of the recent qscript PRs.

**Comment by djspiewak** [comment]
@rintcius Can you re-test this against master?  I ran it in the repl against mongo 3.4 and got real results.  The qscript looks alright as well:

```
Subset(Take)
├─ Unreferenced
├─ From
│  ╰─ EquiJoin
│     ├─ ShiftedRead(/t/extraSmallZips, ExcludeId)
│     ├─ Filter
│     │  ├─ Map
│     │  │  ├─ ○
│     │  │  ╰─ MakeMap
│     │  │     ├─ Constant(Str(city))
│     │  │     ╰─ Guard
│     │  │        ├─ ○
│     │  │        ├─ Type(Obj(Map[], Some(Top)))
│     │  │        ├─ ProjectKey
│     │  │        │  ├─ ○
│     │  │        │  ╰─ Constant(Str(city))
│     │  │        ╰─ Undefined
│     │  ╰─ Guard
│     │     ├─ ProjectKey
│     │     │  ├─ ○
│     │     │  ╰─ Constant(Str(city))
│     │     ├─ Type(Str)
│     │     ├─ Constant(Bool(true))
│     │     ╰─ Constant(Bool(false))
│     ├─ Reduce
│     │  ├─ ○
│     │  ├─ Bucket
│     │  │  ╰─ List
│     │  │     ╰─ Guard
│     │  │        ├─ Guard
│     │  │        │  ├─ ○
│     │  │        │  ├─ Type(Obj(Map[], Some(Top)))
│     │  │        │  ├─ ProjectKey
│     │  │        │  │  ├─ ○
│     │  │        │  │  ╰─ Constant(Str(city))
│     │  │        │  ╰─ Undefined
│     │  │        ├─ Type(Str)
│     │  │        ├─ Guard
│     │  │        │  ├─ ○
│     │  │        │  ├─ Type(Obj(Map[], Some(Top)))
│     │  │        │  ├─ Lower
│     │  │        │  │  ╰─ ProjectKey
│     │  │        │  │     ├─ ○
│     │  │        │  │     ╰─ Constant(Str(city))
│     │  │        │  ╰─ Undefined
│     │  │        ╰─ Undefined
│     │  ├─ Reducers
│     │  │  ╰─ Sum
│     │  │     ╰─ Guard
│     │  │        ├─ Guard
│     │  │        │  ├─ ○
│     │  │        │  ├─ Type(Obj(Map[], Some(Top)))
│     │  │        │  ├─ ProjectKey
│     │  │        │  │  ├─ ○
│     │  │        │  │  ╰─ Constant(Str(pop))
│     │  │        │  ╰─ Undefined
│     │  │        ├─ Type(Int, Dec, or Interval)
│     │  │        ├─ Guard
│     │  │        │  ├─ ○
│     │  │        │  ├─ Type(Obj(Map[], Some(Top)))
│     │  │        │  ├─ ProjectKey
│     │  │        │  │  ├─ ○
│     │  │        │  │  ╰─ Constant(Str(pop))
│     │  │        │  ╰─ Undefined
│     │  │        ╰─ Undefined
│     │  ╰─ Repair
│     │     ╰─ ConcatMaps
│     │        ├─ MakeMap
│     │        │  ├─ Constant(Str(identities))
│     │        │  ╰─ MakeMap
│     │        │     ├─ Constant(Str(qsu17_0))
│     │        │     ╰─ ReduceIndex(-\/(0))
│     │        ╰─ MakeMap
│     │           ├─ Constant(Str(value))
│     │           ╰─ MakeMap
│     │              ├─ Constant(Str(1))
│     │              ╰─ ReduceIndex(\/-(0))
│     ├─ List
│     │  ╰─ tuple
│     │     ├─ Lower
│     │     │  ╰─ ProjectKey
│     │     │     ├─ ○
│     │     │     ╰─ Constant(Str(city))
│     │     ╰─ ProjectKey
│     │        ├─ ProjectKey
│     │        │  ├─ ○
│     │        │  ╰─ Constant(Str(identities))
│     │        ╰─ Constant(Str(qsu17_0))
│     ├─ Inner
│     ╰─ ConcatMaps
│        ├─ LeftSide
│        ╰─ ProjectKey
│           ├─ RightSide
│           ╰─ Constant(Str(value))
╰─ Count
   ╰─ Map
      ├─ Unreferenced
      ╰─ Constant(Int(11))
```

**Comment by rintcius** [comment]
@djspiewak yes, just created a PR for that  #3219 :)
