### ISSUE TITLE
expression with grouping gives an implementation is missing

### ISSUE THREAD

**Issue by rintcius** [quasar-analytics/quasar#3172]
Test in `PlannerSpec`:

`select case when pop > 1000 then city else lower(city) end, count(*) from zips group by city` fails with: an implementation is missing (ReifyIdentities.scala:358)

**Comment by wemrysi** [comment]
This is likely due to #3114 which is needed to finish up the last case in `ReifyIdentities`.

**Comment by djspiewak** [comment]
It is most definitely #3114.  I'm going to close this one out as a duplicate.
