### ISSUE TITLE
ReifyBuckets can produce duplicates

### ISSUE THREAD

**Issue by wemrysi** [quasar-analytics/quasar#3186]
When the same `Value` provenance appears multiple times in the dimensions of the source to a reduce vertex, it results in duplicate buckets in the reduce. The duplicates should be elided.

**Comment by zeeiyerWork** [comment]
@wemrysi -> Does this need to be skulled or is it more of an optimization that we can wait on.

**Comment by wemrysi** [comment]
It _shouldn't_ affect correctness and so probably isn't blocking 5.0, but it needs to get fixed asap. It may have adverse affects for some connectors, depending on how they handle grouping.

**Comment by zeeiyerWork** [comment]
since @djspiewak mentions he is blocked by this and skulled it, added to 5.0.0 project, november milestone.
