### ISSUE TITLE
Demo integration tests

### ISSUE THREAD

**Issue by rabbitonweb** [quasar-analytics/quasar#3211]
Move work from #3166 to integration tests

**Comment by rabbitonweb** [comment]
Not done yet

**Comment by djspiewak** [comment]
@rabbitonweb It's because you used the phrase "partially resolves" in the PR description, so github auto-closed it.

**Comment by rabbitonweb** [comment]
@djspiewak yeah, i know, i just put comment so we know why i'm opening it
