### ISSUE TITLE
`flattenGroupedObject.test` failing for all connectors

### ISSUE THREAD

**Issue by alissapajer** [quasar-analytics/quasar#3252]
```sql
select distinct commit{*}, count(*) from slamengine_commits where commit{*} like "http%" group by committer.login
```

Needs investigation into why it's failing. As it's failing for all connectors, it's probably a qscript bug.

**Comment by djspiewak** [comment]
Hmm, this actually seems like a relatively complicated query due to the grouped map flatten within the autojoin.

**Comment by djspiewak** [comment]
@wemrysi Looks like this is hitting the `Both` case, at the very least.

**Comment by wemrysi** [comment]
@djspiewak Nice, I've been looking for a good example for that.
