### ISSUE TITLE
Audit integration tests for 5.0

### ISSUE THREAD

**Issue by alissapajer** [quasar-analytics/quasar#3253]
We need to audit all the integration tests before we can release 5.0.

Any integration test that is failing for all (or nearly all) connectors should have an individual issue opened and 💀'd. This is likely a qscript bug.

Any integration test that is failing for a small set of connectors should have an individual issue per connector (assuming the qscript is correct). These should be provisionally 💀'd until we determine the importance of that query to run on that connector for 5.0.

**Comment by alissapajer** [comment]
@djspiewak while you're doing this, we also have the option of closing out the "make all the integration tests work" issues we have open for individual connectors. At this point most tests are working for most connectors, so I think having individual issues makes sense in lieu of the giant issues. 

These are somewhat out of date anyways:
ML: https://github.com/quasar-analytics/quasar/issues/1948
CB: https://github.com/quasar-analytics/quasar/issues/1607
mimir: https://github.com/quasar-analytics/quasar/issues/2542
mongo: https://github.com/quasar-analytics/quasar/issues/2532

I couldn't find one for spark.

**Comment by alissapajer** [comment]
As a side note, I do think it's useful to be able ask and immediately answer the question: "Which integration tests / demo environments are not working for connector X?". But this isn't something that should ever be maintained manually; we'd have a dashboard or something for this that updates automatically each time we release quasar.

**Comment by wemrysi** [comment]
If we had slamdata running somewhere and a current copy of the `quasar` source tree, we could dogfood a dashboard for this.

**Comment by djspiewak** [comment]
I audited everything… And then accidentally deleted all the work right before a backup cycle.  So we get the roughly-reconstructed version of the ones that are actually relevant:

- **tests/subqueryGroupBy.test**
  + bizarre `distinct` recognition thing, I think
- **tests/groupByFlatten.test**
  + ❌ `[ReifyBuckets] Expected to find a mappable region in 'qsu23 based on one of NonEmpty['extract34]`
- **tests/flattenOrElseField.test**
  + ❌ The `flattenable` dataset is just missing; I think @rintcius forgot to add it
- **tests/unsupportedTests.test**
  + This one is concerning. No idea why it's not working on mimir and mongo
+ - **tests/multitypeFlatten.test**
  + Hits the `Both` case
  + Several others in this category
