### ISSUE TITLE
flattenable dataset is missing

### ISSUE THREAD

**Issue by djspiewak** [quasar-analytics/quasar#3273]
I think someone forgot a `git add`.  :-D

**Comment by alissapajer** [comment]
That should give `tests/flattenOrElseField.test` at least a chance to pass :) If it doesn't pass, we should open a new issue for it specifically.

**Comment by alissapajer** [comment]
@djspiewak that data is here https://github.com/quasar-analytics/quasar/blob/master/it/src/main/resources/tests/flattenable.data. Closing this issue.

**Comment by alissapajer** [comment]
Tracking the actual failing test in https://github.com/quasar-analytics/quasar/issues/3277
