### ISSUE TITLE
`tests/flattenOrElseField.test` is failing for all connectors

### ISSUE THREAD

**Issue by alissapajer** [quasar-analytics/quasar#3277]
```sql
select t0.b[*] ?? t0.b from flattenable as t0
```
This is failing for all connectors, probably for qscript or logical plan reasons.

**Comment by djspiewak** [comment]
Just so the history is clear…  It's failing because `flattenable.data` doesn't exist.

**Comment by rintcius** [comment]
@djspiewak  `flattenable.data` **is** there though, see #3249 - can you point me to the travis failures? AFAICS it looks quite green over there

**Comment by djspiewak** [comment]
@rintcius Ah you're correct!  I couldn't find it in my local mimir because I hadn't re-uploaded the test data, and I forgot I had to do that since I *used* to just reupload constantly.

**Comment by djspiewak** [comment]
Re-ran the test.  Took a closer look at the results.  This is an exact duplicate of #2960.
