### ISSUE TITLE
Further improve mongo's AssumeReadType

### ISSUE THREAD

**Issue by rintcius** [quasar-analytics/quasar#3300]
`AssumeReadType` does not recognize all shape preserving constructions yet - see https://github.com/quasar-analytics/quasar/pull/3240#issuecomment-350229794 so there are still guards left that can be elided. Investigate whether this can be improved further.

**Comment by jsantos17** [comment]
Have we considered changing the the type of the LP `Read` node in a per connector basis? Maybe whoever is working on this can use a few hours of their day to explore doing it through BackendModule.
