### ISSUE TITLE
mongodb: take advantage of `jsMode` when possible.

### ISSUE THREAD

**Issue by sellout** [quasar-analytics/quasar#341]
Map/reduce is much faster if we use `jsMode`, which means we don’t spend time converting data to BSON, writing it to disk, reading it from disk, and converting it back in between the map and reduce operations. However, it means we can’t have more than 500k unique keys emitted during the map.

We already distinguish between `MapOp` and `FlatMapOp`. If the map operation is a `MapOp`, we can be sure there won’t be more unique keys than the cardinality of the source collection (and we’re going to need to be able to query the cardinality of collections for θJoin support, anyway) so, if that is 
≤500k, we can use `jsMode`. We may be able to further separate `FlatMapOp`s. EG, a `FilterOp` could emit 0 or 1 key, so we could use the same bound as a `MapOp`. We could possibly also add a `maxEmits: Option[Long]` parameter to `FlatMapOp` to use as a hint that the operation never emits more than `maxEmits * cardinality` keys, and then turn on `jsMode` appropriately.

**Comment by jdegoes** [comment]
See discussion on #586
