### ISSUE TITLE
coalesce $simpleMap with Workflow.$match. 

### ISSUE THREAD

**Issue by sellout** [quasar-analytics/quasar#454]
We sometimes end up with a `$simpleMap` followed by a `$match`, and we should be able to coalesce these into a single `$match` with a `$where` (JS) clause.

**Comment by jdegoes** [comment]
> You cannot use $where in $match queries as part of the aggregation pipeline.

**Comment by jdegoes** [comment]
We should probably close this or maybe label it 'futuremongo' or something, because this is not useful right now (see above doc).

**Comment by sellout** [comment]
The description here is a bit unclear. This is about `Workflow.$match`, which can become either a `$match` in `aggregate()` or a `query` in `mapReduce`.

Mostly we want to avoid `$simpleMap; $match; $simpleMap` becoming two mapReduce operations, but even with something like `$simpleMap; $match; $project` it can be better to convert the $simpleMap to a `$where` and have a mapReduce that we use only for its query, because the non-$where conditions may filter out docs before we ever run the JS condition, and so we run the map & reduce functions on fewer cases than if we did `mapReduce; aggregate($match; $project)`.
