### ISSUE TITLE
filter on array projection without JS

### ISSUE THREAD

**Issue by sellout** [quasar-analytics/quasar#455]
Perhaps a special case of #454, array projection is currently broken in Mongo and requires us to use JS. As a result, instead of getting a nice selector like
```scala
$match(Selector.Doc(BsonField.Name("loc") \ BsonField.Index(0) -> Selector.Lt(Bson.Int64(-73))))
```
we end up with
```scala
$simpleMap(value => Obj(ListMap(
  "__tmp7" -> Access(Select(value, "loc").fix, Literal(Js.Num(0, false)).fix).fix,
  "__tmp8" -> value)).fix),
$match(Selector.Doc(BsonField.Name("__tmp7") -> Selector.Lt(Bson.Int64(-73))))
```
fixing #454 would collapse this into a `$where` selector, but we need a better approach to make it a standard selector.

**Comment by sellout** [comment]
Index projection has now been backported to Mongo 2.6 (https://jira.mongodb.org/browse/SERVER-4589 – dunno if a release has gone out). Should we just fix this and forget it was ever broken?

**Comment by jdegoes** [comment]
The backport is not in an official release. If it were in 2.6 official, I'd be tempted to say yes. Anyway, we need to propagate MongoDB / environment state into the planner so it can generate version-specific plans.
