### ISSUE TITLE
integration tests: have multiple expected result sets

### ISSUE THREAD

**Issue by sellout** [quasar-analytics/quasar#575]
(I thought there was already a ticket for this, but I couldn’t find it.)

Rather than the current structure of
```json
    "predicate": "containsAtLeast",
    "expected": […]
```
we should use the predicate name as the key for the expected results, like
```json
    "containsAtLeast": […]
```
This way we can do multiple checks against the same result set:
```json
    "containsAtLeast": […],
    "doesNotContain": […]
```

**Comment by jdegoes** [comment]
Good idea. For tickets like this one, feel free to just grab it anytime if you happen to need / want the functionality. Need a label for these kinds of tickets.
