### ISSUE TITLE
planner: generated JavaScript is overly complex and inefficient with method calls

### ISSUE THREAD

**Issue by mossprescott** [quasar-analytics/quasar#581]
When expressions are nested, such that a method call is embedded within a binary operator expression, the method call is duplicated (in the "defined-ness" check and in the result). The duplication is compounded in larger expressions.

See the translation of `time_of_day` in the planner, and the comment referencing this issue in jscore.scala.

**Comment by jdegoes** [comment]
Maybe we generate with lets, have a pass to inline lets, translate lets into anonymous functions (when producing js), and also have a JS optimizer that can coalesce nested multiple encoded lets into a single anonymous function using vars. i.e. have all these independent pieces we can snap together for different use cases (e.g. where MongoDB allows anonymous functions versus where it does not allow them).

**Comment by mossprescott** [comment]
Yes, that's the idea, along with optimizing away lets that bind trivial expressions. And another issue that comes up is generating unique names for the lets.
