### ISSUE TITLE
mongobd: results don't have the correct types when the mongodb representation is not precise

### ISSUE THREAD

**Issue by mossprescott** [quasar-analytics/quasar#593]
Now that we've clearly defined how all of the SlamEngine types are represented in output (see #255), it's possible to tell when the result of a query comes back with a type that doesn't match you would expect (and indeed, what the type-checker said the projection has).

To fix this, we'll need to either:

1. Keep track of the expected types of the result collection in some kind of schema, or
2. Construct encoded values in the result collection.

Note: you need to be looking at "Precise JSON" output to see these issues, which currently means running an integration test or hacking the REPL or admin UI. See #592.

For example, in this query the result of `length` is typed as `Dec` instead of `Int` because its value is produced by a map-reduce, and all values from JavaScript are `Dec`. `pop` is also affected, because its projection was inlined into the map-reduce:
```
💪 $ select _id as zip, length(city), pop from zips

{ "zip": "80301", "1": { "$dec": 7 }, "pop": { "$dec": 18174 } }
```

Here, `Date` and `Time` values come back as `Timestamp` and `Str`, respectively, because that's how they're represented in MongoDB:
```
💪 $ select date '2015-02-03', time_of_day("date") from days

{ "value": { "0": { "$timestamp": "2015-02-03T00:00:00Z" }, "1": "06:00:00.000" } }
```

**Comment by jdegoes** [comment]
There are `NumberLong` and `NumberInt` constructors that MongoDB exposes, which could be used directly in map/reduce jobs when the type is known.
