### ISSUE TITLE
mongodb: (performance) match should be pushed ahead of map-reduce op if it can't be inlined

### ISSUE THREAD

**Issue by mossprescott** [quasar-analytics/quasar#621]
As a rule, we should always attempt to do filtering *before* map-reduce whenever possible

For example, in `select length(name) from foo where a=b`, the comparison cannot be handled by a simple selector, but could be done with project/match. Instead the planner currently produces this sequence, which inlines the comparison into SimpleMap. The result is an unnecessarily large, slow map-reduce.

```
Chain
├─ $Read(foo)
├─ $SimpleMap
│  ╰─ JsMacro({
│             "0": _.name.length,
│             "__tmp0": _.a === _.b
│           })
├─ $Match
│  ╰─ Selector(Doc)
│     ╰─ Selector(BsonField.Name("__tmp0") -> Eq(Bool(true)))
╰─ $Project
   ├─ Name(0 -> $0)
   ╰─ ExcludeId
```

Oddly, in the similar query `select length(name) from foo where a=1`, the $match op *does* end up before the $simpleMap, and ends up getting inlined into the map-reduce command anyway.

**Comment by sellout** [comment]
The latter case is caught by the try-to-force-SPB-earlier code in `toCollectionBuilder(ShapePreservingBuilder)`, but `deleteUnusedFields` doesn’t yet do anything to clean up `$Simple*Map` ops.

But I think the former case should also be caught by that code. I’ll have to dig in to see why it’s not.

**Comment by sellout** [comment]
Also, I do not like the try-to-force-SPB-earlier code. I think that would be better handled by a `Workflow` optimizer.

**Comment by sellout** [comment]
Ah, we only force SPBs earlier when the input expressions can be inlined into the `$match`, IE, `DocField`s.
