### ISSUE TITLE
repl: import/export commands for JSON 

### ISSUE THREAD

**Issue by mossprescott** [quasar-analytics/quasar#642]
We should add commands to the REPL to load and save data from the local filesystem to any mounted backend and path. Maybe `load` and `save` (except we're already save in the opposite sense), or maybe `import` and `export`.

Now that our JSON format is no longer entirely compatible with MongoDB's *strict* mode, there is no simple way to get data in and out of a MongoDB instance. As a result, our cleanup script (which uses mongoimport) can no longer load the `days.data` dataset.

At some point, the API will support a "ContentType" to extract data in the form of Precise JSON, but anyway I think it makes sense to have a way to get at it from a terminal.

**Comment by jdegoes** [comment]
Let's [steal FTP commands here](http://www.cs.colostate.edu/helpdocs/ftp.html).
