### ISSUE TITLE
mongodb: planner vey slow with DISTINCT and complex ORDER BY

### ISSUE THREAD

**Issue by mossprescott** [quasar-analytics/quasar#656]
The planner takes many seconds to process queries that contain DISTINCT and an ORDER BY clause with more than a few keys. This is just the planning time, before anything is executed.

For example, this one takes around 20s:
```sql
select distinct (count(*)) / (1000) as p0, (pop) / (1000) as p1, 'foo' as p2, max(city) as p3 from zips 
  order by pop ASC, city DESC, length(city) ASC, city ASC, city DESC, lower(city) DESC, pop DESC
```

**Comment by jdegoes** [comment]
This is almost certainly algorithmic in nature, probably a O(n^3) or something in the planner. Can likely be solved simply with memoization or through more clever algorithms.

**Comment by mossprescott** [comment]
I can't reproduce this as of this point in time. That code's been reworked, so probably whatever it was got fixed along the way.

**Comment by mossprescott** [comment]
The planner test which provokes this problem and found it's still happening, it just needs a slightly larger number of keys to show up.

See the FIXME in PlannerSpec referencing this issue.
