### ISSUE TITLE
support alternate DATETIME syntax for TIMESTAMP operator

### ISSUE THREAD

**Issue by jdegoes** [quasar-analytics/quasar#688]
Postgres lets you use TIMESTAMP or DATETIME.

**Comment by sellout** [comment]
Can you add a link to docs for this? I can’t find `DATETIME` mentioned anywhere. Is it really just a simple alias to `TIMESTAMP`, or is there some other difference?

**Comment by jdegoes** [comment]
See [here](https://wiki.postgresql.org/wiki/Working_with_Dates_and_Times_in_PostgreSQL#WORKING_with_DATETIME.2C_DATE.2C_and_INTERVAL_VALUES).

**Comment by jdegoes** [comment]
It looks like a simple alias to me. Btw, I want to make sure the parser allows "keywords" to be used as field names when completely *globally unambiguous*. No need to do that work now, just don't make things worse when mucking with the parser. :smile:
