### ISSUE TITLE
Empty databases do not appear in file system

### ISSUE THREAD

**Issue by cryogenian** [quasar-analytics/quasar#710]
version `2.0.0` (local), `1.3.5` (slamdata.cryogenian.ru)
my config file 
```json
{
    "server": {
        "port": 8080
    },
    "mountings": {
        "/foo": {
            "mongodb": {
                "connectionUri": "mongodb://localhost/",
                "database": "foo"
            }
        },
        "/bar": {
            "mongodb": {
                "connectionUri": "mongodb://localhost",
                "database": "bar"
            }
        },
        "/duux/quux": {
            "mongodb": {
                "connectionUri": "mongodb://localhost",
                "database": "baz"
            }
        }
    }
}
```
mongo queries 
```
> show databases 
admin  (empty)
bar    0.078GB
baz    (empty)
foo    0.078GB
local  0.078GB
test   0.078GB
> use foo 
switched to db foo
> show collections
aa
bar.baz
baz.quux
system.indexes
> use bar
switched to db bar
> show collections
system.indexes
trololo
trololo.ololo.quux
> 
> use baz 
switched to db baz
> show collections 
> 
```
api queries 
http://local.slamdata.com/metadata/fs//
```json
{
    "children": [
        {
            "name": "foo",
            "type": "mount"
        },
        {
            "name": "bar",
            "type": "mount"
        },
        {
            "name": "duux",
            "type": "mount"
        }
    ]
}
```
http://local.slamdata.com/metadata/fs//foo/
```json
{
    "children": [
        {
            "name": "bar",
            "type": "directory"
        },
        {
            "name": "foo",
            "type": "directory"
        },
        {
            "name": "local",
            "type": "directory"
        },
        {
            "name": "test",
            "type": "directory"
        }
    ]
}
```
http://local.slamdata.com/metadata/fs//foo/foo/
```json 
{
    "children": [
        {
            "name": "aa",
            "type": "file"
        },
        {
            "name": "bar",
            "type": "directory"
        },
        {
            "name": "baz",
            "type": "directory"
        },
        {
            "name": "system",
            "type": "directory"
        }
    ]
}
```
http://local.slamdata.com/metadata/fs//duux/quux/foo/
```json
{
    "children": [
        {
            "name": "aa",
            "type": "file"
        },
        {
            "name": "bar",
            "type": "directory"
        },
        {
            "name": "baz",
            "type": "directory"
        },
        {
            "name": "system",
            "type": "directory"
        }
    ]
}
```
Seems, that first level has duplicate of all mounts and exact content appears only in second level of nesting (i.e. `/foo/foo/` -> `/foo/`)

**Comment by mossprescott** [comment]
This is correct behavior as far as I can tell. The `database` field is no
longer needed and is ignored. All the databases in the mongo instance
appear as directories under each mount.

In your example, admin and baz are empty, so it seems mongodb is not
including them when we enumerate the available dbs. That's something we
might want to look into.

**Comment by jdegoes** [comment]
@cryogenian The way it works now is you mount the *cluster*, and all *databases* are automatically mounted as children of that cluster. This makes more sense than forcing admin to manually mount every single database (sometimes dozens or hundreds). It's slightly less flexible until we have symbolic links + permissions in our file system, but still saves a lot of effort and helps unify our connection mechanism to different backends (now it really is just a URI).

**Comment by jdegoes** [comment]
@mossprescott Should we change the title to, "Empty databases do not appear in file system"?

**Comment by cryogenian** [comment]
I've tried to move directory (or notebook) 
`http://local.slamdata.com/data/fs//foo/foo/Untitled%20Notebook.slam/`
Destination: `/foo/foo/Untitled.slam/`

Error: ```No file/dir at path: ./foo/Untitled Notebook.slam```

It works in **1.2.12** and doesn't work in **1.3.5**. Do I need to change `Destination` somehow or it's bug?

**Comment by jdegoes** [comment]
Are you sure the notebook exists? If there is no content in it, it would fail, because the server does not recognize empty directories (a bit like Git).

**Comment by cryogenian** [comment]
http://local.slamdata.com/metadata/fs//foo/foo/
```json
{
    "children": [
        {
            "name": "Untitled.slam",
            "type": "directory"
        },
        {
            "name": "aabbc",
            "type": "file"
        },
        {
            "name": "bar",
            "type": "directory"
        },
        {
            "name": "baz",
            "type": "directory"
        },
        {
            "name": "system",
            "type": "directory"
        }
    ]
}
```
MOVE@http://local.slamdata.com/data/fs//foo/foo/Untitled.slam/
DESTINATION: /foo/foo/U.slam/
ERROR: No file/dir at path: ./foo/Untitled.slam

**Comment by jdegoes** [comment]
I mean, are you sure that the `Untitled.slam` directory contains some content?

Either way, @mossprescott, I vote that moving a non-existent directory to a non-existent location succeed, on grounds it's a no-op, like deleting a non-existing resource -- OK w/you?

**Comment by cryogenian** [comment]
Sure, I can move it in older slamengine. 
```
> use foo
switched to db foo
> show collections
Untitled\.slam.index
aabbc
bar.bazqqdasf
baz.quux
system.indexes
```

**Comment by jdegoes** [comment]
This is showing you have an `index` file inside the `Untitled.slam` directory, which means this is definitely a bug. Can you report it in a new ticket ("Move of directory containing a file fails) and I'll prioritize it above "not showing empty databases"?

**Comment by cryogenian** [comment]
reported #711

**Comment by mossprescott** [comment]
I'm fine with allowing a non-existent dir to be moved to another non-existent path. I guess I'll add it to #711.
