### ISSUE TITLE
add SAMPLE function

### ISSUE THREAD

**Issue by cryogenian** [quasar-analytics/quasar#722]
It would be great to have `RANDOM()` function returning random integer. One can use it to get sample of heterogeneous data.

**Comment by jdegoes** [comment]
Probably we will do a `SAMPLE(<set>, <n>)` function, which takes `n` random samples of the specified `set`. Would that work? Is there some reason you want a random integer?

**Comment by cryogenian** [comment]
I think `SAMPLE` would be even better.

**Comment by mossprescott** [comment]
How would you use that in a query? Or would we have some other way of using it, like a new API?

**Comment by jdegoes** [comment]
Same way as any other many-to-one function, e.g: `SELECT SAMPLE(*, 100) FROM "/zips"`
