### ISSUE TITLE
DELETE database does not work

### ISSUE THREAD

**Issue by garyb** [quasar-analytics/quasar#759]
Making `DELETE` requests for a folder gives me 500 responses like this currently:

```
Command failed with error 20: 'can't drop system ns' on server localhost:27001. The full response is { "ns" : "data1.system.indexes", "nIndexesWas" : 0, "ok" : 0.0, "errmsg" : "can't drop system ns", "code" : 20 }
```

Also making `DELETE` requests for non-existant paths results in a 200 at the moment, I'm not sure if that's right or not?

**Comment by garyb** [comment]
Ah, correction. This is attempting to `DELETE` a database, not a folder.

**Comment by jdegoes** [comment]
Attempting to delete folders that do not exist must always succeed.

I've scheduled this bug (deleting databases) for 2.1.

**Comment by jdegoes** [comment]
We should also make sure deleting a cluster works. It's very convenient to be able to delete an entire MongoDB cluster with 1 click. :smiling_imp: 

The alternative is deleting each database individually which is much too painful...

**Comment by garyb** [comment]
By a cluster do you mean a mount? If so, yep, that works.

**Comment by jdegoes** [comment]
Yes, a mount.

**Comment by sellout** [comment]
@garyb: There is a difference (I think) between `DELETE /mount/fs/some-mount/` and `DELETE /data/fs/some-mount/`. The former should remove the mountpoint, the latter should actually delete all the data from the mongo instance it’s connected to. Does the latter actually work?

**Comment by jdegoes** [comment]
@sellout You are correct, deleting on /mount/ should delete the mount configuration, and by extension, remove the mount point. Whereas, deleting on /data/ should have no effect on the mount and should merely wipe all the data — in the case of MongoDB, this means wiping out every collection in every database.

**Comment by garyb** [comment]
I think this probably was trying to `DELETE /data/fs/some-mount/`, but I'm not sure. I'll go check!

**Comment by garyb** [comment]
Hm, I think things have changed since this issue was written up.

- Deleting mounts is fine, and yes it just removes them from the config.
- Deleting databases within a mount now fails as it tries to move them under `.trash`
- Actually trying to `DELETE /data/fs/mount1/test` gives:

```
500 Internal Service Error
Command failed with error 20: 'can't drop system ns' on server localhost:27001. The full response is { "ns" : "test.system.indexes", "nIndexesWas" : 0, "ok" : 0.0, "errmsg" : "can't drop system ns", "code" : 20 }
```

**Comment by jdegoes** [comment]
@garyb How about deleting the mount itself, e.g. `/data/fs/mount1/`? In theory this should wipe away all collections from all databases, leaving an empty MongoDB cluster.

@sellout The above error with deleting a database is happening because you can't delete MongoDB protected collections; probably the logic we're using just fails if any one collection cannot be deleted, instead of treating MongoDB's magical collections specially.

**Comment by garyb** [comment]
```
500 Internal Service Error
Command failed with error 20: 'can't drop system ns' on server localhost:27001. The full response is { "ns" : "aaaa.system.indexes", "nIndexesWas" : 0, "ok" : 0.0, "errmsg" : "can't drop system ns", "code" : 20 }
```

`aaaa` is the first database in the mount

**Comment by jdegoes** [comment]
@sellout You have a fix for this somewhere, right? (Pairing with Shifra?)
