### ISSUE TITLE
issue when searching files with _id columns

### ISSUE THREAD

**Issue by garyb** [quasar-analytics/quasar#761]
If I have a query like `SELECT * FROM "/slamengine-test-01/zips" WHERE true`, and then search the results, the engine returns an error:

```
An error occurred during evaluation: com.mongodb.MongoCommandException: Command failed with error 16007: 'exception: can't convert from BSON type OID to String' on server ds045089.mongolab.com:45089. The full response is { "errmsg" : "exception: can't convert from BSON type OID to String", "code" : 16007, "ok" : 0.0 }
```

Avoiding selecting the `_id` field in the original query fixes this.

**Comment by mossprescott** [comment]
We're projecting under value (because of `where true`, which we don't translate to a selector). That puts an OID at `value._id`, and then apparently our flattening type check doesn't catch it.

```
db.zips.aggregate(
  [
    { "$project": { "__tmp0": { "$literal": true }, "__tmp1": "$$ROOT" } },
    { "$match": { "__tmp0": true } },
    { "$project": { "value": "$__tmp1", "_id": false } },
    { "$out": "tmp.gen_0" }],
  { "allowDiskUse": true });
db.tmp.gen_0.find();
```

```
 value._id | value.city    | value.loc[0] | value.loc[1] | value.pop | value.state |
-----------|---------------|--------------|--------------|-----------|-------------|
 01001     | AGAWAM        |   -72.622739 |    42.070206 |     15338 | MA          |
 01002     | CUSHMAN       |    -72.51565 |    42.377017 |     36963 | MA          |
```

**Comment by sellout** [comment]
So … what we need to do here is protect other operations like we do flattening ops? Because what this comes down to is `_id LIKE '%foo%'` being in the search query, and that should result in `null` rather than getting an error from MongoDB.

Granted, we should also be eliminating `_id`, but an `ObjectID` can be in any field, and we need to handle that.

**Comment by jdegoes** [comment]
All ops should be protected (& result in undefined for wrong types), it's the part of MRA semantics that makes cross-schema queries sane.

**Comment by sellout** [comment]
Right – but many operations just return null when applied to the "wrong" types, and we don't want to do extra work to protect those. But yeah, generalizing our ExprOp type checks beyond the current two special cases is necessary.

As far as null vs undefined, we unfortunately don't always have control over that.

**Comment by jdegoes** [comment]
> As far as null vs undefined, we unfortunately don't always have control over that.

I think if we stop trusting MongoDB, and introduce safety ourselves, we can ensure that undefineds are generated on mis-matched types. In any case, beyond the scope of this ticket. :smile:

**Comment by sellout** [comment]
The problem I had was that even when we used the (deprecated) Undefined BSON value, it came back to us in the query result as Null. But, when I ran into that, I didn’t push too hard on trying to figure it out, so I may have mucked it up somehow.

**Comment by sellout** [comment]
And yeah … this is a case where we should just always do the right thing, and then tossing the typechecks is an optimization.

**Comment by jdegoes** [comment]
Yeah, exactly, also I can talk to MongoDB about the first problem if we can't find a workaround.
