### ISSUE TITLE
can’t distinguish between a bad path and cross-backend queries

### ISSUE THREAD

**Issue by sellout** [quasar-analytics/quasar#771]
In `NestedBackend.run`, we check if any backend contains all of the paths, but not the orthogonal condition of whether a particular path is in any backend.

Since we will always want to make sure a path exists _somewhere_ and will eventually support cross-backend requests, we should pivot this function to do the orthogonal check.

**Comment by mossprescott** [comment]
Note: current behavior is that any request for which no backend can be identified produces a confusing 500 response from the server, rather than a 404 (a regression in #775).
