### ISSUE TITLE
logical plan: improve simplification

### ISSUE THREAD

**Issue by sellout** [quasar-analytics/quasar#777]
There are at least two parts to this:

1. constant folding and
2. uhh … other simplifications

We already _have_ constant folding in the typechecker, but we don’t take advantage of it. Part of the problem is that we typecheck the SQL AST instead of the LogicalPlan, so

1. we don’t store constants in the AST as `Data`, which makes it harder to substitute all the constants into the AST,
2. many structures change shape, so the resulting LP might have folds available to us that the AST didn’t make obvious, and
3. the AST is just more complicated in general to be handling this stuff on.

To fix that, we need to move the typechecking phase to the LogicalPlan, then when nodes type as a `Const`, we replace the node with `Constant`.

As for the other cases of this (EG, simplifying `DROP(foo, 0)` ⇒ `foo`), I think adding a `simplify` operation to `Func` is the way to go (that way we keep the simplifications near the constant folding), and then we only need one case in `simplifyƒ` for `InvokeF`.

I have the last part of this done, including duplication of some of the constant folding.

**Comment by jdegoes** [comment]
I agree the logical plan should be where type checking takes place. Not only is everything saner there, but types would be extraordinarily useful during physical plan generation, especially when we have more precise types. One will have to be very careful about errors, though, which have to be reported on the SQL AST and not the logical plan.

**Comment by sellout** [comment]
Yeah – this really depends on #40 (source locations) to some extent.

**Comment by sellout** [comment]
With #796, this ticket is now “move typechecking to the LogicalPlan”, which should enable the remaining constant folds that are currently inaccessible (#796 has a pending test for at least one of those currently-unhittable cases).
