### ISSUE TITLE
attempting to rename databases in mongodb mounts fails

### ISSUE THREAD

**Issue by garyb** [quasar-analytics/quasar#787]
I'm not sure if this is new actually, but attempting to rename a database currently results in errors like this:
```
{
  "error": "com.mongodb.MongoCommandException: Command failed with error -1: 'renaming system.indexes is not allowed' on server localhost:27001. The full response is { \"ok\" : 0.0, \"errmsg\" : \"renaming system.indexes is not allowed\" }"
}
```
With the contents of the database partially moved over and the old one left behind too with any unmoved files/directories still present.

**Comment by jdegoes** [comment]
Hmmm, MongoDB does not support renaming databases, but it looks like `copyDatabase` can serve a similar purpose, then the old database can be deleted.

This is probably a bug in SlamEngine, as renaming collections cannot ever assist in renaming a database (you're sure it was a database you renamed and not a collection, right?).

<https://jira.mongodb.org/browse/SERVER-701>

**Comment by garyb** [comment]
Ah, that is odd! It definitely was a database, I just attempted to do it again with the same result.

**Comment by jdegoes** [comment]
OK, sounds like the backend is just screwing up, if we get through other bugs in time we'll have a quick look at this one (could be a 1 liner fix, who knows).

**Comment by mossprescott** [comment]
MongoDB *will* rename collections across different databases by [copying and then dropping](http://docs.mongodb.org/manual/reference/command/renameCollection/#dbcmd.renameCollection).

If the backend thinks the Path refers to a dir, it will recursively issue `rename` commands for each contained file (collection). That will work, except for collections where that's not allowed. On my local db the copy worked, but the drop failed.

So we could make it an error to try moving a DB, or we could make it "work", by handling (and ignoring?) any errors.

**Comment by garyb** [comment]
It seemed to be failing at the `system` collection in the database each time, if that's any help?

**Comment by jdegoes** [comment]
> So we could make it an error to try moving a DB, or we could make it "work", by handling (and ignoring?) any errors.

Let's use the `copyDatabase` command and then drop the old database. this has the pro that it is "more" atomic, i.e. if the copy fails, at least you have the old one in-tact.
