### ISSUE TITLE
mongodb: join condition interpreted too loosely, queries with bad references blow up

### ISSUE THREAD

**Issue by mossprescott** [quasar-analytics/quasar#817]
SlamEngine should require that fields referenced in `join` conditions be defined, to avoid "accidental" and massive joins on `null` values when references are incorrect.

In a query like this:
```sql
select a.foo from a join b on a.something.id = b.something.parentId ...
```
the join expression is non-trivial, and may contain a reference error if the user isn't completely correct in identifying the right fields. If both fields aren't correct, then both sides of the condition end up evaluating to `null`, and effectively it's a full cross-join, which in most cases will just blow up and not produce anything useful.

We should impose the additional condition that both fields are defined (i.e. they exist and have *some* value). That way, if there's any error we'll simply return nothing, quickly.

See #793 and the associated support ticket.

**Comment by jdegoes** [comment]
There is no fast way to check if a field exists aside from doing a full collection scan, and even that is out of date before the scan completes. Nonetheless, this could generate a warning, and quota management should certainly allow policies that disallow such queries from being run until there is "proof" (via sampling or full collection scan) that they will not blow up.

A secondary issue is that `foo.bar` should not evaluate to `null` for non-existent `foo`/`bar`, but should evaluate to `undefined`, and for all `x`, `x /= undefined`, so `JOIN` would exclude such join keys from the result. That alone would fix these pathological cases.

Related to #465.

**Comment by mossprescott** [comment]
I wasn't suggesting a global test for field existence, but just that we only include documents that have the field present in the joined set. I think that's feasible, using the `$exists` op in aggregation, and `== undefined` or some such in JS.

As far as I know, there's no concept of `undefined` in aggregation, but if we can somehow emulate it, then I think that's another way of describing exactly the same behavior I'm asking for. To do this in general, we'd need to encode these values in BSON, etc.

**Comment by jdegoes** [comment]
BSON has an undefined value, it's just deprecated (\x06). Why that's deprecated by JavaScript code type isn't, I have no idea.

In any case, I agree that not adding "undefined" values as join keys should help this situation, and is semantically the correct thing to do. One could say that about `null` as well, if one accepts ANSI SQL's three-valued logic with JS `null` as the third-value.
