### ISSUE TITLE
API: clean up and improve error messages

### ISSUE THREAD

**Issue by mossprescott** [quasar-analytics/quasar#822]
Currently all errors are returned in a JSON-formatted response of the form `{ "error": "..." }`, with a free-form message which looks different and contains different amounts of information for each type of error. In many cases these messages are just taken from the `message` of some exception or other.

We should adopt a common style for these messages, and capture useful information as separate fields in the response.
- [ ] Make the value under `error` an object with at least one field, `status`.
- [ ] `status` should contain a fixed text summarizing the problem. These messages should be short, grammatical, capitalized, and end with a period, e.g. `"'Destination' header missing."`
- [ ] The same status should be used in the HTTP status line, e.g. `400 'Destination' header missing.`
- [ ] Any additional detail which may help the user/client to understand the problem should be included as separate fields in the `error` object, e.g. the text of an unanticipated runtime error message.
- [ ] Where possible, units of data should be captured as *separate* fields, so that they can be easily captured and used without parsing strings, e.g. `"status": "Invalid path.", "detail": "The specified path is not contained within something or other.", "path": "../foo", "targetPath": "/"`

Needing clarity:
- What exactly constitutes "grammatical"?
- Should error responses ever include information that's visible in the request (e.g. `path` in the example above, probably). 
- Is there any need to document the fields, other than in the API tests?

To implement this cleanly, we probably need a simple, clean abstraction for representing errors to be rendered into this form, and then we need a way to map various kinds of errors that arise in the API services to that form. It will also mean capturing some errors in a way that preserves more detail than we currently have. Also see #774.

Split from #757. See discussion on PR #819.

**Comment by jdegoes** [comment]
> What exactly constitutes "grammatical"?

Must contain (possibly implicit) subject, explicit verb, and explicit object.

> Should error responses ever include information that's visible in the request (e.g. path in the example above, probably).

This would be helpful. The client can reconstruct it, of course, but it may not keep 1-to-1 track of request to response. A lot of times these will end up in some log file so the context won't be known.

> Is there any need to document the fields, other than in the API tests?

No, let's just assume the client can, if necessary, either log them or dynamically pull them out into a way that a user can understand.

**Comment by sellout** [comment]
I have a lot of work done on #774, so we should talk before any effort is put into representing errors.

**Comment by jdegoes** [comment]
@sellout How much of this ticket is already done with your work on #774?

**Comment by mossprescott** [comment]
#774 (via #844) lays the ground work, in that we now have a clearly-defined way of representing all the errors and capturing the information.

#870 makes a start on actually formatting the error types with nice messages, but does not adopt the new format for responses called for in this issue.

What remains is to go through all the errors, make sure they capture the information we want to include as fields in the responses, write JSON encoders with a nice message for each, and make sure they all get trapped and encoded properly in the API.
