### ISSUE TITLE
ls command does not work in repl -- classnotdefined error?

### ISSUE THREAD

**Issue by jdegoes** [quasar-analytics/quasar#830]

**Comment by mossprescott** [comment]
Can you provide any more context? It's working for me currently on master.

**Comment by jdegoes** [comment]
Sorry in a meeting, I will later. This is always reproducible on Linux.

**Comment by sellout** [comment]
Does the user have the right JRE?

If they’re using the repl, they must have cloned and built themself, right? Even if not, we don’t bundle a JRE on Linux.

**Comment by jdegoes** [comment]
This was using sbt and building from source, and (possibly) the prebuilt web jar (but I can't remember).

**Comment by jdegoes** [comment]
sbt would complain if the wrong jre were available.
