### ISSUE TITLE
std: Unify Func and VirtualFunc

### ISSUE THREAD

**Issue by mossprescott** [quasar-analytics/quasar#87]
`VirtualFunc`s should appear in the list of functions exported by each library, and therefore need to have some type in common with our other existing functions.

Maybe refactor `Func` into `Func` (more abstract than it is now) and `PrimitiveFunc` (which all of our existing functions would extend.

**Comment by jdegoes** [comment]
To avoid many ad hoc functions in the standard library / planner, we should be able to support virtual functions, which simply compile to other functions. This will allow us to implement some functions as combinations of more primitive functions.
