### ISSUE TITLE
API: don't restart the http4s server when changing mounts

### ISSUE THREAD

**Issue by mossprescott** [quasar-analytics/quasar#874]
Currently, whenever a request changes any aspect of configuration, we shutdown the current http4s server (just the server "object", not the whole Java process), and start up a new one with the new config. But this actually only necessary when the port changes, a relatively uncommon situation. When mounts change, it would be sufficient to modify the configuration in place in the existing server instance.

In particular, this would simplify our lives when it comes to testing the API, which involves starting and stopping server instances for each test.

Note: we'll need to take care to avoid race conditions when one request handling thread updates the configuration while other threads are using it. It should be sufficient to make sure that each request is handled using the configuration that was current _as of the time the request was received_, without even being _too_ picky about what we mean by "current".

**Comment by jdegoes** [comment]
This can be pulled earlier if the build fails.
