### ISSUE TITLE
getting big response from slamengine may produce error

### ISSUE THREAD

**Issue by cryogenian** [quasar-analytics/quasar#881]
How to reproduce: 
* Open testing db
* Open `zips` file
* Click `chart` in next cell left menu

Result: 
* Data has not been loaded. 
* There is no available chart types

Expected:
* Data has been loaded
* There is at least one available chart 

Cause: 
* `GET data/fs//demo/zips` returns `(failed) net::ERR_INCORRECT_CHUNKED_ENCODING` with status code __200__

**Comment by jdegoes** [comment]
I'd look at scalaz-stream / gzip / chunk for likely troubles.

**Comment by mossprescott** [comment]
I haven't been able to reproduce this with either Safari, following the sequence above, or with `curl --compressed`, which seems to be able to download the entire zips dataset with no problems.

I'm trying other browsers now.

**Comment by jdegoes** [comment]
@cryogenian It would be helpful to see the headers sent in the request, so @mossprescott can reproduce it more easily.

**Comment by jdegoes** [comment]
A quick Google search also says anti-virus and packet prediction settings can cause this error message.

**Comment by mossprescott** [comment]
Firefox seems to hang trying to load, offering to kill the script. If I let it continue, it never finishes.

**Comment by mossprescott** [comment]
Chrome hangs for a while, but eventually loads the data (as seen in the Network inspector), but the Category and Measure drop downs are unresponsive.

If I use a query to limit the result to 2000 or less, then the data loads faster and the UI works. It seems like it might just be taking n^2 time to load, since it will eventually come in, but it's hard to tell what's happening.

**Comment by cryogenian** [comment]
Request
```
GET /data/fs//demo/cities HTTP/1.1
Host: 104.236.166.167:8080
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36
Accept: */*
Referer: http://104.236.166.167:8080/slamdata/notebook.html
Accept-Encoding: gzip, deflate, sdch
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4
```

Response: 
```
HTTP/1.1 200 OK
Content-Type: application/ldjson; mode="readable"; charset=UTF-8
Content-Encoding: gzip
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, PUT, POST, DELETE, MOVE, OPTIONS
Access-Control-Max-Age: 1728000
Access-Control-Allow-Headers: Destination
Date: Wed, 19 Aug 2015 17:35:35 GMT
Transfer-Encoding: chunked
```

**Comment by mossprescott** [comment]
Thanks, @cryogenian. I don't see anything there that seems like it could be confusing the server.

The plot's thickened somewhat. I *sometimes* get an error when I attempt to pull a large dataset with a command like this:
```bash
curl -i -H "Accept-Encoding: gzip" http://104.236.166.167:8080/data/fs/demo/zips -o zips.json.gz
```

When it does happen, it looks like the server is just dropping the socket after the first few bytes of zipped content. Which could explain what @cryogenian is seeing.

But it doesn't happen most of the time, and I can find no pattern. Earlier today, it wasn't happening at all. I've seen in it several times in the last few minutes, but then it works fine many times in between failures.

I whipped up a bash script to bash on it which will hopefully establish some kind of pattern.

**Comment by garyb** [comment]
Are you still using your nginx setup @cryogenian? Perhaps the differences are related to that?

**Comment by cryogenian** [comment]
Yes, I'm using nginx.
