### ISSUE TITLE
error when using case inside where clause

### ISSUE THREAD

**Issue by jdegoes** [quasar-analytics/quasar#884]
```sql
select distinct crawler, host, count(*) 
  from "/foo/bar/stats" 
  where "timestamp" > :startperiod 
    and "timestamp" < :endperiod 
    and (CASE 
      WHEN :namespace = '' OR :namespace IS NULL THEN TRUE 
      ELSE "namespace" = :namespace 
    END) 
  group by crawler, host 
  order by crawler,  host
```

**Comment by sellout** [comment]
This query is missing an `END` in the case statement. Is that the error that’s happening? If not, any chance of getting the error message?

**Comment by jdegoes** [comment]
Oops, should have noticed that. ![http://i.imgur.com/BWusbEy.png] Will see if that takes care of the problem.

**Comment by jdegoes** [comment]
The problem still exists, trying to get an error message now.

**Comment by jdegoes** [comment]
```
Error in query: Expected field "out"
```

**Comment by sellout** [comment]
So, I think this error message is coming from the front-end, during parsing the JSON response (on a successful query, there should be an `out` field in the JSON). I wonder if this is the same issue as #890, where an empty response is returned as `200 OK`.

**Comment by sellout** [comment]
Although, I would expect the JSON parser to respond to “” differently than to “{}”. (And the error message looks like a response to the latter.)
