### ISSUE TITLE
`count` doesn't work on temp file generated by `group by` queries

### ISSUE THREAD

**Issue by cryogenian** [quasar-analytics/quasar#890]
Unfortunately, I can't reproduce this bug. You can see discussion and lots of information about it in slamdata/slamdata#408

In short
* temporary file `out0` is generated by `POST /query/fs/path` with query `select dictinct count(*), status from path group by status` 
* `GET /data/fs/out0?limit=0&offset=10` works as expected
* `GET /query/fs/out0?q=query` where query is encoded `select count(*) as total from out0` returns empty response.

**Comment by cryogenian** [comment]
I've just remembered. I had similar problem with notworking `count` when updates from 2.1.2 to 2.1.3. And it disappeared in 2.1.4

**Comment by cryogenian** [comment]
slamdata/slamdata#424

**Comment by jdegoes** [comment]
This is almost an "always happens" for one user on 2.1.8.

**Comment by mossprescott** [comment]
Not sure if this is the problem, but the third request listed above is incorrect as presented. It should be `GET /data/fs/demo/?q=select+count(*)+as+total+from+out0` (assuming the mount is at `/` and a database called `demo`). Or else the source in the query should be a full path as in `... from "/demo/out0"`. If the request path is valid but the source path doesn't exist, a simple query like this will usually return an empty result and no error.

The API should probably return an error if any source collection is missing. Currently you'll get an error if map-reduce is involved (including any join), but not if the query runs in the aggregation pipeline, but this is a MongoDB detail that shouldn't be exposed to the user.

**Comment by jdegoes** [comment]
@cryogenian Can you fix the count SQL generation to work correctly? Would like to

**Comment by cryogenian** [comment]
Here are requests from @pjaffe fiddler 

* GET /query/fs//Dev/slamdata-defects/SlamData%20Isolate%20Defects/Simple%20Visualization.slam/out2?q=SELECT%20COUNT(*)%20as%20total%20FROM%20%22%2FDev%2Fslamdata-defects%2FSlamData%20Isolate%20Defects%2FSimple%20Visualization.slam%2Fout2%22 HTTP/1.1
* GET /query/fs//Dev/slamdata-defects/parent?q=SELECT%20COUNT(*)%20as%20total%20FROM%20%22%2FDev%2Fslamdata-defects%2Fparent%22 HTTP/1.1

They both have source setted to target file and fully specified paths in requests.

**Comment by jdegoes** [comment]
## First Query

This one looks wrong:

```
GET /query/fs//Dev/slamdata-defects/SlamData Isolate Defects/Simple Visualization.slam/out2?q=
SELECT COUNT(*) as total FROM "/Dev/slamdata-defects/SlamData Isolate Defects/Simple Visualization.slam/out2"
```

The query is being executed *inside* the file (i.e. the base path is equal to the file). I think you want the root of the file system, e.g:

```
GET /query/fs/?q=
```

...since you fully qualify in the `FROM` clause.

## Second Query

This also looks wrong:

```
GET /query/fs//Dev/slamdata-defects/parent?q=
SELECT COUNT(*) as total FROM "/Dev/slamdata-defects/parent"
```

For similar reason.

**Comment by cryogenian** [comment]
So, 
```
GET /query/fs//fully/qualified/path?q=select * from "/fully/qualified/path" where something
```
should not work? I supposed that source is used only to determine backend.

> GET /query/fs/[path]?q=[query]

> Executes a SQL query, contained in the single, required query parameter, on the backend responsible > for the request path.

We don't know what is backend for current path in frontend. That's why path is setted as source. Fully qualified path is used because we know it and it seems to be a slightly simpler. 

The main reason of my complain is that these requests works nice on CI and my machine. In case of incorrect request it won't work anywhere.

**Comment by sellout** [comment]
@cryogenian: I think you should be able to fully-qualify both and have it work. In general, the path can be split between the URL and FROM, so any path in the FROM is relative to the path in the the URL. EG, `GET /query/fs/fully/?q=select * from "qualified/path" …`, and so, with a fully-qualified path in the FROM, you don’t need to include any path in the URL (`GET /query/fs?q=select * from "/fully/qualified/path" …`). But I think what you’re doing _should_ work.

**Comment by jdegoes** [comment]
Possibly the same as #884.

**Comment by jdegoes** [comment]
> @cryogenian: I think you should be able to fully-qualify both and have it work.

Agreed. I was thinking, "that path doesn't exist", but it shouldn't matter to the backend -- it's just executing the query relative to an "empty" location in the file system.

Nonetheless, it is certainly not best practice, since the path is fully qualified in the `FROM` clause, and since no relative paths are being used, it would represent best practice to query relative to the root of the file system.

**Comment by jdegoes** [comment]
> The main reason of my complain is that these requests works nice on CI and my machine. In case of incorrect request it won't work anywhere.

That's true, if the URL is exactly the same. The browser reports the same requests that you see locally, but on route to AWS, it's possible the URL is modified in some way. The most likely candidate for modification is not the SQL query embedded in the query string, since if there's no a priori reason a single element of that query (the `FROM` clause) would be singled out for modification, while the rest would survive unscathed enough to not report SQL errors. So it's far more likely to be the other components of the request, including the path and request headers.

It'd be nice to have server request logging so we can see what the server actually sees (or at least fiddler on the server side).
