### ISSUE TITLE
Rename the project SlamEngine -> Quasar

### ISSUE THREAD

**Issue by jdegoes** [quasar-analytics/quasar#899]
- [ ] rename packages in source code
- [ ] rename references in documentation, comments, strings, and types
- [ ] rename git project
- [ ] ensure existing tooling continues to work
- [ ] update name in third-party tools

**Comment by mossprescott** [comment]
Clarifying:

The `slamdata.engine` package should be just `quasar.` For example, `quasar.Bson`, `quasar.physical.mongodb.Workflow`, etc. I assume there's no "Quasar Engine" (Quasar *is* the engine)† By the way, :+1: for shortening the name.

The git project becomes `slamdata/quasar`, or do we want to to call it something like `quasar-core`, anticipating future modularization?

I can't seem to find any artifact identifiers referring to slamdata, but presumably we'll need a domain name for that eventually, and we'll publish JARs under `org.quasar` or some such.

† That means a handful of things that are now in `slamdata` but outside `slamdata.engine` either need to go into `quasar` or become their own projects.  In particular, `slamdata.recursionschemes` and the `fp` stuff (which I believe @sellout was planning to move anyway, but I'm not sure where to). Other than that, I don't think there's anything all that exciting.

**Comment by jdegoes** [comment]
> I assume there's no "Quasar Engine" (Quasar is the engine)†

Yes, that's correct.

> I can't seem to find any artifact identifiers referring to slamdata

It may be hidden in bowels of our SBT build files, I think derived from the project name.

> I can't seem to find any artifact identifiers referring to slamdata, but presumably we'll need a domain name for that eventually, and we'll publish JARs under org.quasar or some such.

`quasar.apache.org` if all goes well. :smiley: 

> † That means a handful of things that are now in slamdata but outside slamdata.engine either need to go into quasar or become their own projects.

Yes. For this ticket, let's move them in `quasar` and separate tickets can break, e.g. `recursionschemes` into other projects.
